<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.inditex.rrhh.icmclcwb</groupId>
    <artifactId>APPWEB-INCOMEMotorCalculoJava</artifactId>
    <version>4.74.0</version>
  </parent>

  <artifactId>jacoco-report-aggregate</artifactId>
  <packaging>pom</packaging>

  <name>${project.groupId}:${project.artifactId}</name>
  <description />

  <properties>
    <amiga.jacoco.excludes>**/*DTO.class,**/*dto.class,**/*Dto.class,**/*VO.class,**/*vo.class,**/*Vo.class,**/com/inditex/**/model/entity/*.class,**/com/inditex/**/model/entity/id/*.class,**/com/inditex/**/config/*Configuration.class**,**/com/inditex/**/config/*Configure.class**,/com/inditex/mypackage/*.class,**/com/inditex/**/Application.class,/com/inditex/mypackage/*.class,**/com/inditex/**/Constants.class,**/com/inditex/**/ApiErrorResponse.class</amiga.jacoco.excludes>
  </properties>

  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-model</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-boot</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-api</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-ms</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-ws</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>
</project>
