package com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.tiendas.dto;

import java.io.Serializable;
import java.time.LocalDate;

import lombok.Data;

@Data
public class TiendasResultItemDto implements Serializable {

  private static final long serialVersionUID = -3031337074794238735L;

  private String m4AutoGeneratedRecordID;

  private boolean m4AutoGeneratedToDelete;

  private String idPais;

  private LocalDate fechaInicio;

  private LocalDate fechaFin;

  private String idCadena;

  private String idOrigen;

  private String idEmpresa;

  private String idTiendaMtu;

  private boolean esComisionable;

  private String idLugarTrabajo;

}
