package com.inditex.rrhh.icmclcwb.model.primary.tarea.repository;

public interface TareaCalculoAlgoritmoChallengeDirectoVentaPorcentajeV1RepositoryCustom extends TareaCalculoAlgoritmoBaseRepositoryCustom {
}
