package com.inditex.rrhh.icmclcwb.model.primary.tarea.repository;

public interface TareaCalculoAlgoritmoDirectoVentaPresenciaReduccionJornadaPorcentajeDiariaDesplazamientoV1RepositoryCustom
    extends TareaCalculoAlgoritmoBaseRepositoryCustom {

}
