package com.inditex.rrhh.icmclcwb.model.primary.tarea.repository;

public interface TareaCalculoAlgoritmoGlobalTiendaSeccionPersonasPorVentaNoVendedoresPorcentajeDesplazamientoV1RepositoryCustom
    extends TareaCalculoAlgoritmoBaseRepositoryCustom {

}
