<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.inditex.aqsw.framework.amiga</groupId>
    <artifactId>amiga-framework</artifactId>
    <version>4.6.2</version>
  </parent>
  <groupId>com.inditex.rrhh.icmclcwb</groupId>
  <artifactId>APPWEB-INCOMEMotorCalculoJava</artifactId>
  <version>4.15.0</version>
  <packaging>pom</packaging>
  <name>${project.groupId}:${project.artifactId}</name>

  <modules>
    <module>APPWEB-INCOMEMotorCalculoJava-api</module>
    <module>APPWEB-INCOMEMotorCalculoJava-model</module>
    <module>APPWEB-INCOMEMotorCalculoJava-ws</module>
    <module>APPWEB-INCOMEMotorCalculoJava-ms</module>
    <module>APPWEB-INCOMEMotorCalculoJava-boot</module>
    <module>APPWEB-INCOMEMotorCalculoJava-ws-api</module>
    <module>jacoco-report-aggregate</module>
  </modules>

  <properties>
    <maven.test.skip>false</maven.test.skip>
    <!-- TODO [javierev] se excluyen ficheros markdown porque sonar los confunde con otra cosa (¿MetaDapper?) -->
    <sonar.exclusions>**/model/meta4/icmwscalcincome/entity/**,**/model/meta4/login/entity/**,**/resources/*.md,**/resources/*.sql</sonar.exclusions>
    <amiga-javaformat.version>2.0.5</amiga-javaformat.version>
    <junit-jupiter-params.version>5.6.3</junit-jupiter-params.version>
    <test-framework-randomizer.version>3.3.0</test-framework-randomizer.version>
    <app.github.chrisvest.version>3.1</app.github.chrisvest.version>
    <app.org.jvnet.jaxb2_commons.version>0.12.0</app.org.jvnet.jaxb2_commons.version>
    <app.org.codehaus.mojo.jaxws-maven-plugin.version>2.6</app.org.codehaus.mojo.jaxws-maven-plugin.version>
    <app.org.codehaus.mojo.wagon-maven-plugin.version>2.0.0</app.org.codehaus.mojo.wagon-maven-plugin.version>
  </properties>

  <dependencyManagement>
    <dependencies>

      <!-- PROJECT DEPENDENCIES -->
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>APPWEB-INCOMEMotorCalculoJava-api</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>APPWEB-INCOMEMotorCalculoJava-model</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>APPWEB-INCOMEMotorCalculoJava-ws</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>APPWEB-INCOMEMotorCalculoJava-ms</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>APPWEB-INCOMEMotorCalculoJava-ws-api</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>com.inditex.aqsw.amiga.javaformat</groupId>
        <artifactId>amiga-javaformat-maven-plugin</artifactId>
        <version>${amiga-javaformat.version}</version>
        <configuration>
          <checkstyle>
            <excludes>com/inditex/rrhh/icmclcwb/model/meta4/icmwscalcincome/entity/**,
              com/inditex/rrhh/icmclcwb/model/meta4/login/entity/**</excludes>
          </checkstyle>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
