package com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.empleados.dto;

import java.io.Serializable;

import lombok.Data;

@Data
public class EmpleadosResultItemDto implements Serializable {

  private static final long serialVersionUID = -631613481122106352L;

  private String m4AutoGeneratedRecordID;

  private boolean m4AutoGeneratedToDelete;

  private String valor;

  private String fechaInicio;

  private String fechaFin;

  private String idCadena;

  private String idOrigen;

  private String idPais;

  private String idEmpresa;

  private String idEmpleado;

  private String orEmpleado;

  private String idTiendaMtu;

  private String idComponente;

  private String idTipoCalculo;

  private String percentageBoy;

  private String percentageMan;

  private String esComisionable;

  private String idLugarTrabajo;

  private String idEmpleadoLocal;

  private String percentageWoman;

}
