package com.inditex.rrhh.icmclcwb.model.app.calcular.mapper;

import java.util.List;

import com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.presupuestoswloc.dto.PresupuestosWlocResultItemDto;
import com.inditex.rrhh.icmclcwb.rest.client.dto.PresupuestoResponseDTO;

import org.mapstruct.Context;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper
public interface PresupuestosWlocMapper {

  @Mapping(target = "idOrigen", source = "cclIdOrigen")
  @Mapping(target = "fechaInicio", expression = "java(source.getFechaInicio().atStartOfDay())")
  @Mapping(target = "fechaFin", expression = "java(source.getFechaFin().atStartOfDay())")
  @Mapping(target = "banda", source = "source.banda")
  @Mapping(target = "ordinal", source = "source.ordinal")
  @Mapping(target = "excepcion", expression = "java(String.valueOf(source.getExcepcion()))")
  @Mapping(target = "idEmpresa", expression = "java(String.valueOf(source.getIdEmpresa()))")
  @Mapping(target = "idSeccion", source = "source.idSeccion")
  @Mapping(target = "idLugarTrabajoMtu", source = "source.idCodOrigen") // Assuming this field is not mapped
  @Mapping(target = "idTpPresupuesto", source = "source.idTpPresupuesto")
  @Mapping(target = "importeConImpuestos", expression = "java(String.valueOf(source.getImporteConIva()))")
  @Mapping(target = "importeSinImpuestos", expression = "java(String.valueOf(source.getImporteSinIva()))")
  @Mapping(target = "m4AutoGeneratedRecordID", ignore = true)
  @Mapping(target = "m4AutoGeneratedToDelete", ignore = true)
  @Mapping(target = "cumplida", ignore = true)
  @Mapping(target = "idLugarTrabajo", source = "source.idTienda")
  PresupuestosWlocResultItemDto toPresupuestosWlocResultItemDto(PresupuestoResponseDTO source, String cclIdOrigen);

  List<PresupuestosWlocResultItemDto> toPresupuestosWlocResultItemDtoList(List<PresupuestoResponseDTO> source,
      @Context String cclIdOrigen);

  default PresupuestosWlocResultItemDto mapContext(PresupuestoResponseDTO car, @Context String cclIdOrigen) {
    return this.toPresupuestosWlocResultItemDto(car, cclIdOrigen);
  }
}
