
package com.inditex.rrhh.icmclcwb.model.meta4.icmwscalcincome.entity;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

/**
 * <p>Java class for Icm_ParamcalempleadospresenciaRecord complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Icm_ParamcalempleadospresenciaRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="fechafin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idorigen" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idempresa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idempleado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idtipohora" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechainicio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idlugartrabajo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_ParamcalempleadospresenciaRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "fechafin",
    "idorigen",
    "idempresa",
    "idempleado",
    "idtipohora",
    "fechainicio",
    "idlugartrabajo"
})
public class IcmParamcalempleadospresenciaRecord implements Serializable, Cloneable, CopyTo2, Equals2, HashCode2, ToString2 {

  private final static long serialVersionUID = 1L;

  @XmlElement(required = true, nillable = true)
  protected String m4AutoGeneratedRecordID;

  protected boolean m4AutoGeneratedToDelete;

  @XmlElement(required = true, nillable = true)
  protected String fechafin;

  @XmlElement(required = true, nillable = true)
  protected String idorigen;

  @XmlElement(required = true, nillable = true)
  protected String idempresa;

  @XmlElement(required = true, nillable = true)
  protected String idempleado;

  @XmlElement(required = true, nillable = true)
  protected String idtipohora;

  @XmlElement(required = true, nillable = true)
  protected String fechainicio;

  @XmlElement(required = true, nillable = true)
  protected String idlugartrabajo;

  /**
   * Gets the value of the m4AutoGeneratedRecordID property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getM4AutoGeneratedRecordID() {
    return m4AutoGeneratedRecordID;
  }

  /**
   * Sets the value of the m4AutoGeneratedRecordID property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setM4AutoGeneratedRecordID(String value) {
    this.m4AutoGeneratedRecordID = value;
  }

  /**
   * Gets the value of the m4AutoGeneratedToDelete property.
   *
   */
  public boolean isM4AutoGeneratedToDelete() {
    return m4AutoGeneratedToDelete;
  }

  /**
   * Sets the value of the m4AutoGeneratedToDelete property.
   *
   */
  public void setM4AutoGeneratedToDelete(boolean value) {
    this.m4AutoGeneratedToDelete = value;
  }

  /**
   * Gets the value of the fechafin property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getFechafin() {
    return fechafin;
  }

  /**
   * Sets the value of the fechafin property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setFechafin(String value) {
    this.fechafin = value;
  }

  /**
   * Gets the value of the idorigen property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getIdorigen() {
    return idorigen;
  }

  /**
   * Sets the value of the idorigen property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setIdorigen(String value) {
    this.idorigen = value;
  }

  /**
   * Gets the value of the idempresa property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getIdempresa() {
    return idempresa;
  }

  /**
   * Sets the value of the idempresa property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setIdempresa(String value) {
    this.idempresa = value;
  }

  /**
   * Gets the value of the idempleado property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getIdempleado() {
    return idempleado;
  }

  /**
   * Sets the value of the idempleado property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setIdempleado(String value) {
    this.idempleado = value;
  }

  /**
   * Gets the value of the idtipohora property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getIdtipohora() {
    return idtipohora;
  }

  /**
   * Sets the value of the idtipohora property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setIdtipohora(String value) {
    this.idtipohora = value;
  }

  /**
   * Gets the value of the fechainicio property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getFechainicio() {
    return fechainicio;
  }

  /**
   * Sets the value of the fechainicio property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setFechainicio(String value) {
    this.fechainicio = value;
  }

  /**
   * Gets the value of the idlugartrabajo property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getIdlugartrabajo() {
    return idlugartrabajo;
  }

  /**
   * Sets the value of the idlugartrabajo property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setIdlugartrabajo(String value) {
    this.idlugartrabajo = value;
  }

  public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
    if ((object == null) || (this.getClass() != object.getClass())) {
      return false;
    }
    if (this == object) {
      return true;
    }
    final IcmParamcalempleadospresenciaRecord that = ((IcmParamcalempleadospresenciaRecord) object);
    {
      String lhsM4AutoGeneratedRecordID;
      lhsM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
      String rhsM4AutoGeneratedRecordID;
      rhsM4AutoGeneratedRecordID = that.getM4AutoGeneratedRecordID();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedRecordID", lhsM4AutoGeneratedRecordID),
          LocatorUtils.property(thatLocator, "m4AutoGeneratedRecordID", rhsM4AutoGeneratedRecordID), lhsM4AutoGeneratedRecordID,
          rhsM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID != null), (that.m4AutoGeneratedRecordID != null))) {
        return false;
      }
    }
    {
      boolean lhsM4AutoGeneratedToDelete;
      lhsM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
      boolean rhsM4AutoGeneratedToDelete;
      rhsM4AutoGeneratedToDelete = that.isM4AutoGeneratedToDelete();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedToDelete", lhsM4AutoGeneratedToDelete),
          LocatorUtils.property(thatLocator, "m4AutoGeneratedToDelete", rhsM4AutoGeneratedToDelete), lhsM4AutoGeneratedToDelete,
          rhsM4AutoGeneratedToDelete, true, true)) {
        return false;
      }
    }
    {
      String lhsFechafin;
      lhsFechafin = this.getFechafin();
      String rhsFechafin;
      rhsFechafin = that.getFechafin();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "fechafin", lhsFechafin),
          LocatorUtils.property(thatLocator, "fechafin", rhsFechafin), lhsFechafin, rhsFechafin, (this.fechafin != null),
          (that.fechafin != null))) {
        return false;
      }
    }
    {
      String lhsIdorigen;
      lhsIdorigen = this.getIdorigen();
      String rhsIdorigen;
      rhsIdorigen = that.getIdorigen();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "idorigen", lhsIdorigen),
          LocatorUtils.property(thatLocator, "idorigen", rhsIdorigen), lhsIdorigen, rhsIdorigen, (this.idorigen != null),
          (that.idorigen != null))) {
        return false;
      }
    }
    {
      String lhsIdempresa;
      lhsIdempresa = this.getIdempresa();
      String rhsIdempresa;
      rhsIdempresa = that.getIdempresa();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "idempresa", lhsIdempresa),
          LocatorUtils.property(thatLocator, "idempresa", rhsIdempresa), lhsIdempresa, rhsIdempresa, (this.idempresa != null),
          (that.idempresa != null))) {
        return false;
      }
    }
    {
      String lhsIdempleado;
      lhsIdempleado = this.getIdempleado();
      String rhsIdempleado;
      rhsIdempleado = that.getIdempleado();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "idempleado", lhsIdempleado),
          LocatorUtils.property(thatLocator, "idempleado", rhsIdempleado), lhsIdempleado, rhsIdempleado, (this.idempleado != null),
          (that.idempleado != null))) {
        return false;
      }
    }
    {
      String lhsIdtipohora;
      lhsIdtipohora = this.getIdtipohora();
      String rhsIdtipohora;
      rhsIdtipohora = that.getIdtipohora();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "idtipohora", lhsIdtipohora),
          LocatorUtils.property(thatLocator, "idtipohora", rhsIdtipohora), lhsIdtipohora, rhsIdtipohora, (this.idtipohora != null),
          (that.idtipohora != null))) {
        return false;
      }
    }
    {
      String lhsFechainicio;
      lhsFechainicio = this.getFechainicio();
      String rhsFechainicio;
      rhsFechainicio = that.getFechainicio();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "fechainicio", lhsFechainicio),
          LocatorUtils.property(thatLocator, "fechainicio", rhsFechainicio), lhsFechainicio, rhsFechainicio, (this.fechainicio != null),
          (that.fechainicio != null))) {
        return false;
      }
    }
    {
      String lhsIdlugartrabajo;
      lhsIdlugartrabajo = this.getIdlugartrabajo();
      String rhsIdlugartrabajo;
      rhsIdlugartrabajo = that.getIdlugartrabajo();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "idlugartrabajo", lhsIdlugartrabajo),
          LocatorUtils.property(thatLocator, "idlugartrabajo", rhsIdlugartrabajo), lhsIdlugartrabajo, rhsIdlugartrabajo,
          (this.idlugartrabajo != null), (that.idlugartrabajo != null))) {
        return false;
      }
    }
    return true;
  }

  public boolean equals(Object object) {
    final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE2;
    return equals(null, null, object, strategy);
  }

  public String toString() {
    final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE2;
    final StringBuilder buffer = new StringBuilder();
    append(null, buffer, strategy);
    return buffer.toString();
  }

  public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
    strategy.appendStart(locator, this, buffer);
    appendFields(locator, buffer, strategy);
    strategy.appendEnd(locator, this, buffer);
    return buffer;
  }

  public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
    {
      String theM4AutoGeneratedRecordID;
      theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
      strategy.appendField(locator, this, "m4AutoGeneratedRecordID", buffer, theM4AutoGeneratedRecordID,
          (this.m4AutoGeneratedRecordID != null));
    }
    {
      boolean theM4AutoGeneratedToDelete;
      theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
      strategy.appendField(locator, this, "m4AutoGeneratedToDelete", buffer, theM4AutoGeneratedToDelete, true);
    }
    {
      String theFechafin;
      theFechafin = this.getFechafin();
      strategy.appendField(locator, this, "fechafin", buffer, theFechafin, (this.fechafin != null));
    }
    {
      String theIdorigen;
      theIdorigen = this.getIdorigen();
      strategy.appendField(locator, this, "idorigen", buffer, theIdorigen, (this.idorigen != null));
    }
    {
      String theIdempresa;
      theIdempresa = this.getIdempresa();
      strategy.appendField(locator, this, "idempresa", buffer, theIdempresa, (this.idempresa != null));
    }
    {
      String theIdempleado;
      theIdempleado = this.getIdempleado();
      strategy.appendField(locator, this, "idempleado", buffer, theIdempleado, (this.idempleado != null));
    }
    {
      String theIdtipohora;
      theIdtipohora = this.getIdtipohora();
      strategy.appendField(locator, this, "idtipohora", buffer, theIdtipohora, (this.idtipohora != null));
    }
    {
      String theFechainicio;
      theFechainicio = this.getFechainicio();
      strategy.appendField(locator, this, "fechainicio", buffer, theFechainicio, (this.fechainicio != null));
    }
    {
      String theIdlugartrabajo;
      theIdlugartrabajo = this.getIdlugartrabajo();
      strategy.appendField(locator, this, "idlugartrabajo", buffer, theIdlugartrabajo, (this.idlugartrabajo != null));
    }
    return buffer;
  }

  public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
    int currentHashCode = 1;
    {
      String theM4AutoGeneratedRecordID;
      theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", theM4AutoGeneratedRecordID),
          currentHashCode, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID != null));
    }
    {
      boolean theM4AutoGeneratedToDelete;
      theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", theM4AutoGeneratedToDelete),
          currentHashCode, theM4AutoGeneratedToDelete, true);
    }
    {
      String theFechafin;
      theFechafin = this.getFechafin();
      currentHashCode =
          strategy.hashCode(LocatorUtils.property(locator, "fechafin", theFechafin), currentHashCode, theFechafin, (this.fechafin != null));
    }
    {
      String theIdorigen;
      theIdorigen = this.getIdorigen();
      currentHashCode =
          strategy.hashCode(LocatorUtils.property(locator, "idorigen", theIdorigen), currentHashCode, theIdorigen, (this.idorigen != null));
    }
    {
      String theIdempresa;
      theIdempresa = this.getIdempresa();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idempresa", theIdempresa), currentHashCode, theIdempresa,
          (this.idempresa != null));
    }
    {
      String theIdempleado;
      theIdempleado = this.getIdempleado();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idempleado", theIdempleado), currentHashCode, theIdempleado,
          (this.idempleado != null));
    }
    {
      String theIdtipohora;
      theIdtipohora = this.getIdtipohora();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idtipohora", theIdtipohora), currentHashCode, theIdtipohora,
          (this.idtipohora != null));
    }
    {
      String theFechainicio;
      theFechainicio = this.getFechainicio();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fechainicio", theFechainicio), currentHashCode, theFechainicio,
          (this.fechainicio != null));
    }
    {
      String theIdlugartrabajo;
      theIdlugartrabajo = this.getIdlugartrabajo();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idlugartrabajo", theIdlugartrabajo), currentHashCode,
          theIdlugartrabajo, (this.idlugartrabajo != null));
    }
    return currentHashCode;
  }

  public int hashCode() {
    final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE2;
    return this.hashCode(null, strategy);
  }

  public Object clone() {
    return copyTo(createNewInstance());
  }

  public Object copyTo(Object target) {
    final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE2;
    return copyTo(null, target, strategy);
  }

  public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
    final Object draftCopy = ((target == null) ? createNewInstance() : target);
    if (draftCopy instanceof IcmParamcalempleadospresenciaRecord) {
      final IcmParamcalempleadospresenciaRecord copy = ((IcmParamcalempleadospresenciaRecord) draftCopy);
      {
        Boolean m4AutoGeneratedRecordIDShouldBeCopiedAndSet =
            strategy.shouldBeCopiedAndSet(locator, (this.m4AutoGeneratedRecordID != null));
        if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceM4AutoGeneratedRecordID;
          sourceM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
          String copyM4AutoGeneratedRecordID =
              ((String) strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", sourceM4AutoGeneratedRecordID),
                  sourceM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID != null)));
          copy.setM4AutoGeneratedRecordID(copyM4AutoGeneratedRecordID);
        } else {
          if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.m4AutoGeneratedRecordID = null;
          }
        }
      }
      {
        Boolean m4AutoGeneratedToDeleteShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, true);
        if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.TRUE) {
          boolean sourceM4AutoGeneratedToDelete;
          sourceM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
          boolean copyM4AutoGeneratedToDelete =
              strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", sourceM4AutoGeneratedToDelete),
                  sourceM4AutoGeneratedToDelete, true);
          copy.setM4AutoGeneratedToDelete(copyM4AutoGeneratedToDelete);
        } else {
          if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.FALSE) {
          }
        }
      }
      {
        Boolean fechafinShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.fechafin != null));
        if (fechafinShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceFechafin;
          sourceFechafin = this.getFechafin();
          String copyFechafin =
              ((String) strategy.copy(LocatorUtils.property(locator, "fechafin", sourceFechafin), sourceFechafin, (this.fechafin != null)));
          copy.setFechafin(copyFechafin);
        } else {
          if (fechafinShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.fechafin = null;
          }
        }
      }
      {
        Boolean idorigenShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idorigen != null));
        if (idorigenShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceIdorigen;
          sourceIdorigen = this.getIdorigen();
          String copyIdorigen =
              ((String) strategy.copy(LocatorUtils.property(locator, "idorigen", sourceIdorigen), sourceIdorigen, (this.idorigen != null)));
          copy.setIdorigen(copyIdorigen);
        } else {
          if (idorigenShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.idorigen = null;
          }
        }
      }
      {
        Boolean idempresaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idempresa != null));
        if (idempresaShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceIdempresa;
          sourceIdempresa = this.getIdempresa();
          String copyIdempresa = ((String) strategy.copy(LocatorUtils.property(locator, "idempresa", sourceIdempresa), sourceIdempresa,
              (this.idempresa != null)));
          copy.setIdempresa(copyIdempresa);
        } else {
          if (idempresaShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.idempresa = null;
          }
        }
      }
      {
        Boolean idempleadoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idempleado != null));
        if (idempleadoShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceIdempleado;
          sourceIdempleado = this.getIdempleado();
          String copyIdempleado = ((String) strategy.copy(LocatorUtils.property(locator, "idempleado", sourceIdempleado), sourceIdempleado,
              (this.idempleado != null)));
          copy.setIdempleado(copyIdempleado);
        } else {
          if (idempleadoShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.idempleado = null;
          }
        }
      }
      {
        Boolean idtipohoraShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idtipohora != null));
        if (idtipohoraShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceIdtipohora;
          sourceIdtipohora = this.getIdtipohora();
          String copyIdtipohora = ((String) strategy.copy(LocatorUtils.property(locator, "idtipohora", sourceIdtipohora), sourceIdtipohora,
              (this.idtipohora != null)));
          copy.setIdtipohora(copyIdtipohora);
        } else {
          if (idtipohoraShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.idtipohora = null;
          }
        }
      }
      {
        Boolean fechainicioShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.fechainicio != null));
        if (fechainicioShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceFechainicio;
          sourceFechainicio = this.getFechainicio();
          String copyFechainicio = ((String) strategy.copy(LocatorUtils.property(locator, "fechainicio", sourceFechainicio),
              sourceFechainicio, (this.fechainicio != null)));
          copy.setFechainicio(copyFechainicio);
        } else {
          if (fechainicioShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.fechainicio = null;
          }
        }
      }
      {
        Boolean idlugartrabajoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idlugartrabajo != null));
        if (idlugartrabajoShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceIdlugartrabajo;
          sourceIdlugartrabajo = this.getIdlugartrabajo();
          String copyIdlugartrabajo = ((String) strategy.copy(LocatorUtils.property(locator, "idlugartrabajo", sourceIdlugartrabajo),
              sourceIdlugartrabajo, (this.idlugartrabajo != null)));
          copy.setIdlugartrabajo(copyIdlugartrabajo);
        } else {
          if (idlugartrabajoShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.idlugartrabajo = null;
          }
        }
      }
    }
    return draftCopy;
  }

  public Object createNewInstance() {
    return new IcmParamcalempleadospresenciaRecord();
  }

}
