
package com.inditex.rrhh.icmclcwb.model.meta4.icmwscalcincome.entity;

import jakarta.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.3.2 Generated source version: 2.2
 *
 */
@WebFault(name = "fault", targetNamespace = "http://schemas.meta4.com/")
public class M4SoapException_Exception
    extends Exception {

  /**
   * Java type that goes as soapenv:Fault detail element.
   *
   */
  private final M4SoapException faultInfo;

  /**
   *
   * @param faultInfo
   * @param message
   */
  public M4SoapException_Exception(final String message, final M4SoapException faultInfo) {
    super(message);
    this.faultInfo = faultInfo;
  }

  /**
   *
   * @param faultInfo
   * @param cause
   * @param message
   */
  public M4SoapException_Exception(final String message, final M4SoapException faultInfo, final Throwable cause) {
    super(message, cause);
    this.faultInfo = faultInfo;
  }

  /**
   *
   * @return returns fault bean: com.inditex.rrhh.icmclcwb.model.meta4.icmwscalcincome.entity.generated.M4SoapException
   */
  public M4SoapException getFaultInfo() {
    return this.faultInfo;
  }

}
