<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.inditex.amigafwk</groupId>
    <artifactId>amiga-framework</artifactId>
    <version>5.18.2</version>
  </parent>
  <groupId>com.inditex.rrhh.icmclcwb</groupId>
  <artifactId>APPWEB-INCOMEMotorCalculoJava</artifactId>
  <version>4.83.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>${project.groupId}:${project.artifactId}</name>

  <modules>
    <module>APPWEB-INCOMEMotorCalculoJava-pipe</module>
    <module>APPWEB-INCOMEMotorCalculoJava-api</module>
    <module>APPWEB-INCOMEMotorCalculoJava-model</module>
    <module>APPWEB-INCOMEMotorCalculoJava-ws</module>
    <module>APPWEB-INCOMEMotorCalculoJava-ms</module>
    <module>APPWEB-INCOMEMotorCalculoJava-boot</module>
    <module>APPWEB-INCOMEMotorCalculoJava-ws-api</module>
    <module>jacoco-report-aggregate</module>
    <module>APPWEB-INCOMEMotorCalculoJava-rest-clients</module>
    <module>APPWEB-INCOMEMotorCalculoJava-soap-clients</module>
  </modules>

  <scm>
    <connection>scm:git:https://github.com/inditex/mic-incomemotorcalculojava.git</connection>
    <developerConnection>scm:git:https://github.com/inditex/mic-incomemotorcalculojava.git</developerConnection>
    <url>https://github.com/inditex/mic-incomemotorcalculojava</url>
    <tag>HEAD</tag>
  </scm>
  <distributionManagement>
    <repository>
      <id>inditex-artifacts</id>
      <name>Inditex Maven Repository</name>
      <url>https://inditex.jfrog.io/artifactory/maven-release-local</url>
    </repository>
    <snapshotRepository>
      <id>inditex-artifacts</id>
      <name>Inditex Maven Repository</name>
      <url>https://inditex.jfrog.io/artifactory/maven-snapshot-local</url>
    </snapshotRepository>
    <site />
  </distributionManagement>

  <properties>
    <maven.test.skip>false</maven.test.skip>
    <!-- TODO [javierev] se excluyen ficheros markdown porque sonar los confunde con otra cosa (¿MetaDapper?) -->
    <amiga-javaformat.version>3.2.0</amiga-javaformat.version>
    <junit-jupiter-params.version>5.6.3</junit-jupiter-params.version>
    <app.github.chrisvest.version>3.1</app.github.chrisvest.version>
    <app.org.jvnet.jaxb2_commons.version>0.12.0</app.org.jvnet.jaxb2_commons.version>
    <app.org.codehaus.mojo.jaxws-maven-plugin.version>2.6</app.org.codehaus.mojo.jaxws-maven-plugin.version>
    <app.org.codehaus.mojo.wagon-maven-plugin.version>2.0.0</app.org.codehaus.mojo.wagon-maven-plugin.version>
    <project.scm.id>inditex-scm-github</project.scm.id>
    <release.strategy.multibaseline>false</release.strategy.multibaseline>
    <release.strategy.developmentBranch>develop</release.strategy.developmentBranch>
    <release.strategy.syncPullReqLabels>kind/internal</release.strategy.syncPullReqLabels>
    <release.strategy.createSyncPR>true</release.strategy.createSyncPR>
  </properties>

  <dependencyManagement>
    <dependencies>

      <!-- PROJECT DEPENDENCIES -->
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>APPWEB-INCOMEMotorCalculoJava-api</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>APPWEB-INCOMEMotorCalculoJava-model</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>APPWEB-INCOMEMotorCalculoJava-ws</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>APPWEB-INCOMEMotorCalculoJava-ms</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>APPWEB-INCOMEMotorCalculoJava-ws-api</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>APPWEB-INCOMEMotorCalculoJava-pipe</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-release-plugin</artifactId>
          <version>3.0.0</version>
          <dependencies>
            <dependency>
              <groupId>com.inditex.maven.release</groupId>
              <artifactId>maven-release-strategies</artifactId>
              <version>0.7.1</version>
            </dependency>
            <dependency>
              <groupId>org.apache.maven.release</groupId>
              <artifactId>maven-release-semver-policy</artifactId>
              <version>3.0.0</version>
            </dependency>
          </dependencies>
          <configuration>
            <arguments>-DskipEnforceSnapshots -DskipITs -Dbuild.type=release</arguments>
            <goals>deploy</goals>
            <projectVersionPolicyId>SemVerVersionPolicy</projectVersionPolicyId>
            <releaseStrategyId>GithubReleaseStrategy</releaseStrategyId>
            <scmReleaseCommitComment>@{prefix} Prepare release @{releaseLabel}</scmReleaseCommitComment>
            <scmDevelopmentCommitComment>@{prefix} Prepare for next development iteration</scmDevelopmentCommitComment>
            <tagNameFormat>@{project.version}</tagNameFormat>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>com.inditex.libamfmt</groupId>
        <artifactId>amiga-javaformat-maven-plugin</artifactId>
        <version>3.3.0</version>
        <configuration>
          <checkstyle>
            <excludes>com/inditex/rrhh/icmclcwb/model/meta4/icmwscalcincome/entity/**,
              com/inditex/rrhh/icmclcwb/model/meta4/login/entity/**</excludes>
          </checkstyle>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
