package com.inditex.rrhh.icmclcwb.model.meta4.icm_ws_calc_income.mapper;

import java.util.List;

import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

import com.inditex.rrhh.icmclcwb.api.meta4.dto.PageDto;
import com.inditex.rrhh.icmclcwb.api.meta4.icm_ws_income.tiendasempleado.dto.TiendasEmpleadoFilterDto;
import com.inditex.rrhh.icmclcwb.api.meta4.icm_ws_income.tiendasempleado.dto.TiendasEmpleadoFilterParametersDto;
import com.inditex.rrhh.icmclcwb.api.meta4.icm_ws_income.tiendasempleado.dto.TiendasEmpleadoResultItemDto;
import com.inditex.rrhh.icmclcwb.api.meta4.util.Meta4Constants;
import com.inditex.rrhh.icmclcwb.model.meta4.icm_ws_calc_income.entity.IcmListatiendasRecord;
import com.inditex.rrhh.icmclcwb.model.meta4.icm_ws_calc_income.entity.IcmParametrosentradaBlock;
import com.inditex.rrhh.icmclcwb.model.meta4.icm_ws_calc_income.entity.IcmParametrosentradaRecord;
import com.inditex.rrhh.icmclcwb.model.meta4.icm_ws_calc_income.entity.IcmParametrospaginacionBlock;

@Mapper
public interface IcmWsCalcIncomeMapper {

	@Mappings({ @Mapping(source = "tipoorden", target = "tipoOrden"),
		@Mapping(source = "campoorden", target = "campoOrden"),
		@Mapping(source = "idbusqueda", target = "idBusqueda"),
		@Mapping(source = "numeropagina", target = "numeroPagina"),
		@Mapping(source = "numerototalpaginas", target = "numeroTotalPaginas"),
		@Mapping(source = "numeroregistrospagina", target = "numeroRegistrosPagina"),
		@Mapping(source = "numerototalresultados", target = "numeroTotalResultados") })
	PageDto asPageDto(IcmParametrospaginacionBlock src);
	
	@InheritInverseConfiguration
	IcmParametrospaginacionBlock asIcmParametrospaginacionBlock(PageDto src);
	
	@InheritInverseConfiguration
	IcmParametrosentradaBlock asIcmParametrosentradaBlock(TiendasEmpleadoFilterDto src);

	@Mappings({ @Mapping(source = "fechafin", target = "fechaFin", dateFormat = Meta4Constants.META4_DATE_FULL),
				@Mapping(source = "fechainicio", target = "fechaInicio", dateFormat = Meta4Constants.META4_DATE_FULL),
				@Mapping(source = "idorigen", target = "idOrigen"),
				@Mapping(source = "idempresa", target = "idEmpresa"),
				@Mapping(source = "icmParametrosentradaRecordSet", target = "items")
	})
	TiendasEmpleadoFilterDto asTiendasEmpleadoFilterDto(IcmParametrosentradaBlock src);
	
	@Mappings({ @Mapping(source = "idempleado", target = "idEmpleado"),
		@Mapping(source = "orempleado", target = "orEmpleado"),
		@Mapping(source = "idlugartrabajo", target = "idLugarTrabajo")
	})	
	TiendasEmpleadoFilterParametersDto asTiendasEmpleadoFilterParametersDto(IcmParametrosentradaRecord src);

	@Mappings({ @Mapping(source = "m4AutoGeneratedRecordID", target = "m4AutoGeneratedRecordID"),
		@Mapping(source = "m4AutoGeneratedToDelete", target = "m4AutoGeneratedToDelete"),
		@Mapping(source = "idpais", target = "idPais"),
		@Mapping(source = "fechainicio", target = "fechaInicio", dateFormat = Meta4Constants.META4_DATE_FULL),
		@Mapping(source = "fechafin", target = "fechaFin", dateFormat = Meta4Constants.META4_DATE_FULL),
		@Mapping(source = "idcadena", target = "idCadena"),
		@Mapping(source = "idorigen", target = "idOrigen"),
		@Mapping(source = "idempresa", target = "idEmpresa"),
		@Mapping(source = "idtiendamtu", target = "idTiendaMtu"),
		@Mapping(source = "escomisionable", target = "esComisionable"),
		@Mapping(source = "idlugartrabajo", target = "idLugarTrabajo")})
	TiendasEmpleadoResultItemDto asTiendasEmpleadoResultItemDto(IcmListatiendasRecord src);

	@InheritInverseConfiguration
	IcmListatiendasRecord asIcmListatiendasRecord(TiendasEmpleadoResultItemDto src);

	List<TiendasEmpleadoResultItemDto> asTiendasEmpleadoResultItemDtos(List<IcmListatiendasRecord> src);

	
	
}
