package com.inditex.rrhh.icmclcwb.model.meta4.icm_ws_calc_income.mapper;

import java.util.List;

import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

import com.inditex.rrhh.icmclcwb.api.meta4.dto.PageDto;
import com.inditex.rrhh.icmclcwb.api.meta4.icm_ws_income.generic.dto.GenericEmpleadoResultItemDto;
import com.inditex.rrhh.icmclcwb.api.meta4.icm_ws_income.generic.dto.GenericFilterDto;
import com.inditex.rrhh.icmclcwb.api.meta4.icm_ws_income.generic.dto.GenericTiendaResultItemDto;
import com.inditex.rrhh.icmclcwb.api.meta4.util.Meta4Constants;
import com.inditex.rrhh.icmclcwb.model.meta4.icm_ws_calc_income.entity.IcmListaempleadosRecord;
import com.inditex.rrhh.icmclcwb.model.meta4.icm_ws_calc_income.entity.IcmListatiendasRecord;
import com.inditex.rrhh.icmclcwb.model.meta4.icm_ws_calc_income.entity.IcmParametrosentradaBlock;
import com.inditex.rrhh.icmclcwb.model.meta4.icm_ws_calc_income.entity.IcmParametrospaginacionBlock;

@Mapper
public interface IcmWsCalcIncomeMapper {

	@Mappings({ @Mapping(source = "tipoorden", target = "tipoOrden"),
		@Mapping(source = "campoorden", target = "campoOrden"),
		@Mapping(source = "idbusqueda", target = "idBusqueda"),
		@Mapping(source = "numeropagina", target = "numeroPagina"),
		@Mapping(source = "numerototalpaginas", target = "numeroTotalPaginas"),
		@Mapping(source = "numeroregistrospagina", target = "numeroRegistrosPagina"),
		@Mapping(source = "numerototalresultados", target = "numeroTotalResultados") })
	PageDto asPageDto(IcmParametrospaginacionBlock src);
	
	@InheritInverseConfiguration
	IcmParametrospaginacionBlock asIcmParametrospaginacionBlock(PageDto src);
	

	@InheritInverseConfiguration
	IcmParametrosentradaBlock asIcmParametrosentradaBlock(GenericFilterDto src);

	@Mappings({ @Mapping(source = "fechafin", target = "fechaFin", dateFormat = Meta4Constants.META4_DATE_FULL),
				@Mapping(source = "fechainicio", target = "fechaInicio", dateFormat = Meta4Constants.META4_DATE_FULL),
				@Mapping(source = "idorigen", target = "idOrigen"),
				@Mapping(source = "idempresa", target = "idEmpresa"),
				@Mapping(source = "icmParametrosentradaRecordSet", target = "items")
	})
	GenericFilterDto asGenericFilterDto(IcmParametrosentradaBlock src);
	
	@Mappings({ @Mapping(source = "m4AutoGeneratedRecordID", target = "m4AutoGeneratedRecordID"),
		@Mapping(source = "m4AutoGeneratedToDelete", target = "m4AutoGeneratedToDelete"),
		@Mapping(source = "idpais", target = "idPais"),
		@Mapping(source = "fechainicio", target = "fechaInicio", dateFormat = Meta4Constants.META4_DATE_FULL),
		@Mapping(source = "fechafin", target = "fechaFin", dateFormat = Meta4Constants.META4_DATE_FULL),
		@Mapping(source = "idcadena", target = "idCadena"),
		@Mapping(source = "idorigen", target = "idOrigen"),
		@Mapping(source = "idempresa", target = "idEmpresa"),
		@Mapping(source = "idtiendamtu", target = "idTiendaMtu"),
		@Mapping(source = "escomisionable", target = "esComisionable"),
		@Mapping(source = "idlugartrabajo", target = "idLugarTrabajo")})
	GenericTiendaResultItemDto asGenericTiendaResultItemDto(IcmListatiendasRecord src);

	@InheritInverseConfiguration
	IcmListatiendasRecord asIcmListatiendasRecord(GenericTiendaResultItemDto src);

	List<GenericTiendaResultItemDto> asGenericTiendaResultItemDtos(List<IcmListatiendasRecord> src);
	
	
	@Mappings({ @Mapping(source = "m4AutoGeneratedRecordID", target = "m4AutoGeneratedRecordID"),
		@Mapping(source = "m4AutoGeneratedToDelete", target = "m4AutoGeneratedToDelete"),
		@Mapping(source = "valor", target = "valor"),
		@Mapping(source = "fechainicio", target = "fechaInicio", dateFormat = Meta4Constants.META4_DATE_FULL),
		@Mapping(source = "fechafin", target = "fechaFin", dateFormat = Meta4Constants.META4_DATE_FULL),
		@Mapping(source = "idcadena", target = "idCadena"),
		@Mapping(source = "idorigen", target = "idOrigen"),
		@Mapping(source = "idpais", target = "idPais"),
		@Mapping(source = "idempresa", target = "idEmpresa"),
		@Mapping(source = "idempleado", target = "idEmpleado"),
		@Mapping(source = "orempleado", target = "orEmpleado"),
		@Mapping(source = "idtiendamtu", target = "idTiendaMtu"),
		@Mapping(source = "idcomponente", target = "idComponente"),
		@Mapping(source = "idtipocalculo", target = "idTipoCalculo"),
		@Mapping(source = "percentageboy", target = "percentageBoy"),
		@Mapping(source = "percentageman", target = "percentageMan"),
		@Mapping(source = "escomisionable", target = "esComisionable"),
		@Mapping(source = "idlugartrabajo", target = "idLugarTrabajo"),
		@Mapping(source = "idempleadolocal", target = "idEmpleadoLocal"),
		@Mapping(source = "percentagewoman", target = "percentageWoman")
		})
	GenericEmpleadoResultItemDto asGenericEmpleadoResultItemDto(IcmListaempleadosRecord src);

	@InheritInverseConfiguration
	IcmListaempleadosRecord asIcmListatiendasRecord(GenericEmpleadoResultItemDto src);

	List<GenericEmpleadoResultItemDto> asGenericEmpleadoResultItemDtos(List<IcmListaempleadosRecord> src);

	
}
