package com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.agruponline.dto;

import java.io.Serializable;

import lombok.Data;

@Data
public class AgrupOnlineResultItemDto implements Serializable {

  private static final long serialVersionUID = 3625846058717086929L;

  private String m4AutoGeneratedRecordID;

  private boolean m4AutoGeneratedToDelete;

  private String fechaFin;

  private String idCadena;

  private String idOrigen;

  private String idEmpresa;

  private String idConcepto;

  private String idProducto;

  private String porcentaje;

  private String fechaInicio;

  private String idAgrupacion;

}
