<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.inditex.rrhh.icmclcwb</groupId>
    <artifactId>APPWEB-INCOMEMotorCalculoJava</artifactId>
    <version>4.51.0</version>
  </parent>
  <artifactId>APPWEB-INCOMEMotorCalculoJava-boot</artifactId>
  <packaging>jar</packaging>
  <name>${project.groupId}:${project.artifactId}</name>

  <dependencies>
    <!-- PROJECT DEPENDENCIES -->
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-ws</artifactId>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-ms</artifactId>
    </dependency>

    <!-- FWK DEPENDENCIES -->
    <dependency>
      <groupId>com.inditex.aqsw.framework.common</groupId>
      <artifactId>common-framework-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.aqsw.framework.data</groupId>
      <artifactId>data-framework-starter-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.aqsw.framework.common</groupId>
      <artifactId>common-framework-starter-async</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.aqsw.framework.common</groupId>
      <artifactId>common-framework-starter-rest-client</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.aqsw.framework.common</groupId>
      <artifactId>common-framework-starter-oauth2-client</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.aqsw.framework.common</groupId>
      <artifactId>common-framework-starter-executor</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.aqsw.framework.common</groupId>
      <artifactId>common-framework-starter-cache-datagrid-embedded</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.aqsw.framework.common</groupId>
      <artifactId>common-framework-starter-cache-datagrid-remote</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
      <optional>true</optional>
    </dependency>

    <!-- CLIENT DEPENDENCIES -->
    <dependency>
      <groupId>org.apache.cxf</groupId>
      <artifactId>cxf-rt-frontend-jaxws</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.cxf</groupId>
      <artifactId>cxf-rt-transports-http</artifactId>
    </dependency>
    <dependency>
      <groupId>com.github.chrisvest</groupId>
      <artifactId>stormpot</artifactId>
      <version>${app.github.chrisvest.version}</version>
    </dependency>

    <!-- BBDD DEPENDENCIES -->
    <dependency>
      <groupId>com.ibm.db2</groupId>
      <artifactId>db2jcc4</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.oracle.database.jdbc</groupId>
      <artifactId>ojdbc10</artifactId>
      <scope>runtime</scope>
      <exclusions>
        <exclusion>
          <groupId>com.oracle.jdbc</groupId>
          <artifactId>xmlparserv2</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <!-- OTHER DEPENDENCIES -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- TEST DEPENDENCIES -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.inditex.aqsw.framework.test</groupId>
      <artifactId>test-framework-randomizer</artifactId>
      <version>3.3.0</version>
      <scope>test</scope>
    </dependency>

  </dependencies>
</project>
