<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.inditex.rrhh.icmclcwb</groupId>
    <artifactId>APPWEB-INCOMEMotorCalculoJava</artifactId>
    <version>4.79.0-SNAPSHOT</version>
  </parent>
  <artifactId>APPWEB-INCOMEMotorCalculoJava-model</artifactId>
  <name>${project.groupId}:${project.artifactId}</name>
  <description>Este módulo se proporciona para que el ejemplo funcione, pero lo recomendable es que no exista
    dentro del proyecto, y en su lugar se importe una librería con el api y el acceso a datos.</description>

  <dependencies>

    <!-- PROJECT DEPENDENCIES -->
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-api</artifactId>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-ms</artifactId>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-pipe</artifactId>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-client-soap-api-incomemotorcalculometa</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-client-soap-api-incomemotorcalculometalogin</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- FRAMEWORK DEPENDENCIES -->
    <dependency>
      <groupId>com.inditex.amigafwk.common</groupId>
      <artifactId>common-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.amigafwk.data</groupId>
      <artifactId>data-starter-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.amigafwk.common</groupId>
      <artifactId>common-starter-reactor</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.amigafwk.common</groupId>
      <artifactId>common-starter-rest-client</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.amigafwk.common</groupId>
      <artifactId>common-starter-retry</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.amigafwk.common</groupId>
      <artifactId>common-starter-metrics-annotation</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.amigafwk.common</groupId>
      <artifactId>common-starter-mail</artifactId>
    </dependency>

    <!-- OTHER DEPENDENCIES -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.jvnet.jaxb2_commons</groupId>
      <artifactId>jaxb2-basics-runtime</artifactId>
      <version>${app.org.jvnet.jaxb2_commons.version}</version>
    </dependency>

    <!-- CLIENT DEPENDENCIES -->
    <dependency>
      <groupId>org.apache.cxf</groupId>
      <artifactId>cxf-rt-frontend-jaxws</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.cxf</groupId>
      <artifactId>cxf-rt-transports-http</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.cxf</groupId>
      <artifactId>cxf-rt-features-logging</artifactId>
      <version>${cxf.version}</version>
    </dependency>
    <dependency>
      <groupId>com.github.chrisvest</groupId>
      <artifactId>stormpot</artifactId>
      <version>${app.github.chrisvest.version}</version>
    </dependency>

    <!-- TEST -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
      <version>${junit-jupiter-params.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.inditex.amigafwk.test</groupId>
      <artifactId>test-starter-instancio</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

</project>
