package com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.tiendasonline.dto;

import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

@Data
public class TiendaOnlineResultItemDto implements Serializable {

    private static final long serialVersionUID = -1933236363737256885L;

    private String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private LocalDateTime fechaInicio;
    private LocalDateTime fechaFin;
    private String idCadena;
    private String idOrigen;
    private String idEmpresa;
    private Long idLocalizacion;
    private String idLocalizacionMeta4;
}
