
package com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.icm_ws_income.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Clase Java para Icm_CalendarioempleadoRecord complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="Icm_CalendarioempleadoRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="inout" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="moneda" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechafin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechapago" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombrepago" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechainicio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idestadopago" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="periodoactivo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idfrecuenciapago" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="comisioncalculada" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_CalendarioempleadoRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "inout",
    "moneda",
    "fechafin",
    "fechapago",
    "nombrepago",
    "fechainicio",
    "idestadopago",
    "periodoactivo",
    "idfrecuenciapago",
    "comisioncalculada"
})
public class IcmCalendarioempleadoRecord {

    @XmlElement(required = true, nillable = true)
    protected String m4AutoGeneratedRecordID;
    protected boolean m4AutoGeneratedToDelete;
    @XmlElement(required = true, nillable = true)
    protected String inout;
    @XmlElement(required = true, nillable = true)
    protected String moneda;
    @XmlElement(required = true, nillable = true)
    protected String fechafin;
    @XmlElement(required = true, nillable = true)
    protected String fechapago;
    @XmlElement(required = true, nillable = true)
    protected String nombrepago;
    @XmlElement(required = true, nillable = true)
    protected String fechainicio;
    @XmlElement(required = true, nillable = true)
    protected String idestadopago;
    @XmlElement(required = true, nillable = true)
    protected String periodoactivo;
    @XmlElement(required = true, nillable = true)
    protected String idfrecuenciapago;
    @XmlElement(required = true, nillable = true)
    protected String comisioncalculada;

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM4AutoGeneratedRecordID(String value) {
        this.m4AutoGeneratedRecordID = value;
    }

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public void setM4AutoGeneratedToDelete(boolean value) {
        this.m4AutoGeneratedToDelete = value;
    }

    /**
     * Obtiene el valor de la propiedad inout.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInout() {
        return inout;
    }

    /**
     * Define el valor de la propiedad inout.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInout(String value) {
        this.inout = value;
    }

    /**
     * Obtiene el valor de la propiedad moneda.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoneda() {
        return moneda;
    }

    /**
     * Define el valor de la propiedad moneda.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoneda(String value) {
        this.moneda = value;
    }

    /**
     * Obtiene el valor de la propiedad fechafin.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechafin() {
        return fechafin;
    }

    /**
     * Define el valor de la propiedad fechafin.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechafin(String value) {
        this.fechafin = value;
    }

    /**
     * Obtiene el valor de la propiedad fechapago.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechapago() {
        return fechapago;
    }

    /**
     * Define el valor de la propiedad fechapago.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechapago(String value) {
        this.fechapago = value;
    }

    /**
     * Obtiene el valor de la propiedad nombrepago.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombrepago() {
        return nombrepago;
    }

    /**
     * Define el valor de la propiedad nombrepago.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombrepago(String value) {
        this.nombrepago = value;
    }

    /**
     * Obtiene el valor de la propiedad fechainicio.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechainicio() {
        return fechainicio;
    }

    /**
     * Define el valor de la propiedad fechainicio.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechainicio(String value) {
        this.fechainicio = value;
    }

    /**
     * Obtiene el valor de la propiedad idestadopago.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdestadopago() {
        return idestadopago;
    }

    /**
     * Define el valor de la propiedad idestadopago.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdestadopago(String value) {
        this.idestadopago = value;
    }

    /**
     * Obtiene el valor de la propiedad periodoactivo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodoactivo() {
        return periodoactivo;
    }

    /**
     * Define el valor de la propiedad periodoactivo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodoactivo(String value) {
        this.periodoactivo = value;
    }

    /**
     * Obtiene el valor de la propiedad idfrecuenciapago.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdfrecuenciapago() {
        return idfrecuenciapago;
    }

    /**
     * Define el valor de la propiedad idfrecuenciapago.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdfrecuenciapago(String value) {
        this.idfrecuenciapago = value;
    }

    /**
     * Obtiene el valor de la propiedad comisioncalculada.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComisioncalculada() {
        return comisioncalculada;
    }

    /**
     * Define el valor de la propiedad comisioncalculada.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComisioncalculada(String value) {
        this.comisioncalculada = value;
    }

}
