
package com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.icm_ws_income.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Clase Java para Icm_CondicionesventaRecord complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="Icm_CondicionesventaRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="inout" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nuevo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="borrado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechafin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idcadena" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="modificado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechainicio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idcanalventa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombrecadena" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="porcexcluido" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idorigenstock" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idpuntoentrega" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombrecanalventa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombreorigenstock" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombrepuntoentrega" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_CondicionesventaRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "inout",
    "nuevo",
    "borrado",
    "fechafin",
    "idcadena",
    "modificado",
    "fechainicio",
    "idcanalventa",
    "nombrecadena",
    "porcexcluido",
    "idorigenstock",
    "idpuntoentrega",
    "nombrecanalventa",
    "nombreorigenstock",
    "nombrepuntoentrega"
})
public class IcmCondicionesventaRecord {

    @XmlElement(required = true, nillable = true)
    protected String m4AutoGeneratedRecordID;
    protected boolean m4AutoGeneratedToDelete;
    @XmlElement(required = true, nillable = true)
    protected String inout;
    @XmlElement(required = true, nillable = true)
    protected String nuevo;
    @XmlElement(required = true, nillable = true)
    protected String borrado;
    @XmlElement(required = true, nillable = true)
    protected String fechafin;
    @XmlElement(required = true, nillable = true)
    protected String idcadena;
    @XmlElement(required = true, nillable = true)
    protected String modificado;
    @XmlElement(required = true, nillable = true)
    protected String fechainicio;
    @XmlElement(required = true, nillable = true)
    protected String idcanalventa;
    @XmlElement(required = true, nillable = true)
    protected String nombrecadena;
    @XmlElement(required = true, nillable = true)
    protected String porcexcluido;
    @XmlElement(required = true, nillable = true)
    protected String idorigenstock;
    @XmlElement(required = true, nillable = true)
    protected String idpuntoentrega;
    @XmlElement(required = true, nillable = true)
    protected String nombrecanalventa;
    @XmlElement(required = true, nillable = true)
    protected String nombreorigenstock;
    @XmlElement(required = true, nillable = true)
    protected String nombrepuntoentrega;

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM4AutoGeneratedRecordID(String value) {
        this.m4AutoGeneratedRecordID = value;
    }

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public void setM4AutoGeneratedToDelete(boolean value) {
        this.m4AutoGeneratedToDelete = value;
    }

    /**
     * Obtiene el valor de la propiedad inout.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInout() {
        return inout;
    }

    /**
     * Define el valor de la propiedad inout.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInout(String value) {
        this.inout = value;
    }

    /**
     * Obtiene el valor de la propiedad nuevo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuevo() {
        return nuevo;
    }

    /**
     * Define el valor de la propiedad nuevo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuevo(String value) {
        this.nuevo = value;
    }

    /**
     * Obtiene el valor de la propiedad borrado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrado() {
        return borrado;
    }

    /**
     * Define el valor de la propiedad borrado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrado(String value) {
        this.borrado = value;
    }

    /**
     * Obtiene el valor de la propiedad fechafin.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechafin() {
        return fechafin;
    }

    /**
     * Define el valor de la propiedad fechafin.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechafin(String value) {
        this.fechafin = value;
    }

    /**
     * Obtiene el valor de la propiedad idcadena.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdcadena() {
        return idcadena;
    }

    /**
     * Define el valor de la propiedad idcadena.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdcadena(String value) {
        this.idcadena = value;
    }

    /**
     * Obtiene el valor de la propiedad modificado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificado() {
        return modificado;
    }

    /**
     * Define el valor de la propiedad modificado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificado(String value) {
        this.modificado = value;
    }

    /**
     * Obtiene el valor de la propiedad fechainicio.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechainicio() {
        return fechainicio;
    }

    /**
     * Define el valor de la propiedad fechainicio.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechainicio(String value) {
        this.fechainicio = value;
    }

    /**
     * Obtiene el valor de la propiedad idcanalventa.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdcanalventa() {
        return idcanalventa;
    }

    /**
     * Define el valor de la propiedad idcanalventa.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdcanalventa(String value) {
        this.idcanalventa = value;
    }

    /**
     * Obtiene el valor de la propiedad nombrecadena.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombrecadena() {
        return nombrecadena;
    }

    /**
     * Define el valor de la propiedad nombrecadena.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombrecadena(String value) {
        this.nombrecadena = value;
    }

    /**
     * Obtiene el valor de la propiedad porcexcluido.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPorcexcluido() {
        return porcexcluido;
    }

    /**
     * Define el valor de la propiedad porcexcluido.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPorcexcluido(String value) {
        this.porcexcluido = value;
    }

    /**
     * Obtiene el valor de la propiedad idorigenstock.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdorigenstock() {
        return idorigenstock;
    }

    /**
     * Define el valor de la propiedad idorigenstock.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdorigenstock(String value) {
        this.idorigenstock = value;
    }

    /**
     * Obtiene el valor de la propiedad idpuntoentrega.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdpuntoentrega() {
        return idpuntoentrega;
    }

    /**
     * Define el valor de la propiedad idpuntoentrega.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdpuntoentrega(String value) {
        this.idpuntoentrega = value;
    }

    /**
     * Obtiene el valor de la propiedad nombrecanalventa.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombrecanalventa() {
        return nombrecanalventa;
    }

    /**
     * Define el valor de la propiedad nombrecanalventa.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombrecanalventa(String value) {
        this.nombrecanalventa = value;
    }

    /**
     * Obtiene el valor de la propiedad nombreorigenstock.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreorigenstock() {
        return nombreorigenstock;
    }

    /**
     * Define el valor de la propiedad nombreorigenstock.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreorigenstock(String value) {
        this.nombreorigenstock = value;
    }

    /**
     * Obtiene el valor de la propiedad nombrepuntoentrega.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombrepuntoentrega() {
        return nombrepuntoentrega;
    }

    /**
     * Define el valor de la propiedad nombrepuntoentrega.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombrepuntoentrega(String value) {
        this.nombrepuntoentrega = value;
    }

}
