
package com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.icm_ws_income.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Clase Java para Icm_DatosgentiendaRecord complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="Icm_DatosgentiendaRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="inout" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idestado1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idestado2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idestado3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="comisionable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idestadomtu1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idestadomtu2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idestadomtu3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombreestado1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombreestado2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombreestado3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idlugartrabajo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombreestadomtu1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombreestadomtu2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombreestadomtu3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombrelugartrabajo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_DatosgentiendaRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "inout",
    "idestado1",
    "idestado2",
    "idestado3",
    "comisionable",
    "idestadomtu1",
    "idestadomtu2",
    "idestadomtu3",
    "nombreestado1",
    "nombreestado2",
    "nombreestado3",
    "idlugartrabajo",
    "nombreestadomtu1",
    "nombreestadomtu2",
    "nombreestadomtu3",
    "nombrelugartrabajo"
})
public class IcmDatosgentiendaRecord {

    @XmlElement(required = true, nillable = true)
    protected String m4AutoGeneratedRecordID;
    protected boolean m4AutoGeneratedToDelete;
    @XmlElement(required = true, nillable = true)
    protected String inout;
    @XmlElement(required = true, nillable = true)
    protected String idestado1;
    @XmlElement(required = true, nillable = true)
    protected String idestado2;
    @XmlElement(required = true, nillable = true)
    protected String idestado3;
    @XmlElement(required = true, nillable = true)
    protected String comisionable;
    @XmlElement(required = true, nillable = true)
    protected String idestadomtu1;
    @XmlElement(required = true, nillable = true)
    protected String idestadomtu2;
    @XmlElement(required = true, nillable = true)
    protected String idestadomtu3;
    @XmlElement(required = true, nillable = true)
    protected String nombreestado1;
    @XmlElement(required = true, nillable = true)
    protected String nombreestado2;
    @XmlElement(required = true, nillable = true)
    protected String nombreestado3;
    @XmlElement(required = true, nillable = true)
    protected String idlugartrabajo;
    @XmlElement(required = true, nillable = true)
    protected String nombreestadomtu1;
    @XmlElement(required = true, nillable = true)
    protected String nombreestadomtu2;
    @XmlElement(required = true, nillable = true)
    protected String nombreestadomtu3;
    @XmlElement(required = true, nillable = true)
    protected String nombrelugartrabajo;

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM4AutoGeneratedRecordID(String value) {
        this.m4AutoGeneratedRecordID = value;
    }

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public void setM4AutoGeneratedToDelete(boolean value) {
        this.m4AutoGeneratedToDelete = value;
    }

    /**
     * Obtiene el valor de la propiedad inout.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInout() {
        return inout;
    }

    /**
     * Define el valor de la propiedad inout.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInout(String value) {
        this.inout = value;
    }

    /**
     * Obtiene el valor de la propiedad idestado1.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdestado1() {
        return idestado1;
    }

    /**
     * Define el valor de la propiedad idestado1.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdestado1(String value) {
        this.idestado1 = value;
    }

    /**
     * Obtiene el valor de la propiedad idestado2.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdestado2() {
        return idestado2;
    }

    /**
     * Define el valor de la propiedad idestado2.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdestado2(String value) {
        this.idestado2 = value;
    }

    /**
     * Obtiene el valor de la propiedad idestado3.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdestado3() {
        return idestado3;
    }

    /**
     * Define el valor de la propiedad idestado3.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdestado3(String value) {
        this.idestado3 = value;
    }

    /**
     * Obtiene el valor de la propiedad comisionable.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComisionable() {
        return comisionable;
    }

    /**
     * Define el valor de la propiedad comisionable.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComisionable(String value) {
        this.comisionable = value;
    }

    /**
     * Obtiene el valor de la propiedad idestadomtu1.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdestadomtu1() {
        return idestadomtu1;
    }

    /**
     * Define el valor de la propiedad idestadomtu1.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdestadomtu1(String value) {
        this.idestadomtu1 = value;
    }

    /**
     * Obtiene el valor de la propiedad idestadomtu2.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdestadomtu2() {
        return idestadomtu2;
    }

    /**
     * Define el valor de la propiedad idestadomtu2.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdestadomtu2(String value) {
        this.idestadomtu2 = value;
    }

    /**
     * Obtiene el valor de la propiedad idestadomtu3.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdestadomtu3() {
        return idestadomtu3;
    }

    /**
     * Define el valor de la propiedad idestadomtu3.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdestadomtu3(String value) {
        this.idestadomtu3 = value;
    }

    /**
     * Obtiene el valor de la propiedad nombreestado1.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreestado1() {
        return nombreestado1;
    }

    /**
     * Define el valor de la propiedad nombreestado1.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreestado1(String value) {
        this.nombreestado1 = value;
    }

    /**
     * Obtiene el valor de la propiedad nombreestado2.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreestado2() {
        return nombreestado2;
    }

    /**
     * Define el valor de la propiedad nombreestado2.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreestado2(String value) {
        this.nombreestado2 = value;
    }

    /**
     * Obtiene el valor de la propiedad nombreestado3.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreestado3() {
        return nombreestado3;
    }

    /**
     * Define el valor de la propiedad nombreestado3.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreestado3(String value) {
        this.nombreestado3 = value;
    }

    /**
     * Obtiene el valor de la propiedad idlugartrabajo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdlugartrabajo() {
        return idlugartrabajo;
    }

    /**
     * Define el valor de la propiedad idlugartrabajo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdlugartrabajo(String value) {
        this.idlugartrabajo = value;
    }

    /**
     * Obtiene el valor de la propiedad nombreestadomtu1.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreestadomtu1() {
        return nombreestadomtu1;
    }

    /**
     * Define el valor de la propiedad nombreestadomtu1.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreestadomtu1(String value) {
        this.nombreestadomtu1 = value;
    }

    /**
     * Obtiene el valor de la propiedad nombreestadomtu2.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreestadomtu2() {
        return nombreestadomtu2;
    }

    /**
     * Define el valor de la propiedad nombreestadomtu2.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreestadomtu2(String value) {
        this.nombreestadomtu2 = value;
    }

    /**
     * Obtiene el valor de la propiedad nombreestadomtu3.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreestadomtu3() {
        return nombreestadomtu3;
    }

    /**
     * Define el valor de la propiedad nombreestadomtu3.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreestadomtu3(String value) {
        this.nombreestadomtu3 = value;
    }

    /**
     * Obtiene el valor de la propiedad nombrelugartrabajo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombrelugartrabajo() {
        return nombrelugartrabajo;
    }

    /**
     * Define el valor de la propiedad nombrelugartrabajo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombrelugartrabajo(String value) {
        this.nombrelugartrabajo = value;
    }

}
