
package com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.icm_ws_income.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Clase Java para Icm_PresenciamanualRecord complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="Icm_PresenciamanualRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="fecha" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="horas" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="inout" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nuevo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="borrado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="minutos" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idmotivo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idseccion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idempleado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idtipohora" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="modificado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="orempleado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="orpresencia" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="estrasladada" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idtipoorigen" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombremotivo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="porctraslado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombreseccion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idlugartrabajo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombreempleado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombretipohora" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechatrasladada" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idempleadolocal" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombrelugartrabajo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_PresenciamanualRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "fecha",
    "horas",
    "inout",
    "nuevo",
    "borrado",
    "minutos",
    "idmotivo",
    "idseccion",
    "idempleado",
    "idtipohora",
    "modificado",
    "orempleado",
    "orpresencia",
    "estrasladada",
    "idtipoorigen",
    "nombremotivo",
    "porctraslado",
    "nombreseccion",
    "idlugartrabajo",
    "nombreempleado",
    "nombretipohora",
    "fechatrasladada",
    "idempleadolocal",
    "nombrelugartrabajo"
})
public class IcmPresenciamanualRecord {

    @XmlElement(required = true, nillable = true)
    protected String m4AutoGeneratedRecordID;
    protected boolean m4AutoGeneratedToDelete;
    @XmlElement(required = true, nillable = true)
    protected String fecha;
    @XmlElement(required = true, nillable = true)
    protected String horas;
    @XmlElement(required = true, nillable = true)
    protected String inout;
    @XmlElement(required = true, nillable = true)
    protected String nuevo;
    @XmlElement(required = true, nillable = true)
    protected String borrado;
    @XmlElement(required = true, nillable = true)
    protected String minutos;
    @XmlElement(required = true, nillable = true)
    protected String idmotivo;
    @XmlElement(required = true, nillable = true)
    protected String idseccion;
    @XmlElement(required = true, nillable = true)
    protected String idempleado;
    @XmlElement(required = true, nillable = true)
    protected String idtipohora;
    @XmlElement(required = true, nillable = true)
    protected String modificado;
    @XmlElement(required = true, nillable = true)
    protected String orempleado;
    @XmlElement(required = true, nillable = true)
    protected String orpresencia;
    @XmlElement(required = true, nillable = true)
    protected String estrasladada;
    @XmlElement(required = true, nillable = true)
    protected String idtipoorigen;
    @XmlElement(required = true, nillable = true)
    protected String nombremotivo;
    @XmlElement(required = true, nillable = true)
    protected String porctraslado;
    @XmlElement(required = true, nillable = true)
    protected String nombreseccion;
    @XmlElement(required = true, nillable = true)
    protected String idlugartrabajo;
    @XmlElement(required = true, nillable = true)
    protected String nombreempleado;
    @XmlElement(required = true, nillable = true)
    protected String nombretipohora;
    @XmlElement(required = true, nillable = true)
    protected String fechatrasladada;
    @XmlElement(required = true, nillable = true)
    protected String idempleadolocal;
    @XmlElement(required = true, nillable = true)
    protected String nombrelugartrabajo;

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM4AutoGeneratedRecordID(String value) {
        this.m4AutoGeneratedRecordID = value;
    }

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public void setM4AutoGeneratedToDelete(boolean value) {
        this.m4AutoGeneratedToDelete = value;
    }

    /**
     * Obtiene el valor de la propiedad fecha.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFecha() {
        return fecha;
    }

    /**
     * Define el valor de la propiedad fecha.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFecha(String value) {
        this.fecha = value;
    }

    /**
     * Obtiene el valor de la propiedad horas.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoras() {
        return horas;
    }

    /**
     * Define el valor de la propiedad horas.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoras(String value) {
        this.horas = value;
    }

    /**
     * Obtiene el valor de la propiedad inout.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInout() {
        return inout;
    }

    /**
     * Define el valor de la propiedad inout.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInout(String value) {
        this.inout = value;
    }

    /**
     * Obtiene el valor de la propiedad nuevo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuevo() {
        return nuevo;
    }

    /**
     * Define el valor de la propiedad nuevo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuevo(String value) {
        this.nuevo = value;
    }

    /**
     * Obtiene el valor de la propiedad borrado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrado() {
        return borrado;
    }

    /**
     * Define el valor de la propiedad borrado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrado(String value) {
        this.borrado = value;
    }

    /**
     * Obtiene el valor de la propiedad minutos.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinutos() {
        return minutos;
    }

    /**
     * Define el valor de la propiedad minutos.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinutos(String value) {
        this.minutos = value;
    }

    /**
     * Obtiene el valor de la propiedad idmotivo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdmotivo() {
        return idmotivo;
    }

    /**
     * Define el valor de la propiedad idmotivo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdmotivo(String value) {
        this.idmotivo = value;
    }

    /**
     * Obtiene el valor de la propiedad idseccion.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdseccion() {
        return idseccion;
    }

    /**
     * Define el valor de la propiedad idseccion.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdseccion(String value) {
        this.idseccion = value;
    }

    /**
     * Obtiene el valor de la propiedad idempleado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdempleado() {
        return idempleado;
    }

    /**
     * Define el valor de la propiedad idempleado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdempleado(String value) {
        this.idempleado = value;
    }

    /**
     * Obtiene el valor de la propiedad idtipohora.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdtipohora() {
        return idtipohora;
    }

    /**
     * Define el valor de la propiedad idtipohora.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdtipohora(String value) {
        this.idtipohora = value;
    }

    /**
     * Obtiene el valor de la propiedad modificado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificado() {
        return modificado;
    }

    /**
     * Define el valor de la propiedad modificado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificado(String value) {
        this.modificado = value;
    }

    /**
     * Obtiene el valor de la propiedad orempleado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrempleado() {
        return orempleado;
    }

    /**
     * Define el valor de la propiedad orempleado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrempleado(String value) {
        this.orempleado = value;
    }

    /**
     * Obtiene el valor de la propiedad orpresencia.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrpresencia() {
        return orpresencia;
    }

    /**
     * Define el valor de la propiedad orpresencia.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrpresencia(String value) {
        this.orpresencia = value;
    }

    /**
     * Obtiene el valor de la propiedad estrasladada.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstrasladada() {
        return estrasladada;
    }

    /**
     * Define el valor de la propiedad estrasladada.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstrasladada(String value) {
        this.estrasladada = value;
    }

    /**
     * Obtiene el valor de la propiedad idtipoorigen.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdtipoorigen() {
        return idtipoorigen;
    }

    /**
     * Define el valor de la propiedad idtipoorigen.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdtipoorigen(String value) {
        this.idtipoorigen = value;
    }

    /**
     * Obtiene el valor de la propiedad nombremotivo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombremotivo() {
        return nombremotivo;
    }

    /**
     * Define el valor de la propiedad nombremotivo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombremotivo(String value) {
        this.nombremotivo = value;
    }

    /**
     * Obtiene el valor de la propiedad porctraslado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPorctraslado() {
        return porctraslado;
    }

    /**
     * Define el valor de la propiedad porctraslado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPorctraslado(String value) {
        this.porctraslado = value;
    }

    /**
     * Obtiene el valor de la propiedad nombreseccion.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreseccion() {
        return nombreseccion;
    }

    /**
     * Define el valor de la propiedad nombreseccion.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreseccion(String value) {
        this.nombreseccion = value;
    }

    /**
     * Obtiene el valor de la propiedad idlugartrabajo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdlugartrabajo() {
        return idlugartrabajo;
    }

    /**
     * Define el valor de la propiedad idlugartrabajo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdlugartrabajo(String value) {
        this.idlugartrabajo = value;
    }

    /**
     * Obtiene el valor de la propiedad nombreempleado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreempleado() {
        return nombreempleado;
    }

    /**
     * Define el valor de la propiedad nombreempleado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreempleado(String value) {
        this.nombreempleado = value;
    }

    /**
     * Obtiene el valor de la propiedad nombretipohora.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombretipohora() {
        return nombretipohora;
    }

    /**
     * Define el valor de la propiedad nombretipohora.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombretipohora(String value) {
        this.nombretipohora = value;
    }

    /**
     * Obtiene el valor de la propiedad fechatrasladada.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechatrasladada() {
        return fechatrasladada;
    }

    /**
     * Define el valor de la propiedad fechatrasladada.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechatrasladada(String value) {
        this.fechatrasladada = value;
    }

    /**
     * Obtiene el valor de la propiedad idempleadolocal.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdempleadolocal() {
        return idempleadolocal;
    }

    /**
     * Define el valor de la propiedad idempleadolocal.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdempleadolocal(String value) {
        this.idempleadolocal = value;
    }

    /**
     * Obtiene el valor de la propiedad nombrelugartrabajo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombrelugartrabajo() {
        return nombrelugartrabajo;
    }

    /**
     * Define el valor de la propiedad nombrelugartrabajo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombrelugartrabajo(String value) {
        this.nombrelugartrabajo = value;
    }

}
