spring:
  main:
    allow-bean-definition-overriding: false
  application:
    name: ICMCLCCORE
  profiles:
    active: standalone
    include: datasource, datasource-legacy
app:
  id: ${spring.application.name}
  version: '@project.version@'
  motor-calculo:
    nuevo:
      enabled: false
  envars:
    migracion:
      comision:
        page-size:
          default: 100
    iopcomercialcalendar:
      config:
        max-attempts: 2
      service:
        iopcomercialcalendarService:
          festivos:
            endpoint: /v1/holidays?
            rows: 100
            maxFilterSize: 50
    meta4:
      ping-query-custom:
        enabled: true
        connect-timeout: 10s
        read-timeout: 10s
        type: 2
amiga:
  common:
    soap:
      client:
        login:
          url: https://des-openshift.axdesocp1.central.inditex.grp/icmclcws/services/Login
        meta4:
          url: https://des-openshift.axdesocp1.central.inditex.grp/icmclcws/services/ICM_WS_CALC_INCOME
    rest:
      client:
        health:
          ping-enabled: true
    cache:
      redis:
        enabled: true
        cache-names: >
          itx.icmlcwb.id_localizacion_by_tarea_and_id_origen_in_ambito,
          itx.icmlcwb.id_localizacion_local_by_tarea_and_id_origen_in_ambito,
          itx.icmlcwb.id_localizacion_local_by_tarea_and_id_origen,
          itx.icmlcwb.id_cadena_by_tarea_and_id_origen_and_tipo_dato,
          itx.icmlcwb.id_cadena_by_tarea_and_id_origen,
          itx.icmlcwb.id_persona_historico_by_tarea_and_id_origen_and_tipo_dato,
          itx.icmlcwb.id_producto_by_id_tarea_and_id_origen,
          itx.icmlcwb.id_tipo_dato_by_id_tipo_grupo_dato,
          itx.icmlcwb.id_persona_historico_by_tarea_and_id_origen,
          itx.icmlcwb.periodo_by_tarea,
          itx.icmlcwb.id_persona_historico_grupo_fechas_by_tarea,
          itx.icmlcwb.id_localizacion_local_presupuestos_by_tarea,
          itx.icmlcwb.id_persona_local_challenge_by_tarea,
          itx.icmlcwb.presupuestos_by_tarea,
          itx.icmlcwb.list_periodo_presupuestos_by_id_tarea_and_page,
          itx.icmlcwb.list_periodo_presupuestos_by_id_tarea_and_page_and_days,
          itx.icmlcwb.periodo_presupuestos_by_id_tarea,
          itx.icmlcwb.periodo_presupuestos_by_id_tarea_repository,
          itx.icmlcwb.periodo_presupuestos_by_id_tarea,
          itx.icmlcwb.tipo_ausencia_by_icm_tp_absence,
          itx.icmlcwb.tipo_ausencia_by_id,
          itx.icmlcwb.tipo_opcion_calculo_by_id_meta4,
          itx.icmlcwb.tipo_politica_by_id_meta4,
          itx.icmlcwb.tipo_politica_by_id,
          itx.icmlcwb.tipo_presupuesto_by_icm_id_tp_presupuesto,
          itx.icmlcwb.tipo_presupuesto_by_id,
          itx.icmlcwb.tipo_unidad_tiempo_by_icm_id_unidad_tiempo,
          itx.icmlcwb.tipo_unidad_tiempo_by_id,
          itx.icmlcwb.tipo_venta_concepto_by_id_meta4,
          itx.icmlcwb.tipo_venta_concepto_by_id,
          itx.icmlcwb.tipo_venta_concepto_challenge_by_icm_id_concepto_venta,
          itx.icmlcwb.tipo_venta_concepto_challenge_by_id,
          itx.icmlcwb.id_localizacion_local_by_tarea_and_id_origen_and_id_tipo_calculo,
          itx.icmlcwb.id_localizacion_local_by_tarea_and_id_origen_and_ids_empresa,
          itx.icmlcwb.id_localizacion_local_presupuestos_by_id_empresa_and_id_tarea,
          itx.icmlcwb.id_localizacion_local_by_tarea_and_id_origen_and_id_empresa_and_id_tipo_calculo,
          itx.icmlcwb.id_localizacion_local_by_id_tipo_presupuesto_and_fecha_and_tarea,
          itx.icmlcwb.id_empresa_by_tarea,
          itx.icmlcwb.fecha_ambito_by_tarea_and_id_tipo_dato,
          itx.icmlcwb.id_localizacion_local_by_tarea_and_id_origen_and_id_empresa_in_ambito,
          itx.icmlcwb.accion_dto_by_id,itx.icmlcwb.tarea_ambito_dto_by_tarea,
          itx.icmlcwb.get_sistema_destino,
          itx.icmlcwb.id_localizacion_by_tarea_and_id_origen_and_id_empresa_in_ambito,
          itx.icmlcwb.id_cadena_by_tarea_and_id_origen_and_tipo_dato_not_in_ambito,
          itx.icmlcwb.id_localizacion_local_by_tarea_and_id_origen_and_id_cadena,
          itx.icmlcwb.horario_comercial_festivos,
          itx.icmlcwb.calcular_festivos,
          itx.icmlcwb.get_tipos_hora,
          itx.icmlcwb.id_persona_historico_localizacion_by_tarea_and_id_origen,
          itx.icmlcwb.get_clases,itx.icmlcwb.id_localizacion_by_tarea
        database: 0
        timeout: 500ms
        default-cache-conf:
          time-to-live: PT24H

    logging:
      file:
        enabled: false
    async:
      default-executor:
        core-pool-size: 10
        maximum-pool-size: 100
        queue-size: 2000
        allow-core-thread-timeout: true
        keep-alive-time: 60s
    executor:
      meta4-executor:
        name: async-meta4-executor
        name-format: async-meta4-executor-%d
        executor-type: THREAD_POOL
        core-pool-size: 10
        maximum-pool-size: 100
        queue-size: 2000
        allow-core-thread-timeout: true
        keep-alive-time: 60s
      ptr-venta-executor:
        name: async-ptr-venta-executor
        name-format: async-ptr-venta-executor-%d
        executor-type: THREAD_POOL
        core-pool-size: 10
        maximum-pool-size: 100
        queue-size: 2000
        allow-core-thread-timeout: true
        keep-alive-time: 60s
      ptr-presencia-executor:
        name: async-ptr-presencia-executor
        name-format: async-ptr-presencia-executor-%d
        executor-type: THREAD_POOL
        core-pool-size: 10
        maximum-pool-size: 100
        queue-size: 2000
        allow-core-thread-timeout: true
        keep-alive-time: 60s
      iopcomercialcalendar-executor:
        name: async-iopcomercialcalendar-executor
        name-format: async-iopcomercialcalendar-executor-%d
        executor-type: THREAD_POOL
        core-pool-size: 10
        maximum-pool-size: 100
        queue-size: 2000
        allow-core-thread-timeout: true
        keep-alive-time: 60s
      repository-primary-executor:
        name: async-repository-primary-executor
        name-format: async-repository-primary-executor-%d
        executor-type: THREAD_POOL
        core-pool-size: 10
        maximum-pool-size: 100
        queue-size: 2000
        allow-core-thread-timeout: true
        keep-alive-time: 60s
      algoritmo-calculo-executor:
        name: async-algoritmo-calculo-executor
        name-format: async-algoritmo-calculo-executor-%d
        executor-type: THREAD_POOL
        core-pool-size: 10
        maximum-pool-size: 100
        queue-size: 2000
        allow-core-thread-timeout: true
        keep-alive-time: 60s
      calculo-executor:
        name: async-calculo-executor
        name-format: async-calculo-executor-%d
        executor-type: THREAD_POOL
        core-pool-size: 10
        maximum-pool-size: 100
        queue-size: 2000
        allow-core-thread-timeout: true
        keep-alive-time: 60s
      algoritmo-ajuste-executor:
        name: async-algoritmo-ajuste-executor
        name-format: async-algoritmo-ajuste-executor-%d
        executor-type: THREAD_POOL
        core-pool-size: 10
        maximum-pool-size: 100
        queue-size: 2000
        allow-core-thread-timeout: true
        keep-alive-time: 60s
      ajuste-executor:
        name: async-ajuste-executor
        name-format: async-ajuste-executor-%d
        executor-type: THREAD_POOL
        core-pool-size: 10
        maximum-pool-size: 100
        queue-size: 2000
        allow-core-thread-timeout: true
        keep-alive-time: 60s
      regularizar-executor:
        name: async-regularizar-executor
        name-format: async-regularizar-executor-%d
        executor-type: THREAD_POOL
        core-pool-size: 10
        maximum-pool-size: 100
        queue-size: 2000
        allow-core-thread-timeout: true
        keep-alive-time: 60s
      validacion-executor:
        name: async-validacion-executor
        name-format: async-validacion-executor-%d
        executor-type: THREAD_POOL
        core-pool-size: 10
        maximum-pool-size: 100
        queue-size: 2000
        allow-core-thread-timeout: true
        keep-alive-time: 60s
    metrics:
      type: influx

  service:
    session:
      session-type: REMOTE
    core:
      mdc-filter:
        enabled: true
    aaa:
      paths:
        app-public-path: /amiga/**,/swagger-ui**,/itx-openapi.js,/swagger-api-docs/**,/webjars/springfox-swagger-ui/**,/v2/api-docs,/swagger-resources/**
      user-details:
        source-type: HEIMDAL
        heimdal:
          enabled: true
          application-id: IOPINCOME

    rest-swagger:
      ui:
        title: '@project.name@'
        description: '@project.description@'
    web:
      api:
        problem-details:
          enabled: false

