-- TODO [javierev] WHERE 1 = 1 para evitar que Sonar se queje de que no tiene cláusula WHERE
DELETE FROM PERIODO_CALCULO_PERSONA WHERE 1 = 1;
DELETE FROM PERIODO_LOCALIZACION_PERSONA WHERE 1 = 1;
DELETE FROM PERIODO_LOCALIZACION WHERE 1 = 1;
DELETE FROM PERIODO_PERSONA WHERE 1 = 1;
