-- > 2000 (Venta - VentaNoIntegra)
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2046, 'VENTA_NO_INTEGRA', 'Tipo de dato para marcar la tiendas con venta no integra para un cálculo', 0, NULL, NULL);

-- > ACCION
INSERT INTO ACCION(ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (30, 'ventaIntegraV1', 'There are stores with incorrect sales', 100, 0, 0, 0, 0);

-- > FASE_ACCION
INSERT INTO FASE_ACCION(ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 30, 3, 100);
