  INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2043, 'VENTA_RANGO_FISICA_DEVOLUCION_VENTA_ORIGINAL_OTRA_TIENDA_LOCALIZACION', 'Venta rango fisica devolucion venta original otra [localizacion]', 0, NULL, 5);
  INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2044, 'VENTA_RANGO_FISICA_DEVOLUCION_VENTA_ORIGINAL_OTRA_TIENDA_LOCALIZACION_SECCION', 'Venta rango fisica devolucion venta original otra [localizacion|seccion]', 0, NULL, 5);

  INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2043);
  INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2044);
  