-- Inserción del tipo de dato para horas fijas
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (5010, 'PRESENCIA_HORASFIJAS_LOCALIZACION-SECCION-PERSONA-TIPO_HORA', 'Presencias horas fijas [localizacion|seccion|persona|tipo hora]', 1, 2, NULL);
-- Inserción del tipo de dato horas fijas en los grupos que correspondan
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1000, 5010);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3001, 5010);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3006, 5010);
