INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (7101, 0, 'porVentaDevolucionPorcentajeV1', 0, 0);
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (7102, 0, 'porVentaDevolucionPorcentajeDiariaV1', 0, 0);
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (7106, 0, 'porVentaDevolucionPorcentajeDesplazamientoV1', 1, 0);
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (7107, 0, 'porVentaDevolucionPorcentajeDiariaDesplazamientoV1', 1, 0);
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (7111, 0, 'porVentaDevolucionPorcentajeDesplazamientoBaseV1', 1, 1);
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (7112, 0, 'porVentaDevolucionPorcentajeDiariaDesplazamientoBaseV1', 1, 1);

UPDATE ALGORITMO_TIPO_CALCULO SET ID_ALGORITMO = 7101 WHERE ID_ALGORITMO = 7014;
UPDATE ALGORITMO_TIPO_CALCULO SET ID_ALGORITMO = 7102 WHERE ID_ALGORITMO = 7017;
UPDATE ALGORITMO_TIPO_CALCULO SET ID_ALGORITMO = 7106 WHERE ID_ALGORITMO = 7015;
UPDATE ALGORITMO_TIPO_CALCULO SET ID_ALGORITMO = 7107 WHERE ID_ALGORITMO = 7018;
UPDATE ALGORITMO_TIPO_CALCULO SET ID_ALGORITMO = 7111 WHERE ID_ALGORITMO = 7016;
UPDATE ALGORITMO_TIPO_CALCULO SET ID_ALGORITMO = 7112 WHERE ID_ALGORITMO = 7019;

UPDATE ALGORITMO_TIPO_COMISION SET ID_ALGORITMO = 7101 WHERE ID_ALGORITMO = 7014;
UPDATE ALGORITMO_TIPO_COMISION SET ID_ALGORITMO = 7102 WHERE ID_ALGORITMO = 7017;
UPDATE ALGORITMO_TIPO_COMISION SET ID_ALGORITMO = 7106 WHERE ID_ALGORITMO = 7015;
UPDATE ALGORITMO_TIPO_COMISION SET ID_ALGORITMO = 7107 WHERE ID_ALGORITMO = 7018;
UPDATE ALGORITMO_TIPO_COMISION SET ID_ALGORITMO = 7111 WHERE ID_ALGORITMO = 7016;
UPDATE ALGORITMO_TIPO_COMISION SET ID_ALGORITMO = 7112 WHERE ID_ALGORITMO = 7019;

UPDATE ALGORITMO_TIPO_DATO SET ID_ALGORITMO = 7101 WHERE ID_ALGORITMO = 7014;
UPDATE ALGORITMO_TIPO_DATO SET ID_ALGORITMO = 7102 WHERE ID_ALGORITMO = 7017;
UPDATE ALGORITMO_TIPO_DATO SET ID_ALGORITMO = 7106 WHERE ID_ALGORITMO = 7015;
UPDATE ALGORITMO_TIPO_DATO SET ID_ALGORITMO = 7107 WHERE ID_ALGORITMO = 7018;
UPDATE ALGORITMO_TIPO_DATO SET ID_ALGORITMO = 7111 WHERE ID_ALGORITMO = 7016;
UPDATE ALGORITMO_TIPO_DATO SET ID_ALGORITMO = 7112 WHERE ID_ALGORITMO = 7019;

UPDATE TAREA_CALCULO SET ID_ALGORITMO = 7101 WHERE ID_ALGORITMO = 7014;
UPDATE TAREA_CALCULO SET ID_ALGORITMO = 7102 WHERE ID_ALGORITMO = 7017;
UPDATE TAREA_CALCULO SET ID_ALGORITMO = 7106 WHERE ID_ALGORITMO = 7015;
UPDATE TAREA_CALCULO SET ID_ALGORITMO = 7107 WHERE ID_ALGORITMO = 7018;
UPDATE TAREA_CALCULO SET ID_ALGORITMO = 7111 WHERE ID_ALGORITMO = 7016;
UPDATE TAREA_CALCULO SET ID_ALGORITMO = 7112 WHERE ID_ALGORITMO = 7019;

DELETE FROM ALGORITMO WHERE ID_ALGORITMO IN (7014,7017,7015,7018,7016,7019);
