-- TIPO_DATO VENTAS TRASLADADAS
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3005, 'VENTA_ONLINE_IPOD_TRASLADADA_LOCALIZACION', 'Venta online ipod trasladada [localizacion]', 1, NULL, 2);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3006, 'VENTA_ONLINE_IPOD_TRASLADADA_LOCALIZACION-SECCION', 'Venta online ipod trasladada [localizacion|seccion]', 1, NULL, 2);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3007, 'VENTA_ONLINE_SINT_TRASLADADA_LOCALIZACION', 'Venta online sint trasladada [localizacion]', 1, NULL, 3);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3008, 'VENTA_ONLINE_SINT_TRASLADADA_LOCALIZACION-SECCION', 'Venta online sint traslada [localizacion|seccion]', 1, NULL, 3);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3009, 'VENTA_ONLINE_ENTREGATIENDA_TRASLADADA_LOCALIZACION', 'Venta online entrega tienda traslada [localizacion]',1, NULL, 4);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3010, 'VENTA_ONLINE_ENTREGATIENDA_TRASLADADA_LOCALIZACION-SECCION', 'Venta online entrega tienda trasladada [localizacion|seccion]', 1, NULL, 4);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3011, 'VENTA_ONLINE_ENTREGADOMICILIO_TRASLADADA_LOCALIZACION', 'Venta online entrega domicilio trasladada [localizacion]', 1, NULL, 5);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3012, 'VENTA_ONLINE_ENTREGADOMICILIO_TRASLADADA_LOCALIZACION-SECCION', 'Venta online entrega domicilio trasladada [localizacion|seccion]', 1, NULL, 5);
-- TIPO_GRUPO_DATO_TIPO_DATO VENTAS TRASLADADAS
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2001, 3006);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2001, 3008);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2001, 3010);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2001, 3012);
