/***************************/
/**    Resalta  Manual    **/
/***************************/

-- ALGORITMO
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (17001, 1, 'resaltaManualV1', 0, 0);
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (17006, 1, 'resaltaManualDesplazamientoV1', 1, 0);
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (17011, 1, 'resaltaManualDesplazamientoBaseV1', 1, 1);

-- TIPO_COMISION
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES ('014', 'RESALTA_MANUAL');

-- TIPO_COMISION_RELACION_COMIS
INSERT INTO TIPO_COMISION_RELACION_COMIS (ID_TIPO_COMISION_RELACION_COMIS, ID_TIPO_COMISION, COD_TIPO_COMISION_COMIS) VALUES (13, '014', 0);

-- ALGORITMO_TIPO_COMISION
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (17001, '014');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (17006, '014');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (17011, '014');

-- ALGORITMO_TIPO_CALCULO
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (17001, '000');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (17006, '000');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (17011, '000');

-- TIPO_GRUPO_DATO
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2032, 'VENTA_ONLINE_EXCLUIDO_ENTREGA_DOMICILIO_LOCALIZACION', 'Venta online exclulido online entrega domicilio [localizacion]');

-- TIPO_GRUPO_DATO_TIPO_DATO
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2032, 2003);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2032, 2004);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2032, 2005);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2032, 2006);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2032, 2007);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2032, 2008);
