// CREACION NUEVA VALIDACION CALCULOS PENDIENTES

INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (33, 'validarCalculoPendienteV1', 'Validate employees with calculations with "pendant" status.', 100, 0, 0, 0, 0);

INSERT INTO FASE_ACCION (ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (4, 33, 3, 200);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT) VALUES (33, 11, 8);
