-- Correccion

-- Fase 1: [CZ|HU|SK]
-- [MOCK][INICIO] PROGRAMACION
-- Programacion: 1 | Programacion ambito: 1 || Sociedad: AT | Origen: 38 | Empresa: [95,135,251,315,329,340,425,468]
DELETE FROM PROGRAMACION_AMBITO_ORIGEN WHERE ID_PROGRAMACION_AMBITO_ORIGEN IN (2, 3, 4, 5, 6, 7, 8, 9);

INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '95');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '135');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '251');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '315');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '329');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '340');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '425');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '468');

