INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('018', 'CHALLENGE_PORCENTAJE');


INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (23001, 1, 0, 0, 'challengePorcentajeV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (23006, 1, 1, 0, 'challengePorcentajeDesplazamientoV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (23011, 1, 1, 1, 'challengePorcentajeDesplazamientoBaseV1');

INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (23001, '018');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (23006, '018');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (23011, '018');

INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (23001, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (23006, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (23011, '005');

INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (23001, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (23006, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (23011, 2002);


INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (5024, 'PRESENCIA_LOCALIZACION_INCLUIDOCHALLENGEPORCENTAJE', 'Presencia incluido challenge porcentaje [localizacion]', 1, NULL, NULL);


INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (28, 'condicionesHistoricoChallengeIncluidoPorcentajeV1', 'The employees conditions history differ between origin and INCOME on percentage challenge. ', 100, 0, 0, 0, 0);

INSERT INTO FASE_ACCION (ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 28, 3, 200);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT) VALUES (28, 11, 8);

INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (29, 'condicionesDesplazamientoChallengeIncluidoPorcentajeV1', 'Displacement conditions differ between SIL and INCOME on percentage challenge. . ', 100, 0, 0, 0, 0);

INSERT INTO FASE_ACCION (ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 29, 3, 200);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT) VALUES (29, 11, 8);
