// CREACION NUEVA VALIDACION PORCENTAJES0

INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (34, 'validarPorcentaje0V1', 'Validate employees with 0 comissions in every section.', 100, 0, 0, 0, 0);

INSERT INTO FASE_ACCION (ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (4, 34, 3, 200);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO) VALUES (34, 11, 11,1);
