INSERT INTO TIPO_ESTADO_VALIDACION (ID_TIPO_ESTADO_VALIDACION, NOMBRE) VALUES (1, 'ONLINE');
INSERT INTO TIPO_ESTADO_VALIDACION (ID_TIPO_ESTADO_VALIDACION, NOMBRE) VALUES (2, 'OFFLINE');

INSERT INTO TIPO_ACCION_VALIDACION (ID_TIPO_ACCION_VALIDACION, NOMBRE) VALUES (1, 'NO_REINTENTAR');
INSERT INTO TIPO_ACCION_VALIDACION (ID_TIPO_ACCION_VALIDACION, NOMBRE) VALUES (2, 'ESPERAR_LLAMADA');
INSERT INTO TIPO_ACCION_VALIDACION (ID_TIPO_ACCION_VALIDACION, NOMBRE) VALUES (3, 'REENCOLAR_DELAY');
INSERT INTO TIPO_ACCION_VALIDACION (ID_TIPO_ACCION_VALIDACION, NOMBRE) VALUES (4, 'REENCOLAR');

INSERT INTO PRIORIDAD_VALIDACION (ID_PRIORIDAD_VALIDACION, NOMBRE) VALUES (1, 'LO');
INSERT INTO PRIORIDAD_VALIDACION (ID_PRIORIDAD_VALIDACION, NOMBRE) VALUES (2, 'HI');

INSERT INTO ESTADO_TAREA_PREVALIDACION (ID_ESTADO_TAREA_PREVALIDACION, NOMBRE, PESO) VALUES (1, 'EN_CURSO', 100);
INSERT INTO ESTADO_TAREA_PREVALIDACION (ID_ESTADO_TAREA_PREVALIDACION, NOMBRE, PESO) VALUES (2, 'FINALIZADO OK', 100);
INSERT INTO ESTADO_TAREA_PREVALIDACION (ID_ESTADO_TAREA_PREVALIDACION, NOMBRE, PESO) VALUES (3, 'FINALIZADO KO', 100);
INSERT INTO ESTADO_TAREA_PREVALIDACION (ID_ESTADO_TAREA_PREVALIDACION, NOMBRE, PESO) VALUES (4, 'FINALIZADO PLANIFICADO', 100);

INSERT INTO ESTADO_VALIDACION (ID_ESTADO_VALIDACION, NOMBRE, PESO) VALUES (1, 'OK', 100);
INSERT INTO ESTADO_VALIDACION (ID_ESTADO_VALIDACION, NOMBRE, PESO) VALUES (2, 'KO', 100);
INSERT INTO ESTADO_VALIDACION (ID_ESTADO_VALIDACION, NOMBRE, PESO) VALUES (3, 'PLANIFICADA', 100);

INSERT INTO TIPO_VALIDACION (ID_TIPO_VALIDACION, NOMBRE) VALUES (1, 'PRESENCIAS');
