<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.inditex.rrhh.icmclcwb</groupId>
    <artifactId>APPWEB-INCOMEMotorCalculoJava</artifactId>
    <version>4.69.0</version>
  </parent>
  <artifactId>APPWEB-INCOMEMotorCalculoJava-api</artifactId>
  <name>${project.groupId}:${project.artifactId}</name>
  <description>Este módulo se proporciona para que el ejemplo funcione, pero lo recomendable es que no exista
    dentro del proyecto, y en su lugar se importe una librería con el api y el acceso a datos.</description>

  <dependencies>

    <!-- PROJECT DEPENDENCIES -->
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-ws-api</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>APPWEB-INCOMEMotorCalculoJava-client-rest-api-incomemeta</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- FWK DEPENDENCIES -->
    <dependency>
      <groupId>com.inditex.amigafwk.common</groupId>
      <artifactId>common-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.amigafwk.common</groupId>
      <artifactId>common-starter-api-validation</artifactId>
    </dependency>

    <!-- OTHER DEPENDENCIES -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.module</groupId>
      <artifactId>jackson-module-parameter-names</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jdk8</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jsr310</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.amigafwk.data</groupId>
      <artifactId>data-starter-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.amigafwk.service</groupId>
      <artifactId>service-starter-aaa-userdetails-heimdal</artifactId>
    </dependency>

    <!-- TEST -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

</project>
