
package com.inditex.rrhh.icmclcwb.model.meta4.icm_ws_income.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Clase Java para Icm_GlobalempleadoRecord complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="Icm_GlobalempleadoRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="fecha" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inout" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ausencia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="comision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="presencia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idempleado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="desplazamiento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="horaspresencia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombreausencia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cambioestructura" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_GlobalempleadoRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "fecha",
    "inout",
    "ausencia",
    "comision",
    "presencia",
    "idempleado",
    "desplazamiento",
    "horaspresencia",
    "nombreausencia",
    "cambioestructura"
})
public class IcmGlobalempleadoRecord implements Cloneable, CopyTo2, Equals2, HashCode2, ToString2
{

    @XmlElement(required = true, nillable = true)
    protected String m4AutoGeneratedRecordID;
    protected boolean m4AutoGeneratedToDelete;
    @XmlElement(required = true, nillable = true)
    protected String fecha;
    @XmlElement(required = true, nillable = true)
    protected String inout;
    @XmlElement(required = true, nillable = true)
    protected String ausencia;
    @XmlElement(required = true, nillable = true)
    protected String comision;
    @XmlElement(required = true, nillable = true)
    protected String presencia;
    @XmlElement(required = true, nillable = true)
    protected String idempleado;
    @XmlElement(required = true, nillable = true)
    protected String desplazamiento;
    @XmlElement(required = true, nillable = true)
    protected String horaspresencia;
    @XmlElement(required = true, nillable = true)
    protected String nombreausencia;
    @XmlElement(required = true, nillable = true)
    protected String cambioestructura;

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM4AutoGeneratedRecordID(String value) {
        this.m4AutoGeneratedRecordID = value;
    }

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public void setM4AutoGeneratedToDelete(boolean value) {
        this.m4AutoGeneratedToDelete = value;
    }

    /**
     * Obtiene el valor de la propiedad fecha.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFecha() {
        return fecha;
    }

    /**
     * Define el valor de la propiedad fecha.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFecha(String value) {
        this.fecha = value;
    }

    /**
     * Obtiene el valor de la propiedad inout.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInout() {
        return inout;
    }

    /**
     * Define el valor de la propiedad inout.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInout(String value) {
        this.inout = value;
    }

    /**
     * Obtiene el valor de la propiedad ausencia.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAusencia() {
        return ausencia;
    }

    /**
     * Define el valor de la propiedad ausencia.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAusencia(String value) {
        this.ausencia = value;
    }

    /**
     * Obtiene el valor de la propiedad comision.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComision() {
        return comision;
    }

    /**
     * Define el valor de la propiedad comision.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComision(String value) {
        this.comision = value;
    }

    /**
     * Obtiene el valor de la propiedad presencia.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresencia() {
        return presencia;
    }

    /**
     * Define el valor de la propiedad presencia.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresencia(String value) {
        this.presencia = value;
    }

    /**
     * Obtiene el valor de la propiedad idempleado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdempleado() {
        return idempleado;
    }

    /**
     * Define el valor de la propiedad idempleado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdempleado(String value) {
        this.idempleado = value;
    }

    /**
     * Obtiene el valor de la propiedad desplazamiento.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesplazamiento() {
        return desplazamiento;
    }

    /**
     * Define el valor de la propiedad desplazamiento.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesplazamiento(String value) {
        this.desplazamiento = value;
    }

    /**
     * Obtiene el valor de la propiedad horaspresencia.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoraspresencia() {
        return horaspresencia;
    }

    /**
     * Define el valor de la propiedad horaspresencia.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoraspresencia(String value) {
        this.horaspresencia = value;
    }

    /**
     * Obtiene el valor de la propiedad nombreausencia.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreausencia() {
        return nombreausencia;
    }

    /**
     * Define el valor de la propiedad nombreausencia.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreausencia(String value) {
        this.nombreausencia = value;
    }

    /**
     * Obtiene el valor de la propiedad cambioestructura.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCambioestructura() {
        return cambioestructura;
    }

    /**
     * Define el valor de la propiedad cambioestructura.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCambioestructura(String value) {
        this.cambioestructura = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final IcmGlobalempleadoRecord that = ((IcmGlobalempleadoRecord) object);
        {
            String lhsM4AutoGeneratedRecordID;
            lhsM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            String rhsM4AutoGeneratedRecordID;
            rhsM4AutoGeneratedRecordID = that.getM4AutoGeneratedRecordID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedRecordID", lhsM4AutoGeneratedRecordID), LocatorUtils.property(thatLocator, "m4AutoGeneratedRecordID", rhsM4AutoGeneratedRecordID), lhsM4AutoGeneratedRecordID, rhsM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null), (that.m4AutoGeneratedRecordID!= null))) {
                return false;
            }
        }
        {
            boolean lhsM4AutoGeneratedToDelete;
            lhsM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            boolean rhsM4AutoGeneratedToDelete;
            rhsM4AutoGeneratedToDelete = that.isM4AutoGeneratedToDelete();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedToDelete", lhsM4AutoGeneratedToDelete), LocatorUtils.property(thatLocator, "m4AutoGeneratedToDelete", rhsM4AutoGeneratedToDelete), lhsM4AutoGeneratedToDelete, rhsM4AutoGeneratedToDelete, true, true)) {
                return false;
            }
        }
        {
            String lhsFecha;
            lhsFecha = this.getFecha();
            String rhsFecha;
            rhsFecha = that.getFecha();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fecha", lhsFecha), LocatorUtils.property(thatLocator, "fecha", rhsFecha), lhsFecha, rhsFecha, (this.fecha!= null), (that.fecha!= null))) {
                return false;
            }
        }
        {
            String lhsInout;
            lhsInout = this.getInout();
            String rhsInout;
            rhsInout = that.getInout();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "inout", lhsInout), LocatorUtils.property(thatLocator, "inout", rhsInout), lhsInout, rhsInout, (this.inout!= null), (that.inout!= null))) {
                return false;
            }
        }
        {
            String lhsAusencia;
            lhsAusencia = this.getAusencia();
            String rhsAusencia;
            rhsAusencia = that.getAusencia();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ausencia", lhsAusencia), LocatorUtils.property(thatLocator, "ausencia", rhsAusencia), lhsAusencia, rhsAusencia, (this.ausencia!= null), (that.ausencia!= null))) {
                return false;
            }
        }
        {
            String lhsComision;
            lhsComision = this.getComision();
            String rhsComision;
            rhsComision = that.getComision();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "comision", lhsComision), LocatorUtils.property(thatLocator, "comision", rhsComision), lhsComision, rhsComision, (this.comision!= null), (that.comision!= null))) {
                return false;
            }
        }
        {
            String lhsPresencia;
            lhsPresencia = this.getPresencia();
            String rhsPresencia;
            rhsPresencia = that.getPresencia();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "presencia", lhsPresencia), LocatorUtils.property(thatLocator, "presencia", rhsPresencia), lhsPresencia, rhsPresencia, (this.presencia!= null), (that.presencia!= null))) {
                return false;
            }
        }
        {
            String lhsIdempleado;
            lhsIdempleado = this.getIdempleado();
            String rhsIdempleado;
            rhsIdempleado = that.getIdempleado();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idempleado", lhsIdempleado), LocatorUtils.property(thatLocator, "idempleado", rhsIdempleado), lhsIdempleado, rhsIdempleado, (this.idempleado!= null), (that.idempleado!= null))) {
                return false;
            }
        }
        {
            String lhsDesplazamiento;
            lhsDesplazamiento = this.getDesplazamiento();
            String rhsDesplazamiento;
            rhsDesplazamiento = that.getDesplazamiento();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "desplazamiento", lhsDesplazamiento), LocatorUtils.property(thatLocator, "desplazamiento", rhsDesplazamiento), lhsDesplazamiento, rhsDesplazamiento, (this.desplazamiento!= null), (that.desplazamiento!= null))) {
                return false;
            }
        }
        {
            String lhsHoraspresencia;
            lhsHoraspresencia = this.getHoraspresencia();
            String rhsHoraspresencia;
            rhsHoraspresencia = that.getHoraspresencia();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "horaspresencia", lhsHoraspresencia), LocatorUtils.property(thatLocator, "horaspresencia", rhsHoraspresencia), lhsHoraspresencia, rhsHoraspresencia, (this.horaspresencia!= null), (that.horaspresencia!= null))) {
                return false;
            }
        }
        {
            String lhsNombreausencia;
            lhsNombreausencia = this.getNombreausencia();
            String rhsNombreausencia;
            rhsNombreausencia = that.getNombreausencia();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nombreausencia", lhsNombreausencia), LocatorUtils.property(thatLocator, "nombreausencia", rhsNombreausencia), lhsNombreausencia, rhsNombreausencia, (this.nombreausencia!= null), (that.nombreausencia!= null))) {
                return false;
            }
        }
        {
            String lhsCambioestructura;
            lhsCambioestructura = this.getCambioestructura();
            String rhsCambioestructura;
            rhsCambioestructura = that.getCambioestructura();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "cambioestructura", lhsCambioestructura), LocatorUtils.property(thatLocator, "cambioestructura", rhsCambioestructura), lhsCambioestructura, rhsCambioestructura, (this.cambioestructura!= null), (that.cambioestructura!= null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            String theM4AutoGeneratedRecordID;
            theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            strategy.appendField(locator, this, "m4AutoGeneratedRecordID", buffer, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null));
        }
        {
            boolean theM4AutoGeneratedToDelete;
            theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            strategy.appendField(locator, this, "m4AutoGeneratedToDelete", buffer, theM4AutoGeneratedToDelete, true);
        }
        {
            String theFecha;
            theFecha = this.getFecha();
            strategy.appendField(locator, this, "fecha", buffer, theFecha, (this.fecha!= null));
        }
        {
            String theInout;
            theInout = this.getInout();
            strategy.appendField(locator, this, "inout", buffer, theInout, (this.inout!= null));
        }
        {
            String theAusencia;
            theAusencia = this.getAusencia();
            strategy.appendField(locator, this, "ausencia", buffer, theAusencia, (this.ausencia!= null));
        }
        {
            String theComision;
            theComision = this.getComision();
            strategy.appendField(locator, this, "comision", buffer, theComision, (this.comision!= null));
        }
        {
            String thePresencia;
            thePresencia = this.getPresencia();
            strategy.appendField(locator, this, "presencia", buffer, thePresencia, (this.presencia!= null));
        }
        {
            String theIdempleado;
            theIdempleado = this.getIdempleado();
            strategy.appendField(locator, this, "idempleado", buffer, theIdempleado, (this.idempleado!= null));
        }
        {
            String theDesplazamiento;
            theDesplazamiento = this.getDesplazamiento();
            strategy.appendField(locator, this, "desplazamiento", buffer, theDesplazamiento, (this.desplazamiento!= null));
        }
        {
            String theHoraspresencia;
            theHoraspresencia = this.getHoraspresencia();
            strategy.appendField(locator, this, "horaspresencia", buffer, theHoraspresencia, (this.horaspresencia!= null));
        }
        {
            String theNombreausencia;
            theNombreausencia = this.getNombreausencia();
            strategy.appendField(locator, this, "nombreausencia", buffer, theNombreausencia, (this.nombreausencia!= null));
        }
        {
            String theCambioestructura;
            theCambioestructura = this.getCambioestructura();
            strategy.appendField(locator, this, "cambioestructura", buffer, theCambioestructura, (this.cambioestructura!= null));
        }
        return buffer;
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            String theM4AutoGeneratedRecordID;
            theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", theM4AutoGeneratedRecordID), currentHashCode, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null));
        }
        {
            boolean theM4AutoGeneratedToDelete;
            theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", theM4AutoGeneratedToDelete), currentHashCode, theM4AutoGeneratedToDelete, true);
        }
        {
            String theFecha;
            theFecha = this.getFecha();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fecha", theFecha), currentHashCode, theFecha, (this.fecha!= null));
        }
        {
            String theInout;
            theInout = this.getInout();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "inout", theInout), currentHashCode, theInout, (this.inout!= null));
        }
        {
            String theAusencia;
            theAusencia = this.getAusencia();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ausencia", theAusencia), currentHashCode, theAusencia, (this.ausencia!= null));
        }
        {
            String theComision;
            theComision = this.getComision();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "comision", theComision), currentHashCode, theComision, (this.comision!= null));
        }
        {
            String thePresencia;
            thePresencia = this.getPresencia();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "presencia", thePresencia), currentHashCode, thePresencia, (this.presencia!= null));
        }
        {
            String theIdempleado;
            theIdempleado = this.getIdempleado();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idempleado", theIdempleado), currentHashCode, theIdempleado, (this.idempleado!= null));
        }
        {
            String theDesplazamiento;
            theDesplazamiento = this.getDesplazamiento();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "desplazamiento", theDesplazamiento), currentHashCode, theDesplazamiento, (this.desplazamiento!= null));
        }
        {
            String theHoraspresencia;
            theHoraspresencia = this.getHoraspresencia();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "horaspresencia", theHoraspresencia), currentHashCode, theHoraspresencia, (this.horaspresencia!= null));
        }
        {
            String theNombreausencia;
            theNombreausencia = this.getNombreausencia();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nombreausencia", theNombreausencia), currentHashCode, theNombreausencia, (this.nombreausencia!= null));
        }
        {
            String theCambioestructura;
            theCambioestructura = this.getCambioestructura();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "cambioestructura", theCambioestructura), currentHashCode, theCambioestructura, (this.cambioestructura!= null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof IcmGlobalempleadoRecord) {
            final IcmGlobalempleadoRecord copy = ((IcmGlobalempleadoRecord) draftCopy);
            {
                Boolean m4AutoGeneratedRecordIDShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.m4AutoGeneratedRecordID!= null));
                if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceM4AutoGeneratedRecordID;
                    sourceM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
                    String copyM4AutoGeneratedRecordID = ((String) strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", sourceM4AutoGeneratedRecordID), sourceM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null)));
                    copy.setM4AutoGeneratedRecordID(copyM4AutoGeneratedRecordID);
                } else {
                    if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.m4AutoGeneratedRecordID = null;
                    }
                }
            }
            {
                Boolean m4AutoGeneratedToDeleteShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, true);
                if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.TRUE) {
                    boolean sourceM4AutoGeneratedToDelete;
                    sourceM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
                    boolean copyM4AutoGeneratedToDelete = strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", sourceM4AutoGeneratedToDelete), sourceM4AutoGeneratedToDelete, true);
                    copy.setM4AutoGeneratedToDelete(copyM4AutoGeneratedToDelete);
                } else {
                    if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.FALSE) {
                    }
                }
            }
            {
                Boolean fechaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.fecha!= null));
                if (fechaShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceFecha;
                    sourceFecha = this.getFecha();
                    String copyFecha = ((String) strategy.copy(LocatorUtils.property(locator, "fecha", sourceFecha), sourceFecha, (this.fecha!= null)));
                    copy.setFecha(copyFecha);
                } else {
                    if (fechaShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.fecha = null;
                    }
                }
            }
            {
                Boolean inoutShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.inout!= null));
                if (inoutShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceInout;
                    sourceInout = this.getInout();
                    String copyInout = ((String) strategy.copy(LocatorUtils.property(locator, "inout", sourceInout), sourceInout, (this.inout!= null)));
                    copy.setInout(copyInout);
                } else {
                    if (inoutShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.inout = null;
                    }
                }
            }
            {
                Boolean ausenciaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.ausencia!= null));
                if (ausenciaShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceAusencia;
                    sourceAusencia = this.getAusencia();
                    String copyAusencia = ((String) strategy.copy(LocatorUtils.property(locator, "ausencia", sourceAusencia), sourceAusencia, (this.ausencia!= null)));
                    copy.setAusencia(copyAusencia);
                } else {
                    if (ausenciaShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.ausencia = null;
                    }
                }
            }
            {
                Boolean comisionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.comision!= null));
                if (comisionShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceComision;
                    sourceComision = this.getComision();
                    String copyComision = ((String) strategy.copy(LocatorUtils.property(locator, "comision", sourceComision), sourceComision, (this.comision!= null)));
                    copy.setComision(copyComision);
                } else {
                    if (comisionShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.comision = null;
                    }
                }
            }
            {
                Boolean presenciaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.presencia!= null));
                if (presenciaShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourcePresencia;
                    sourcePresencia = this.getPresencia();
                    String copyPresencia = ((String) strategy.copy(LocatorUtils.property(locator, "presencia", sourcePresencia), sourcePresencia, (this.presencia!= null)));
                    copy.setPresencia(copyPresencia);
                } else {
                    if (presenciaShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.presencia = null;
                    }
                }
            }
            {
                Boolean idempleadoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idempleado!= null));
                if (idempleadoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdempleado;
                    sourceIdempleado = this.getIdempleado();
                    String copyIdempleado = ((String) strategy.copy(LocatorUtils.property(locator, "idempleado", sourceIdempleado), sourceIdempleado, (this.idempleado!= null)));
                    copy.setIdempleado(copyIdempleado);
                } else {
                    if (idempleadoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idempleado = null;
                    }
                }
            }
            {
                Boolean desplazamientoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.desplazamiento!= null));
                if (desplazamientoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceDesplazamiento;
                    sourceDesplazamiento = this.getDesplazamiento();
                    String copyDesplazamiento = ((String) strategy.copy(LocatorUtils.property(locator, "desplazamiento", sourceDesplazamiento), sourceDesplazamiento, (this.desplazamiento!= null)));
                    copy.setDesplazamiento(copyDesplazamiento);
                } else {
                    if (desplazamientoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.desplazamiento = null;
                    }
                }
            }
            {
                Boolean horaspresenciaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.horaspresencia!= null));
                if (horaspresenciaShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceHoraspresencia;
                    sourceHoraspresencia = this.getHoraspresencia();
                    String copyHoraspresencia = ((String) strategy.copy(LocatorUtils.property(locator, "horaspresencia", sourceHoraspresencia), sourceHoraspresencia, (this.horaspresencia!= null)));
                    copy.setHoraspresencia(copyHoraspresencia);
                } else {
                    if (horaspresenciaShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.horaspresencia = null;
                    }
                }
            }
            {
                Boolean nombreausenciaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.nombreausencia!= null));
                if (nombreausenciaShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceNombreausencia;
                    sourceNombreausencia = this.getNombreausencia();
                    String copyNombreausencia = ((String) strategy.copy(LocatorUtils.property(locator, "nombreausencia", sourceNombreausencia), sourceNombreausencia, (this.nombreausencia!= null)));
                    copy.setNombreausencia(copyNombreausencia);
                } else {
                    if (nombreausenciaShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.nombreausencia = null;
                    }
                }
            }
            {
                Boolean cambioestructuraShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.cambioestructura!= null));
                if (cambioestructuraShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceCambioestructura;
                    sourceCambioestructura = this.getCambioestructura();
                    String copyCambioestructura = ((String) strategy.copy(LocatorUtils.property(locator, "cambioestructura", sourceCambioestructura), sourceCambioestructura, (this.cambioestructura!= null)));
                    copy.setCambioestructura(copyCambioestructura);
                } else {
                    if (cambioestructuraShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.cambioestructura = null;
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new IcmGlobalempleadoRecord();
    }

}
