
package com.inditex.rrhh.icmclcwb.model.meta4.icm_ws_income.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Clase Java para Icm_PlantillacondicionesRecord complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="Icm_PlantillacondicionesRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="inout" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nuevo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="borrado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modificado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idplantilla" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idestructura" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idtipoplantilla" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombreplantilla" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombreestructura" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombretipoplantilla" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Icm_Condicionesfijas" type="{http://schemas.meta4.com/}Icm_CondicionesfijasBlock"/>
 *         &lt;element name="Icm_Condicionescomision" type="{http://schemas.meta4.com/}Icm_CondicionescomisionBlock"/>
 *         &lt;element name="Icm_Condicionespoliticas" type="{http://schemas.meta4.com/}Icm_CondicionespoliticasBlock"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_PlantillacondicionesRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "inout",
    "nuevo",
    "borrado",
    "modificado",
    "idplantilla",
    "idestructura",
    "idtipoplantilla",
    "nombreplantilla",
    "nombreestructura",
    "nombretipoplantilla",
    "icmCondicionesfijas",
    "icmCondicionescomision",
    "icmCondicionespoliticas"
})
public class IcmPlantillacondicionesRecord implements Cloneable, CopyTo2, Equals2, HashCode2, ToString2
{

    @XmlElement(required = true, nillable = true)
    protected String m4AutoGeneratedRecordID;
    protected boolean m4AutoGeneratedToDelete;
    @XmlElement(required = true, nillable = true)
    protected String inout;
    @XmlElement(required = true, nillable = true)
    protected String nuevo;
    @XmlElement(required = true, nillable = true)
    protected String borrado;
    @XmlElement(required = true, nillable = true)
    protected String modificado;
    @XmlElement(required = true, nillable = true)
    protected String idplantilla;
    @XmlElement(required = true, nillable = true)
    protected String idestructura;
    @XmlElement(required = true, nillable = true)
    protected String idtipoplantilla;
    @XmlElement(required = true, nillable = true)
    protected String nombreplantilla;
    @XmlElement(required = true, nillable = true)
    protected String nombreestructura;
    @XmlElement(required = true, nillable = true)
    protected String nombretipoplantilla;
    @XmlElement(name = "Icm_Condicionesfijas", required = true, nillable = true)
    protected IcmCondicionesfijasBlock icmCondicionesfijas;
    @XmlElement(name = "Icm_Condicionescomision", required = true, nillable = true)
    protected IcmCondicionescomisionBlock icmCondicionescomision;
    @XmlElement(name = "Icm_Condicionespoliticas", required = true, nillable = true)
    protected IcmCondicionespoliticasBlock icmCondicionespoliticas;

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM4AutoGeneratedRecordID(String value) {
        this.m4AutoGeneratedRecordID = value;
    }

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public void setM4AutoGeneratedToDelete(boolean value) {
        this.m4AutoGeneratedToDelete = value;
    }

    /**
     * Obtiene el valor de la propiedad inout.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInout() {
        return inout;
    }

    /**
     * Define el valor de la propiedad inout.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInout(String value) {
        this.inout = value;
    }

    /**
     * Obtiene el valor de la propiedad nuevo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuevo() {
        return nuevo;
    }

    /**
     * Define el valor de la propiedad nuevo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuevo(String value) {
        this.nuevo = value;
    }

    /**
     * Obtiene el valor de la propiedad borrado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrado() {
        return borrado;
    }

    /**
     * Define el valor de la propiedad borrado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrado(String value) {
        this.borrado = value;
    }

    /**
     * Obtiene el valor de la propiedad modificado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificado() {
        return modificado;
    }

    /**
     * Define el valor de la propiedad modificado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificado(String value) {
        this.modificado = value;
    }

    /**
     * Obtiene el valor de la propiedad idplantilla.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdplantilla() {
        return idplantilla;
    }

    /**
     * Define el valor de la propiedad idplantilla.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdplantilla(String value) {
        this.idplantilla = value;
    }

    /**
     * Obtiene el valor de la propiedad idestructura.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdestructura() {
        return idestructura;
    }

    /**
     * Define el valor de la propiedad idestructura.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdestructura(String value) {
        this.idestructura = value;
    }

    /**
     * Obtiene el valor de la propiedad idtipoplantilla.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdtipoplantilla() {
        return idtipoplantilla;
    }

    /**
     * Define el valor de la propiedad idtipoplantilla.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdtipoplantilla(String value) {
        this.idtipoplantilla = value;
    }

    /**
     * Obtiene el valor de la propiedad nombreplantilla.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreplantilla() {
        return nombreplantilla;
    }

    /**
     * Define el valor de la propiedad nombreplantilla.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreplantilla(String value) {
        this.nombreplantilla = value;
    }

    /**
     * Obtiene el valor de la propiedad nombreestructura.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreestructura() {
        return nombreestructura;
    }

    /**
     * Define el valor de la propiedad nombreestructura.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreestructura(String value) {
        this.nombreestructura = value;
    }

    /**
     * Obtiene el valor de la propiedad nombretipoplantilla.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombretipoplantilla() {
        return nombretipoplantilla;
    }

    /**
     * Define el valor de la propiedad nombretipoplantilla.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombretipoplantilla(String value) {
        this.nombretipoplantilla = value;
    }

    /**
     * Obtiene el valor de la propiedad icmCondicionesfijas.
     * 
     * @return
     *     possible object is
     *     {@link IcmCondicionesfijasBlock }
     *     
     */
    public IcmCondicionesfijasBlock getIcmCondicionesfijas() {
        return icmCondicionesfijas;
    }

    /**
     * Define el valor de la propiedad icmCondicionesfijas.
     * 
     * @param value
     *     allowed object is
     *     {@link IcmCondicionesfijasBlock }
     *     
     */
    public void setIcmCondicionesfijas(IcmCondicionesfijasBlock value) {
        this.icmCondicionesfijas = value;
    }

    /**
     * Obtiene el valor de la propiedad icmCondicionescomision.
     * 
     * @return
     *     possible object is
     *     {@link IcmCondicionescomisionBlock }
     *     
     */
    public IcmCondicionescomisionBlock getIcmCondicionescomision() {
        return icmCondicionescomision;
    }

    /**
     * Define el valor de la propiedad icmCondicionescomision.
     * 
     * @param value
     *     allowed object is
     *     {@link IcmCondicionescomisionBlock }
     *     
     */
    public void setIcmCondicionescomision(IcmCondicionescomisionBlock value) {
        this.icmCondicionescomision = value;
    }

    /**
     * Obtiene el valor de la propiedad icmCondicionespoliticas.
     * 
     * @return
     *     possible object is
     *     {@link IcmCondicionespoliticasBlock }
     *     
     */
    public IcmCondicionespoliticasBlock getIcmCondicionespoliticas() {
        return icmCondicionespoliticas;
    }

    /**
     * Define el valor de la propiedad icmCondicionespoliticas.
     * 
     * @param value
     *     allowed object is
     *     {@link IcmCondicionespoliticasBlock }
     *     
     */
    public void setIcmCondicionespoliticas(IcmCondicionespoliticasBlock value) {
        this.icmCondicionespoliticas = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final IcmPlantillacondicionesRecord that = ((IcmPlantillacondicionesRecord) object);
        {
            String lhsM4AutoGeneratedRecordID;
            lhsM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            String rhsM4AutoGeneratedRecordID;
            rhsM4AutoGeneratedRecordID = that.getM4AutoGeneratedRecordID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedRecordID", lhsM4AutoGeneratedRecordID), LocatorUtils.property(thatLocator, "m4AutoGeneratedRecordID", rhsM4AutoGeneratedRecordID), lhsM4AutoGeneratedRecordID, rhsM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null), (that.m4AutoGeneratedRecordID!= null))) {
                return false;
            }
        }
        {
            boolean lhsM4AutoGeneratedToDelete;
            lhsM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            boolean rhsM4AutoGeneratedToDelete;
            rhsM4AutoGeneratedToDelete = that.isM4AutoGeneratedToDelete();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedToDelete", lhsM4AutoGeneratedToDelete), LocatorUtils.property(thatLocator, "m4AutoGeneratedToDelete", rhsM4AutoGeneratedToDelete), lhsM4AutoGeneratedToDelete, rhsM4AutoGeneratedToDelete, true, true)) {
                return false;
            }
        }
        {
            String lhsInout;
            lhsInout = this.getInout();
            String rhsInout;
            rhsInout = that.getInout();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "inout", lhsInout), LocatorUtils.property(thatLocator, "inout", rhsInout), lhsInout, rhsInout, (this.inout!= null), (that.inout!= null))) {
                return false;
            }
        }
        {
            String lhsNuevo;
            lhsNuevo = this.getNuevo();
            String rhsNuevo;
            rhsNuevo = that.getNuevo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nuevo", lhsNuevo), LocatorUtils.property(thatLocator, "nuevo", rhsNuevo), lhsNuevo, rhsNuevo, (this.nuevo!= null), (that.nuevo!= null))) {
                return false;
            }
        }
        {
            String lhsBorrado;
            lhsBorrado = this.getBorrado();
            String rhsBorrado;
            rhsBorrado = that.getBorrado();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "borrado", lhsBorrado), LocatorUtils.property(thatLocator, "borrado", rhsBorrado), lhsBorrado, rhsBorrado, (this.borrado!= null), (that.borrado!= null))) {
                return false;
            }
        }
        {
            String lhsModificado;
            lhsModificado = this.getModificado();
            String rhsModificado;
            rhsModificado = that.getModificado();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "modificado", lhsModificado), LocatorUtils.property(thatLocator, "modificado", rhsModificado), lhsModificado, rhsModificado, (this.modificado!= null), (that.modificado!= null))) {
                return false;
            }
        }
        {
            String lhsIdplantilla;
            lhsIdplantilla = this.getIdplantilla();
            String rhsIdplantilla;
            rhsIdplantilla = that.getIdplantilla();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idplantilla", lhsIdplantilla), LocatorUtils.property(thatLocator, "idplantilla", rhsIdplantilla), lhsIdplantilla, rhsIdplantilla, (this.idplantilla!= null), (that.idplantilla!= null))) {
                return false;
            }
        }
        {
            String lhsIdestructura;
            lhsIdestructura = this.getIdestructura();
            String rhsIdestructura;
            rhsIdestructura = that.getIdestructura();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idestructura", lhsIdestructura), LocatorUtils.property(thatLocator, "idestructura", rhsIdestructura), lhsIdestructura, rhsIdestructura, (this.idestructura!= null), (that.idestructura!= null))) {
                return false;
            }
        }
        {
            String lhsIdtipoplantilla;
            lhsIdtipoplantilla = this.getIdtipoplantilla();
            String rhsIdtipoplantilla;
            rhsIdtipoplantilla = that.getIdtipoplantilla();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idtipoplantilla", lhsIdtipoplantilla), LocatorUtils.property(thatLocator, "idtipoplantilla", rhsIdtipoplantilla), lhsIdtipoplantilla, rhsIdtipoplantilla, (this.idtipoplantilla!= null), (that.idtipoplantilla!= null))) {
                return false;
            }
        }
        {
            String lhsNombreplantilla;
            lhsNombreplantilla = this.getNombreplantilla();
            String rhsNombreplantilla;
            rhsNombreplantilla = that.getNombreplantilla();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nombreplantilla", lhsNombreplantilla), LocatorUtils.property(thatLocator, "nombreplantilla", rhsNombreplantilla), lhsNombreplantilla, rhsNombreplantilla, (this.nombreplantilla!= null), (that.nombreplantilla!= null))) {
                return false;
            }
        }
        {
            String lhsNombreestructura;
            lhsNombreestructura = this.getNombreestructura();
            String rhsNombreestructura;
            rhsNombreestructura = that.getNombreestructura();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nombreestructura", lhsNombreestructura), LocatorUtils.property(thatLocator, "nombreestructura", rhsNombreestructura), lhsNombreestructura, rhsNombreestructura, (this.nombreestructura!= null), (that.nombreestructura!= null))) {
                return false;
            }
        }
        {
            String lhsNombretipoplantilla;
            lhsNombretipoplantilla = this.getNombretipoplantilla();
            String rhsNombretipoplantilla;
            rhsNombretipoplantilla = that.getNombretipoplantilla();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nombretipoplantilla", lhsNombretipoplantilla), LocatorUtils.property(thatLocator, "nombretipoplantilla", rhsNombretipoplantilla), lhsNombretipoplantilla, rhsNombretipoplantilla, (this.nombretipoplantilla!= null), (that.nombretipoplantilla!= null))) {
                return false;
            }
        }
        {
            IcmCondicionesfijasBlock lhsIcmCondicionesfijas;
            lhsIcmCondicionesfijas = this.getIcmCondicionesfijas();
            IcmCondicionesfijasBlock rhsIcmCondicionesfijas;
            rhsIcmCondicionesfijas = that.getIcmCondicionesfijas();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "icmCondicionesfijas", lhsIcmCondicionesfijas), LocatorUtils.property(thatLocator, "icmCondicionesfijas", rhsIcmCondicionesfijas), lhsIcmCondicionesfijas, rhsIcmCondicionesfijas, (this.icmCondicionesfijas!= null), (that.icmCondicionesfijas!= null))) {
                return false;
            }
        }
        {
            IcmCondicionescomisionBlock lhsIcmCondicionescomision;
            lhsIcmCondicionescomision = this.getIcmCondicionescomision();
            IcmCondicionescomisionBlock rhsIcmCondicionescomision;
            rhsIcmCondicionescomision = that.getIcmCondicionescomision();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "icmCondicionescomision", lhsIcmCondicionescomision), LocatorUtils.property(thatLocator, "icmCondicionescomision", rhsIcmCondicionescomision), lhsIcmCondicionescomision, rhsIcmCondicionescomision, (this.icmCondicionescomision!= null), (that.icmCondicionescomision!= null))) {
                return false;
            }
        }
        {
            IcmCondicionespoliticasBlock lhsIcmCondicionespoliticas;
            lhsIcmCondicionespoliticas = this.getIcmCondicionespoliticas();
            IcmCondicionespoliticasBlock rhsIcmCondicionespoliticas;
            rhsIcmCondicionespoliticas = that.getIcmCondicionespoliticas();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "icmCondicionespoliticas", lhsIcmCondicionespoliticas), LocatorUtils.property(thatLocator, "icmCondicionespoliticas", rhsIcmCondicionespoliticas), lhsIcmCondicionespoliticas, rhsIcmCondicionespoliticas, (this.icmCondicionespoliticas!= null), (that.icmCondicionespoliticas!= null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            String theM4AutoGeneratedRecordID;
            theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            strategy.appendField(locator, this, "m4AutoGeneratedRecordID", buffer, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null));
        }
        {
            boolean theM4AutoGeneratedToDelete;
            theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            strategy.appendField(locator, this, "m4AutoGeneratedToDelete", buffer, theM4AutoGeneratedToDelete, true);
        }
        {
            String theInout;
            theInout = this.getInout();
            strategy.appendField(locator, this, "inout", buffer, theInout, (this.inout!= null));
        }
        {
            String theNuevo;
            theNuevo = this.getNuevo();
            strategy.appendField(locator, this, "nuevo", buffer, theNuevo, (this.nuevo!= null));
        }
        {
            String theBorrado;
            theBorrado = this.getBorrado();
            strategy.appendField(locator, this, "borrado", buffer, theBorrado, (this.borrado!= null));
        }
        {
            String theModificado;
            theModificado = this.getModificado();
            strategy.appendField(locator, this, "modificado", buffer, theModificado, (this.modificado!= null));
        }
        {
            String theIdplantilla;
            theIdplantilla = this.getIdplantilla();
            strategy.appendField(locator, this, "idplantilla", buffer, theIdplantilla, (this.idplantilla!= null));
        }
        {
            String theIdestructura;
            theIdestructura = this.getIdestructura();
            strategy.appendField(locator, this, "idestructura", buffer, theIdestructura, (this.idestructura!= null));
        }
        {
            String theIdtipoplantilla;
            theIdtipoplantilla = this.getIdtipoplantilla();
            strategy.appendField(locator, this, "idtipoplantilla", buffer, theIdtipoplantilla, (this.idtipoplantilla!= null));
        }
        {
            String theNombreplantilla;
            theNombreplantilla = this.getNombreplantilla();
            strategy.appendField(locator, this, "nombreplantilla", buffer, theNombreplantilla, (this.nombreplantilla!= null));
        }
        {
            String theNombreestructura;
            theNombreestructura = this.getNombreestructura();
            strategy.appendField(locator, this, "nombreestructura", buffer, theNombreestructura, (this.nombreestructura!= null));
        }
        {
            String theNombretipoplantilla;
            theNombretipoplantilla = this.getNombretipoplantilla();
            strategy.appendField(locator, this, "nombretipoplantilla", buffer, theNombretipoplantilla, (this.nombretipoplantilla!= null));
        }
        {
            IcmCondicionesfijasBlock theIcmCondicionesfijas;
            theIcmCondicionesfijas = this.getIcmCondicionesfijas();
            strategy.appendField(locator, this, "icmCondicionesfijas", buffer, theIcmCondicionesfijas, (this.icmCondicionesfijas!= null));
        }
        {
            IcmCondicionescomisionBlock theIcmCondicionescomision;
            theIcmCondicionescomision = this.getIcmCondicionescomision();
            strategy.appendField(locator, this, "icmCondicionescomision", buffer, theIcmCondicionescomision, (this.icmCondicionescomision!= null));
        }
        {
            IcmCondicionespoliticasBlock theIcmCondicionespoliticas;
            theIcmCondicionespoliticas = this.getIcmCondicionespoliticas();
            strategy.appendField(locator, this, "icmCondicionespoliticas", buffer, theIcmCondicionespoliticas, (this.icmCondicionespoliticas!= null));
        }
        return buffer;
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            String theM4AutoGeneratedRecordID;
            theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", theM4AutoGeneratedRecordID), currentHashCode, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null));
        }
        {
            boolean theM4AutoGeneratedToDelete;
            theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", theM4AutoGeneratedToDelete), currentHashCode, theM4AutoGeneratedToDelete, true);
        }
        {
            String theInout;
            theInout = this.getInout();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "inout", theInout), currentHashCode, theInout, (this.inout!= null));
        }
        {
            String theNuevo;
            theNuevo = this.getNuevo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nuevo", theNuevo), currentHashCode, theNuevo, (this.nuevo!= null));
        }
        {
            String theBorrado;
            theBorrado = this.getBorrado();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "borrado", theBorrado), currentHashCode, theBorrado, (this.borrado!= null));
        }
        {
            String theModificado;
            theModificado = this.getModificado();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "modificado", theModificado), currentHashCode, theModificado, (this.modificado!= null));
        }
        {
            String theIdplantilla;
            theIdplantilla = this.getIdplantilla();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idplantilla", theIdplantilla), currentHashCode, theIdplantilla, (this.idplantilla!= null));
        }
        {
            String theIdestructura;
            theIdestructura = this.getIdestructura();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idestructura", theIdestructura), currentHashCode, theIdestructura, (this.idestructura!= null));
        }
        {
            String theIdtipoplantilla;
            theIdtipoplantilla = this.getIdtipoplantilla();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idtipoplantilla", theIdtipoplantilla), currentHashCode, theIdtipoplantilla, (this.idtipoplantilla!= null));
        }
        {
            String theNombreplantilla;
            theNombreplantilla = this.getNombreplantilla();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nombreplantilla", theNombreplantilla), currentHashCode, theNombreplantilla, (this.nombreplantilla!= null));
        }
        {
            String theNombreestructura;
            theNombreestructura = this.getNombreestructura();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nombreestructura", theNombreestructura), currentHashCode, theNombreestructura, (this.nombreestructura!= null));
        }
        {
            String theNombretipoplantilla;
            theNombretipoplantilla = this.getNombretipoplantilla();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nombretipoplantilla", theNombretipoplantilla), currentHashCode, theNombretipoplantilla, (this.nombretipoplantilla!= null));
        }
        {
            IcmCondicionesfijasBlock theIcmCondicionesfijas;
            theIcmCondicionesfijas = this.getIcmCondicionesfijas();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "icmCondicionesfijas", theIcmCondicionesfijas), currentHashCode, theIcmCondicionesfijas, (this.icmCondicionesfijas!= null));
        }
        {
            IcmCondicionescomisionBlock theIcmCondicionescomision;
            theIcmCondicionescomision = this.getIcmCondicionescomision();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "icmCondicionescomision", theIcmCondicionescomision), currentHashCode, theIcmCondicionescomision, (this.icmCondicionescomision!= null));
        }
        {
            IcmCondicionespoliticasBlock theIcmCondicionespoliticas;
            theIcmCondicionespoliticas = this.getIcmCondicionespoliticas();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "icmCondicionespoliticas", theIcmCondicionespoliticas), currentHashCode, theIcmCondicionespoliticas, (this.icmCondicionespoliticas!= null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof IcmPlantillacondicionesRecord) {
            final IcmPlantillacondicionesRecord copy = ((IcmPlantillacondicionesRecord) draftCopy);
            {
                Boolean m4AutoGeneratedRecordIDShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.m4AutoGeneratedRecordID!= null));
                if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceM4AutoGeneratedRecordID;
                    sourceM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
                    String copyM4AutoGeneratedRecordID = ((String) strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", sourceM4AutoGeneratedRecordID), sourceM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null)));
                    copy.setM4AutoGeneratedRecordID(copyM4AutoGeneratedRecordID);
                } else {
                    if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.m4AutoGeneratedRecordID = null;
                    }
                }
            }
            {
                Boolean m4AutoGeneratedToDeleteShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, true);
                if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.TRUE) {
                    boolean sourceM4AutoGeneratedToDelete;
                    sourceM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
                    boolean copyM4AutoGeneratedToDelete = strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", sourceM4AutoGeneratedToDelete), sourceM4AutoGeneratedToDelete, true);
                    copy.setM4AutoGeneratedToDelete(copyM4AutoGeneratedToDelete);
                } else {
                    if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.FALSE) {
                    }
                }
            }
            {
                Boolean inoutShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.inout!= null));
                if (inoutShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceInout;
                    sourceInout = this.getInout();
                    String copyInout = ((String) strategy.copy(LocatorUtils.property(locator, "inout", sourceInout), sourceInout, (this.inout!= null)));
                    copy.setInout(copyInout);
                } else {
                    if (inoutShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.inout = null;
                    }
                }
            }
            {
                Boolean nuevoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.nuevo!= null));
                if (nuevoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceNuevo;
                    sourceNuevo = this.getNuevo();
                    String copyNuevo = ((String) strategy.copy(LocatorUtils.property(locator, "nuevo", sourceNuevo), sourceNuevo, (this.nuevo!= null)));
                    copy.setNuevo(copyNuevo);
                } else {
                    if (nuevoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.nuevo = null;
                    }
                }
            }
            {
                Boolean borradoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.borrado!= null));
                if (borradoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceBorrado;
                    sourceBorrado = this.getBorrado();
                    String copyBorrado = ((String) strategy.copy(LocatorUtils.property(locator, "borrado", sourceBorrado), sourceBorrado, (this.borrado!= null)));
                    copy.setBorrado(copyBorrado);
                } else {
                    if (borradoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.borrado = null;
                    }
                }
            }
            {
                Boolean modificadoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.modificado!= null));
                if (modificadoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceModificado;
                    sourceModificado = this.getModificado();
                    String copyModificado = ((String) strategy.copy(LocatorUtils.property(locator, "modificado", sourceModificado), sourceModificado, (this.modificado!= null)));
                    copy.setModificado(copyModificado);
                } else {
                    if (modificadoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.modificado = null;
                    }
                }
            }
            {
                Boolean idplantillaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idplantilla!= null));
                if (idplantillaShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdplantilla;
                    sourceIdplantilla = this.getIdplantilla();
                    String copyIdplantilla = ((String) strategy.copy(LocatorUtils.property(locator, "idplantilla", sourceIdplantilla), sourceIdplantilla, (this.idplantilla!= null)));
                    copy.setIdplantilla(copyIdplantilla);
                } else {
                    if (idplantillaShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idplantilla = null;
                    }
                }
            }
            {
                Boolean idestructuraShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idestructura!= null));
                if (idestructuraShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdestructura;
                    sourceIdestructura = this.getIdestructura();
                    String copyIdestructura = ((String) strategy.copy(LocatorUtils.property(locator, "idestructura", sourceIdestructura), sourceIdestructura, (this.idestructura!= null)));
                    copy.setIdestructura(copyIdestructura);
                } else {
                    if (idestructuraShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idestructura = null;
                    }
                }
            }
            {
                Boolean idtipoplantillaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idtipoplantilla!= null));
                if (idtipoplantillaShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdtipoplantilla;
                    sourceIdtipoplantilla = this.getIdtipoplantilla();
                    String copyIdtipoplantilla = ((String) strategy.copy(LocatorUtils.property(locator, "idtipoplantilla", sourceIdtipoplantilla), sourceIdtipoplantilla, (this.idtipoplantilla!= null)));
                    copy.setIdtipoplantilla(copyIdtipoplantilla);
                } else {
                    if (idtipoplantillaShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idtipoplantilla = null;
                    }
                }
            }
            {
                Boolean nombreplantillaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.nombreplantilla!= null));
                if (nombreplantillaShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceNombreplantilla;
                    sourceNombreplantilla = this.getNombreplantilla();
                    String copyNombreplantilla = ((String) strategy.copy(LocatorUtils.property(locator, "nombreplantilla", sourceNombreplantilla), sourceNombreplantilla, (this.nombreplantilla!= null)));
                    copy.setNombreplantilla(copyNombreplantilla);
                } else {
                    if (nombreplantillaShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.nombreplantilla = null;
                    }
                }
            }
            {
                Boolean nombreestructuraShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.nombreestructura!= null));
                if (nombreestructuraShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceNombreestructura;
                    sourceNombreestructura = this.getNombreestructura();
                    String copyNombreestructura = ((String) strategy.copy(LocatorUtils.property(locator, "nombreestructura", sourceNombreestructura), sourceNombreestructura, (this.nombreestructura!= null)));
                    copy.setNombreestructura(copyNombreestructura);
                } else {
                    if (nombreestructuraShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.nombreestructura = null;
                    }
                }
            }
            {
                Boolean nombretipoplantillaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.nombretipoplantilla!= null));
                if (nombretipoplantillaShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceNombretipoplantilla;
                    sourceNombretipoplantilla = this.getNombretipoplantilla();
                    String copyNombretipoplantilla = ((String) strategy.copy(LocatorUtils.property(locator, "nombretipoplantilla", sourceNombretipoplantilla), sourceNombretipoplantilla, (this.nombretipoplantilla!= null)));
                    copy.setNombretipoplantilla(copyNombretipoplantilla);
                } else {
                    if (nombretipoplantillaShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.nombretipoplantilla = null;
                    }
                }
            }
            {
                Boolean icmCondicionesfijasShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.icmCondicionesfijas!= null));
                if (icmCondicionesfijasShouldBeCopiedAndSet == Boolean.TRUE) {
                    IcmCondicionesfijasBlock sourceIcmCondicionesfijas;
                    sourceIcmCondicionesfijas = this.getIcmCondicionesfijas();
                    IcmCondicionesfijasBlock copyIcmCondicionesfijas = ((IcmCondicionesfijasBlock) strategy.copy(LocatorUtils.property(locator, "icmCondicionesfijas", sourceIcmCondicionesfijas), sourceIcmCondicionesfijas, (this.icmCondicionesfijas!= null)));
                    copy.setIcmCondicionesfijas(copyIcmCondicionesfijas);
                } else {
                    if (icmCondicionesfijasShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.icmCondicionesfijas = null;
                    }
                }
            }
            {
                Boolean icmCondicionescomisionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.icmCondicionescomision!= null));
                if (icmCondicionescomisionShouldBeCopiedAndSet == Boolean.TRUE) {
                    IcmCondicionescomisionBlock sourceIcmCondicionescomision;
                    sourceIcmCondicionescomision = this.getIcmCondicionescomision();
                    IcmCondicionescomisionBlock copyIcmCondicionescomision = ((IcmCondicionescomisionBlock) strategy.copy(LocatorUtils.property(locator, "icmCondicionescomision", sourceIcmCondicionescomision), sourceIcmCondicionescomision, (this.icmCondicionescomision!= null)));
                    copy.setIcmCondicionescomision(copyIcmCondicionescomision);
                } else {
                    if (icmCondicionescomisionShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.icmCondicionescomision = null;
                    }
                }
            }
            {
                Boolean icmCondicionespoliticasShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.icmCondicionespoliticas!= null));
                if (icmCondicionespoliticasShouldBeCopiedAndSet == Boolean.TRUE) {
                    IcmCondicionespoliticasBlock sourceIcmCondicionespoliticas;
                    sourceIcmCondicionespoliticas = this.getIcmCondicionespoliticas();
                    IcmCondicionespoliticasBlock copyIcmCondicionespoliticas = ((IcmCondicionespoliticasBlock) strategy.copy(LocatorUtils.property(locator, "icmCondicionespoliticas", sourceIcmCondicionespoliticas), sourceIcmCondicionespoliticas, (this.icmCondicionespoliticas!= null)));
                    copy.setIcmCondicionespoliticas(copyIcmCondicionespoliticas);
                } else {
                    if (icmCondicionespoliticasShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.icmCondicionespoliticas = null;
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new IcmPlantillacondicionesRecord();
    }

}
