package com.inditex.rrhh.icmclcwb.api.meta4.empleadostienda.dto;

import java.io.Serializable;

import lombok.Data;

@Data
public class EmpleadosTiendaResultItemDTO implements Serializable  {
	
	private static final long serialVersionUID = -3187757459782088845L;

	private String m4AutoGeneratedRecordID;

	private boolean m4AutoGeneratedToDelete;

	private String inOut;

	private String idPuesto;

	private String idSeccion;

	private String idEmpleado;

	private String nombrePuesto;

	private String numRegistros;

	private String nombreSeccion;

	private String desplazamiento;

	private String nombreEmpleado;

	private String idEmpleadoLocal;

}
