spring:
  application:
    name: ICMCLCWB
  profiles:
    active: standalone
app:
  id: ${spring.application.name}
  version: '@project.version@'
amiga:
  common:
    cache:
      remote:
        enabled: true
    logging:
      includeFullMDC: true
      file:
        enabled: false
      graylog:
        enabled: false
    async:
      default-executor:
        #name-format: async-test-default-executor-%d
        core-pool-size: 25
        maximum-pool-size: 150
        keep-alive-time: 60s
  service:
    session:
      session-type: REMOTE
    core:
      mdc-filter:
        enabled: true
    aaa:
      local:
        enable-local-test: true
      classic:
        sso:
          applicationSSO: AppJoinFashionIntegracion
    rest-swagger:
      ui:
        title: '@project.name@'
        description: '@project.description@'