logging:
  level:
    root: WARN
    com.inditex.rrhh.icmclcwb: INFO
metadata:
  tenant: global
  domain: core
  openshiftproject: icmclcwb
  slot: develop
spring:
  jta:
    atomikos:
      properties:
        enable-logging: false
amiga:
  monitoring:
    metrics:
      enabled: true
      send: false
  common:
    core:
      is-production: false
    cache:
      remote:
        enabled: false
      embedded:
        enabled: true
    rest:
      client:
        defaultConnectTimeout: 300000
        defaultReadTimeout: 300000
        ptr-venta:
          base-url: http://axdesptrapp01-vip.central.inditex.grp:33813/OFDAVTIMPADWSD/service
          #base-url: http://axpreptrapp01-vip.central.inditex.grp:10813/OFDAVTIMPADWSD/service
        ptr-presencia:
          base-url: http://axdesptrapp01-vip.central.inditex.grp:33813/OFDARHPRSCAWSD/service
          #base-url: http://axpreptrapp01-vip.central.inditex.grp:10813/OFDARHPRSCAWSD/service
  service:
    jms:
      trabajo-queue:
        destination-fqdn: ${metadata.tenant}.${metadata.domain}.${metadata.openshiftproject}.private.trabajo-queue-${metadata.slot}
        concurrency: 10-20
      tarea-queue:
        destination-fqdn: ${metadata.tenant}.${metadata.domain}.${metadata.openshiftproject}.private.tarea-queue-${metadata.slot}
        concurrency: 10-20
    session:
      session-type: EMBEDDED
    aaa:
      local:
        enable-local-test: true
    rest:
      logging:
        is-production: false
  data:
    jms:
      connection-factory:
        broker-escritura:
          brokerURL: tcp://10.202.10.178:61616?jms.redeliveryPolicy.maximumRedeliveries=10
          userName: root
          password: V3ct0r1nd1t3x
        broker-lectura:
          brokerURL: tcp://10.202.10.178:61616?jms.redeliveryPolicy.maximumRedeliveries=10
          userName: root
          password: V3ct0r1nd1t3x
      client:
        trabajo:
          destinationName: ${amiga.service.jms.trabajo-queue.destination-fqdn}
          receiveTimeout: 100
          pubSubDomain: false
        tarea:
          destinationName: ${amiga.service.jms.tarea-queue.destination-fqdn}
          receiveTimeout: 100
          pubSubDomain: false
    jdbc:
      configuration:
        prop:
          default-isolation-level: 1
          max-pool-size: 20
      datasource:
        primary:
          driverClassName: com.ibm.db2.jcc.DB2Driver
          url: jdbc:db2://axdesdb22.central.inditex.grp:50000/INDITEX:currentSchema=DESARROLLO_RRHH;
          user: oincome
          password: aMJLp8ahF09w
    hibernate:
      primary:
        #properties: '{''hibernate.hbm2ddl.auto'':''create'',''hibernate.connection.CharSet'':''utf8'',''hibernate.connection.characterEncoding'':''utf8'',''hibernate.connection.useUnicode'':''true'',''hibernate.hbm2ddl.import_files'':''import-primary-ddl.sql,import-primary-dml.sql'',''hibernate.dialect'':''com.inditex.rrhh.icmclcwb.model.primary.dialect.DB2NativeDialect'',''hibernate.connection.CharSet'':''utf8'',''hibernate.connection.characterEncoding'':''utf8'',''hibernate.connection.useUnicode'':''true'',''hibernate.show_sql'':''false'',''hibernate.format_sql'':''false'',''hibernate.jdbc.batch_size'':''1000'',''hibernate.order_inserts'':''true'',''hibernate.order_updates'':''true'',''hibernate.jdbc.batch_versioned_data'':''true'',''hibernate.generate_statistics'':''true''}'
        #properties: '{''hibernate.dialect'':''com.inditex.rrhh.icmclcwb.model.primary.dialect.DB2NativeDialect'',''hibernate.connection.CharSet'':''utf8'',''hibernate.connection.characterEncoding'':''utf8'',''hibernate.connection.useUnicode'':''true'',''hibernate.show_sql'':''false'',''hibernate.format_sql'':''false'',''hibernate.jdbc.batch_size'':''1000'',''hibernate.order_inserts'':''true'',''hibernate.order_updates'':''true'',''hibernate.jdbc.batch_versioned_data'':''true'',''hibernate.generate_statistics'':''true''}'
        properties: '{''hibernate.dialect'':''com.inditex.rrhh.icmclcwb.model.primary.dialect.DB2NativeDialect''}'
app:
  envars:
    calculo:
      cast: false
      precision: 'AS DECIMAL(23, 8)'  
    proceso: 
      cast: true
      precision: 'AS DECIMAL(23, 8)'  
    tarea:
      recolectar:
        days-number: 3
      validar:
        enabled: true
        logging: true
        exception: false
      calcular:
        algoritmo:
          config:
            #batch-size: 1000
            batch-size: 10
    repository:
      batch-size:
        default: 100
        tarea-tienda-venta: 200
    ptr:
      config:
        max-attempts: 2
      venta:
        service:
          version: 1.0.33
          acumuladoVentaImporte:
            getVentaAcumDia:
              endpoint: /acumuladoVentaImporte/getVentaAcumDia
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            getVentaAcumUTC:
              endpoint: /acumuladoVentaImporte/getVentaAcumUTC
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            test:
              endpoint: /acumuladoVentaImporte/test
            getVersion:
              endpoint: /acumuladoVentaImporte/getVersion                    
          ventaEcommerce:
            getVentaOnlineEntregaTienda:
              endpoint: /ventaEcommerce/getVentaOnlineEntregaTienda
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            getVentaOnlineEntregaDomicilio:
              endpoint: /ventaEcommerce/getVentaOnlineEntregaDomicilio
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            getVentaOnlineiPod:
              endpoint: /ventaEcommerce/getVentaOnlineiPod
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            getVentaOnlineIpodIndividualDetalle:
              endpoint: /ventaEcommerce/getVentaOnlineIpodIndividualDetalle
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            getOrdersByCountryMinute:
              endpoint: /ventaEcommerce/getOrdersByCountryMinute
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            getOrdersByCountrySectionProductHour:
              endpoint: /ventaEcommerce/getOrdersByCountrySectionProductHour
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            getOrdersByCountrySectionProductMinute:
              endpoint: /ventaEcommerce/getOrdersByCountrySectionProductMinute
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            getVentaOnlinePicking:
              endpoint: /ventaEcommerce/getVentaOnlinePicking
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            getOrdersByCountryHour:
              endpoint: /ventaEcommerce/getOrdersByCountryHour
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            test:
              endpoint: /ventaEcommerce/test
            getVersion:
              endpoint: /ventaEcommerce/getVersion          
          ventaEmpleado: 
            getVentaIndividualDetalle:
              endpoint: /ventaEmpleado/getVentaIndividualDetalle
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            getVentaIndividualDetalleByMCC:
              endpoint: /ventaEmpleado/getVentaIndividualDetalleByMCC
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            getVentaIndividual:
              endpoint: /ventaEmpleado/getVentaIndividual
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            getVentaIndividualByMCC:
              endpoint: /ventaEmpleado/getVentaIndividualByMCC
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
            test:
              endpoint: /ventaEmpleado/test
            getVersion:
              endpoint: /ventaEmpleado/getVersion                        
          ventaGeneral:
            getVentaTotalizado:
              endpoint: /ventaGeneral/getVentaTotalizado
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            getVentaMensual:
              endpoint: /ventaGeneral/getVentaMensual
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            getVentaDiaria: 
              endpoint: /ventaGeneral/getVentaDiaria
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            getVentaTotalizadoXML: 
              endpoint: /ventaGeneral/getVentaTotalizadoXML
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            getVentaTotalizadoByMCC: 
              endpoint: /ventaGeneral/getVentaTotalizadoByMCC
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            getVentaPresupuestadaMensual:
              endpoint: /ventaGeneral/getVentaPresupuestadaMensual
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            test:
              endpoint: /ventaGeneral/test
            getVersion:
              endpoint: /ventaGeneral/getVersion
      presencia: 
        service:
          version: 1.0.15-rc.1
          presenciasService:
            getPresenciasTotalizado:
              endpoint: /presenciasService/presenciasTotalizado
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            getPresenciasTotalTiendaSeccion:
              endpoint: /presenciasService/presenciasTotalTiendaSeccion
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            getPresenciasTotalTienda:
              endpoint: /presenciasService/presenciasTotalTienda
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            getPresenciasDetalle:
              endpoint: /presenciasService/presenciasDetalle
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            getPresenciasDetalleComisionable:
              endpoint: /presenciasService/presenciasDetalleComisionable
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            getPresenciasTiendasEmpleado:
              endpoint: /presenciasService/presenciasTiendasEmpleado
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            getPresenciasEmpleadosTienda:
              endpoint: /presenciasService/presenciasEmpleadosTienda
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            getTiposHoras:
              endpoint: /presenciasService/tiposHoras
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
            test:
              endpoint: /presenciasService/test
            getVersion:
              endpoint: /presenciasService/getVersion                
    meta4:
      config:
        max-attempts: 20
        credentials:
          user: INCOME_CALC
          password: 123
          #user: CRISTINASOL
          #password: 1234
          language: 2
        pool:
          size: 20
          claimTimeout: 30000
          shutdownTimeout: 60000
        timeout:
          connectTimeout: 300000
          receiveTimeout: 300000
      login:
        server: https://develop-icmclcws.axdesocp1.central.inditex.grp/services/Login
        #server: https://pre-icmclcws.axpreocp1.central.inditex.grp/services/Login
      icmwscalcincome:
        server: https://develop-icmclcws.axdesocp1.central.inditex.grp/services/ICM_WS_CALC_INCOME
        #server: https://pre-icmclcws.axpreocp1.central.inditex.grp/services/ICM_WS_CALC_INCOME
        service:
          getFestivos:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getCoefJornada:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getFlagCalcula:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getPresenciaManual:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getEmpleadosPresencia:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getPeriodos:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getTiendasEmpleado:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          searchTiendas:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getTiendas:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          searchEmpleados:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getComisionEmpleado:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getEmpleados:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3