-- Eliminación de la relación entre algoritmo PorVentaSimplificado en todas sus variantes y tipo cálculo
DELETE FROM ALGORITMO_TIPO_CALCULO WHERE ID_ALGORITMO IN (8001,8002,8003,8006,8007,8008,8011,8012,8013);

-- Eliminación de la relación entre algoritmo PorVentaSimplificado en tdoas sus variantes y tipo comisión
DELETE FROM ALGORITMO_TIPO_COMISION WHERE ID_ALGORITMO IN (8001,8002,8003,8006,8007,8008,8011,8012,8013);

-- Eliminación de la relación entre algoritmo PorVentaSimplificado en todas sus variantes y tipo dato
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO IN (8001,8002,8003,8006,8007,8008,8011,8012,8013);

-- Eliminación del propio algoritmo PorVentaSimplificado en todas sus variantes
DELETE FROM ALGORITMO WHERE ID_ALGORITMO IN (8001,8002,8003,8006,8007,8008,8011,8012,8013);

-- Tipos de dato relacionados con PorVentaSimplificado
DELETE FROM TIPO_DATO WHERE ID_TIPO_DATO IN (3032, 5013);

-- Nuevo tipo de grupo de dato para los calculos VentaOnline
-- TIPO_GRUPO_DATO
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2033, 'VENTA_ONLINE_EXCLUIDO_IPOD_LOCALIZACION', 'Venta online exclulido ipod [localizacion]');

-- TIPO_GRUPO_DATO_TIPO_DATO
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2033, 2005);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2033, 2006);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2033, 2007);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2033, 2008);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2033, 3001);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2033, 3002);

--Nuevos tipos de cálculo y algoritmos para VentaOnline
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('015', 'GLOBAL_TIENDA_VENTA_ONLINE');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('016', 'GLOBAL_SECCION_VENTA_ONLINE');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('017', 'DIRECTO_VENTA_ONLINE');

INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (8001, 1, 'globalTiendaVentaOnlinePorcentajeV1', 0, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (8001, '015');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (8002, 1, 'globalTiendaVentaOnlinePorcentajeDesplazamientoV1', 1, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (8002, '015');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (8003, 1, 'globalTiendaVentaOnlinePorcentajeDesplazamientoBaseV1', 1, 1);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (8003, '015');

