INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (1, 'PENDIENTE CÁLCULO');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (2, 'EN CURSO VALIDACIONES INICIALES');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (3, 'EN CURSO CARGA DATOS INTERMEDIOS');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (4, 'EN CURSO EJECUCIÓN PRECALCULO');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (5, 'EN CURSO EJECUCIÓN CALCULO');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (6, 'EN CURSO EJECUCIÓN POSTCALCULO');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (7, 'PENDIENTE CONSOLIDACIÓN');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (8, 'EN CURSO CONSOLIDACIÓN');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (9, 'CALCULADO');
