INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2045, 'VENTA_FISICA_LOCALIZACION_REPARTO_ONLINE', 'Venta física para su uso en el reparto de la venta online entrega domicilio', 0, NULL, 1);

-- Se aprovecha el tipo de grupo de dato de venta fisica localizacion, que no se usa en ninguna parte a día de hoy
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2002, 2045);
-- Borrar el tipo de dato de seccion que existía en el grupo de dato y que ya no es necesario
DELETE FROM TIPO_GRUPO_DATO_TIPO_DATO WHERE ID_TIPO_GRUPO_DATO = 2002 AND ID_TIPO_DATO = 2002;

INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION)
VALUES (3010, 'PRESENCIA_LOCALIZACION-SECCION-PERSONA-TIPO-HORA-LOCALIZACION-ABIERTA', 'Presencias [localizacion|seccion|persona|tipo hora|localizacion abierta]');

INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3010, 4002);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3010, 4003);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3010, 4004);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3010, 5010);
