--Con este script se cargan los tipos de cálculo y de comisión en las nuevas columnas creadas en la tabla de TAREA_CALCULO

MERGE INTO TAREA_CALCULO AS TC USING
(
    SELECT
      TC.FECHA_INICIO_PERIODO,
      TC.ID_TAREA_CALCULO,
      TPE.ICM_ID_TP_CALCULO,
      TPE.ICM_ID_TP_COMISION
    FROM TAREA_CALCULO TC
    INNER JOIN TAREA_PERSONA_ESTRUCTURA TPE
      ON TC.FECHA_INICIO_PERIODO = TPE.FECHA_INICIO_PERIODO
      AND TC.ID_TAREA_PERSONA_ESTRUCTURA = TPE.ID_TAREA_PERSONA_ESTRUCTURA
) AS S ON (S.FECHA_INICIO_PERIODO = TC.FECHA_INICIO_PERIODO AND S.ID_TAREA_CALCULO = TC.ID_TAREA_CALCULO)
  WHEN MATCHED THEN UPDATE SET TC.ID_TIPO_CALCULO = S.ICM_ID_TP_CALCULO, TC.ID_TIPO_COMISION = S.ICM_ID_TP_COMISION