/*Tipos presupuesto*/
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (1, '01', 'Mensual', 'Mensual');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (2, '02', 'Bimensual', 'Bimensual');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (3, '03', 'Trimestral', 'Trimestral');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (4, '04', 'Cuatrimestral', 'Cuatrimestral');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (5, '05', 'Semestral', 'Semestral');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (6, '06', 'Anual', 'Anual');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (7, '07', 'Abierto', 'Abierto');

/*Tipos concepto venta challenge*/
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (1, 'VENTA_CAJA', 'Venta caja', '01', 1);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (2, 'DEVOLUCIONES_OTRAS_TIENDAS', 'Devoluciones otras tiendas', '02', 1);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (3, 'ONLINE_IPOD', 'Venta online iPod', '03', 2);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (4, 'ONLINE_SINT', 'Venta online SINT', '04', 3);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (5, 'ONLINE_ENTREGA_TIENDA', 'Venta online entrega en tienda', '05', 4);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (6, 'ONLINE_ENTREGA_DOMICILIO', 'Venta online entrega en domicilio', '06', 5);

/*Nuevos tipos de dato*/
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2015, 'VENTA_RANGO_CONGELADA_FISICA_CAJA_LOCALIZACION', 'Venta rango congelada fisica [localizacion]', 0, NULL, 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2016, 'VENTA_RANGO_CONGELADA_FISICA_CAJA_LOCALIZACION_SECCION', 'Venta rango congelada fisica [localizacion|seccion]', 0, NULL, 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2017, 'VENTA_RANGO_CONGELADA_FISICA_DEVOLUCION_LOCALIZACION', 'Venta rango congelada fisica [localizacion]', 0, NULL, 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2018, 'VENTA_RANGO_CONGELADA_FISICA_DEVOLUCION_LOCALIZACION_SECCION', 'Venta rango congelada fisica [localizacion|seccion]', 0, NULL, 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2019, 'VENTA_RANGO_CONGELADA_ONLINE_ENTREGADOMICILIO_LOCALIZACION', 'Venta rango congelada online entrega domicilio [localizacion]', 0, NULL, 5);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2020, 'VENTA_RANGO_CONGELADA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_SECCION', 'Venta rango congelada online entrega domicilio [localizacion|seccion]', 0, NULL, 5);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2021, 'VENTA_RANGO_CONGELADA_ONLINE_IPOD_LOCALIZACION', 'Venta rango congelada online ipod [localizacion]', 0, NULL, 2);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2022, 'VENTA_RANGO_CONGELADA_ONLINE_IPOD_LOCALIZACION_SECCION', 'Venta rango congelada online ipod [localizacion|seccion]', 0, NULL, 2);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2023, 'VENTA_RANGO_CONGELADA_ONLINE_SINT_LOCALIZACION', 'Venta rango congelada online sint [localizacion]', 0, NULL, 3);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2024, 'VENTA_RANGO_CONGELADA_ONLINE_SINT_LOCALIZACION_SECCION', 'Venta rango congelada online sint [localizacion|seccion]', 0, NULL, 3);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2025, 'VENTA_RANGO_CONGELADA_ONLINE_ENTREGATIENDA_LOCALIZACION', 'Venta rango congelada online entrega tienda [localizacion]', 0, NULL, 4);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2026, 'VENTA_RANGO_CONGELADA_ONLINE_ENTREGATIENDA_LOCALIZACION_SECCION', 'Venta rango congelada online entrega tienda [localizacion|seccion]', 0, NULL, 4);

INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2027, 'VENTA_RANGO_FISICA_CAJA_LOCALIZACION', 'Venta rango fisica [localizacion]', 0, NULL, 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2028, 'VENTA_RANGO_FISICA_CAJA_LOCALIZACION_SECCION', 'Venta rango fisica [localizacion|seccion]', 0, NULL, 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2029, 'VENTA_RANGO_FISICA_DEVOLUCION_LOCALIZACION', 'Venta rango fisica [localizacion]', 0, NULL, 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2030, 'VENTA_RANGO_FISICA_DEVOLUCION_LOCALIZACION_SECCION', 'Venta rango fisica [localizacion|seccion]', 0, NULL, 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2031, 'VENTA_RANGO_ONLINE_ENTREGADOMICILIO_LOCALIZACION', 'Venta rango online entrega domicilio [localizacion]', 0, NULL, 5);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2032, 'VENTA_RANGO_ONLINE_ENTREGADOMICILIO_LOCALIZACION_SECCION', 'Venta rango online entrega domicilio [localizacion|seccion]', 0, NULL, 5);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2033, 'VENTA_RANGO_ONLINE_IPOD_LOCALIZACION', 'Venta rango online ipod [localizacion]', 0, NULL, 2);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2034, 'VENTA_RANGO_ONLINE_IPOD_LOCALIZACION_SECCION', 'Venta rango online ipod [localizacion|seccion]', 0, NULL, 2);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2035, 'VENTA_RANGO_ONLINE_SINT_LOCALIZACION', 'Venta rango online sint [localizacion]', 0, NULL, 3);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2036, 'VENTA_RANGO_ONLINE_SINT_LOCALIZACION_SECCION', 'Venta rango online sint [localizacion|seccion]', 0, NULL, 3);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2037, 'VENTA_RANGO_ONLINE_ENTREGATIENDA_LOCALIZACION', 'Venta rango online entrega tienda [localizacion]', 0, NULL, 4);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2038, 'VENTA_RANGO_ONLINE_ENTREGATIENDA_LOCALIZACION_SECCION', 'Venta rango online entrega tienda [localizacion|seccion]', 0, NULL, 4);

/* Tipos grupo dato congelada/real */
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2028, 'VENTA_RANGO', 'Venta rango');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2029, 'VENTA_RANGO_CONGELADA', 'Venta rango congelada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2030, 'VENTA_RANGO_REAL_Y_CONGELADA', 'Venta rango tanto real como congelada');

INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2027);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2028);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2029);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2030);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2031);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2032);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2033);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2034);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2035);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2036);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2037);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2028, 2038);

INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2029, 2015);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2029, 2016);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2029, 2017);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2029, 2018);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2029, 2019);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2029, 2020);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2029, 2021);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2029, 2022);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2029, 2023);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2029, 2024);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2029, 2025);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2029, 2026);

/* Tipos de dato para totalizado de venta */
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2039, 'VENTA_RANGO_CONGELADA_LOCALIZACION', 'Venta rango congelada totalizada [localizacion]', 1, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2040, 'VENTA_RANGO_CONGELADA_LOCALIZACION_SECCION', 'Venta rango congelada totalziada [localizacion|seccion]', 1, NULL, NULL);

INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2041, 'VENTA_RANGO_LOCALIZACION', 'Venta rango totalizada [localizacion]', 1, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2042, 'VENTA_RANGO_LOCALIZACION_SECCION', 'Venta rango totalizada [localizacion|seccion]', 1, NULL, NULL);

INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2030, 2039);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2030, 2040);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2030, 2041);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2030, 2042);