-- INCOME_ESTADO_TRABAJO
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (1, 'PENDIENTE DATOS');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (2, 'EN CURSO DATOS');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (3, 'PENDIENTE CALCULO');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (4, 'EN CURSO CALCULO');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (5, 'PENDIENTE CONSOLIDACION');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (6, 'EN CURSO CONSOLIDACION');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (7, 'FINALIZADO SIN ERRORES');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (8, 'FINALIZADO CON ERRORES');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (9, 'ERROR');
-- INCOME_ESTADO_TRABAJO_TIENDA
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO_TIENDA (ID_ESTADO_TRABAJO_TIENDA, NOMBRE) VALUES (1, 'PENDIENTE');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO_TIENDA (ID_ESTADO_TRABAJO_TIENDA, NOMBRE) VALUES (2, 'FINALIZADO');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO_TIENDA (ID_ESTADO_TRABAJO_TIENDA, NOMBRE) VALUES (3, 'ERROR');
-- INCOME_ESTADO_TRABAJO_EMPLEADO
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO_EMPLEADO (ID_ESTADO_TRABAJO_EMPLEADO, NOMBRE) VALUES (1, 'PENDIENTE');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO_EMPLEADO (ID_ESTADO_TRABAJO_EMPLEADO, NOMBRE) VALUES (2, 'FINALIZADO');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO_EMPLEADO (ID_ESTADO_TRABAJO_EMPLEADO, NOMBRE) VALUES (3, 'ERROR');
-- INCOME_TIPO_TRABAJO_TIENDA
INSERT INTO DESARROLLO_RRHH.INCOME_TIPO_TRABAJO_TIENDA (ID_TIPO_TRABAJO_TIENDA, NOMBRE) VALUES (1, 'PARAMETRO');
INSERT INTO DESARROLLO_RRHH.INCOME_TIPO_TRABAJO_TIENDA (ID_TIPO_TRABAJO_TIENDA, NOMBRE) VALUES (2, 'HISTORICO');
INSERT INTO DESARROLLO_RRHH.INCOME_TIPO_TRABAJO_TIENDA (ID_TIPO_TRABAJO_TIENDA, NOMBRE) VALUES (3, 'PRESENCIA');
-- INCOME_POC_TIENDA
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('3132', '3', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('3714', '3', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('4843', '70', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('7442', '70', '6');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('3834', '72', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('1231', '72', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('3343', '91', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('3489', '91', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('57', '11', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('6479', '11', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('64', '11', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('11931', '11', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('11836', '11', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('691', '11', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (ID_TIENDA, ID_PAIS, ID_CADENA) VALUES ('6659', '11', '1');
-- INCOME_POC_PERIODO
INSERT INTO DESARROLLO_RRHH.INCOME_POC_PERIODO (ID_PERIODO, FECHA_INICIO_PERIODO, FECHA_FIN_PERIODO) VALUES ('1', '2017-07-01', '2017-07-31');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_PERIODO (ID_PERIODO, FECHA_INICIO_PERIODO, FECHA_FIN_PERIODO) VALUES ('2', '2017-08-01', '2017-08-31');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_PERIODO (ID_PERIODO, FECHA_INICIO_PERIODO, FECHA_FIN_PERIODO) VALUES ('3', '2017-09-01', '2017-09-30');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_PERIODO (ID_PERIODO, FECHA_INICIO_PERIODO, FECHA_FIN_PERIODO) VALUES ('4', '2017-10-01', '2017-10-31');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_PERIODO (ID_PERIODO, FECHA_INICIO_PERIODO, FECHA_FIN_PERIODO) VALUES ('5', '2017-11-01', '2017-11-30');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_PERIODO (ID_PERIODO, FECHA_INICIO_PERIODO, FECHA_FIN_PERIODO) VALUES ('6', '2017-12-01', '2017-12-31');
