-- > ACCION
INSERT INTO ACCION(ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (97, 'validarExportacionFranciaV1', 'Validacion fake para exportar empleados Francia ', 100, 0, 0, 0, 0);

INSERT INTO ACCION(ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (96, 'validarRecuperarFranciaV1', 'Validacion fake para marcar como recuperados empleados Francia', 100, 0, 0, 0, 0);

-- > FASE_ACCION
INSERT INTO FASE_ACCION(ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 97, 3, 100);

INSERT INTO FASE_ACCION(ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 96, 3, 100);

-- > ACCION_AMBITO
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,168, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,165, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,48 , 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,201, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,200, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,466, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,49 , 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,184, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,55 , 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,53 , 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,264, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,215, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,19 , 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,144, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,128, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,104, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (96,1,102, 1, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,168, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,165, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,48 , 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,201, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,200, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,466, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,49 , 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,184, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,55 , 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,53 , 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,264, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,215, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,19 , 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,144, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,128, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,104, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (97,1,102, 1, '', '0001-01-01 00:00:00', null, null, null, null);
