UPDATE ALGORITMO SET NOMBRE = 'porVentaSinDevolucionPorcentajeV1' WHERE ID_ALGORITMO = 7001;
UPDATE ALGORITMO SET NOMBRE = 'porVentaSinDevolucionDesplazamientoPorcentajeV1' WHERE ID_ALGORITMO = 7006;
UPDATE ALGORITMO SET NOMBRE = 'porVentaSinDevolucionPorcentajeDesplazamientoBaseV1' WHERE ID_ALGORITMO = 7011;
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7014, 1, 0, 0, 'porVentaDevolucionPorcentajeV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7015, 1, 1, 0, 'porVentaDevolucionPorcentajeDesplazamientoV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7016, 1, 1, 1, 'porVentaDevolucionPorcentajeDesplazamientoBaseV1');

INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7014, '007');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7015, '007');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7016, '007');

INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7014, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7014, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7014, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7014, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7014, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7014, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7015, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7015, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7015, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7015, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7015, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7015, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7016, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7016, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7016, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7016, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7016, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7016, '009');

-- > PorVentaSinDevolucionPorcentajeDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3033);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3034);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3035);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3036);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3037);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3038);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 5011);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 5010);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 5012);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3033);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3034);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3035);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3036);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3037);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3038);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoBaseV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 5011);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoBaseV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 5010);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoBaseV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 5012);
-- > PorVentaDevolucionPorcentajeV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 3033);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 3034);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 3035);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 3036);
-- > PorVentaDevolucionPorcentajeV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 3037);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 3038);
-- > PorVentaDevolucionPorcentajeV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 5011);
-- > PorVentaDevolucionPorcentajeV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 5010);
-- > PorVentaDevolucionPorcentajeV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 5012);
-- > PorVentaDevolucionPorcentajeDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 3033);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 3034);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 3035);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 3036);
-- > PorVentaDevolucionPorcentajeDesplazamientoV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 3037);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 3038);
-- > PorVentaDevolucionPorcentajeDesplazamientoV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 5011);
-- > PorVentaDevolucionPorcentajeDesplazamientoV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 5010);
-- > PorVentaDevolucionPorcentajeDesplazamientoV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 5012);
-- > PorVentaDevolucionPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 3033);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 3034);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 3035);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 3036);
-- > PorVentaDevolucionPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 3037);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 3038);
-- > PorVentaDevolucionPorcentajeDesplazamientoBaseV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 5011);
-- > PorVentaDevolucionPorcentajeDesplazamientoBaseV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 5010);
-- > PorVentaDevolucionPorcentajeDesplazamientoBaseV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 5012);
