-- TIPO_GRUPO_DATO
-- > 1001 (INCOME WEB)
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (1001, 'PRESENCIA_LOCALIZACION_LOCALIZACION-SECCION', 'Presencias [localizacion][localizacion|seccion]');
-- TIPO_GRUPO_DATO_TIPO_DATO
-- > 1001 (INCOME WEB)
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1001, 5001);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1001, 5002);