-- Validación empleados
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (24, 'personasV1', 'There are employees that exist in SIL and do not exist in INCOME. ', 100, 1, 1, 2, 180000);
INSERT INTO FASE_ACCION (ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 24, 3, 100);

-- Ámbito
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (24,38,95, 1, '', '0001-01-01 00:00:00', null, null, null, null);

