-- TIPO_DATO
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (5011, 'PRESENCIA_LOCALIZACION_SECCION_EMPLEADOS_POR_VENTA', 'Presencia [localizacion|seccion] [incluido venta empleados por venta]', 1, NULL, NULL);
UPDATE TIPO_DATO SET NOMBRE = 'IMPORTE_COMISION_VENDEDORES_POR_VENTA', DESCRIPCION = 'Importe comision vendedores [localizacion|seccion]' WHERE ID_TIPO_DATO = 3031;
UPDATE TIPO_DATO SET NOMBRE = 'DEVOLUCION_LOCALIZACION_SECCION', DESCRIPCION = 'Devolucion fisica y iPod [localizacion|seccion]' WHERE ID_TIPO_DATO = 3029;
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3034, 'VENTA_SIN_DEVOLUCION_LOCALIZACION_SECCION', 'Venta fisica y iPod sin devolucion [localizacion|seccion]', 1, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3035, 'IMPORTE_COMISION_VENTAS_LOCALIZACION_POR_VENTA', 'Importe comision ventas [localizacion|seccion]', 1, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3036, 'IMPORTE_COMISION_DEVOLUCIONES_LOCALIZACION_POR_VENTA', 'Importe comision devoluciones [localizacion|seccion]', 1, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (5012, 'INDICADOR_PRESENCIA_EMPLEADOS_POR_VENTA', 'Indicador de presencia empleados por venta [localizacion|persona]', 1, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (5013, 'INDICADOR_PRESENCIA_EMPLEADOS_POR_VENTA_SIMPLIFICADA', 'Indicador de presencia empleados por venta simplificada [localizacion|persona]', 1, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3037, 'DEVOLUCION_INDIVIDUAL_LOCALIZACION_SECCION', 'Devolucion fisica y iPod [localizacion|seccion|persona]', 1, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3038, 'VENTA_SIN_DEVOLUCION_INDIVIDUAL_LOCALIZACION_SECCION', 'Venta fisica y iPod sin devoluciones [localizacion|seccion|persona]', 1, NULL, NULL);
-- TIPO_GRUPO_DATO
DELETE FROM TIPO_GRUPO_DATO_TIPO_DATO WHERE ID_TIPO_GRUPO_DATO = 2025;
DELETE FROM TIPO_GRUPO_DATO WHERE ID_TIPO_GRUPO_DATO = 2025;
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2025, 'VENTA_SIN_DEVOLUCION_LOCALIZACION_SECCION_TOTALIZADA', 'Venta sin devolucion [localizacion|seccion] totalizada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2026, 'VENTA_FISICA_IPOD_LOCALIZACION_SECCION', 'Venta fisica y iPod [localizacion|seccion]');

-- > 2025 (VENTA SIN DEVOLUCION LOCALIZACION TOTALIZADA)
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2025, 2011);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2025, 2013);
-- > 2026 (VENTA FISICA Y IPOD LOCALIZACION SECCION)
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2026, 2002);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2026, 2003);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2026, 3006);

-- TIPO_GRUPO_DATO Asociado a las ventas que se ven desde la web
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (1002, 'VENTA_LOCALIZACION-SECCION', 'Venta [localizacion|seccion]');
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1002, 2002);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1002, 2004);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1002, 2006);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1002, 2008);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1002, 3002);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1002, 3006);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1002, 3008);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1002, 3010);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1002, 3012);

-- > CAMBIO EN EL TIPO DE COMISION 
UPDATE TIPO_COMISION SET NOMBRE = 'CHALLENGE_PRINCIPAL' WHERE ID_TIPO_COMISION = '011';
UPDATE TIPO_COMISION SET NOMBRE = 'CHALLENGE_SECUNDARIO' WHERE ID_TIPO_COMISION = '012';

-- > INSERTAR CHALLENGE PRECIO HORA
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (12001, 1, 0, 0, 'challengePrecioHoraTiendaV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (12006, 1, 1, 0, 'challengePrecioHoraTiendaDesplazamientoV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (12011, 1, 1, 1, 'challengePrecioHoraTiendaDesplazamientoBaseV1');

INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (15001, 1, 0, 0, 'challengePrecioHoraTiendaSeccionV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (15006, 1, 1, 0, 'challengePrecioHoraTiendaSeccionDesplazamientoV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (15011, 1, 1, 1, 'challengePrecioHoraTiendaSeccionDesplazamientoBaseV1');

-- > INSERTAR TIPO DE CALCULO ASOCIADO CHALLENGE PRECIO HORA TIENDA
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (12001, '010');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (15001, '011');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (12006, '010');
-- > INSERTAR TIPO DE CALCULO ASOCIADO CHALLENGE PRECIO HORA TIENDA SECCION
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (15006, '011');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (12011, '010');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (15011, '011');
-- > INSERTAR TIPO DE COMISION ASOCIADO CHALLENGE PRECIO HORA TIENDA
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (12001, '011');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (12006, '011');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (12011, '011');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (12001, '012');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (12006, '012');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (12011, '012');
-- > INSERTAR TIPO DE COMISION ASOCIADO CHALLENGE PRECIO HORA TIENDA SECCION
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (15001, '011');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (15006, '011');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (15011, '011');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (15001, '012');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (15006, '012');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (15011, '012');
-- > INSERTAR CHALLENGE IMPORTE TIENDA
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (13001, 1, 0, 0, 'challengeImporteTiendaV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (13006, 1, 1, 0, 'challengeImporteTiendaDesplazamientoV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (13011, 1, 1, 1, 'challengeImporteTiendaDesplazamientoBaseV1');
-- > INSERTAR CHALLENGE IMPORTE TIENDA sECCION
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (16001, 1, 0, 0, 'challengeImporteTiendaSeccionV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (16006, 1, 1, 0, 'challengeImporteTiendaSeccionDesplazamientoV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (16011, 1, 1, 1, 'challengeImporteTiendaSeccionDesplazamientoBaseV1');

-- > INSERTAR TIPO DE CALCULO ASOCIADO CHALLENGE IMPORTE
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (13001, '012');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (13006, '012');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (13011, '012');
-- > INSERTAR TIPO DE CALCULO ASOCIADO CHALLENGE IMPORTE
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (16001, '013');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (16006, '013');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (16011, '013');

-- > INSERTAR TIPO DE COMISION ASOCIADO CHALLENGE IMPORTE
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (13001, '011');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (13006, '011');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (13011, '011');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (13001, '012');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (13006, '012');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (13011, '012');
-- > INSERTAR TIPO DE COMISION ASOCIADO CHALLENGE IMPORTE TIENDA SECCION
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (16001, '011');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (16006, '011');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (16011, '011');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (16001, '012');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (16006, '012');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (16011, '012');

-- > INSERTAR PRECIO HORA
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (14001, 1, 0, 0, 'precioHoraV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (14006, 1, 1, 0, 'precioHoraDesplazamientoV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (14011, 1, 1, 1, 'precioHoraDesplazamientoBaseV1');

-- > INSERTAR TIPO DE CALCULO ASOCIADO PRECIO HORA
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (14001, '014');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (14006, '014');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (14011, '014');

-- > INSERTAR TIPO DE COMISION ASOCIADO PRECIO HORA
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (14001, '013');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (14006, '013');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (14011, '013');

-- > INSERTAR TIPO DE DATO ASOCIADO PRECIO HORA
-- > precioHoraV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14001, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14001, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14001, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14001, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14001, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14001, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14001, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14001, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14001, 3012);
-- > precioHoraDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14006, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14006, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14006, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14006, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14006, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14006, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14006, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14006, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14006, 3012);
-- > precioHoraDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14011, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14011, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14011, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14011, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14011, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14011, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14011, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14011, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14011, 3012);
-- > precioHoraDesplazamientoBaseV1 (Indicador desplazamiento base [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (14011, 5009);

-- > porVentaPorcentajeV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3033);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3034);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3035);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3036);
-- > porVentaPorcentajeV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3037);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3038);
-- > porVentaPorcentajeV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 5011);
-- > porVentaPorcentajeV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 5010);
-- > porVentaPorcentajeV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 5012);
-- > porVentaSimplificadoPorcentajeV1 (Venta [localizacion|seccion])
-- TODO [JAVIEREV] Revisar estos tipos de datos, creo que están mal
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 3012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 3032);
-- > porVentaSimplificadoPorcentajeV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 5013);




