-- Fase 1: [CZ|HU|SK]
-- [MOCK][INICIO] PROGRAMACION
-- Programacion: 1 | Programacion ambito: 1 || Sociedad: AT | Origen: 38 | Empresa: [95,135,251,315,329,340,425,468]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'AT_38_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'AT');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '38');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '95');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '135');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '251');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '315');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '329');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '340');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '425');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '468');


-- Programacion: 2 | Programacion ambito: 2 || Sociedad: CA | Origen: 404 | Empresa: [97,362,395]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CA_404_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'CA');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '404');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '97');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '362');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '395');

-- Programacion: 3 | Programacion ambito: 3 || Sociedad: CH | Origen: 39 | Empresa: [36,100,137,143,325,348,456,481,508]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CH_39_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'CH');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '39');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '36');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '100');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '137');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '143');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '325');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '348');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '456');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '481');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '508');

-- Programacion: 4 | Programacion ambito: 4 || Sociedad: CZ | Origen: 61 | Empresa: [123,172,173,252,253,254,510,511]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CZ_61_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'CZ');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '61');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '123');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '172');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '173');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '252');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '253');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '254');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '510');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '511');

-- Programacion: 5 | Programacion ambito: 5 || Sociedad: DE | Origen: 4 | Empresa: [52,107,132,316,323,333,338,342,347,370,386,393,403,408,424]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'DE_4_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'DE');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '4');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '52');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '107');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '132');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '316');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '323');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '333');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '338');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '342');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '347');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '370');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '386');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '393');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '403');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '408');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '424');

-- Programacion: 6 | Programacion ambito: 6 || Sociedad: HU | Origen: 64 | Empresa: [157,177,220,221,235,290,457]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'HU_64_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'HU');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '64');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '157');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '177');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '220');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '221');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '235');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '290');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '457');

-- Programacion: 7 | Programacion ambito: 7 || Sociedad: SK | Origen: 63 | Empresa: [209,222,223,224,470,476]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'SK_63_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'SK');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '63');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '209');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '222');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '223');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '224');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '470');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '476');

-- Programacion: 8 | Programacion ambito: 8 || Sociedad: UY | Origen: 524 | Empresa: [87,429]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'UY_524_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'UY');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '524');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '87');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '429');

-- Programacion: 9 | Programacion ambito: 9 || Sociedad: ZA | Origen: 388 | Empresa: [343,477]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'ZA_388_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'ZA');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '388');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '343');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '477');

-- Programacion: 10 | Programacion ambito: 10 || Sociedad: AT | Origen: 38 | Empresa: [95,135]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (1, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'AT_38_DATA', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'AT');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '38');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '95');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '135');

-- Programacion: 11 | Programacion ambito: 11 || Sociedad: CZ | Origen: 61 | Empresa: [123,173]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (1, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CZ_61_DATA', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'CZ');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '61');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '123');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '173');

-- Programacion: 12 | Programacion ambito: 12 || Sociedad: CH | Origen: 39 | Empresa: [100]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (1, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CH_39_DATA', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'CH');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '39');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '100');
-- [MOCK][FIN] PROGRAMACION

