INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (5018, 'PRESENCIA_MANUAL_LOCALIZACION-SECCION_INCLUIDODENOMINADOR', 'Presencia manual [localizacion|seccion] [incluido denominador]', 0, 3, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3046, 'VENTA_MANUAL_LOCALIZACION-SECCION', 'Venta manual [localizacion|seccion]', 0, NULL, NULL);
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2031, 'VENTA_REAL_LOCALIZACION-SECCION', 'Venta real [localizacion|seccion]');

INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2001, 3046);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1002, 3046);

INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2031, 2002);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2031, 2004);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2031, 2006);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2031, 2008);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2031, 3002);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2031, 3006);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2031, 3008);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2031, 3010);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2031, 3012);
