INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (1, 'PENDIENTE DATOS');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (2, 'EN CURSO DATOS');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (3, 'PENDIENTE CALCULO');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (4, 'EN CURSO CALCULO');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (5, 'PENDIENTE CONSOLIDACION');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (6, 'EN CURSO CONSOLIDACION');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (7, 'FINALIZADO SIN ERRORES');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (8, 'FINALIZADO CON ERRORES');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (9, 'ERROR');


