/***************************/
/** ESTADO_TAREA_LIMPIEZA **/
/***************************/

INSERT INTO ESTADO_TAREA_LIMPIEZA (ID_ESTADO_TAREA_LIMPIEZA, NOMBRE, PESO) VALUES (1, 'Pendiente', 100);
INSERT INTO ESTADO_TAREA_LIMPIEZA (ID_ESTADO_TAREA_LIMPIEZA, NOMBRE, PESO) VALUES (2, 'Ok', 200);
INSERT INTO ESTADO_TAREA_LIMPIEZA (ID_ESTADO_TAREA_LIMPIEZA, NOMBRE, PESO) VALUES (3, 'Ko', 300);

/***************************/
/** TIPO_LIMPIEZA **/
/***************************/

INSERT INTO TIPO_LIMPIEZA (ID_TIPO_LIMPIEZA, NOMBRE, DESCRIPCION) VALUES (1, 'Completa', 'Limpieza completa de la tarea');
INSERT INTO TIPO_LIMPIEZA (ID_TIPO_LIMPIEZA, NOMBRE, DESCRIPCION) VALUES (2, 'Parcial', 'Limpieza parcial de la tarea');
