-- > ACCION
INSERT INTO ACCION(ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (98, 'ventasMonacoV1', 'Validacion fake para recuperar las ventas de Monaco utilizando su origen propio', 100, 0, 0, 0, 0);

-- > FASE_ACCION
INSERT INTO FASE_ACCION(ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 98, 3, 100);
