-- INCOME_ESTADO_TRABAJO
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (1, 'PENDIENTE DATOS');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (2, 'EN CURSO DATOS');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (3, 'PENDIENTE CALCULO');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (4, 'EN CURSO CALCULO');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (5, 'PENDIENTE CONSOLIDACION');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (6, 'EN CURSO CONSOLIDACION');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (7, 'FINALIZADO SIN ERRORES');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (8, 'FINALIZADO CON ERRORES');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE) VALUES (9, 'ERROR');
-- INCOME_ESTADO_TRABAJO_EMPLEADO
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO_EMPLEADO (ID_ESTADO_TRABAJO_EMPLEADO, NOMBRE) VALUES (1, 'PENDIENTE');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO_EMPLEADO (ID_ESTADO_TRABAJO_EMPLEADO, NOMBRE) VALUES (2, 'FINALIZADO');
INSERT INTO DESARROLLO_RRHH.INCOME_ESTADO_TRABAJO_EMPLEADO (ID_ESTADO_TRABAJO_EMPLEADO, NOMBRE) VALUES (3, 'ERROR');
-- INCOME_TIPO_TRABAJO_TIENDA
INSERT INTO DESARROLLO_RRHH.INCOME_TIPO_TRABAJO_TIENDA (ID_TIPO_TRABAJO_TIENDA, NOMBRE) VALUES (1, 'INICIAL');
INSERT INTO DESARROLLO_RRHH.INCOME_TIPO_TRABAJO_TIENDA (ID_TIPO_TRABAJO_TIENDA, NOMBRE) VALUES (2, 'PARAMETRO');
INSERT INTO DESARROLLO_RRHH.INCOME_TIPO_TRABAJO_TIENDA (ID_TIPO_TRABAJO_TIENDA, NOMBRE) VALUES (3, 'HISTORICO');
INSERT INTO DESARROLLO_RRHH.INCOME_TIPO_TRABAJO_TIENDA (ID_TIPO_TRABAJO_TIENDA, NOMBRE) VALUES (4, 'PRESENCIA');
-- INCOME_POC_TIENDA
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('3132', 'T3132', '528', '3', '50', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('3714', 'T3714', '528', '3', '50', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('4843', 'T4843', '008', '70', '436', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('7442', 'T7442', '008', '70', '436', '4');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('3834', 'T3834', '804', '72', '227', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('1231', 'T1231', '804', '72', '227', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('3343', 'T3343', '705', '91', '500', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('3489', 'T3489', '704', '91', '500', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('57', 'T57', '724', '11', '8', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('6479', 'T6479', '724', '11', '8', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('64', 'T64', '724', '11', '8', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('11931', 'T11931', '724', '11', '8', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('11836', 'T11836', '724', '11', '8', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('691', 'T691', '724', '11', '8', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('6659', 'T6659', '724', '11', '8', '1');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_TIENDA (CCL_ID_COD_ORIGEN, STD_ID_WORK_LOCAT, STD_ID_COUNTRY, CCL_ID_ORIGEN, STD_ID_LEG_ENT, CCL_ID_CADENA) VALUES ('5167', 'T5167', '724', '11', '11', '2');
-- INCOME_POC_PERIODO
INSERT INTO DESARROLLO_RRHH.INCOME_POC_PERIODO (ID_PERIODO, FECHA_INICIO_PERIODO, FECHA_FIN_PERIODO) VALUES ('1', '2017-07-01', '2017-07-31');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_PERIODO (ID_PERIODO, FECHA_INICIO_PERIODO, FECHA_FIN_PERIODO) VALUES ('2', '2017-08-01', '2017-08-31');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_PERIODO (ID_PERIODO, FECHA_INICIO_PERIODO, FECHA_FIN_PERIODO) VALUES ('3', '2017-09-01', '2017-09-30');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_PERIODO (ID_PERIODO, FECHA_INICIO_PERIODO, FECHA_FIN_PERIODO) VALUES ('4', '2017-10-01', '2017-10-31');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_PERIODO (ID_PERIODO, FECHA_INICIO_PERIODO, FECHA_FIN_PERIODO) VALUES ('5', '2017-11-01', '2017-11-30');
INSERT INTO DESARROLLO_RRHH.INCOME_POC_PERIODO (ID_PERIODO, FECHA_INICIO_PERIODO, FECHA_FIN_PERIODO) VALUES ('6', '2017-12-01', '2017-12-31');
-- INCOME_TRABAJO
INSERT INTO DESARROLLO_RRHH.INCOME_TRABAJO (ID_TRABAJO, FECHA_CREACION, FECHA_FIN_PERIODO, FECHA_FIN_TRABAJO, FECHA_INICIO_PERIODO, FECHA_INICIO_TRABAJO, ID_EMPRESA, ID_ORIGEN, ID_USUARIO, ID_ESTADO_TRABAJO) VALUES (100, '2017-07-31', '2017-07-31', '2017-08-01 00:02:58','2017-07-1', '2017-08-01 00:02:50', 11, 11, 1902, 7);
-- INCOME_TRABAJO_TIPO_HORA
INSERT INTO DESARROLLO_RRHH.INCOME_TRABAJO_TIPO_HORA (ID_TRABAJO_TIPO_HORA, COMISIONABLE, ID_TIPO_HORA, ID_TRABAJO) VALUES (101, 1, '1', 100);