INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (4005, 'PRESENCIA_REAL_LOCALIZACION-SECCION-PERSONA-TIPO_HORA-REPARTIDOPROVINCIA', 'Presencias real [localizacion|seccion|persona|tipo hora|repartido provincia]', 0, 1, NULL);

INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (3009, 'PRESENCIA_LOCALIZACION-SECCION-PERSONA-TIPO_HORA-REPARTIDOPROVINCIA', 'Presencias [localizacion|seccion|persona|tipo hora|repartido provincia]');

INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3009, 4003);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3009, 4005);
