INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3039, 'VENTA_FISICA_SIN_DEVOLUCION_INDIVIDUAL_LOCALIZACION_SECCION', 'Venta fisica sin devoluciones [localizacion|seccion|persona]', 1, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3040, 'VENTA_ONLINE_IPOD_SIN_DEVOLUCION_INDIVIDUAL_LOCALIZACION_SECCION', 'Venta online iPod sin devoluciones [localizacion|seccion|persona]', 1, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3041, 'DEVOLUCION_FISICA_INDIVIDUAL_LOCALIZACION_SECCION', 'Devolución fisica [localizacion|seccion|persona]', 1, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3042, 'DEVOLUCION_ONLINE_IPOD_INDIVIDUAL_LOCALIZACION_SECCION', 'Devolución online iPod [localizacion|seccion|persona]', 1, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (5014, 'PRESENCIA_LOCALIZACION-PERSONA-TIPOHORA_INCLUIDOVENTA', 'Presencia incluido venta [localizacion|persona|tipo hora]', 1, NULL, NULL);

UPDATE TIPO_GRUPO_DATO SET NOMBRE = 'OPERACIONES_VENTA_INDIVIDUAL_LOCALIZACION_SECCION'WHERE ID_TIPO_GRUPO_DATO = 2024;
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2027, 'VENTA_INDIVIDUAL_LOCALIZACION_SECCION', 'Venta fisica y iPod [localizacion|seccion|persona]');

-- > 2027 (VENTA FISICA Y IPOD LOCALIZACION SECCION PERSONA)
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2027, 3039);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2027, 3040);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2027, 3041);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2027, 3042);

UPDATE ALGORITMO SET NOMBRE = 'porVentaSinDevolucionPorcentajeV1' WHERE ID_ALGORITMO = 7001;
UPDATE ALGORITMO SET NOMBRE = 'porVentaSinDevolucionPorcentajeDesplazamientoV1' WHERE ID_ALGORITMO = 7006;
UPDATE ALGORITMO SET NOMBRE = 'porVentaSinDevolucionPorcentajeDesplazamientoBaseV1' WHERE ID_ALGORITMO = 7011;
UPDATE ALGORITMO SET NOMBRE = 'porVentaSinDevolucionPorcentajeDiariaV1' WHERE ID_ALGORITMO = 7002;
UPDATE ALGORITMO SET NOMBRE = 'porVentaSinDevolucionPorcentajeDiariaDesplazamientoV1' WHERE ID_ALGORITMO = 7007;
UPDATE ALGORITMO SET NOMBRE = 'porVentaSinDevolucionPorcentajeDiariaDesplazamientoBaseV1' WHERE ID_ALGORITMO = 7012;
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7014, 1, 0, 0, 'porVentaDevolucionPorcentajeV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7015, 1, 1, 0, 'porVentaDevolucionPorcentajeDesplazamientoV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7016, 1, 1, 1, 'porVentaDevolucionPorcentajeDesplazamientoBaseV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7017, 1, 0, 0, 'porVentaDevolucionPorcentajeDiariaV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7018, 1, 1, 0, 'porVentaDevolucionPorcentajeDiariaDesplazamientoV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7019, 1, 1, 1, 'porVentaDevolucionPorcentajeDiariaDesplazamientoBaseV1');

INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7014, '007');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7015, '007');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7016, '007');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7017, '007');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7018, '007');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7019, '007');

INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7014, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7014, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7014, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7014, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7014, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7014, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7015, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7015, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7015, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7015, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7015, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7015, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7016, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7016, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7016, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7016, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7016, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7016, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7017, '008');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7018, '008');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7019, '008');

-- ALGORITMO_TIPO_DATO - PorVenta*
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO IN
    (7001,7002,7006,7007,7011,7012,7014,7015,7016,7017,7018,7019,8001,8002,8006,
     8007,8011,8012,9001,9002,9006,9007,9011,9012);
-- > PorVentaSinDevolucionPorcentajeV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3033);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3034);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3035);
-- > PorVentaSinDevolucionPorcentajeV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 3037);
-- > PorVentaSinDevolucionPorcentajeV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 5011);
-- > PorVentaSinDevolucionPorcentajeV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 5010);
-- > PorVentaSinDevolucionPorcentajeV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7001, 5012);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3033);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3034);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3035);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 3037);
-- > PorVentaSinDevolucionPorcentajeV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 5011);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 5010);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7006, 5012);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3033);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3034);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3035);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 3037);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoBaseV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 5011);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoBaseV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 5010);
-- > PorVentaSinDevolucionPorcentajeDesplazamientoBaseV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7011, 5012);
-- > PorVentaSinDevolucionPorcentajeDiariaV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 3033);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 3034);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 3035);
-- > PorVentaSinDevolucionPorcentajeDiariaV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 3037);
-- > PorVentaSinDevolucionPorcentajeDiariaV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 5011);
-- > PorVentaSinDevolucionPorcentajeDiariaV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 5010);
-- > PorVentaSinDevolucionPorcentajeDiariaV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7002, 5012);
-- > PorVentaSinDevolucionPorcentajeDiariaDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 3033);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 3034);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 3035);
-- > PorVentaSinDevolucionPorcentajeDiariaDesplazamientoV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 3037);
-- > PorVentaSinDevolucionPorcentajeDiariaV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 5011);
-- > PorVentaSinDevolucionPorcentajeDiariaDesplazamientoV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 5010);
-- > PorVentaSinDevolucionPorcentajeDiariaDesplazamientoV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7007, 5012);
-- > PorVentaSinDevolucionPorcentajeDiariaDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 3033);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 3034);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 3035);
-- > PorVentaSinDevolucionPorcentajeDiariaDesplazamientoBaseV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 3037);
-- > PorVentaSinDevolucionPorcentajeDiariaDesplazamientoBaseV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 5011);
-- > PorVentaSinDevolucionPorcentajeDiariaDesplazamientoBaseV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 5010);
-- > PorVentaSinDevolucionPorcentajeDiariaDesplazamientoBaseV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7012, 5012);
-- > PorVentaDevolucionPorcentajeV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 3035);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 3036);
-- > PorVentaDevolucionPorcentajeV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 3037);
-- > PorVentaDevolucionPorcentajeV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 5011);
-- > PorVentaDevolucionPorcentajeV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 5010);
-- > PorVentaDevolucionPorcentajeV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7014, 5012);
-- > PorVentaDevolucionPorcentajeDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 3035);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 3036);
-- > PorVentaDevolucionPorcentajeDesplazamientoV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 3037);
-- > PorVentaDevolucionPorcentajeDesplazamientoV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 5011);
-- > PorVentaDevolucionPorcentajeDesplazamientoV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 5010);
-- > PorVentaDevolucionPorcentajeDesplazamientoV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7015, 5012);
-- > PorVentaDevolucionPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 3035);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 3036);
-- > PorVentaDevolucionPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 3037);
-- > PorVentaDevolucionPorcentajeDesplazamientoBaseV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 5011);
-- > PorVentaDevolucionPorcentajeDesplazamientoBaseV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 5010);
-- > PorVentaDevolucionPorcentajeDesplazamientoBaseV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7016, 5012);
-- > PorVentaDevolucionPorcentajeDiariaV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 3035);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 3036);
-- > PorVentaDevolucionPorcentajeDiariaV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 3037);
-- > PorVentaDevolucionPorcentajeDiariaV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 5011);
-- > PorVentaDevolucionPorcentajeDiariaV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 5010);
-- > PorVentaDevolucionPorcentajeDiariaV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7017, 5012);
-- > PorVentaDevolucionPorcentajeDiariaDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 3035);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 3036);
-- > PorVentaDevolucionPorcentajeDiariaDesplazamientoV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 3037);
-- > PorVentaDevolucionPorcentajeDiariaDesplazamientoV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 5011);
-- > PorVentaDevolucionPorcentajeDiariaDesplazamientoV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 5010);
-- > PorVentaDevolucionPorcentajeDiariaDesplazamientoV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7018, 5012);
-- > PorVentaDevolucionPorcentajeDiariaDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 3029);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 3031);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 3035);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 3036);
-- > PorVentaDevolucionPorcentajeDiariaDesplazamientoBaseV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 3037);
-- > PorVentaDevolucionPorcentajeDiariaDesplazamientoBaseV1 (Presencia [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 5002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 5011);
-- > PorVentaDevolucionPorcentajeDiariaDesplazamientoBaseV1 (Presencia [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 4003);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 5010);
-- > PorVentaDevolucionPorcentajeDiariaDesplazamientoBaseV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7019, 5012);
-- > porVentaSimplificadoPorcentajeV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 3012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 3032);
-- > porVentaSimplificadoPorcentajeV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 3030);
-- > porVentaSimplificadoPorcentajeV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8001, 5013);
-- > porVentaSimplificadoPorcentajeDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 3012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 3032);
-- > porVentaSimplificadoPorcentajeDesplazamientoV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 3030);
-- > porVentaSimplificadoPorcentajeDesplazamientoV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8006, 5013);
-- > porVentaIndividualPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 3012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 3032);
-- > porVentaSimplificadoPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 3030);
-- > porVentaSimplificadoPorcentajeDesplazamientoBaseV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8011, 5013);

-- > porVentaSimplificadoPorcentajeDiariaV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 3012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 3032);
-- > porVentaSimplificadoPorcentajeDiariaV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 3030);
-- > porVentaSimplificadoPorcentajeDiariaV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8002, 5013);
-- > porVentaSimplificadoPorcentajeDiariaDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 3012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 3032);
-- > porVentaSimplificadoPorcentajeDiariaDesplazamientoV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 3030);
-- > porVentaSimplificadoPorcentajeDiariaDesplazamientoV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8007, 5013);
-- > porVentaIndividualPorcentajeDiariaDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 3012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 3032);
-- > porVentaSimplificadoPorcentajeDiariaDesplazamientoBaseV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 3030);
-- > porVentaSimplificadoPorcentajeDiariaDesplazamientoBaseV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (8012, 5013);
-- > porVentaIndividualPorcentajeV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9001, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9001, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9001, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9001, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9001, 3039);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9001, 3040);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9001, 3041);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9001, 3042);
-- > porVentaIndividualPorcentajeDesplazamientoV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9006, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9006, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9006, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9006, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9006, 3039);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9006, 3040);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9006, 3041);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9006, 3042);
-- > porVentaIndividualPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9011, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9011, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9011, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9011, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9011, 3039);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9011, 3040);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9011, 3041);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9011, 3042);
-- > porVentaIndividualPorcentajeDiariaV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9002, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9002, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9002, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9002, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9002, 3039);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9002, 3040);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9002, 3041);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9002, 3042);
-- > porVentaIndividualPorcentajeDiariaDesplazamientoV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9007, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9007, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9007, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9007, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9007, 3039);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9007, 3040);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9007, 3041);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9007, 3042);
-- > porVentaIndividualPorcentajeDiariaDesplazamientoBaseV1 (Venta [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9012, 2011);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9012, 2012);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9012, 2013);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9012, 2014);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9012, 3039);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9012, 3040);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9012, 3041);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (9012, 3042);

-- POR VENTA GLOBAL TIENDA
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7020, 1, 0, 0, 'porVentaGlobalTiendaPorcentajeV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7021, 1, 1, 0, 'porVentaGlobalTiendaPorcentajeDesplazamientoV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7022, 1, 1, 1, 'porVentaGlobalTiendaPorcentajeDesplazamientoBaseV1');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7020, '007');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7021, '007');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7022, '007');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7020, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7020, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7020, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7020, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7020, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7020, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7021, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7021, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7021, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7021, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7021, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7021, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7022, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7022, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7022, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7022, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7022, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7022, '009');
-- > porVentaGlobalTiendaPorcentajeV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7020, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7020, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7020, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7020, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7020, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7020, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7020, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7020, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7020, 3012);
-- > porVentaGlobalTiendaPorcentajeV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7020, 5011);
-- > porVentaGlobalTiendaPorcentajeV1 (Presencia [localizacion|seccion|persona|tipo hora])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7020, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7020, 4003);
-- > porVentaGlobalTiendaPorcentajeV1 (Presencia [localizacion] [incluido denominador])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7020, 5001);
-- > porVentaGlobalTiendaPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7022, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7022, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7022, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7022, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7022, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7022, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7022, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7022, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7022, 3012);
-- > porVentaGlobalTiendaPorcentajeDesplazamientoBaseV1 (Indicadores [localizacion|seccion|persona])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7022, 5011);
-- > porVentaGlobalTiendaPorcentajeDesplazamientoBaseV1 (Presencia [localizacion|seccion|persona|tipo hora])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7022, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7022, 4003);
-- > porVentaGlobalTiendaPorcentajeDesplazamientoBaseV1 (Presencia [localizacion] [incluido denominador])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7022, 5001);
-- > porVentaGlobalTiendaPorcentajeDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7021, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7021, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7021, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7021, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7021, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7021, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7021, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7021, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7021, 3012);
-- > porVentaGlobalTiendaPorcentajeDesplazamientoV1 (Presencia [localizacion|seccion|persona|tipo hora])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7021, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7021, 4003);
-- > porVentaGlobalTiendaPorcentajeDesplazamientoV1 (Presencia [localizacion] [incluido denominador])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (7021, 5001);

-- POR VENTA GLOBAL TIENDA DIARIA
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7023, 1, 0, 0, 'porVentaGlobalTiendaPorcentajeDiariaV1');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7023, '007');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7023, '008');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7024, 1, 1, 0, 'porVentaGlobalTiendaPorcentajeDiariaDesplazamientoV1');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7024, '007');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7024, '008');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (7025, 1, 1, 1, 'porVentaGlobalTiendaPorcentajeDiariaDesplazamientoBaseV1');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (7025, '007');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (7025, '008');

