-- De primero se lanza, import-primary-dml-v10.sql
-- El script sirve para regularizar los datos con el nuevo cambio de BBDD

-- TAREA_CALCULO:STD_ID_WORK_LOCAT Con desplazamiento
MERGE INTO TAREA_CALCULO AS DATA_A USING (
  SELECT
    TC.ID_TAREA_CALCULO,
    TPED.STD_ID_WORK_LOCAT_DESTINO AS STD_ID_WORK_LOCAT
  FROM TAREA_CALCULO AS TC
  INNER JOIN TAREA_PERSONA_ESTRUCTURA TPE
    ON TPE.FECHA_INICIO_PERIODO = TC.FECHA_INICIO_PERIODO
    AND TPE.ID_TAREA_PERSONA_ESTRUCTURA = TC.ID_TAREA_PERSONA_ESTRUCTURA
  INNER JOIN TAREA_PERSONA_ESTRUCTURA_DESPLAZAMIENTO TPED
    ON TPED.FECHA_INICIO_PERIODO = TPE.FECHA_INICIO_PERIODO
    AND TPED.ID_TAREA = TPE.ID_TAREA
    AND TPED.CCL_ID_PERSON =  TPE.CCL_ID_PERSON
    AND TPED.STD_OR_HR_PERIOD = TPE.STD_OR_HR_PERIOD
    AND TPED.ICM_ID_ESTR_COMISION_PADRE = TPE.ICM_ID_ESTR_COMISION_PADRE
    AND TPED.ICM_ID_ESTR_COMISION_BASE = TPE.ICM_ID_ESTR_COMISION_BASE
    AND TPED.ICM_ID_ESTR_COMISION = TPE.ICM_ID_ESTR_COMISION
    AND TPED.ORDINAL_ESTRUCTURA = TPE.ORDINAL_ESTRUCTURA
    AND TPED.FECHA_INICIO = TPE.FECHA_INICIO
    AND TPED.FECHA_FIN = TPE.FECHA_FIN
  WHERE TC.STD_ID_WORK_LOCAT = 'CAMBIAR'
) AS DATA_B
  ON DATA_A.ID_TAREA_CALCULO = DATA_B.ID_TAREA_CALCULO
WHEN MATCHED THEN
  UPDATE SET STD_ID_WORK_LOCAT = DATA_B.STD_ID_WORK_LOCAT;

-- TAREA_CALCULO:STD_ID_WORK_LOCAT Sin desplazamiento
MERGE INTO TAREA_CALCULO AS DATA_A USING (
  SELECT
    TC.ID_TAREA_CALCULO,
    TLH.STD_ID_WORK_LOCAT
  FROM TAREA_CALCULO TC
  INNER JOIN TAREA_LOCALIZACION_VENTA TLV
    ON TLV.FECHA_INICIO_PERIODO = TC.FECHA_INICIO_PERIODO
    AND TLV.ID_TAREA_LOCALIZACION_VENTA = TC.ID_TAREA_LOCALIZACION_VENTA
  INNER JOIN TAREA_LOCALIZACION_HISTORICO TLH
    ON TLH.ID_TAREA = TLV.ID_TAREA
    AND TLH.CCL_ID_COD_ORIGEN = TLV.CCL_ID_COD_ORIGEN
    AND TLH.FECHA_INICIO <= TLV.FECHA
    AND TLH.FECHA_FIN >= TLV.FECHA
  WHERE TC.STD_ID_WORK_LOCAT = 'CAMBIAR'
) AS DATA_B
  ON DATA_A.ID_TAREA_CALCULO = DATA_B.ID_TAREA_CALCULO
WHEN MATCHED THEN
  UPDATE SET STD_ID_WORK_LOCAT = DATA_B.STD_ID_WORK_LOCAT;