-- Inserción del tipo de dato para horas fijas
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (5010, 'PRESENCIA_HORASFIJAS_LOCALIZACION-SECCION-PERSONA-TIPO_HORA', 'Presencias horas fijas [localizacion|seccion|persona|tipo hora]', 1, 2, NULL);
-- Inserción del tipo de dato horas fijas en los grupos que correspondan
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1000, 5010);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3001, 5010);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3006, 5010);
-- ALGORITMO SIN ASIGNAR
INSERT INTO TIPO_POLITICA (ID_TIPO_POLITICA, NOMBRE, ICM_ID_TP_POLITICAS, PESO) VALUES (0, 'SIN_ASIGNAR', '000', 0);
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE, NOMBRE) VALUES (0, 0, 0, 0, 'sinAsignarV1');
INSERT INTO ALGORITMO_AJUSTE (ID_ALGORITMO_AJUSTE, ID_TIPO_POLITICA, NOMBRE, PESO, ES_ACTIVO) VALUES (0, 0, 'sinAsignarV1', 0, 0);
