INSERT INTO TIPO_DATO (ID_TIPO_DATO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA, ES_PROCESADO, NOMBRE, DESCRIPCION)
VALUES (5019, NULL, NULL, 1, 'PRESENCIA_LOCALIZACION_SECCION_HORAS_SINDICALES', 'Presencia [localizacion|seccion][horas sindicales]');
INSERT INTO TIPO_DATO (ID_TIPO_DATO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA, ES_PROCESADO, NOMBRE, DESCRIPCION)
VALUES (5020, NULL, NULL, 1, 'PRESENCIA_LOCALIZACION-SECCION_INCLUIDOECOMMERCE', 'Presencia [localizacion|seccion][incluido ecommerce]');
INSERT INTO TIPO_DATO (ID_TIPO_DATO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA, ES_PROCESADO, NOMBRE, DESCRIPCION)
VALUES (5021, NULL, NULL, 1, 'REPARTO_HORAS_SINDICALES_LOCALIZACION', 'Reparto presencias sindicales [localizacion]');
INSERT INTO TIPO_DATO (ID_TIPO_DATO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA, ES_PROCESADO, NOMBRE, DESCRIPCION)
VALUES (5022, NULL, NULL, 1, 'REPARTO_HORAS_SINDICALES_LOCALIZACION-SECCION', 'Reparto presencias sindicales [localizacion|seccion]');

UPDATE TIPO_DATO SET NOMBRE='PRESENCIA_LOCALIZACION_INCLUIDOECOMMERCE', DESCRIPCION = 'Presencia [localizacion] [incluido ecommerce]' WHERE ID_TIPO_DATO = 5004;
