-- [AT][38]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'AT');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '38');
-- [CH][39]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'CH');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '39');
-- [CZ][61]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'CZ');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '61');
-- [PL][60]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'PL');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '60');
-- [SK][63]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'SK');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '63');
-- [UK][6]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'UK');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '6');
-- [UY][524]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'UY');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '524');
-- [ZA][388]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'ZA');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '388');
