/***************************/
/**    Resalta  Manual    **/
/***************************/

-- ALGORITMO
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (17001, 1, 'resaltaManualV1', 0, 0);
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (17006, 1, 'resaltaManualDesplazamientoV1', 1, 0);
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (17011, 1, 'resaltaManualDesplazamientoBaseV1', 1, 1);

-- TIPO_COMISION
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES ('014', 'RESALTA_MANUAL');

-- ALGORITMO_TIPO_COMISION
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (17001, '014');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (17006, '014');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (17011, '014');

-- ALGORITMO_TIPO_CALCULO
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (17001, '000');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (17006, '000');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (17011, '000');
