INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (1, '01', 'Mensual', 'Mensual');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (2, '02', 'Bimensual', 'Bimensual');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (3, '03', 'Trimestral', 'Trimestral');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (4, '04', 'Cuatrimestral', 'Cuatrimestral');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (5, '05', 'Semestral', 'Semestral');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (6, '06', 'Anual', 'Anual');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (7, '07', 'Abierto', 'Abierto');


INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (1, 'VENTA_CAJA', 'Venta caja', '01', 1);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (2, 'DEVOLUCIONES_OTRAS_TIENDAS', 'Devoluciones otras tiendas', '02', 1);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (3, 'ONLINE_IPOD', 'Venta online iPod', '03', 2);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (4, 'ONLINE_SINT', 'Venta online SINT', '04', 3);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (5, 'ONLINE_ENTREGA_TIENDA', 'Venta online entrega en tienda', '05', 4);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (6, 'ONLINE_ENTREGA_DOMICILIO', 'Venta online entrega en domicilio', '06', 5);
