/***************************/
/** ESTADO_TAREA_LIMPIEZA **/
/***************************/

INSERT INTO ESTADO_TAREA_LIMPIEZA (ID_ESTADO_TAREA_LIMPIEZA, NOMBRE, PESO) VALUES (1, 'Pendiente', 100);
INSERT INTO ESTADO_TAREA_LIMPIEZA (ID_ESTADO_TAREA_LIMPIEZA, NOMBRE, PESO) VALUES (2, 'Ok', 200);
INSERT INTO ESTADO_TAREA_LIMPIEZA (ID_ESTADO_TAREA_LIMPIEZA, NOMBRE, PESO) VALUES (3, 'Ko', 300);
