INSERT INTO ESTADO_TAREA_FASE (ID_ESTADO_TAREA_FASE, NOMBRE, PESO) VALUES (1, 'Pendiente', 100);
INSERT INTO ESTADO_TAREA_FASE (ID_ESTADO_TAREA_FASE, NOMBRE, PESO) VALUES (2, 'Ko', 200);
INSERT INTO ESTADO_TAREA_FASE (ID_ESTADO_TAREA_FASE, NOMBRE, PESO) VALUES (3, 'Ok', 300);
INSERT INTO ESTADO_TAREA_FASE (ID_ESTADO_TAREA_FASE, NOMBRE, PESO) VALUES (4, 'No ejecutada', 400);
INSERT INTO ESTADO_TAREA_FASE (ID_ESTADO_TAREA_FASE, NOMBRE, PESO) VALUES (5, 'Error', 500);

INSERT INTO ESTADO_TAREA_FASE_ACCION (ID_ESTADO_TAREA_FASE_ACCION, NOMBRE, PESO) VALUES (1, 'Pendiente', 100);
INSERT INTO ESTADO_TAREA_FASE_ACCION (ID_ESTADO_TAREA_FASE_ACCION, NOMBRE, PESO) VALUES (2, 'Ko', 200);
INSERT INTO ESTADO_TAREA_FASE_ACCION (ID_ESTADO_TAREA_FASE_ACCION, NOMBRE, PESO) VALUES (3, 'Ok', 300);
INSERT INTO ESTADO_TAREA_FASE_ACCION (ID_ESTADO_TAREA_FASE_ACCION, NOMBRE, PESO) VALUES (4, 'No ejecutada', 400);
INSERT INTO ESTADO_TAREA_FASE_ACCION (ID_ESTADO_TAREA_FASE_ACCION, NOMBRE, PESO) VALUES (5, 'Error', 500);

INSERT INTO FASE (ID_FASE, NOMBRE, PESO) VALUES (1, 'Recolectar', 100);
INSERT INTO FASE (ID_FASE, NOMBRE, PESO) VALUES (2, 'Validar recolección', 200);
INSERT INTO FASE (ID_FASE, NOMBRE, PESO) VALUES (3, 'Procesar', 300);
INSERT INTO FASE (ID_FASE, NOMBRE, PESO) VALUES (4, 'Calcular', 400);
INSERT INTO FASE (ID_FASE, NOMBRE, PESO) VALUES (5, 'Regularizar Challenge', 500);
INSERT INTO FASE (ID_FASE, NOMBRE, PESO) VALUES (6, 'Regularizar', 600);
INSERT INTO FASE (ID_FASE, NOMBRE, PESO) VALUES (7, 'Ajustar', 700);

INSERT INTO PUNTO_EJECUCION (ID_PUNTO_EJECUCION, NOMBRE) VALUES (1, 'Antes');
INSERT INTO PUNTO_EJECUCION (ID_PUNTO_EJECUCION, NOMBRE) VALUES (2, 'Durante');
INSERT INTO PUNTO_EJECUCION (ID_PUNTO_EJECUCION, NOMBRE) VALUES (3, 'Despues');
INSERT INTO PUNTO_EJECUCION (ID_PUNTO_EJECUCION, NOMBRE) VALUES (4, 'Error');

INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (1, 'motivosDesplazamientoV1', 'Displacement reasons unsynchronized. ', 100, 0, 0, 0, 0);
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (2, 'condicionesHistoricoV1', 'The employees conditions history differ between SIL and INCOME. ', 100, 1, 1, 3, 180000);
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (3, 'fechasV1', 'There are cases of inverted or overlapped dates in SIL. ', 100, 1, 1, 3, 180000);
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (4, 'presenciasV1', 'The hours number differs in PTR and SIL for the country in the selected period. ', 100, 1, 1, 3, 180000);
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (5, 'validarBajaItV1', 'The IT leavers in SIL do not correspond to the IT leaver policies in INCOME. ', 100, 1, 1, 3, 180000);
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (6, 'validarCarenciaV1', 'The exclusion periods in SIL do not correspond to the exclusion period policies in INCOME. ', 100, 1, 1, 3, 180000);
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (7, 'condicionesResaltaV1', 'Resalta conditions differ between SIL and INCOME. ', 100, 1, 1, 3, 180000);
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (8, 'condicionesDesplazamientoV1', 'Displacement conditions differ between SIL and INCOME. ', 100, 1, 1, 3, 180000);

INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE, PESO) VALUES (6, 'ERROR VALIDACION', 300);
