-- Fase 1: [CZ|HU|SK]
-- [MOCK][INICIO] PROGRAMACION
-- Programacion: 1 | Programacion ambito: 1 || Sociedad: AT | Origen: 38 | Empresa: [95,135,251,315,329,340,425,468]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (1, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'AT_38_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_ORGANIZATION) VALUES (1, 1, 'AT');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES (1, '38');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '95');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '135');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '251');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '315');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '329');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '340');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '425');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (1, '468');
-- Programacion: 2 | Programacion ambito: 2 || Sociedad: CA | Origen: 404 | Empresa: [97,362,395]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (2, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CA_404_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_ORGANIZATION) VALUES (2, 2, 'CA');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES (2, '404');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (2, '97');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (2, '362');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (2, '395');
-- Programacion: 3 | Programacion ambito: 3 || Sociedad: CH | Origen: 39 | Empresa: [36,100,137,143,325,348,456,481,508]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (3, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CH_39_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_ORGANIZATION) VALUES (3, 3, 'CH');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES (3, '39');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (3, '36');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (3, '100');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (3, '137');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (3, '143');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (3, '325');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (3, '348');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (3, '456');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (3, '481');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (3, '508');
-- Programacion: 4 | Programacion ambito: 4 || Sociedad: CZ | Origen: 61 | Empresa: [123,172,173,252,253,254,510,511]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (4, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CZ_61_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_ORGANIZATION) VALUES (4, 4, 'CZ');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES (4, '61');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (4, '123');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (4, '172');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (4, '173');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (4, '252');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (4, '253');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (4, '254');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (4, '510');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (4, '511');
-- Programacion: 5 | Programacion ambito: 5 || Sociedad: DE | Origen: 4 | Empresa: [52,107,132,316,323,333,338,342,347,370,386,393,403,408,424]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (5, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'DE_4_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_ORGANIZATION) VALUES (5, 5, 'DE');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES (5, '4');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '52');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '107');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '132');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '316');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '323');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '333');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '338');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '342');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '347');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '370');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '386');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '393');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '403');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '408');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (5, '424');
-- Programacion: 6 | Programacion ambito: 6 || Sociedad: HU | Origen: 64 | Empresa: [157,177,220,221,235,290,457]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (6, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'HU_64_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_ORGANIZATION) VALUES (6, 6, 'HU');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES (6, '64');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (6, '157');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (6, '177');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (6, '220');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (6, '221');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (6, '235');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (6, '290');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (6, '457');
-- Programacion: 7 | Programacion ambito: 7 || Sociedad: SK | Origen: 63 | Empresa: [209,222,223,224,470,476]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (7, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'SK_63_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_ORGANIZATION) VALUES (7, 7, 'SK');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES (7, '63');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (7, '209');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (7, '222');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (7, '223');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (7, '224');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (7, '470');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (7, '476');
-- Programacion: 8 | Programacion ambito: 8 || Sociedad: UY | Origen: 524 | Empresa: [87,429]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (8, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'UY_524_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_ORGANIZATION) VALUES (8, 8, 'UY');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES (8, '524');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (8, '87');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (8, '429');
-- Programacion: 9 | Programacion ambito: 9 || Sociedad: ZA | Origen: 388 | Empresa: [343,477]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (9, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'ZA_388_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_ORGANIZATION) VALUES (9, 9, 'ZA');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES (9, '388');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (9, '343');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (9, '477');
-- Programacion: 10 | Programacion ambito: 10 || Sociedad: AT | Origen: 38 | Empresa: [95,135]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (10, 1, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'AT_38_DATA', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_ORGANIZATION) VALUES (10, 10, 'AT');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES (10, '38');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (10, '95');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (10, '135');
-- Programacion: 11 | Programacion ambito: 11 || Sociedad: CZ | Origen: 61 | Empresa: [123,173]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (11, 1, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CZ_61_DATA', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_ORGANIZATION) VALUES (11, 11, 'CZ');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES (11, '61');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (11, '123');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (11, '173');
-- Programacion: 12 | Programacion ambito: 12 || Sociedad: CH | Origen: 39 | Empresa: [100]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (12, 1, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CH_39_DATA', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_ORGANIZATION) VALUES (12, 12, 'CH');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES (12, '39');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, STD_ID_LEG_ENT) VALUES (12, '100');
-- [MOCK][FIN] PROGRAMACION