INSERT INTO TIPO_CALCULO_RELACION_COMIS (ID_TIPO_CALCULO_RELACION_COMIS, ID_TIPO_CALCULO, COD_TIPO_CALCULO_COMIS) VALUES (16, '003', 6);
INSERT INTO TIPO_CALCULO_RELACION_COMIS (ID_TIPO_CALCULO_RELACION_COMIS, ID_TIPO_CALCULO, COD_TIPO_CALCULO_COMIS) VALUES (17, '002', 7);
INSERT INTO TIPO_CALCULO_RELACION_COMIS (ID_TIPO_CALCULO_RELACION_COMIS, ID_TIPO_CALCULO, COD_TIPO_CALCULO_COMIS) VALUES (18, '001', 8);

INSERT INTO TIPO_DATO (ID_TIPO_DATO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA, ES_PROCESADO, NOMBRE, DESCRIPCION)
VALUES (5019, NULL, NULL, 1, 'PRESENCIA_LOCALIZACION_SECCION_HORAS_SINDICALES', 'Presencia [localizacion|seccion][horas sindicales]');
