ALTER TABLE DESARROLLO_RRHH.PROGRAMACION ALTER COLUMN ID_PROGRAMACION SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.PROGRAMACION DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.PROGRAMACION ADD CONSTRAINT PK_PROGRAMACION PRIMARY KEY (ID_PROGRAMACION);
CREATE UNIQUE INDEX IX_PROGRAMACION_01 ON DESARROLLO_RRHH.PROGRAMACION (ID_PROGRAMACION);

ALTER TABLE DESARROLLO_RRHH.PROGRAMACION_EMPLEADO ALTER COLUMN ID_PROGRAMACION_EMPLEADO SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.PROGRAMACION_EMPLEADO DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.PROGRAMACION_EMPLEADO ADD CONSTRAINT PK_PROGRAMACION_EMPLEADO PRIMARY KEY (ID_PROGRAMACION_EMPLEADO);
CREATE UNIQUE INDEX IX_PROGRAMACION_EMPLEADO_01 ON DESARROLLO_RRHH.PROGRAMACION_EMPLEADO (ID_PROGRAMACION_EMPLEADO);
ALTER TABLE DESARROLLO_RRHH.PROGRAMACION_EMPLEADO ADD CONSTRAINT FK_PROGRAMACION_EMPLEADO_PROGRAMACION FOREIGN KEY (ID_PROGRAMACION) REFERENCES DESARROLLO_RRHH.PROGRAMACION (ID_PROGRAMACION);

ALTER TABLE DESARROLLO_RRHH.PROGRAMACION_TRABAJO DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.PROGRAMACION_TRABAJO ADD CONSTRAINT PK_PROGRAMACION_TRABAJO PRIMARY KEY (ID_TRABAJO);
CREATE UNIQUE INDEX IX_PROGRAMACION_TRABAJO_01 ON DESARROLLO_RRHH.PROGRAMACION_TRABAJO (ID_TRABAJO);
ALTER TABLE DESARROLLO_RRHH.PROGRAMACION_TRABAJO ADD CONSTRAINT FK_PROGRAMACION_TRABAJO_PROGRAMACION FOREIGN KEY (ID_PROGRAMACION) REFERENCES DESARROLLO_RRHH.PROGRAMACION (ID_PROGRAMACION);

ALTER TABLE DESARROLLO_RRHH.PROGRAMACION_TIENDA ALTER COLUMN ID_PROGRAMACION_TIENDA SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.PROGRAMACION_TIENDA DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.PROGRAMACION_TIENDA ADD CONSTRAINT PK_PROGRAMACION_TIENDA PRIMARY KEY (ID_PROGRAMACION_TIENDA);
CREATE UNIQUE INDEX IX_PROGRAMACION_TIENDA_01 ON DESARROLLO_RRHH.PROGRAMACION_TIENDA (ID_PROGRAMACION_TIENDA);
ALTER TABLE DESARROLLO_RRHH.PROGRAMACION_TIENDA ADD CONSTRAINT FK_PROGRAMACION_TIENDA_PROGRAMACION FOREIGN KEY (ID_PROGRAMACION) REFERENCES DESARROLLO_RRHH.PROGRAMACION (ID_PROGRAMACION);

ALTER TABLE DESARROLLO_RRHH.TRABAJO ALTER COLUMN ID_TRABAJO SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO ADD CONSTRAINT PK_TRABAJO PRIMARY KEY (ID_TRABAJO);
CREATE UNIQUE INDEX IX_TRABAJO_01 ON DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);
ALTER TABLE DESARROLLO_RRHH.PROGRAMACION_TRABAJO ADD CONSTRAINT FK_PROGRAMACION_TRABAJO_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_CALCULO ALTER COLUMN ID_TRABAJO_CALCULO SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_CALCULO DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_CALCULO ADD CONSTRAINT PK_TRABAJO_CALCULO PRIMARY KEY (ID_TRABAJO_CALCULO);
CREATE UNIQUE INDEX IX_TRABAJO_CALCULO_01 ON DESARROLLO_RRHH.TRABAJO_CALCULO (ID_TRABAJO_CALCULO);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_CALCULO ADD CONSTRAINT FK_TRABAJO_CALCULO_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO ALTER COLUMN ID_TRABAJO_EMPLEADO SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO ADD CONSTRAINT PK_TRABAJO_EMPLEADO PRIMARY KEY (ID_TRABAJO_EMPLEADO);
CREATE UNIQUE INDEX IX_TRABAJO_EMPLEADO_01 ON DESARROLLO_RRHH.TRABAJO_CALCULO (ID_TRABAJO_CALCULO);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO ADD CONSTRAINT FK_TRABAJO_EMPLEADO_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO_ESTADO ALTER COLUMN ID_TRABAJO_EMPLEADO_ESTADO SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO_ESTADO DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO_ESTADO ADD CONSTRAINT PK_TRABAJO_EMPLEADO_ESTADO PRIMARY KEY (ID_TRABAJO_EMPLEADO_ESTADO);
CREATE UNIQUE INDEX IX_TRABAJO_EMPLEADO_ESTADO_01 ON DESARROLLO_RRHH.TRABAJO_EMPLEADO_ESTADO (ID_TRABAJO_EMPLEADO_ESTADO);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO_ESTADO ADD CONSTRAINT FK_TRABAJO_EMPLEADO_ESTADO_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO_ESTRUCTURA ALTER COLUMN ID_TRABAJO_EMPLEADO_ESTRUCTURA SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO_ESTRUCTURA DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO_ESTRUCTURA ADD CONSTRAINT PK_TRABAJO_EMPLEADO_ESTRUCTURA PRIMARY KEY (ID_TRABAJO_EMPLEADO_ESTRUCTURA);
CREATE UNIQUE INDEX IX_TRABAJO_EMPLEADO_ESTRUCTURA_01 ON DESARROLLO_RRHH.TRABAJO_EMPLEADO_ESTRUCTURA (ID_TRABAJO_EMPLEADO_ESTRUCTURA);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO_ESTRUCTURA ADD CONSTRAINT FK_TRABAJO_EMPLEADO_ESTRUCTURA_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO_HISTORICO ALTER COLUMN ID_TRABAJO_EMPLEADO_HISTORICO SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO_HISTORICO DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO_HISTORICO ADD CONSTRAINT PK_TRABAJO_EMPLEADO_HISTORICO PRIMARY KEY (ID_TRABAJO_EMPLEADO_HISTORICO);
CREATE UNIQUE INDEX IX_TRABAJO_EMPLEADO_HISTORICO_01 ON DESARROLLO_RRHH.TRABAJO_EMPLEADO_HISTORICO (ID_TRABAJO_EMPLEADO_HISTORICO);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_EMPLEADO_HISTORICO ADD CONSTRAINT FK_TRABAJO_EMPLEADO_HISTORICO_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.ESTADO_TRABAJO DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.ESTADO_TRABAJO ADD CONSTRAINT PK_ESTADO_TRABAJO PRIMARY KEY (ID_ESTADO_TRABAJO);
CREATE UNIQUE INDEX IX_ESTADO_TRABAJO_01 ON DESARROLLO_RRHH.ESTADO_TRABAJO (ID_ESTADO_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.ESTADO_TRABAJO_EMPLEADO DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.ESTADO_TRABAJO_EMPLEADO ADD CONSTRAINT PK_ESTADO_TRABAJO_EMPLEADO PRIMARY KEY (ID_ESTADO_TRABAJO_EMPLEADO);
CREATE UNIQUE INDEX IX_ESTADO_TRABAJO_EMPLEADO_01 ON DESARROLLO_RRHH.ESTADO_TRABAJO_EMPLEADO (ID_ESTADO_TRABAJO_EMPLEADO);

ALTER TABLE DESARROLLO_RRHH.TIPO_TRABAJO_TIENDA DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TIPO_TRABAJO_TIENDA ADD CONSTRAINT PK_TIPO_TRABAJO_TIENDA PRIMARY KEY (ID_TIPO_TRABAJO_TIENDA);
CREATE UNIQUE INDEX IX_TIPO_TRABAJO_TIENDA_01 ON DESARROLLO_RRHH.TIPO_TRABAJO_TIENDA (ID_TIPO_TRABAJO_TIENDA);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA ALTER COLUMN ID_TRABAJO_TIENDA SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA ADD CONSTRAINT PK_TRABAJO_TIENDA PRIMARY KEY (ID_TRABAJO_TIENDA);
CREATE UNIQUE INDEX IX_TRABAJO_TIENDA_01 ON DESARROLLO_RRHH.TRABAJO_TIENDA (ID_TRABAJO_TIENDA);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA ADD CONSTRAINT FK_TRABAJO_TIENDA_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_COMISION_HISTORICO ALTER COLUMN ID_TRABAJO_TIENDA_COMISION_HISTORICO SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_COMISION_HISTORICO DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_COMISION_HISTORICO ADD CONSTRAINT PK__TRABAJO_TIENDA_COMISION_HISTORICO PRIMARY KEY (ID_TRABAJO_TIENDA_COMISION_HISTORICO);
CREATE UNIQUE INDEX IX_TRABAJO_TIENDA_COMISION_HISTORICO_01 ON DESARROLLO_RRHH.TRABAJO_TIENDA_COMISION_HISTORICO (ID_TRABAJO_TIENDA_COMISION_HISTORICO);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_COMISION_HISTORICO ADD CONSTRAINT FK_TRABAJO_TIENDA_COMISION_HISTORICO_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_EMPLEADO_PRESENCIA_SECCION ALTER COLUMN ID_TRABAJO_TIENDA_EMPLEADO_PRESENCIA_SECCION SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_EMPLEADO_PRESENCIA_SECCION DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_EMPLEADO_PRESENCIA_SECCION ADD CONSTRAINT PK_TRABAJO_TIENDA_EMPLEADO_PRESENCIA_SECCION PRIMARY KEY (ID_TRABAJO_TIENDA_EMPLEADO_PRESENCIA_SECCION);
CREATE UNIQUE INDEX IX_TRABAJO_TIENDA_EMPLEADO_PRESENCIA_SECCION_01 ON DESARROLLO_RRHH.TRABAJO_TIENDA_EMPLEADO_PRESENCIA_SECCION (ID_TRABAJO_TIENDA_EMPLEADO_PRESENCIA_SECCION);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_EMPLEADO_PRESENCIA_SECCION ADD CONSTRAINT FK_TRABAJO_TIENDA_EMPLEADO_PRESENCIA_SECCION_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_ESTADO ALTER COLUMN ID_TRABAJO_TIENDA_ESTADO SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_ESTADO DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_ESTADO ADD CONSTRAINT PK_TRABAJO_TIENDA_ESTADO PRIMARY KEY (ID_TRABAJO_TIENDA_ESTADO);
CREATE UNIQUE INDEX IX_TRABAJO_TIENDA_ESTADO_01 ON DESARROLLO_RRHH.TRABAJO_TIENDA_ESTADO (ID_TRABAJO_TIENDA_ESTADO);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_ESTADO ADD CONSTRAINT FK_TRABAJO_TIENDA_ESTADO_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_HISTORICO ALTER COLUMN ID_TRABAJO_TIENDA_HISTORICO SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_HISTORICO DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_HISTORICO ADD CONSTRAINT PK_TRABAJO_TIENDA_HISTORICO PRIMARY KEY (ID_TRABAJO_TIENDA_HISTORICO);
CREATE UNIQUE INDEX IX_TRABAJO_TIENDA_HISTORICO_01 ON DESARROLLO_RRHH.TRABAJO_TIENDA_HISTORICO (ID_TRABAJO_TIENDA_HISTORICO);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_HISTORICO ADD CONSTRAINT FK_TRABAJO_TIENDA_HISTORICO_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_PRESENCIA_SECCION ALTER COLUMN ID_TRABAJO_TIENDA_PRESENCIA_SECCION SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_PRESENCIA_SECCION DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_PRESENCIA_SECCION ADD CONSTRAINT PK_TRABAJO_TIENDA_PRESENCIA_SECCION PRIMARY KEY (ID_TRABAJO_TIENDA_PRESENCIA_SECCION);
CREATE UNIQUE INDEX IX_TRABAJO_TIENDA_PRESENCIA_SECCION_01 ON DESARROLLO_RRHH.TRABAJO_TIENDA_PRESENCIA_SECCION (ID_TRABAJO_TIENDA_PRESENCIA_SECCION);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_PRESENCIA_SECCION ADD CONSTRAINT FK_TRABAJO_TIENDA_PRESENCIA_SECCION_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_EMPLEADO_PRESENCIA ALTER COLUMN ID_TRABAJO_TIENDA_SECCION_EMPLEADO_PRESENCIA SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_EMPLEADO_PRESENCIA DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_EMPLEADO_PRESENCIA ADD CONSTRAINT PK_TRABAJO_TIENDA_SECCION_EMPLEADO_PRESENCIA PRIMARY KEY (ID_TRABAJO_TIENDA_SECCION_EMPLEADO_PRESENCIA);
CREATE UNIQUE INDEX IX_TRABAJO_TIENDA_SECCION_EMPLEADO_PRESENCIA_01 ON DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_EMPLEADO_PRESENCIA (ID_TRABAJO_TIENDA_SECCION_EMPLEADO_PRESENCIA);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_EMPLEADO_PRESENCIA ADD CONSTRAINT FK_TRABAJO_TIENDA_SECCION_EMPLEADO_PRESENCIA_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_PRESENCIA ALTER COLUMN ID_TRABAJO_TIENDA_SECCION_PRESENCIA SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_PRESENCIA DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_PRESENCIA ADD CONSTRAINT PK__TRABAJO_TIENDA_SECCION_PRESENCIA PRIMARY KEY (ID_TRABAJO_TIENDA_SECCION_PRESENCIA);
CREATE UNIQUE INDEX IX_TRABAJO_TIENDA_SECCION_PRESENCIA_01 ON DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_PRESENCIA (ID_TRABAJO_TIENDA_SECCION_PRESENCIA);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_PRESENCIA ADD CONSTRAINT FK_TRABAJO_TIENDA_SECCION_PRESENCIA_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_VENTA ALTER COLUMN ID_TRABAJO_TIENDA_SECCION_VENTA SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_VENTA DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_VENTA ADD CONSTRAINT PK_TRABAJO_TIENDA_SECCION_VENTA PRIMARY KEY (ID_TRABAJO_TIENDA_SECCION_VENTA);
CREATE UNIQUE INDEX IX_TRABAJO_TIENDA_SECCION_PRESENCIA_01 ON DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_VENTA (ID_TRABAJO_TIENDA_SECCION_VENTA);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_SECCION_VENTA ADD CONSTRAINT FK_TRABAJO_TIENDA_SECCION_VENTA_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_VENTA_SECCION ALTER COLUMN ID_TRABAJO_TIENDA_VENTA_SECCION SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_VENTA_SECCION DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_VENTA_SECCION ADD CONSTRAINT PK_TRABAJO_TIENDA_VENTA_SECCION PRIMARY KEY (ID_TRABAJO_TIENDA_VENTA_SECCION);
CREATE UNIQUE INDEX IX_TRABAJO_TIENDA_VENTA_SECCION_01 ON DESARROLLO_RRHH.TRABAJO_TIENDA_VENTA_SECCION (ID_TRABAJO_TIENDA_VENTA_SECCION);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIENDA_VENTA_SECCION ADD CONSTRAINT FK_TRABAJO_TIENDA_VENTA_SECCION_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO;

ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIPO_HORA ALTER COLUMN ID_TRABAJO_TIPO_HORA SET CACHE 100;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIPO_HORA DROP PRIMARY KEY;
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIPO_HORA ADD CONSTRAINT PK_TRABAJO_TIPO_HORA PRIMARY KEY (ID_TRABAJO_TIPO_HORA);
CREATE UNIQUE INDEX IX_TRABAJO_TIPO_HORA_01 ON DESARROLLO_RRHH.TRABAJO_TIPO_HORA (ID_TRABAJO_TIPO_HORA);
ALTER TABLE DESARROLLO_RRHH.TRABAJO_TIPO_HORA ADD CONSTRAINT FK_TRABAJO_TIPO_HORA_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES DESARROLLO_RRHH.TRABAJO (ID_TRABAJO);

