-- [AT][38]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'AT');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '38');
-- [CH][39]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'CH');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '39');
-- [CZ][61]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'CZ');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '61');
-- [SK][63]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'SK');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '63');
-- [UY][524]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'UY');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '524');
-- [ZA][388]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'ZA');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '388');
-- [ME][97]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:03:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'ME');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '97');
-- [RS][98]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:03:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'RS');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '98');
-- [CL][512]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:03:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'CL');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '512');
-- [AR][528]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:03:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'AR');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '528');
-- [DK][8]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:03:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'DK');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '8');
-- [NO][28]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:03:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'NO');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '28');
-- [FI][32]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:03:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'FI');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '32');
-- [SE][30]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:03:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'SE');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '30');
-- PENDIENTE LANZAR (SOLO FALTA PRO)
-- [PL][60]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'PL');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '60');
-- [UK][6]
INSERT INTO PROGRAMACION (ES_ACTIVO, FECHA_HORA_CREACION, FECHA_HORA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, PROGRAMACION_HUSO, NOMBRE_USUARIO, ID_TIPO_AMBITO) VALUES (0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'srvcicmclcwbax', 2);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION, ID_ORGANIZATION) VALUES ((SELECT MAX(ID_PROGRAMACION) FROM PROGRAMACION), 'UK');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, CCL_ID_ORIGEN) VALUES ((SELECT MAX(ID_PROGRAMACION_AMBITO) FROM PROGRAMACION_AMBITO), '6'); 