/***********/
/** COMUN **/
/***********/
ALTER TABLE TIPO_AMBITO DROP PRIMARY KEY;
ALTER TABLE TIPO_AMBITO ADD CONSTRAINT PK_TIPO_AMBITO PRIMARY KEY (ID_TIPO_AMBITO);
CREATE UNIQUE INDEX IX_TIPO_AMBITO_01 ON TIPO_AMBITO (ID_TIPO_AMBITO);

/******************/
/** PROGRAMACION **/
/******************/
ALTER TABLE PROGRAMACION ALTER COLUMN ID_PROGRAMACION SET CACHE 100;
ALTER TABLE PROGRAMACION DROP PRIMARY KEY;
ALTER TABLE PROGRAMACION ADD CONSTRAINT PK_PROGRAMACION PRIMARY KEY (ID_PROGRAMACION);
CREATE UNIQUE INDEX IX_PROGRAMACION_01 ON PROGRAMACION (ID_PROGRAMACION);
ALTER TABLE PROGRAMACION ADD CONSTRAINT FK_PROGRAMACION_TIPO_AMBITO FOREIGN KEY (ID_TIPO_AMBITO) REFERENCES TIPO_AMBITO (ID_TIPO_AMBITO);

ALTER TABLE PROGRAMACION_AMBITO ALTER COLUMN ID_PROGRAMACION_AMBITO SET CACHE 100;
ALTER TABLE PROGRAMACION_AMBITO DROP PRIMARY KEY;
ALTER TABLE PROGRAMACION_AMBITO ADD CONSTRAINT PK_PROGRAMACION_AMBITO PRIMARY KEY (ID_PROGRAMACION_AMBITO);
CREATE UNIQUE INDEX IX_PROGRAMACION_AMBITO_01 ON PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO);
ALTER TABLE PROGRAMACION_AMBITO ADD CONSTRAINT FK_PROGRAMACION_AMBITO_PROGRAMACION FOREIGN KEY (ID_PROGRAMACION) REFERENCES PROGRAMACION (ID_PROGRAMACION);

ALTER TABLE PROGRAMACION_AMBITO_EMPRESA ALTER COLUMN ID_PROGRAMACION_AMBITO_EMPRESA SET CACHE 100;
ALTER TABLE PROGRAMACION_AMBITO_EMPRESA DROP PRIMARY KEY;
ALTER TABLE PROGRAMACION_AMBITO_EMPRESA ADD CONSTRAINT PK_PROGRAMACION_AMBITO_EMPRESA PRIMARY KEY (ID_PROGRAMACION_AMBITO_EMPRESA);
CREATE UNIQUE INDEX IX_PROGRAMACION_AMBITO_EMPRESA_01 ON PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO_EMPRESA);
ALTER TABLE PROGRAMACION_AMBITO_EMPRESA ADD CONSTRAINT FK_PROGRAMACION_AMBITO_EMPRESA_PROGRAMACION_AMBITO FOREIGN KEY (ID_PROGRAMACION_AMBITO) REFERENCES PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO);

ALTER TABLE PROGRAMACION_AMBITO_LOCALIZACION ALTER COLUMN ID_PROGRAMACION_AMBITO_LOCALIZACION SET CACHE 100;
ALTER TABLE PROGRAMACION_AMBITO_LOCALIZACION DROP PRIMARY KEY;
ALTER TABLE PROGRAMACION_AMBITO_LOCALIZACION ADD CONSTRAINT PK_PROGRAMACION_AMBITO_LOCALIZACION PRIMARY KEY (ID_PROGRAMACION_AMBITO_LOCALIZACION);
CREATE UNIQUE INDEX IX_PROGRAMACION_AMBITO_LOCALIZACION_01 ON PROGRAMACION_AMBITO_LOCALIZACION (ID_PROGRAMACION_AMBITO_LOCALIZACION);
ALTER TABLE PROGRAMACION_AMBITO_LOCALIZACION ADD CONSTRAINT FK_PROGRAMACION_AMBITO_LOCALIZACION_PROGRAMACION_AMBITO FOREIGN KEY (ID_PROGRAMACION_AMBITO) REFERENCES PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO);

ALTER TABLE PROGRAMACION_AMBITO_ORIGEN ALTER COLUMN ID_PROGRAMACION_AMBITO_ORIGEN SET CACHE 100;
ALTER TABLE PROGRAMACION_AMBITO_ORIGEN DROP PRIMARY KEY;
ALTER TABLE PROGRAMACION_AMBITO_ORIGEN ADD CONSTRAINT PK_PROGRAMACION_AMBITO_ORIGEN PRIMARY KEY (ID_PROGRAMACION_AMBITO_ORIGEN);
CREATE UNIQUE INDEX IX_PROGRAMACION_AMBITO_ORIGEN_01 ON PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO_ORIGEN);
ALTER TABLE PROGRAMACION_AMBITO_ORIGEN ADD CONSTRAINT FK_PROGRAMACION_AMBITO_ORIGEN_PROGRAMACION_AMBITO FOREIGN KEY (ID_PROGRAMACION_AMBITO) REFERENCES PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO);

ALTER TABLE PROGRAMACION_AMBITO_PERSONA ALTER COLUMN ID_PROGRAMACION_AMBITO_PERSONA SET CACHE 100;
ALTER TABLE PROGRAMACION_AMBITO_PERSONA DROP PRIMARY KEY;
ALTER TABLE PROGRAMACION_AMBITO_PERSONA ADD CONSTRAINT PK_PROGRAMACION_AMBITO_PERSONA PRIMARY KEY (ID_PROGRAMACION_AMBITO_PERSONA);
CREATE UNIQUE INDEX IX_PROGRAMACION_AMBITO_PERSONA_01 ON PROGRAMACION_AMBITO_PERSONA (ID_PROGRAMACION_AMBITO_PERSONA);
ALTER TABLE PROGRAMACION_AMBITO_PERSONA ADD CONSTRAINT FK_PROGRAMACION_AMBITO_PERSONA_PROGRAMACION_AMBITO FOREIGN KEY (ID_PROGRAMACION_AMBITO) REFERENCES PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO);

/*************/
/** TRABAJO **/
/*************/
ALTER TABLE TRABAJO ALTER COLUMN ID_TRABAJO SET CACHE 100;
ALTER TABLE TRABAJO DROP PRIMARY KEY;
ALTER TABLE TRABAJO ADD CONSTRAINT PK_TRABAJO PRIMARY KEY (ID_TRABAJO);
CREATE UNIQUE INDEX IX_TRABAJO_01 ON TRABAJO (ID_TRABAJO);
ALTER TABLE TRABAJO ADD CONSTRAINT FK_TRABAJO_TIPO_AMBITO FOREIGN KEY (ID_TIPO_AMBITO) REFERENCES TIPO_AMBITO (ID_TIPO_AMBITO);
ALTER TABLE TRABAJO ADD CONSTRAINT FK_TRABAJO_PROGRAMACION FOREIGN KEY (ID_PROGRAMACION) REFERENCES PROGRAMACION (ID_PROGRAMACION);

ALTER TABLE TRABAJO_AMBITO_EMPRESA ALTER COLUMN ID_TRABAJO_AMBITO_EMPRESA SET CACHE 100;
ALTER TABLE TRABAJO_AMBITO_EMPRESA DROP PRIMARY KEY;
ALTER TABLE TRABAJO_AMBITO_EMPRESA ADD CONSTRAINT PK_TRABAJO_AMBITO_EMPRESA PRIMARY KEY (ID_TRABAJO_AMBITO_EMPRESA);
CREATE UNIQUE INDEX IX_TRABAJO_AMBITO_EMPRESA_01 ON TRABAJO_AMBITO_EMPRESA (ID_TRABAJO_AMBITO_EMPRESA);
ALTER TABLE TRABAJO_AMBITO_EMPRESA ADD CONSTRAINT FK_TRABAJO_AMBITO_EMPRESA_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES TRABAJO (ID_TRABAJO);

ALTER TABLE TRABAJO_AMBITO_LOCALIZACION ALTER COLUMN ID_TRABAJO_AMBITO_LOCALIZACION SET CACHE 100;
ALTER TABLE TRABAJO_AMBITO_LOCALIZACION DROP PRIMARY KEY;
ALTER TABLE TRABAJO_AMBITO_LOCALIZACION ADD CONSTRAINT PK_TRABAJO_AMBITO_LOCALIZACION PRIMARY KEY (ID_TRABAJO_AMBITO_LOCALIZACION);
CREATE UNIQUE INDEX IX_TRABAJO_AMBITO_LOCALIZACION_01 ON TRABAJO_AMBITO_LOCALIZACION (ID_TRABAJO_AMBITO_LOCALIZACION);
ALTER TABLE TRABAJO_AMBITO_LOCALIZACION ADD CONSTRAINT FK_TRABAJO_AMBITO_LOCALIZACION_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES TRABAJO (ID_TRABAJO);

ALTER TABLE TRABAJO_AMBITO_ORIGEN ALTER COLUMN ID_TRABAJO_AMBITO_ORIGEN SET CACHE 100;
ALTER TABLE TRABAJO_AMBITO_ORIGEN DROP PRIMARY KEY;
ALTER TABLE TRABAJO_AMBITO_ORIGEN ADD CONSTRAINT PK_TRABAJO_AMBITO_ORIGEN PRIMARY KEY (ID_TRABAJO_AMBITO_ORIGEN);
CREATE UNIQUE INDEX IX_TRABAJO_AMBITO_ORIGEN_01 ON TRABAJO_AMBITO_ORIGEN (ID_TRABAJO_AMBITO_ORIGEN);
ALTER TABLE TRABAJO_AMBITO_ORIGEN ADD CONSTRAINT FK_TRABAJO_AMBITO_ORIGEN_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES TRABAJO (ID_TRABAJO);

ALTER TABLE TRABAJO_AMBITO_PERSONA ALTER COLUMN ID_TRABAJO_AMBITO_PERSONA SET CACHE 100;
ALTER TABLE TRABAJO_AMBITO_PERSONA DROP PRIMARY KEY;
ALTER TABLE TRABAJO_AMBITO_PERSONA ADD CONSTRAINT PK_TRABAJO_AMBITO_PERSONA PRIMARY KEY (ID_TRABAJO_AMBITO_PERSONA);
CREATE UNIQUE INDEX IX_TRABAJO_AMBITO_PERSONA_01 ON TRABAJO_AMBITO_PERSONA (ID_TRABAJO_AMBITO_PERSONA);
ALTER TABLE TRABAJO_AMBITO_PERSONA ADD CONSTRAINT FK_TRABAJO_AMBITO_PERSONA_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES TRABAJO (ID_TRABAJO);

/***********/
/** TAREA **/
/***********/
ALTER TABLE TIPO_DATO DROP PRIMARY KEY;
ALTER TABLE TIPO_DATO ADD CONSTRAINT PK_TIPO_DATO PRIMARY KEY (ID_TIPO_DATO);

ALTER TABLE ESTADO_TAREA DROP PRIMARY KEY;
ALTER TABLE ESTADO_TAREA ADD CONSTRAINT PK_ESTADO_TAREA PRIMARY KEY (ID_ESTADO_TAREA);
CREATE UNIQUE INDEX IX_ESTADO_TAREA_01 ON ESTADO_TAREA (ID_ESTADO_TAREA);

ALTER TABLE ESTADO_TAREA_PERSONA DROP PRIMARY KEY;
ALTER TABLE ESTADO_TAREA_PERSONA ADD CONSTRAINT PK_ESTADO_TAREA_PERSONA PRIMARY KEY (ID_ESTADO_TAREA_PERSONA);
CREATE UNIQUE INDEX IX_ESTADO_TAREA_PERSONA_01 ON ESTADO_TAREA_PERSONA (ID_ESTADO_TAREA_PERSONA);

ALTER TABLE TAREA ALTER COLUMN ID_TAREA SET CACHE 100;
ALTER TABLE TAREA DROP PRIMARY KEY;
ALTER TABLE TAREA ADD CONSTRAINT PK_TAREA PRIMARY KEY (ID_TAREA);
CREATE UNIQUE INDEX IX_TAREA_01 ON TAREA (ID_TAREA);
ALTER TABLE TAREA ADD CONSTRAINT FK_TAREA_ESTADO_TAREA FOREIGN KEY (ID_ESTADO_TAREA) REFERENCES ESTADO_TAREA (ID_ESTADO_TAREA);
ALTER TABLE TAREA ADD CONSTRAINT FK_TAREA_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES TRABAJO (ID_TRABAJO);

ALTER TABLE TAREA_AMBITO ALTER COLUMN ID_TAREA_AMBITO SET CACHE 100;
ALTER TABLE TAREA_AMBITO DROP PRIMARY KEY;
ALTER TABLE TAREA_AMBITO ADD CONSTRAINT PK_TAREA_AMBITO PRIMARY KEY (ID_TAREA_AMBITO);
CREATE UNIQUE INDEX IX_TAREA_AMBITO_01 ON TAREA_AMBITO (ID_TAREA_AMBITO);
ALTER TABLE TAREA_AMBITO ADD CONSTRAINT FK_TAREA_AMBITO_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);

ALTER TABLE TAREA_AMBITO_LOCALIZACION ALTER COLUMN ID_TAREA_AMBITO_LOCALIZACION SET CACHE 100;
ALTER TABLE TAREA_AMBITO_LOCALIZACION DROP PRIMARY KEY;
ALTER TABLE TAREA_AMBITO_LOCALIZACION ADD CONSTRAINT PK_TAREA_AMBITO_LOCALIZACION PRIMARY KEY (ID_TAREA_AMBITO_LOCALIZACION);
CREATE UNIQUE INDEX IX_TAREA_AMBITO_LOCALIZACION_01 ON TAREA_AMBITO_LOCALIZACION (ID_TAREA_AMBITO_LOCALIZACION);
ALTER TABLE TAREA_AMBITO_LOCALIZACION ADD CONSTRAINT FK_TAREA_AMBITO_LOCALIZACION_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);

ALTER TABLE TAREA_AMBITO_PERSONA ALTER COLUMN ID_TAREA_AMBITO_PERSONA SET CACHE 100;
ALTER TABLE TAREA_AMBITO_PERSONA DROP PRIMARY KEY;
ALTER TABLE TAREA_AMBITO_PERSONA ADD CONSTRAINT PK_TAREA_AMBITO_PERSONA PRIMARY KEY (ID_TAREA_AMBITO_PERSONA);
CREATE UNIQUE INDEX IX_TAREA_AMBITO_PERSONA_01 ON TAREA_AMBITO_PERSONA (ID_TAREA_AMBITO_PERSONA);
ALTER TABLE TAREA_AMBITO_PERSONA ADD CONSTRAINT FK_TAREA_AMBITO_PERSONA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);

ALTER TABLE TAREA_CALCULO ALTER COLUMN ID_TAREA_CALCULO SET CACHE 100;
ALTER TABLE TAREA_CALCULO DROP PRIMARY KEY;
ALTER TABLE TAREA_CALCULO ADD CONSTRAINT PK_TAREA_CALCULO PRIMARY KEY (ID_TAREA_CALCULO);
CREATE UNIQUE INDEX IX_TAREA_CALCULO_01 ON TAREA_CALCULO (ID_TAREA_CALCULO);
ALTER TABLE TAREA_CALCULO ADD CONSTRAINT FK_TAREA_CALCULO_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);

ALTER TABLE TAREA_PERSONA_ESTRUCTURA ALTER COLUMN ID_TAREA_PERSONA_ESTRUCTURA SET CACHE 100;
ALTER TABLE TAREA_PERSONA_ESTRUCTURA DROP PRIMARY KEY;
ALTER TABLE TAREA_PERSONA_ESTRUCTURA ADD CONSTRAINT PK_TAREA_PERSONA_ESTRUCTURA PRIMARY KEY (ID_TAREA_PERSONA_ESTRUCTURA);
CREATE UNIQUE INDEX IX_TAREA_PERSONA_ESTRUCTURA_01 ON TAREA_PERSONA_ESTRUCTURA (ID_TAREA_PERSONA_ESTRUCTURA);
ALTER TABLE TAREA_PERSONA_ESTRUCTURA ADD CONSTRAINT FK_TAREA_PERSONA_ESTRUCTURA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_PERSONA_ESTRUCTURA_02 ON TAREA_PERSONA_ESTRUCTURA (ID_TAREA);
CREATE INDEX IX_TAREA_PERSONA_ESTRUCTURA_03 ON TAREA_PERSONA_ESTRUCTURA (ID_PERSONA);
CREATE INDEX IX_TAREA_PERSONA_ESTRUCTURA_04 ON TAREA_PERSONA_ESTRUCTURA (ID_PERSONA_LOCAL);
CREATE INDEX IX_TAREA_PERSONA_ESTRUCTURA_05 ON TAREA_PERSONA_ESTRUCTURA (OR_PERSONA);
CREATE INDEX IX_TAREA_PERSONA_ESTRUCTURA_06 ON TAREA_PERSONA_ESTRUCTURA (FECHA_INICIO);
CREATE INDEX IX_TAREA_PERSONA_ESTRUCTURA_07 ON TAREA_PERSONA_ESTRUCTURA (FECHA_FIN);
CREATE INDEX IX_TAREA_PERSONA_ESTRUCTURA_08 ON TAREA_PERSONA_ESTRUCTURA (ID_TAREA, ID_PERSONA, ID_PERSONA_LOCAL, OR_PERSONA, FECHA_INICIO, FECHA_FIN);
CREATE INDEX IX_TAREA_PERSONA_ESTRUCTURA_09 ON TAREA_PERSONA_ESTRUCTURA (ID_TIPO_CALCULO, ID_TIPO_COMISION);

ALTER TABLE TAREA_AMBITO_GLOBAL_PERSONA ALTER COLUMN ID_TAREA_AMBITO_GLOBAL_PERSONA SET CACHE 100;
ALTER TABLE TAREA_AMBITO_GLOBAL_PERSONA DROP PRIMARY KEY;
ALTER TABLE TAREA_AMBITO_GLOBAL_PERSONA ADD CONSTRAINT PK_TAREA_AMBITO_GLOBAL_PERSONA PRIMARY KEY (ID_TAREA_AMBITO_GLOBAL_PERSONA);
CREATE UNIQUE INDEX IX_TAREA_AMBITO_GLOBAL_PERSONA_01 ON TAREA_AMBITO_GLOBAL_PERSONA (ID_TAREA_AMBITO_GLOBAL_PERSONA);
ALTER TABLE TAREA_AMBITO_GLOBAL_PERSONA ADD CONSTRAINT FK_TAREA_AMBITO_GLOBAL_PERSONA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_AMBITO_GLOBAL_PERSONA_02 ON TAREA_AMBITO_GLOBAL_PERSONA (ID_TAREA);

ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION ALTER COLUMN ID_TAREA_AMBITO_GLOBAL_LOCALIZACION SET CACHE 100;
ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION DROP PRIMARY KEY;
ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION ADD CONSTRAINT PK_TAREA_AMBITO_GLOBAL_LOCALIZACION PRIMARY KEY (ID_TAREA_AMBITO_GLOBAL_LOCALIZACION);
CREATE UNIQUE INDEX IX_TAREA_AMBITO_GLOBAL_LOCALIZACION_01 ON TAREA_AMBITO_GLOBAL_LOCALIZACION (ID_TAREA_AMBITO_GLOBAL_LOCALIZACION);
ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION ADD CONSTRAINT FK_TAREA_AMBITO_GLOBAL_LOCALIZACION_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_AMBITO_GLOBAL_LOCALIZACION_02 ON TAREA_AMBITO_GLOBAL_LOCALIZACION (ID_TAREA);

ALTER TABLE TAREA_LOCALIZACION_CALCULAR ALTER COLUMN ID_TAREA_LOCALIZACION_CALCULAR SET CACHE 100;
ALTER TABLE TAREA_LOCALIZACION_CALCULAR DROP PRIMARY KEY;
ALTER TABLE TAREA_LOCALIZACION_CALCULAR ADD CONSTRAINT PK_TAREA_LOCALIZACION_CALCULAR PRIMARY KEY (ID_TAREA_LOCALIZACION_CALCULAR);
CREATE UNIQUE INDEX IX_TAREA_LOCALIZACION_CALCULAR_01 ON TAREA_LOCALIZACION_CALCULAR (ID_TAREA_LOCALIZACION_CALCULAR);
ALTER TABLE TAREA_LOCALIZACION_CALCULAR ADD CONSTRAINT FK_TAREA_LOCALIZACION_CALCULAR_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_CALCULAR_02 ON TAREA_LOCALIZACION_CALCULAR (ID_TAREA);

ALTER TABLE TAREA_LOCALIZACION_FESTIVO ALTER COLUMN ID_TAREA_LOCALIZACION_FESTIVO SET CACHE 100;
ALTER TABLE TAREA_LOCALIZACION_FESTIVO DROP PRIMARY KEY;
ALTER TABLE TAREA_LOCALIZACION_FESTIVO ADD CONSTRAINT PK_TAREA_LOCALIZACION_FESTIVO PRIMARY KEY (ID_TAREA_LOCALIZACION_FESTIVO);
CREATE UNIQUE INDEX IX_TAREA_LOCALIZACION_FESTIVO_01 ON TAREA_LOCALIZACION_FESTIVO (ID_TAREA_LOCALIZACION_FESTIVO);
ALTER TABLE TAREA_LOCALIZACION_FESTIVO ADD CONSTRAINT FK_TAREA_LOCALIZACION_FESTIVO_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_FESTIVO_02 ON TAREA_LOCALIZACION_FESTIVO (ID_TAREA);

ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA ALTER COLUMN ID_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA SET CACHE 100;
ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA DROP PRIMARY KEY;
ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA ADD CONSTRAINT PK_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA PRIMARY KEY (ID_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA);
CREATE UNIQUE INDEX IX_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_01 ON TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA (ID_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA);
ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA ADD CONSTRAINT FK_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_02 ON TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA (ID_TAREA);

ALTER TABLE TAREA_CALCULO_PERSONA ALTER COLUMN ID_TAREA_CALCULO_PERSONA SET CACHE 100;
ALTER TABLE TAREA_CALCULO_PERSONA DROP PRIMARY KEY;
ALTER TABLE TAREA_CALCULO_PERSONA ADD CONSTRAINT PK_TAREA_CALCULO_PERSONA PRIMARY KEY (ID_TAREA_CALCULO_PERSONA);
CREATE UNIQUE INDEX IX_TAREA_CALCULO_PERSONA_01 ON TAREA_CALCULO_PERSONA (ID_TAREA_CALCULO_PERSONA);
ALTER TABLE TAREA_CALCULO_PERSONA ADD CONSTRAINT FK_TAREA_CALCULO_PERSONA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_CALCULO_PERSONA_02 ON TAREA_CALCULO_PERSONA (ID_TAREA);
ALTER TABLE TAREA_CALCULO_PERSONA ADD CONSTRAINT FK_TAREA_CALCULO_PERSONA_ESTADO_TAREA_PERSONA FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TAREA_PERSONA (ID_ESTADO_TAREA_PERSONA);

ALTER TABLE TAREA_PERSONA_HISTORICO ALTER COLUMN ID_TAREA_PERSONA_HISTORICO SET CACHE 100;
ALTER TABLE TAREA_PERSONA_HISTORICO DROP PRIMARY KEY;
ALTER TABLE TAREA_PERSONA_HISTORICO ADD CONSTRAINT PK_TAREA_PERSONA_HISTORICO PRIMARY KEY (ID_TAREA_PERSONA_HISTORICO);
CREATE UNIQUE INDEX IX_TAREA_PERSONA_HISTORICO_01 ON TAREA_PERSONA_HISTORICO (ID_TAREA_PERSONA_HISTORICO);
ALTER TABLE TAREA_PERSONA_HISTORICO ADD CONSTRAINT FK_TAREA_PERSONA_HISTORICO_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_PERSONA_HISTORICO_02 ON TAREA_PERSONA_HISTORICO (ID_TAREA);
CREATE INDEX IX_TAREA_PERSONA_HISTORICO_03 ON TAREA_PERSONA_HISTORICO (ID_PERSONA_LOCAL);
CREATE INDEX IX_TAREA_PERSONA_HISTORICO_04 ON TAREA_PERSONA_HISTORICO (FECHA_INICIO);
CREATE INDEX IX_TAREA_PERSONA_HISTORICO_05 ON TAREA_PERSONA_HISTORICO (FECHA_FIN);
CREATE INDEX IX_TAREA_PERSONA_HISTORICO_06 ON TAREA_PERSONA_HISTORICO (ID_TAREA, ID_PERSONA_LOCAL, FECHA_INICIO, FECHA_FIN);

ALTER TABLE TAREA_PERSONA_COEFICIENTE ALTER COLUMN ID_TAREA_PERSONA_COEFICIENTE SET CACHE 100;
ALTER TABLE TAREA_PERSONA_COEFICIENTE DROP PRIMARY KEY;
ALTER TABLE TAREA_PERSONA_COEFICIENTE ADD CONSTRAINT PK_TAREA_PERSONA_COEFICIENTE PRIMARY KEY (ID_TAREA_PERSONA_COEFICIENTE);
CREATE UNIQUE INDEX IX_TAREA_PERSONA_COEFICIENTE_01 ON TAREA_PERSONA_COEFICIENTE (ID_TAREA_PERSONA_COEFICIENTE);
ALTER TABLE TAREA_PERSONA_COEFICIENTE ADD CONSTRAINT FK_TAREA_PERSONA_COEFICIENTE_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);

ALTER TABLE TAREA_LOCALIZACION_COMISION_HISTORICO ALTER COLUMN ID_TAREA_LOCALIZACION_COMISION_HISTORICO SET CACHE 100;
ALTER TABLE TAREA_LOCALIZACION_COMISION_HISTORICO DROP PRIMARY KEY;
ALTER TABLE TAREA_LOCALIZACION_COMISION_HISTORICO ADD CONSTRAINT PK_TAREA_LOCALIZACION_COMISION_HISTORICO PRIMARY KEY (ID_TAREA_LOCALIZACION_COMISION_HISTORICO);
CREATE UNIQUE INDEX IX_TAREA_LOCALIZACION_COMISION_HISTORICO_01 ON TAREA_LOCALIZACION_COMISION_HISTORICO (ID_TAREA_LOCALIZACION_COMISION_HISTORICO);
ALTER TABLE TAREA_LOCALIZACION_COMISION_HISTORICO ADD CONSTRAINT FK_TAREA_LOCALIZACION_COMISION_HISTORICO_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_COMISION_HISTORICO_02 ON TAREA_LOCALIZACION_COMISION_HISTORICO (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_COMISION_HISTORICO_03 ON TAREA_LOCALIZACION_COMISION_HISTORICO (STD_ID_WORK_LOCAT);
CREATE INDEX IX_TAREA_LOCALIZACION_COMISION_HISTORICO_04 ON TAREA_LOCALIZACION_COMISION_HISTORICO (FECHA_INICIO);
CREATE INDEX IX_TAREA_LOCALIZACION_COMISION_HISTORICO_05 ON TAREA_LOCALIZACION_COMISION_HISTORICO (FECHA_FIN);
CREATE INDEX IX_TAREA_LOCALIZACION_COMISION_HISTORICO_06 ON TAREA_LOCALIZACION_COMISION_HISTORICO (ID_TAREA, STD_ID_WORK_LOCAT, FECHA_INICIO, FECHA_FIN);
CREATE INDEX IX_TAREA_LOCALIZACION_COMISION_HISTORICO_07 ON TAREA_LOCALIZACION_COMISION_HISTORICO (ID_TAREA, STD_ID_WORK_LOCAT, FECHA_INICIO, FECHA_FIN, COMISIONABLE);

ALTER TABLE TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA ALTER COLUMN ID_TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA SET CACHE 100;
ALTER TABLE TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA DROP PRIMARY KEY;
ALTER TABLE TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA ADD CONSTRAINT PK_TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA PRIMARY KEY (ID_TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA);
CREATE UNIQUE INDEX IX_TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA_01 ON TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA (ID_TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA);
ALTER TABLE TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA ADD CONSTRAINT FK_TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA_02 ON TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA (ID_TAREA);
ALTER TABLE TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA ADD CONSTRAINT FK_TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);
CREATE INDEX IX_TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA_03 ON TAREA_LOCALIZACION_PERSONA_SECCION_PRESENCIA (ID_TIPO_DATO);

ALTER TABLE TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION ALTER COLUMN ID_TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION SET CACHE 100;
ALTER TABLE TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION DROP PRIMARY KEY;
ALTER TABLE TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION ADD CONSTRAINT PK_TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION PRIMARY KEY (ID_TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION);
CREATE UNIQUE INDEX IX_TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION_01 ON TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION (ID_TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION);
ALTER TABLE TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION ADD CONSTRAINT FK_TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION_02 ON TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION (ID_TAREA);
ALTER TABLE TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION ADD CONSTRAINT FK_TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);
CREATE INDEX IX_TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION_03 ON TAREA_LOCALIZACION_PERSONA_PRESENCIA_SECCION (ID_TIPO_DATO);

ALTER TABLE TAREA_LOCALIZACION_PERSONA_PRESENCIA ALTER COLUMN ID_TAREA_LOCALIZACION_PERSONA_PRESENCIA SET CACHE 100;
ALTER TABLE TAREA_LOCALIZACION_PERSONA_PRESENCIA DROP PRIMARY KEY;
ALTER TABLE TAREA_LOCALIZACION_PERSONA_PRESENCIA ADD CONSTRAINT PK_TAREA_LOCALIZACION_PERSONA_PRESENCIA PRIMARY KEY (ID_TAREA_LOCALIZACION_PERSONA_PRESENCIA);
CREATE UNIQUE INDEX IX_TAREA_LOCALIZACION_PERSONA_PRESENCIA_01 ON TAREA_LOCALIZACION_PERSONA_PRESENCIA (ID_TAREA_LOCALIZACION_PERSONA_PRESENCIA);
ALTER TABLE TAREA_LOCALIZACION_PERSONA_PRESENCIA ADD CONSTRAINT FK_TAREA_LOCALIZACION_PERSONA_PRESENCIA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_PERSONA_PRESENCIA_02 ON TAREA_LOCALIZACION_PERSONA_PRESENCIA (ID_TAREA);
ALTER TABLE TAREA_LOCALIZACION_PERSONA_PRESENCIA ADD CONSTRAINT FK_TAREA_LOCALIZACION_PERSONA_PRESENCIA_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);
CREATE INDEX IX_TAREA_LOCALIZACION_PERSONA_PRESENCIA_03 ON TAREA_LOCALIZACION_PERSONA_PRESENCIA (ID_TIPO_DATO);

ALTER TABLE TAREA_LOCALIZACION_HISTORICO ALTER COLUMN ID_TAREA_LOCALIZACION_HISTORICO SET CACHE 100;
ALTER TABLE TAREA_LOCALIZACION_HISTORICO DROP PRIMARY KEY;
ALTER TABLE TAREA_LOCALIZACION_HISTORICO ADD CONSTRAINT PK_TAREA_LOCALIZACION_HISTORICO PRIMARY KEY (ID_TAREA_LOCALIZACION_HISTORICO);
CREATE UNIQUE INDEX IX_TAREA_LOCALIZACION_HISTORICO_01 ON TAREA_LOCALIZACION_HISTORICO (ID_TAREA_LOCALIZACION_HISTORICO);
ALTER TABLE TAREA_LOCALIZACION_HISTORICO ADD CONSTRAINT FK_TAREA_LOCALIZACION_HISTORICO_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_HISTORICO_02 ON TAREA_LOCALIZACION_HISTORICO (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_HISTORICO_03 ON TAREA_LOCALIZACION_HISTORICO (STD_ID_WORK_LOCAT);
CREATE INDEX IX_TAREA_LOCALIZACION_HISTORICO_04 ON TAREA_LOCALIZACION_HISTORICO (FECHA_INICIO);
CREATE INDEX IX_TAREA_LOCALIZACION_HISTORICO_05 ON TAREA_LOCALIZACION_HISTORICO (FECHA_FIN);
CREATE INDEX IX_TAREA_LOCALIZACION_HISTORICO_06 ON TAREA_LOCALIZACION_HISTORICO (ID_TAREA, STD_ID_WORK_LOCAT, FECHA_INICIO, FECHA_FIN);
CREATE INDEX IX_TAREA_LOCALIZACION_HISTORICO_07 ON TAREA_LOCALIZACION_HISTORICO (CCL_ID_COD_ORIGEN);
CREATE INDEX IX_TAREA_LOCALIZACION_HISTORICO_08 ON TAREA_LOCALIZACION_HISTORICO (ID_TAREA, CCL_ID_COD_ORIGEN, FECHA_INICIO, FECHA_FIN);

ALTER TABLE TAREA_LOCALIZACION_PRESENCIA_SECCION ALTER COLUMN ID_TAREA_LOCALIZACION_PRESENCIA_SECCION SET CACHE 100;
ALTER TABLE TAREA_LOCALIZACION_PRESENCIA_SECCION DROP PRIMARY KEY;
ALTER TABLE TAREA_LOCALIZACION_PRESENCIA_SECCION ADD CONSTRAINT PK_TAREA_LOCALIZACION_PRESENCIA_SECCION PRIMARY KEY (ID_TAREA_LOCALIZACION_PRESENCIA_SECCION);
CREATE UNIQUE INDEX IX_TAREA_LOCALIZACION_PRESENCIA_SECCION_01 ON TAREA_LOCALIZACION_PRESENCIA_SECCION (ID_TAREA_LOCALIZACION_PRESENCIA_SECCION);
ALTER TABLE TAREA_LOCALIZACION_PRESENCIA_SECCION ADD CONSTRAINT FK_TAREA_LOCALIZACION_PRESENCIA_SECCION_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_PRESENCIA_SECCION_02 ON TAREA_LOCALIZACION_PRESENCIA_SECCION (ID_TAREA);
ALTER TABLE TAREA_LOCALIZACION_PRESENCIA_SECCION ADD CONSTRAINT FK_TAREA_LOCALIZACION_PRESENCIA_SECCION_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);
CREATE INDEX IX_TAREA_LOCALIZACION_PRESENCIA_SECCION_03 ON TAREA_LOCALIZACION_PRESENCIA_SECCION (ID_TIPO_DATO);
CREATE INDEX IX_TAREA_LOCALIZACION_PRESENCIA_SECCION_04 ON TAREA_LOCALIZACION_PRESENCIA_SECCION (ID_LOCALIZACION);
CREATE INDEX IX_TAREA_LOCALIZACION_PRESENCIA_SECCION_05 ON TAREA_LOCALIZACION_PRESENCIA_SECCION (FECHA);
CREATE INDEX IX_TAREA_LOCALIZACION_PRESENCIA_SECCION_06 ON TAREA_LOCALIZACION_PRESENCIA_SECCION (ID_TAREA, ID_LOCALIZACION, FECHA);

ALTER TABLE TAREA_LOCALIZACION_PRESENCIA ALTER COLUMN ID_TAREA_LOCALIZACION_PRESENCIA SET CACHE 100;
ALTER TABLE TAREA_LOCALIZACION_PRESENCIA DROP PRIMARY KEY;
ALTER TABLE TAREA_LOCALIZACION_PRESENCIA ADD CONSTRAINT ID_TAREA_LOCALIZACION_PRESENCIA PRIMARY KEY (ID_TAREA_LOCALIZACION_PRESENCIA);
CREATE UNIQUE INDEX IX_TAREA_LOCALIZACION_PRESENCIA_01 ON TAREA_LOCALIZACION_PRESENCIA (ID_TAREA_LOCALIZACION_PRESENCIA);
ALTER TABLE TAREA_LOCALIZACION_PRESENCIA ADD CONSTRAINT FK_ID_TAREA_LOCALIZACION_PRESENCIA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_PRESENCIA_02 ON TAREA_LOCALIZACION_PRESENCIA (ID_TAREA);
ALTER TABLE TAREA_LOCALIZACION_PRESENCIA ADD CONSTRAINT FK_TAREA_LOCALIZACION_PRESENCIA_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);
CREATE INDEX IX_TAREA_LOCALIZACION_PRESENCIA_03 ON TAREA_LOCALIZACION_PRESENCIA (ID_TIPO_DATO);
CREATE INDEX IX_TAREA_LOCALIZACION_PRESENCIA_04 ON TAREA_LOCALIZACION_PRESENCIA (ID_LOCALIZACION);
CREATE INDEX IX_TAREA_LOCALIZACION_PRESENCIA_05 ON TAREA_LOCALIZACION_PRESENCIA (FECHA);
CREATE INDEX IX_TAREA_LOCALIZACION_PRESENCIA_06 ON TAREA_LOCALIZACION_PRESENCIA (ID_TAREA, ID_LOCALIZACION, FECHA);

ALTER TABLE TAREA_LOCALIZACION_VENTA ALTER COLUMN ID_TAREA_LOCALIZACION_VENTA SET CACHE 100;
ALTER TABLE TAREA_LOCALIZACION_VENTA DROP PRIMARY KEY;
ALTER TABLE TAREA_LOCALIZACION_VENTA ADD CONSTRAINT PK_TAREA_LOCALIZACION_VENTA PRIMARY KEY (ID_TAREA_LOCALIZACION_VENTA);
CREATE UNIQUE INDEX IX_TAREA_LOCALIZACION_VENTA_01 ON TAREA_LOCALIZACION_VENTA (ID_TAREA_LOCALIZACION_VENTA);
ALTER TABLE TAREA_LOCALIZACION_VENTA ADD CONSTRAINT FK_TAREA_LOCALIZACION_VENTA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_VENTA_02 ON TAREA_LOCALIZACION_VENTA (ID_TAREA);
ALTER TABLE TAREA_LOCALIZACION_VENTA ADD CONSTRAINT FK_TAREA_LOCALIZACION_VENTA_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);

ALTER TABLE TAREA_CADENA_VENTA ALTER COLUMN ID_TAREA_CADENA_VENTA SET CACHE 100;
ALTER TABLE TAREA_CADENA_VENTA DROP PRIMARY KEY;
ALTER TABLE TAREA_CADENA_VENTA ADD CONSTRAINT PK_TAREA_CADENA_VENTA PRIMARY KEY (ID_TAREA_CADENA_VENTA);
CREATE UNIQUE INDEX IX_TAREA_CADENA_VENTA_01 ON TAREA_CADENA_VENTA (ID_TAREA_CADENA_VENTA);
ALTER TABLE TAREA_CADENA_VENTA ADD CONSTRAINT FK_TAREA_CADENA_VENTA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_CADENA_VENTA_02 ON TAREA_CADENA_VENTA (ID_TAREA);
ALTER TABLE TAREA_CADENA_VENTA ADD CONSTRAINT FK_TAREA_CADENA_VENTA_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);

ALTER TABLE TAREA_CADENA_VENTA_SECCION ALTER COLUMN ID_TAREA_CADENA_VENTA_SECCION SET CACHE 100;
ALTER TABLE TAREA_CADENA_VENTA_SECCION DROP PRIMARY KEY;
ALTER TABLE TAREA_CADENA_VENTA_SECCION ADD CONSTRAINT PK_TAREA_CADENA_VENTA_SECCION PRIMARY KEY (ID_TAREA_CADENA_VENTA_SECCION);
CREATE UNIQUE INDEX IX_TAREA_CADENA_VENTA_SECCION_01 ON TAREA_CADENA_VENTA_SECCION (ID_TAREA_CADENA_VENTA_SECCION);
ALTER TABLE TAREA_CADENA_VENTA_SECCION ADD CONSTRAINT FK_TAREA_CADENA_VENTA_SECCION_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_CADENA_VENTA_SECCION_02 ON TAREA_CADENA_VENTA_SECCION (ID_TAREA);
ALTER TABLE TAREA_CADENA_VENTA_SECCION ADD CONSTRAINT FK_TAREA_CADENA_VENTA_SECCION_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);

ALTER TABLE TAREA_AGRUPACION_CADENA ALTER COLUMN ID_TAREA_AGRUPACION_CADENA SET CACHE 100;
ALTER TABLE TAREA_AGRUPACION_CADENA DROP PRIMARY KEY;
ALTER TABLE TAREA_AGRUPACION_CADENA ADD CONSTRAINT PK_TAREA_AGRUPACION_CADENA PRIMARY KEY (ID_TAREA_AGRUPACION_CADENA);
CREATE UNIQUE INDEX IX_TAREA_AGRUPACION_CADENA_01 ON TAREA_AGRUPACION_CADENA (ID_TAREA_AGRUPACION_CADENA);
ALTER TABLE TAREA_AGRUPACION_CADENA ADD CONSTRAINT FK_TAREA_AGRUPACION_CADENA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_AGRUPACION_CADENA_02 ON TAREA_AGRUPACION_CADENA (ID_TAREA);

ALTER TABLE TAREA_AGRUPACION_CADENA_VENTA ALTER COLUMN ID_TAREA_AGRUPACION_CADENA_VENTA SET CACHE 100;
ALTER TABLE TAREA_AGRUPACION_CADENA_VENTA DROP PRIMARY KEY;
ALTER TABLE TAREA_AGRUPACION_CADENA_VENTA ADD CONSTRAINT PK_TAREA_AGRUPACION_CADENA_VENTA PRIMARY KEY (ID_TAREA_AGRUPACION_CADENA_VENTA);
CREATE UNIQUE INDEX IX_TAREA_AGRUPACION_CADENA_VENTA_01 ON TAREA_AGRUPACION_CADENA_VENTA (ID_TAREA_AGRUPACION_CADENA_VENTA);
ALTER TABLE TAREA_AGRUPACION_CADENA_VENTA ADD CONSTRAINT FK_TAREA_AGRUPACION_CADENA_VENTA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_AGRUPACION_CADENA_VENTA_02 ON TAREA_AGRUPACION_CADENA_VENTA (ID_TAREA);
ALTER TABLE TAREA_AGRUPACION_CADENA_VENTA ADD CONSTRAINT FK_TAREA_AGRUPACION_CADENA_VENTA_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);

ALTER TABLE TAREA_AGRUPACION_CADENA_VENTA_SECCION ALTER COLUMN ID_TAREA_AGRUPACION_CADENA_VENTA_SECCION SET CACHE 100;
ALTER TABLE TAREA_AGRUPACION_CADENA_VENTA_SECCION DROP PRIMARY KEY;
ALTER TABLE TAREA_AGRUPACION_CADENA_VENTA_SECCION ADD CONSTRAINT PK_TAREA_AGRUPACION_CADENA_VENTA_SECCION PRIMARY KEY (ID_TAREA_AGRUPACION_CADENA_VENTA_SECCION);
CREATE UNIQUE INDEX IX_TAREA_AGRUPACION_CADENA_VENTA_SECCION_01 ON TAREA_AGRUPACION_CADENA_VENTA_SECCION (ID_TAREA_AGRUPACION_CADENA_VENTA_SECCION);
ALTER TABLE TAREA_AGRUPACION_CADENA_VENTA_SECCION ADD CONSTRAINT FK_TAREA_AGRUPACION_CADENA_VENTA_SECCION_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_AGRUPACION_CADENA_VENTA_SECCION_02 ON TAREA_AGRUPACION_CADENA_VENTA_SECCION (ID_TAREA);
ALTER TABLE TAREA_AGRUPACION_CADENA_VENTA_SECCION ADD CONSTRAINT FK_TAREA_AGRUPACION_CADENA_VENTA_SECCION_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);

ALTER TABLE TAREA_LOCALIZACION_PERSONA_VENTA ALTER COLUMN ID_TAREA_LOCALIZACION_PERSONA_VENTA SET CACHE 100;
ALTER TABLE TAREA_LOCALIZACION_PERSONA_VENTA DROP PRIMARY KEY;
ALTER TABLE TAREA_LOCALIZACION_PERSONA_VENTA ADD CONSTRAINT TAREA_LOCALIZACION_PERSONA_VENTA PRIMARY KEY (ID_TAREA_LOCALIZACION_PERSONA_VENTA);
CREATE UNIQUE INDEX IX_TAREA_LOCALIZACION_PERSONA_VENTA_01 ON TAREA_LOCALIZACION_PERSONA_VENTA (ID_TAREA_LOCALIZACION_PERSONA_VENTA);
ALTER TABLE TAREA_LOCALIZACION_PERSONA_VENTA ADD CONSTRAINT FK_TAREA_LOCALIZACION_PERSONA_VENTA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_PERSONA_VENTA_02 ON TAREA_LOCALIZACION_PERSONA_VENTA (ID_TAREA);
ALTER TABLE TAREA_LOCALIZACION_PERSONA_VENTA ADD CONSTRAINT FK_TAREA_LOCALIZACION_PERSONA_VENTA_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);

ALTER TABLE TAREA_OPERACION_LOCALIZACION_VENTA ALTER COLUMN ID_TAREA_OPERACION_LOCALIZACION_VENTA SET CACHE 100;
ALTER TABLE TAREA_OPERACION_LOCALIZACION_VENTA DROP PRIMARY KEY;
ALTER TABLE TAREA_OPERACION_LOCALIZACION_VENTA ADD CONSTRAINT PK_TAREA_OPERACION_LOCALIZACION_VENTA PRIMARY KEY (ID_TAREA_OPERACION_LOCALIZACION_VENTA);
CREATE UNIQUE INDEX IX_TAREA_OPERACION_LOCALIZACION_VENTA_01 ON TAREA_OPERACION_LOCALIZACION_VENTA (ID_TAREA_OPERACION_LOCALIZACION_VENTA);
ALTER TABLE TAREA_OPERACION_LOCALIZACION_VENTA ADD CONSTRAINT FK_TAREA_OPERACION_LOCALIZACION_VENTA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
ALTER TABLE TAREA_OPERACION_LOCALIZACION_VENTA ADD CONSTRAINT FK_TAREA_OPERACION_LOCALIZACION_VENTA_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);

ALTER TABLE TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA ALTER COLUMN ID_TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA SET CACHE 100;
ALTER TABLE TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA DROP PRIMARY KEY;
ALTER TABLE TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA ADD CONSTRAINT PK_TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA PRIMARY KEY (ID_TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA);
CREATE UNIQUE INDEX IX_TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA_01 ON TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA (ID_TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA);
ALTER TABLE TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA ADD CONSTRAINT FK_TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA_02 ON TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA (ID_TAREA);
ALTER TABLE TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA ADD CONSTRAINT FK_TAREA_OPERACION_PERSONA_LOCALIZACION_VENTA_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);

ALTER TABLE TAREA_LOCALIZACION_VENTA_SECCION ALTER COLUMN ID_TAREA_LOCALIZACION_VENTA_SECCION SET CACHE 100;
ALTER TABLE TAREA_LOCALIZACION_VENTA_SECCION DROP PRIMARY KEY;
ALTER TABLE TAREA_LOCALIZACION_VENTA_SECCION ADD CONSTRAINT PK_TAREA_LOCALIZACION_VENTA_SECCION PRIMARY KEY (ID_TAREA_LOCALIZACION_VENTA_SECCION);
CREATE UNIQUE INDEX IX_TAREA_LOCALIZACION_VENTA_SECCION_01 ON TAREA_LOCALIZACION_VENTA_SECCION (ID_TAREA_LOCALIZACION_VENTA_SECCION);
ALTER TABLE TAREA_LOCALIZACION_VENTA_SECCION ADD CONSTRAINT FK_TAREA_LOCALIZACION_VENTA_SECCION_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA;
CREATE INDEX IX_TAREA_LOCALIZACION_VENTA_SECCION_02 ON TAREA_LOCALIZACION_VENTA_SECCION (ID_TAREA);
ALTER TABLE TAREA_LOCALIZACION_VENTA_SECCION ADD CONSTRAINT FK_TAREA_LOCALIZACION_VENTA_SECCION_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);
CREATE INDEX IX_TAREA_LOCALIZACION_VENTA_SECCION_03 ON TAREA_LOCALIZACION_VENTA_SECCION (ID_TIPO_DATO);
CREATE INDEX IX_TAREA_LOCALIZACION_VENTA_SECCION_04 ON TAREA_LOCALIZACION_VENTA_SECCION (ID_LOCALIZACION);
CREATE INDEX IX_TAREA_LOCALIZACION_VENTA_SECCION_05 ON TAREA_LOCALIZACION_VENTA_SECCION (FECHA);
CREATE INDEX IX_TAREA_LOCALIZACION_VENTA_SECCION_06 ON TAREA_LOCALIZACION_VENTA_SECCION (ID_TAREA, ID_LOCALIZACION, FECHA, ID_TIPO_DATO);

ALTER TABLE TAREA_TIPO_HORA ALTER COLUMN ID_TAREA_TIPO_HORA SET CACHE 100;
ALTER TABLE TAREA_TIPO_HORA DROP PRIMARY KEY;
ALTER TABLE TAREA_TIPO_HORA ADD CONSTRAINT PK_TAREA_TIPO_HORA PRIMARY KEY (ID_TAREA_TIPO_HORA);
CREATE UNIQUE INDEX IX_TAREA_TIPO_HORA_01 ON TAREA_TIPO_HORA (ID_TAREA_TIPO_HORA);
ALTER TABLE TAREA_TIPO_HORA ADD CONSTRAINT FK_TAREA_TIPO_HORA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_TIPO_HORA_02 ON TAREA_TIPO_HORA (ID_TAREA);
CREATE INDEX IX_TAREA_TIPO_HORA_03 ON TAREA_TIPO_HORA (ID_TAREA, ID_TAREA_TIPO_HORA);
CREATE INDEX IX_TAREA_TIPO_HORA_04 ON TAREA_TIPO_HORA (ID_TAREA, ID_TAREA_TIPO_HORA, EXCLUIDO_CALCULO);

ALTER TABLE TAREA_LOCALIZACION_ABIERTA ALTER COLUMN ID_TAREA_LOCALIZACION_ABIERTA SET CACHE 100;
ALTER TABLE TAREA_LOCALIZACION_ABIERTA DROP PRIMARY KEY;
ALTER TABLE TAREA_LOCALIZACION_ABIERTA ADD CONSTRAINT PK_TAREA_LOCALIZACION_ABIERTA PRIMARY KEY (ID_TAREA_LOCALIZACION_ABIERTA);
CREATE UNIQUE INDEX IX_TAREA_LOCALIZACION_ABIERTA_01 ON TAREA_LOCALIZACION_ABIERTA (ID_TAREA_LOCALIZACION_ABIERTA);
ALTER TABLE TAREA_LOCALIZACION_ABIERTA ADD CONSTRAINT FK_TAREA_LOCALIZACION_ABIERTA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_LOCALIZACION_ABIERTA_02 ON TAREA_LOCALIZACION_ABIERTA (ID_TAREA);


ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA ALTER COLUMN ID_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA SET CACHE 100;
ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA DROP PRIMARY KEY;
ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA ADD CONSTRAINT PK_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA PRIMARY KEY (ID_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA);
CREATE UNIQUE INDEX IX_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_01 ON TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA (ID_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA);
ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA ADD CONSTRAINT FK_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_02 ON TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA (ID_TAREA);

ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_MANUAL ALTER COLUMN ID_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_MANUAL SET CACHE 100;
ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_MANUAL DROP PRIMARY KEY;
ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_MANUAL ADD CONSTRAINT PK_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_MANUAL PRIMARY KEY (ID_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_MANUAL);
CREATE UNIQUE INDEX IX_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_MANUAL_01 ON TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_MANUAL (ID_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_MANUAL);
ALTER TABLE TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_MANUAL ADD CONSTRAINT FK_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_MANUAL_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);
CREATE INDEX IX_TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_MANUAL_02 ON TAREA_AMBITO_GLOBAL_LOCALIZACION_PERSONA_PRESENCIA_MANUAL (ID_TAREA);

/***************/
/**  PERIODO  **/
/***************/

ALTER TABLE ESTADO_PERIODO_CALCULO_PERSONA DROP PRIMARY KEY;
ALTER TABLE ESTADO_PERIODO_CALCULO_PERSONA ADD CONSTRAINT PK_ESTADO_PERIODO_CALCULO_PERSONA PRIMARY KEY (ID_ESTADO_PERIODO_CALCULO_PERSONA);
CREATE INDEX IX_ESTADO_PERIODO_CALCULO_PERSONA_01 ON ESTADO_PERIODO_CALCULO_PERSONA (ID_ESTADO_PERIODO_CALCULO_PERSONA);

ALTER TABLE PERIODO_PERSONA DROP PRIMARY KEY;
ALTER TABLE PERIODO_PERSONA ADD CONSTRAINT PK_PERIODO_PERSONA PRIMARY KEY (ID_PERIODO, ID_ORIGEN, ID_EMPRESA, ID_PERSONA);
CREATE UNIQUE INDEX IX_PERIODO_PERSONA_01 ON PERIODO_PERSONA (ID_PERIODO, ID_ORIGEN, ID_EMPRESA, ID_PERSONA);

ALTER TABLE PERIODO_LOCALIZACION DROP PRIMARY KEY;
ALTER TABLE PERIODO_LOCALIZACION ADD CONSTRAINT PK_PERIODO_LOCALIZACION PRIMARY KEY (ID_PERIODO, ID_ORIGEN, ID_EMPRESA, ID_LOCALIZACION);
CREATE UNIQUE INDEX IX_PERIODO_LOCALIZACION_01 ON PERIODO_LOCALIZACION (ID_PERIODO, ID_ORIGEN, ID_EMPRESA, ID_LOCALIZACION);

ALTER TABLE PERIODO_LOCALIZACION_PERSONA DROP PRIMARY KEY;
ALTER TABLE PERIODO_LOCALIZACION_PERSONA ADD CONSTRAINT PK_PERIODO_LOCALIZACION_PERSONA PRIMARY KEY (ID_PERIODO, ID_ORIGEN, ID_EMPRESA, ID_PERSONA, ID_LOCALIZACION);
CREATE UNIQUE INDEX IX_PERIODO_LOCALIZACION_PERSONA_01 ON PERIODO_LOCALIZACION_PERSONA (ID_PERIODO, ID_ORIGEN, ID_EMPRESA, ID_PERSONA, ID_LOCALIZACION);

ALTER TABLE PERIODO_CALCULO_PERSONA DROP PRIMARY KEY;
ALTER TABLE PERIODO_CALCULO_PERSONA ADD CONSTRAINT PK_PERIODO_CALCULO_PERSONA PRIMARY KEY (ID_PERIODO, ID_ORIGEN, ID_EMPRESA, ID_PERSONA, OR_PERSONA);
CREATE UNIQUE INDEX IX_PERIODO_CALCULO_PERSONA_01 ON PERIODO_CALCULO_PERSONA (ID_PERIODO, ID_ORIGEN, ID_EMPRESA, ID_PERSONA, OR_PERSONA);
ALTER TABLE PERIODO_CALCULO_PERSONA ADD CONSTRAINT FK_PERIODO_CALCULO_PERSONA_ESTADO_PERIODO_CALCULO_PERSONA FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_PERIODO_CALCULO_PERSONA (ID_ESTADO_PERIODO_CALCULO_PERSONA);

/***************/
/** ALGORITMO **/
/***************/
ALTER TABLE TIPO_CALCULO DROP PRIMARY KEY;
ALTER TABLE TIPO_CALCULO ADD CONSTRAINT PK_TIPO_CALCULO PRIMARY KEY (ID_TIPO_CALCULO);
CREATE UNIQUE INDEX IX_TIPO_CALCULO_01 ON TIPO_CALCULO (ID_TIPO_CALCULO);

ALTER TABLE TIPO_COMISION DROP PRIMARY KEY;
ALTER TABLE TIPO_COMISION ADD CONSTRAINT PK_TIPO_COMISION PRIMARY KEY (ID_TIPO_COMISION);
CREATE UNIQUE INDEX IX_TIPO_COMISION_01 ON TIPO_COMISION (ID_TIPO_COMISION);

ALTER TABLE ALGORITMO DROP PRIMARY KEY;
ALTER TABLE ALGORITMO ADD CONSTRAINT PK_ALGORITMO PRIMARY KEY (ID_ALGORITMO);
CREATE UNIQUE INDEX IX_ALGORITMO_01 ON ALGORITMO (ID_ALGORITMO);
CREATE UNIQUE INDEX IX_ALGORITMO_02 ON ALGORITMO (NOMBRE);
ALTER TABLE TAREA_CALCULO ADD CONSTRAINT FK_TAREA_CALCULO_ALGORITMO FOREIGN KEY (ID_ALGORITMO) REFERENCES ALGORITMO (ID_ALGORITMO);
ALTER TABLE ALGORITMO_TIPO_CALCULO ADD CONSTRAINT FK_ALGORITMO_TIPO_CALCULO_ALGORITMO FOREIGN KEY (ID_ALGORITMO) REFERENCES ALGORITMO (ID_ALGORITMO);
ALTER TABLE ALGORITMO_TIPO_COMISION ADD CONSTRAINT FK_ALGORITMO_TIPO_COMISION_ALGORITMO FOREIGN KEY (ID_ALGORITMO) REFERENCES ALGORITMO (ID_ALGORITMO);
ALTER TABLE ALGORITMO_TIPO_DATO ADD CONSTRAINT FK_ALGORITMO_TIPO_DATO_ALGORITMO FOREIGN KEY (ID_ALGORITMO) REFERENCES ALGORITMO (ID_ALGORITMO);
ALTER TABLE ALGORITMO_TIPO_CALCULO ADD CONSTRAINT FK_ALGORITMO_TIPO_CALCULO_TIPO_CALCULO FOREIGN KEY (ID_TIPO_CALCULO) REFERENCES TIPO_CALCULO (ID_TIPO_CALCULO);
ALTER TABLE ALGORITMO_TIPO_COMISION ADD CONSTRAINT FK_ALGORITMO_TIPO_COMISION_TIPO_COMISION FOREIGN KEY (ID_TIPO_COMISION) REFERENCES TIPO_COMISION (ID_TIPO_COMISION);
ALTER TABLE ALGORITMO_TIPO_DATO ADD CONSTRAINT FK_ALGORITMO_TIPO_CALCULO_TIPO_DATO FOREIGN KEY (ID_TIPO_DATO) REFERENCES TIPO_DATO (ID_TIPO_DATO);

