/******************/
/** PROGRAMACION **/
/******************/
ALTER TABLE PROGRAMACION ALTER COLUMN ID_PROGRAMACION SET CACHE 100;
ALTER TABLE PROGRAMACION DROP PRIMARY KEY;
ALTER TABLE PROGRAMACION ADD CONSTRAINT PK_PROGRAMACION PRIMARY KEY (ID_PROGRAMACION);
CREATE UNIQUE INDEX IX_PROGRAMACION_01 ON PROGRAMACION (ID_PROGRAMACION);

ALTER TABLE PROGRAMACION_AMBITO ALTER COLUMN ID_PROGRAMACION_AMBITO SET CACHE 100;
ALTER TABLE PROGRAMACION_AMBITO DROP PRIMARY KEY;
ALTER TABLE PROGRAMACION_AMBITO ADD CONSTRAINT PK_PROGRAMACION_AMBITO PRIMARY KEY (ID_PROGRAMACION_AMBITO);
CREATE UNIQUE INDEX IX_PROGRAMACION_AMBITO_01 ON PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO);
ALTER TABLE PROGRAMACION_AMBITO ADD CONSTRAINT FK_PROGRAMACION_AMBITO_PROGRAMACION FOREIGN KEY (ID_PROGRAMACION) REFERENCES PROGRAMACION (ID_PROGRAMACION);

ALTER TABLE PROGRAMACION_AMBITO_EMPRESA ALTER COLUMN PROGRAMACION_AMBITO_EMPRESA SET CACHE 100;
ALTER TABLE PROGRAMACION_AMBITO_EMPRESA DROP PRIMARY KEY;
ALTER TABLE PROGRAMACION_AMBITO_EMPRESA ADD CONSTRAINT PK_PROGRAMACION_AMBITO_EMPRESA PRIMARY KEY (ID_PROGRAMACION_AMBITO_EMPRESA);
CREATE UNIQUE INDEX IX_PROGRAMACION_AMBITO_EMPRESA_01 ON PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO_EMPRESA);
ALTER TABLE PROGRAMACION_AMBITO_EMPRESA ADD CONSTRAINT FK_PROGRAMACION_AMBITO_EMPRESA_PROGRAMACION_AMBITO FOREIGN KEY (ID_PROGRAMACION_AMBITO) REFERENCES PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO);

ALTER TABLE PROGRAMACION_AMBITO_LOCALIZACION ALTER COLUMN PROGRAMACION_AMBITO_LOCALIZACION SET CACHE 100;
ALTER TABLE PROGRAMACION_AMBITO_LOCALIZACION DROP PRIMARY KEY;
ALTER TABLE PROGRAMACION_AMBITO_LOCALIZACION ADD CONSTRAINT PK_PROGRAMACION_AMBITO_LOCALIZACION PRIMARY KEY (ID_PROGRAMACION_AMBITO_LOCALIZACION);
CREATE UNIQUE INDEX IX_PROGRAMACION_AMBITO_LOCALIZACION_01 ON PROGRAMACION_AMBITO_LOCALIZACION (ID_PROGRAMACION_AMBITO_LOCALIZACION);
ALTER TABLE PROGRAMACION_AMBITO_LOCALIZACION ADD CONSTRAINT FK_PROGRAMACION_AMBITO_LOCALIZACION_PROGRAMACION_AMBITO FOREIGN KEY (ID_PROGRAMACION_AMBITO) REFERENCES PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO);

ALTER TABLE PROGRAMACION_AMBITO_ORIGEN ALTER COLUMN PROGRAMACION_AMBITO_ORIGEN SET CACHE 100;
ALTER TABLE PROGRAMACION_AMBITO_ORIGEN DROP PRIMARY KEY;
ALTER TABLE PROGRAMACION_AMBITO_ORIGEN ADD CONSTRAINT PK_PROGRAMACION_AMBITO_ORIGEN PRIMARY KEY (ID_PROGRAMACION_AMBITO_ORIGEN);
CREATE UNIQUE INDEX IX_PROGRAMACION_AMBITO_ORIGEN_01 ON PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO_ORIGEN);
ALTER TABLE PROGRAMACION_AMBITO_ORIGEN ADD CONSTRAINT FK_PROGRAMACION_AMBITO_ORIGEN_PROGRAMACION_AMBITO FOREIGN KEY (ID_PROGRAMACION_AMBITO) REFERENCES PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO);

ALTER TABLE PROGRAMACION_AMBITO_PERSONA ALTER COLUMN PROGRAMACION_AMBITO_PERSONA SET CACHE 100;
ALTER TABLE PROGRAMACION_AMBITO_PERSONA DROP PRIMARY KEY;
ALTER TABLE PROGRAMACION_AMBITO_PERSONA ADD CONSTRAINT PK_PROGRAMACION_AMBITO_PERSONA PRIMARY KEY (ID_PROGRAMACION_AMBITO_PERSONA);
CREATE UNIQUE INDEX IX_PROGRAMACION_AMBITO_PERSONA_01 ON PROGRAMACION_AMBITO_PERSONA (ID_PROGRAMACION_AMBITO_PERSONA);
ALTER TABLE PROGRAMACION_AMBITO_PERSONA ADD CONSTRAINT FK_PROGRAMACION_AMBITO_PERSONA_PROGRAMACION_AMBITO FOREIGN KEY (ID_PROGRAMACION_AMBITO) REFERENCES PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO);

/*************/
/** TRABAJO **/
/*************/
ALTER TABLE TRABAJO ALTER COLUMN ID_TRABAJO SET CACHE 100;
ALTER TABLE TRABAJO DROP PRIMARY KEY;
ALTER TABLE TRABAJO ADD CONSTRAINT PK_TRABAJO PRIMARY KEY (ID_TRABAJO);
CREATE UNIQUE INDEX IX_TRABAJO_01 ON TRABAJO (ID_TRABAJO);
ALTER TABLE PROGRAMACION_TRABAJO ADD CONSTRAINT FK_PROGRAMACION_TRABAJO_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES TRABAJO (ID_TRABAJO);

ALTER TABLE TRABAJO_AMBITO_EMPRESA ALTER COLUMN ID_TRABAJO_AMBITO_EMPRESA SET CACHE 100;
ALTER TABLE TRABAJO_AMBITO_EMPRESA DROP PRIMARY KEY;
ALTER TABLE TRABAJO_AMBITO_EMPRESA ADD CONSTRAINT PK_TRABAJO_AMBITO_EMPRESA PRIMARY KEY (ID_TRABAJO_AMBITO_EMPRESA);
CREATE UNIQUE INDEX IX_TRABAJO_AMBITO_EMPRESA_01 ON PROCESO_CALCULO (ID_PROCESO_CALCULO);
ALTER TABLE TRABAJO_AMBITO_EMPRESA ADD CONSTRAINT FK_TRABAJO_AMBITO_EMPRESA_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES TRABAJO (ID_TRABAJO);

ALTER TABLE TRABAJO_AMBITO_LOCALIZACION ALTER COLUMN ID_TRABAJO_AMBITO_LOCALIZACION SET CACHE 100;
ALTER TABLE TRABAJO_AMBITO_LOCALIZACION DROP PRIMARY KEY;
ALTER TABLE TRABAJO_AMBITO_LOCALIZACION ADD CONSTRAINT PK_TRABAJO_AMBITO_LOCALIZACION PRIMARY KEY (ID_TRABAJO_AMBITO_LOCALIZACION);
CREATE UNIQUE INDEX IX_TRABAJO_AMBITO_LOCALIZACION_01 ON PROCESO_CALCULO (ID_PROCESO_CALCULO);
ALTER TABLE TRABAJO_AMBITO_LOCALIZACION ADD CONSTRAINT FK_TRABAJO_AMBITO_LOCALIZACION_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES TRABAJO (ID_TRABAJO);

ALTER TABLE TRABAJO_AMBITO_ORIGEN ALTER COLUMN ID_TRABAJO_AMBITO_ORIGEN SET CACHE 100;
ALTER TABLE TRABAJO_AMBITO_ORIGEN DROP PRIMARY KEY;
ALTER TABLE TRABAJO_AMBITO_ORIGEN ADD CONSTRAINT PK_TRABAJO_AMBITO_ORIGEN PRIMARY KEY (ID_TRABAJO_AMBITO_ORIGEN);
CREATE UNIQUE INDEX IX_TRABAJO_AMBITO_ORIGEN_01 ON PROCESO_CALCULO (ID_PROCESO_CALCULO);
ALTER TABLE TRABAJO_AMBITO_ORIGEN ADD CONSTRAINT FK_TRABAJO_AMBITO_ORIGEN_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES TRABAJO (ID_TRABAJO);

ALTER TABLE TRABAJO_AMBITO_PERSONA ALTER COLUMN ID_TRABAJO_AMBITO_PERSONA SET CACHE 100;
ALTER TABLE TRABAJO_AMBITO_PERSONA DROP PRIMARY KEY;
ALTER TABLE TRABAJO_AMBITO_PERSONA ADD CONSTRAINT PK_TRABAJO_AMBITO_PERSONA PRIMARY KEY (ID_TRABAJO_AMBITO_PERSONA);
CREATE UNIQUE INDEX IX_TRABAJO_AMBITO_PERSONA_01 ON PROCESO_CALCULO (ID_PROCESO_CALCULO);
ALTER TABLE TRABAJO_AMBITO_PERSONA ADD CONSTRAINT FK_TRABAJO_AMBITO_PERSONA_TRABAJO FOREIGN KEY (ID_TRABAJO) REFERENCES TRABAJO (ID_TRABAJO);

/***********/
/** TAREA **/
/***********/
ALTER TABLE TAREA ALTER COLUMN ID_TAREA SET CACHE 100;
ALTER TABLE TAREA DROP PRIMARY KEY;
ALTER TABLE TAREA ADD CONSTRAINT PK_TAREA PRIMARY KEY (ID_TAREA);
CREATE UNIQUE INDEX IX_TAREA_01 ON TAREA (ID_TAREA);
ALTER TABLE TRABAJO_TAREA ADD CONSTRAINT FK_TRABAJO_TAREA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);

ALTER TABLE TAREA_AMBITO ALTER COLUMN ID_TAREA_AMBITO SET CACHE 100;
ALTER TABLE TAREA_AMBITO DROP PRIMARY KEY;
ALTER TABLE TAREA_AMBITO ADD CONSTRAINT PK_TAREA_AMBITO PRIMARY KEY (ID_TAREA_AMBITO);
CREATE UNIQUE INDEX IX_TAREA_AMBITO_01 ON PROCESO_CALCULO (ID_PROCESO_CALCULO);
ALTER TABLE TAREA_AMBITO ADD CONSTRAINT FK_TAREA_AMBITO_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);

ALTER TABLE TAREA_AMBITO_LOCALIZACION ALTER COLUMN ID_TAREA_AMBITO_LOCALIZACION SET CACHE 100;
ALTER TABLE TAREA_AMBITO_LOCALIZACION DROP PRIMARY KEY;
ALTER TABLE TAREA_AMBITO_LOCALIZACION ADD CONSTRAINT PK_TAREA_AMBITO_LOCALIZACION PRIMARY KEY (ID_TAREA_AMBITO_LOCALIZACION);
CREATE UNIQUE INDEX IX_TAREA_AMBITO_LOCALIZACION_01 ON PROCESO_CALCULO (ID_PROCESO_CALCULO);
ALTER TABLE TAREA_AMBITO_LOCALIZACION ADD CONSTRAINT FK_TAREA_AMBITO_LOCALIZACION_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);

ALTER TABLE TAREA_AMBITO_PERSONA ALTER COLUMN ID_TAREA_AMBITO_PERSONA SET CACHE 100;
ALTER TABLE TAREA_AMBITO_PERSONA DROP PRIMARY KEY;
ALTER TABLE TAREA_AMBITO_PERSONA ADD CONSTRAINT PK_TAREA_AMBITO_PERSONA PRIMARY KEY (ID_TAREA_AMBITO_PERSONA);
CREATE UNIQUE INDEX IX_TAREA_AMBITO_PERSONA_01 ON PROCESO_CALCULO (ID_PROCESO_CALCULO);
ALTER TABLE TAREA_AMBITO_PERSONA ADD CONSTRAINT FK_TAREA_AMBITO_PERSONA_TAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA);

ALTER TABLE ESTADO_TAREA DROP PRIMARY KEY;
ALTER TABLE ESTADO_TAREA ADD CONSTRAINT PK_ESTADO_TAREA PRIMARY KEY (ID_ESTADO_TAREA);
CREATE UNIQUE INDEX IX_ESTADO_TAREA_01 ON ESTADO_TAREA (ID_ESTADO_TAREA);

/*************/
/** PROCESO **/
/*************/
ALTER TABLE PROCESO ALTER COLUMN ID_PROCESO SET CACHE 100;
ALTER TABLE PROCESO DROP PRIMARY KEY;
ALTER TABLE PROCESO ADD CONSTRAINT PK_PROCESO PRIMARY KEY (ID_PROCESO);
CREATE UNIQUE INDEX IX_PROCESO_01 ON PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_CALCULO ALTER COLUMN ID_PROCESO_CALCULO SET CACHE 100;
ALTER TABLE PROCESO_CALCULO DROP PRIMARY KEY;
ALTER TABLE PROCESO_CALCULO ADD CONSTRAINT PK_PROCESO_CALCULO PRIMARY KEY (ID_PROCESO_CALCULO);
CREATE UNIQUE INDEX IX_PROCESO_CALCULO_01 ON PROCESO_CALCULO (ID_PROCESO_CALCULO);
ALTER TABLE PROCESO_CALCULO ADD CONSTRAINT FK_PROCESO_CALCULO_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_EMPLEADO ALTER COLUMN ID_PROCESO_EMPLEADO SET CACHE 100;
ALTER TABLE PROCESO_EMPLEADO DROP PRIMARY KEY;
ALTER TABLE PROCESO_EMPLEADO ADD CONSTRAINT PK_PROCESO_EMPLEADO PRIMARY KEY (ID_PROCESO_EMPLEADO);
CREATE UNIQUE INDEX IX_PROCESO_EMPLEADO_01 ON PROCESO_EMPLEADO (ID_PROCESO_EMPLEADO);
ALTER TABLE PROCESO_EMPLEADO ADD CONSTRAINT FK_PROCESO_EMPLEADO_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_EMPLEADO_ESTADO ALTER COLUMN ID_PROCESO_EMPLEADO_ESTADO SET CACHE 100;
ALTER TABLE PROCESO_EMPLEADO_ESTADO DROP PRIMARY KEY;
ALTER TABLE PROCESO_EMPLEADO_ESTADO ADD CONSTRAINT PK_PROCESO_EMPLEADO_ESTADO PRIMARY KEY (ID_PROCESO_EMPLEADO_ESTADO);
CREATE UNIQUE INDEX IX_PROCESO_EMPLEADO_ESTADO_01 ON PROCESO_EMPLEADO_ESTADO (ID_PROCESO_EMPLEADO_ESTADO);
ALTER TABLE PROCESO_EMPLEADO_ESTADO ADD CONSTRAINT FK_PROCESO_EMPLEADO_ESTADO_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_EMPLEADO_ESTRUCTURA ALTER COLUMN ID_PROCESO_EMPLEADO_ESTRUCTURA SET CACHE 100;
ALTER TABLE PROCESO_EMPLEADO_ESTRUCTURA DROP PRIMARY KEY;
ALTER TABLE PROCESO_EMPLEADO_ESTRUCTURA ADD CONSTRAINT PK_PROCESO_EMPLEADO_ESTRUCTURA PRIMARY KEY (ID_PROCESO_EMPLEADO_ESTRUCTURA);
CREATE UNIQUE INDEX IX_PROCESO_EMPLEADO_ESTRUCTURA_01 ON PROCESO_EMPLEADO_ESTRUCTURA (ID_PROCESO_EMPLEADO_ESTRUCTURA);
ALTER TABLE PROCESO_EMPLEADO_ESTRUCTURA ADD CONSTRAINT FK_PROCESO_EMPLEADO_ESTRUCTURA_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_EMPLEADO_HISTORICO ALTER COLUMN ID_PROCESO_EMPLEADO_HISTORICO SET CACHE 100;
ALTER TABLE PROCESO_EMPLEADO_HISTORICO DROP PRIMARY KEY;
ALTER TABLE PROCESO_EMPLEADO_HISTORICO ADD CONSTRAINT PK_PROCESO_EMPLEADO_HISTORICO PRIMARY KEY (ID_PROCESO_EMPLEADO_HISTORICO);
CREATE UNIQUE INDEX IX_PROCESO_EMPLEADO_HISTORICO_01 ON PROCESO_EMPLEADO_HISTORICO (ID_PROCESO_EMPLEADO_HISTORICO);
ALTER TABLE PROCESO_EMPLEADO_HISTORICO ADD CONSTRAINT FK_PROCESO_EMPLEADO_HISTORICO_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE ESTADO_PROCESO DROP PRIMARY KEY;
ALTER TABLE ESTADO_PROCESO ADD CONSTRAINT PK_ESTADO_PROCESO PRIMARY KEY (ID_ESTADO_PROCESO);
CREATE UNIQUE INDEX IX_ESTADO_PROCESO_01 ON ESTADO_PROCESO (ID_ESTADO_PROCESO);

ALTER TABLE ESTADO_PROCESO_EMPLEADO DROP PRIMARY KEY;
ALTER TABLE ESTADO_PROCESO_EMPLEADO ADD CONSTRAINT PK_ESTADO_PROCESO_EMPLEADO PRIMARY KEY (ID_ESTADO_PROCESO_EMPLEADO);
CREATE UNIQUE INDEX IX_ESTADO_PROCESO_EMPLEADO_01 ON ESTADO_PROCESO_EMPLEADO (ID_ESTADO_PROCESO_EMPLEADO);

ALTER TABLE TIPO_PROCESO_TIENDA DROP PRIMARY KEY;
ALTER TABLE TIPO_PROCESO_TIENDA ADD CONSTRAINT PK_TIPO_PROCESO_TIENDA PRIMARY KEY (ID_TIPO_PROCESO_TIENDA);
CREATE UNIQUE INDEX IX_TIPO_PROCESO_TIENDA_01 ON TIPO_PROCESO_TIENDA (ID_TIPO_PROCESO_TIENDA);

ALTER TABLE PROCESO_TIENDA ALTER COLUMN ID_PROCESO_TIENDA SET CACHE 100;
ALTER TABLE PROCESO_TIENDA DROP PRIMARY KEY;
ALTER TABLE PROCESO_TIENDA ADD CONSTRAINT PK_PROCESO_TIENDA PRIMARY KEY (ID_PROCESO_TIENDA);
CREATE UNIQUE INDEX IX_PROCESO_TIENDA_01 ON PROCESO_TIENDA (ID_PROCESO_TIENDA);
ALTER TABLE PROCESO_TIENDA ADD CONSTRAINT FK_PROCESO_TIENDA_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_TIENDA_COMISION_HISTORICO ALTER COLUMN ID_PROCESO_TIENDA_COMISION_HISTORICO SET CACHE 100;
ALTER TABLE PROCESO_TIENDA_COMISION_HISTORICO DROP PRIMARY KEY;
ALTER TABLE PROCESO_TIENDA_COMISION_HISTORICO ADD CONSTRAINT PK_PROCESO_TIENDA_COMISION_HISTORICO PRIMARY KEY (ID_PROCESO_TIENDA_COMISION_HISTORICO);
CREATE UNIQUE INDEX IX_PROCESO_TIENDA_COMISION_HISTORICO_01 ON PROCESO_TIENDA_COMISION_HISTORICO (ID_PROCESO_TIENDA_COMISION_HISTORICO);
ALTER TABLE PROCESO_TIENDA_COMISION_HISTORICO ADD CONSTRAINT FK_PROCESO_TIENDA_COMISION_HISTORICO_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_TIENDA_EMPLEADO_PRESENCIA_SECCION ALTER COLUMN ID_PROCESO_TIENDA_EMPLEADO_PRESENCIA_SECCION SET CACHE 100;
ALTER TABLE PROCESO_TIENDA_EMPLEADO_PRESENCIA_SECCION DROP PRIMARY KEY;
ALTER TABLE PROCESO_TIENDA_EMPLEADO_PRESENCIA_SECCION ADD CONSTRAINT PK_PROCESO_TIENDA_EMPLEADO_PRESENCIA_SECCION PRIMARY KEY (ID_PROCESO_TIENDA_EMPLEADO_PRESENCIA_SECCION);
CREATE UNIQUE INDEX IX_PROCESO_TIENDA_EMPLEADO_PRESENCIA_SECCION_01 ON PROCESO_TIENDA_EMPLEADO_PRESENCIA_SECCION (ID_PROCESO_TIENDA_EMPLEADO_PRESENCIA_SECCION);
ALTER TABLE PROCESO_TIENDA_EMPLEADO_PRESENCIA_SECCION ADD CONSTRAINT FK_PROCESO_TIENDA_EMPLEADO_PRESENCIA_SECCION_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_TIENDA_ESTADO ALTER COLUMN ID_PROCESO_TIENDA_ESTADO SET CACHE 100;
ALTER TABLE PROCESO_TIENDA_ESTADO DROP PRIMARY KEY;
ALTER TABLE PROCESO_TIENDA_ESTADO ADD CONSTRAINT PK_PROCESO_TIENDA_ESTADO PRIMARY KEY (ID_PROCESO_TIENDA_ESTADO);
CREATE UNIQUE INDEX IX_PROCESO_TIENDA_ESTADO_01 ON PROCESO_TIENDA_ESTADO (ID_PROCESO_TIENDA_ESTADO);
ALTER TABLE PROCESO_TIENDA_ESTADO ADD CONSTRAINT FK_PROCESO_TIENDA_ESTADO_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_TIENDA_HISTORICO ALTER COLUMN ID_PROCESO_TIENDA_HISTORICO SET CACHE 100;
ALTER TABLE PROCESO_TIENDA_HISTORICO DROP PRIMARY KEY;
ALTER TABLE PROCESO_TIENDA_HISTORICO ADD CONSTRAINT PK_PROCESO_TIENDA_HISTORICO PRIMARY KEY (ID_PROCESO_TIENDA_HISTORICO);
CREATE UNIQUE INDEX IX_PROCESO_TIENDA_HISTORICO_01 ON PROCESO_TIENDA_HISTORICO (ID_PROCESO_TIENDA_HISTORICO);
ALTER TABLE PROCESO_TIENDA_HISTORICO ADD CONSTRAINT FK_PROCESO_TIENDA_HISTORICO_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_TIENDA_PRESENCIA_SECCION ALTER COLUMN ID_PROCESO_TIENDA_PRESENCIA_SECCION SET CACHE 100;
ALTER TABLE PROCESO_TIENDA_PRESENCIA_SECCION DROP PRIMARY KEY;
ALTER TABLE PROCESO_TIENDA_PRESENCIA_SECCION ADD CONSTRAINT PK_PROCESO_TIENDA_PRESENCIA_SECCION PRIMARY KEY (ID_PROCESO_TIENDA_PRESENCIA_SECCION);
CREATE UNIQUE INDEX IX_PROCESO_TIENDA_PRESENCIA_SECCION_01 ON PROCESO_TIENDA_PRESENCIA_SECCION (ID_PROCESO_TIENDA_PRESENCIA_SECCION);
ALTER TABLE PROCESO_TIENDA_PRESENCIA_SECCION ADD CONSTRAINT FK_PROCESO_TIENDA_PRESENCIA_SECCION_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_TIENDA_SECCION_EMPLEADO_PRESENCIA ALTER COLUMN ID_PROCESO_TIENDA_SECCION_EMPLEADO_PRESENCIA SET CACHE 100;
ALTER TABLE PROCESO_TIENDA_SECCION_EMPLEADO_PRESENCIA DROP PRIMARY KEY;
ALTER TABLE PROCESO_TIENDA_SECCION_EMPLEADO_PRESENCIA ADD CONSTRAINT PK_PROCESO_TIENDA_SECCION_EMPLEADO_PRESENCIA PRIMARY KEY (ID_PROCESO_TIENDA_SECCION_EMPLEADO_PRESENCIA);
CREATE UNIQUE INDEX IX_PROCESO_TIENDA_SECCION_EMPLEADO_PRESENCIA_01 ON PROCESO_TIENDA_SECCION_EMPLEADO_PRESENCIA (ID_PROCESO_TIENDA_SECCION_EMPLEADO_PRESENCIA);
ALTER TABLE PROCESO_TIENDA_SECCION_EMPLEADO_PRESENCIA ADD CONSTRAINT FK_PROCESO_TIENDA_SECCION_EMPLEADO_PRESENCIA_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_TIENDA_SECCION_PRESENCIA ALTER COLUMN ID_PROCESO_TIENDA_SECCION_PRESENCIA SET CACHE 100;
ALTER TABLE PROCESO_TIENDA_SECCION_PRESENCIA DROP PRIMARY KEY;
ALTER TABLE PROCESO_TIENDA_SECCION_PRESENCIA ADD CONSTRAINT PK_PROCESO_TIENDA_SECCION_PRESENCIA PRIMARY KEY (ID_PROCESO_TIENDA_SECCION_PRESENCIA);
CREATE UNIQUE INDEX IX_PROCESO_TIENDA_SECCION_PRESENCIA_01 ON PROCESO_TIENDA_SECCION_PRESENCIA (ID_PROCESO_TIENDA_SECCION_PRESENCIA);
ALTER TABLE PROCESO_TIENDA_SECCION_PRESENCIA ADD CONSTRAINT FK_PROCESO_TIENDA_SECCION_PRESENCIA_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_TIENDA_SECCION_VENTA ALTER COLUMN ID_PROCESO_TIENDA_SECCION_VENTA SET CACHE 100;
ALTER TABLE PROCESO_TIENDA_SECCION_VENTA DROP PRIMARY KEY;
ALTER TABLE PROCESO_TIENDA_SECCION_VENTA ADD CONSTRAINT PK_PROCESO_TIENDA_SECCION_VENTA PRIMARY KEY (ID_PROCESO_TIENDA_SECCION_VENTA);
CREATE UNIQUE INDEX IX_PROCESO_TIENDA_SECCION_PRESENCIA_01 ON PROCESO_TIENDA_SECCION_VENTA (ID_PROCESO_TIENDA_SECCION_VENTA);
ALTER TABLE PROCESO_TIENDA_SECCION_VENTA ADD CONSTRAINT FK_PROCESO_TIENDA_SECCION_VENTA_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

ALTER TABLE PROCESO_TIENDA_VENTA_SECCION ALTER COLUMN ID_PROCESO_TIENDA_VENTA_SECCION SET CACHE 100;
ALTER TABLE PROCESO_TIENDA_VENTA_SECCION DROP PRIMARY KEY;
ALTER TABLE PROCESO_TIENDA_VENTA_SECCION ADD CONSTRAINT PK_PROCESO_TIENDA_VENTA_SECCION PRIMARY KEY (ID_PROCESO_TIENDA_VENTA_SECCION);
CREATE UNIQUE INDEX IX_PROCESO_TIENDA_VENTA_SECCION_01 ON PROCESO_TIENDA_VENTA_SECCION (ID_PROCESO_TIENDA_VENTA_SECCION);
ALTER TABLE PROCESO_TIENDA_VENTA_SECCION ADD CONSTRAINT FK_PROCESO_TIENDA_VENTA_SECCION_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO;

ALTER TABLE PROCESO_TIPO_HORA ALTER COLUMN ID_PROCESO_TIPO_HORA SET CACHE 100;
ALTER TABLE PROCESO_TIPO_HORA DROP PRIMARY KEY;
ALTER TABLE PROCESO_TIPO_HORA ADD CONSTRAINT PK_PROCESO_TIPO_HORA PRIMARY KEY (ID_PROCESO_TIPO_HORA);
CREATE UNIQUE INDEX IX_PROCESO_TIPO_HORA_01 ON PROCESO_TIPO_HORA (ID_PROCESO_TIPO_HORA);
ALTER TABLE PROCESO_TIPO_HORA ADD CONSTRAINT FK_PROCESO_TIPO_HORA_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO (ID_PROCESO);

/***************/
/** ALGORITMO **/
/***************/
ALTER TABLE TIPO_CALCULO DROP PRIMARY KEY;
ALTER TABLE TIPO_CALCULO ADD CONSTRAINT PK_TIPO_CALCULO PRIMARY KEY (ID_TIPO_CALCULO);
CREATE UNIQUE INDEX IX_TIPO_CALCULO_01 ON TIPO_CALCULO (ID_TIPO_CALCULO);

ALTER TABLE TIPO_COMISION DROP PRIMARY KEY;
ALTER TABLE TIPO_COMISION ADD CONSTRAINT PK_TIPO_COMISION PRIMARY KEY (ID_TIPO_COMISION);
CREATE UNIQUE INDEX IX_TIPO_COMISION_01 ON TIPO_COMISION (ID_TIPO_COMISION);

ALTER TABLE ALGORITMO DROP PRIMARY KEY;
ALTER TABLE ALGORITMO ADD CONSTRAINT PK_ALGORITMO PRIMARY KEY (ID_ALGORITMO);
CREATE UNIQUE INDEX IX_ALGORITMO_01 ON ALGORITMO (ID_ALGORITMO);
ALTER TABLE ALGORITMO_TIPO_CALCULO ADD CONSTRAINT FK_ALGORITMO_TIPO_CALCULO_ALGORITMO FOREIGN KEY (ID_ALGORITMO) REFERENCES ALGORITMO (ID_ALGORITMO);
ALTER TABLE ALGORITMO_TIPO_COMISION ADD CONSTRAINT FK_ALGORITMO_TIPO_COMISION_ALGORITMO FOREIGN KEY (ID_ALGORITMO) REFERENCES ALGORITMO (ID_ALGORITMO);
ALTER TABLE ALGORITMO_TIPO_CALCULO ADD CONSTRAINT FK_ALGORITMO_TIPO_CALCULO_TIPO_CALCULO FOREIGN KEY (ID_TIPO_CALCULO) REFERENCES TIPO_CALCULO (ID_TIPO_CALCULO);
ALTER TABLE ALGORITMO_TIPO_COMISION ADD CONSTRAINT FK_ALGORITMO_TIPO_COMISION_TIPO_COMISION FOREIGN KEY (ID_TIPO_COMISION) REFERENCES TIPO_COMISION (ID_TIPO_COMISION);
