INSERT INTO ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE, PESO, ID_ESTADO_TAREA) VALUES (1, 'PENDIENTE', 100, 1);
INSERT INTO ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE, PESO, ID_ESTADO_TAREA) VALUES (2, 'EN CURSO', 200, 1);
INSERT INTO ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE, PESO, ID_ESTADO_TAREA) VALUES (3, 'OK', 400, 5);
INSERT INTO ESTADO_TRABAJO (ID_ESTADO_TRABAJO, NOMBRE, PESO, ID_ESTADO_TAREA) VALUES (4, 'KO', 300, 5);

UPDATE ESTADO_TAREA SET PESO = 100 WHERE ID_ESTADO_TAREA = 1;
UPDATE ESTADO_TAREA SET PESO = 200 WHERE ID_ESTADO_TAREA = 2;
UPDATE ESTADO_TAREA SET PESO = 500 WHERE ID_ESTADO_TAREA = 3;
UPDATE ESTADO_TAREA SET PESO = 400 WHERE ID_ESTADO_TAREA = 4;
UPDATE ESTADO_TAREA SET PESO = 300 WHERE ID_ESTADO_TAREA = 5;

UPDATE ESTADO_TAREA_PERSONA SET PESO = 100 WHERE ID_ESTADO_TAREA_PERSONA = 1;
UPDATE ESTADO_TAREA_PERSONA SET PESO = 300 WHERE ID_ESTADO_TAREA_PERSONA = 2;
UPDATE ESTADO_TAREA_PERSONA SET PESO = 200 WHERE ID_ESTADO_TAREA_PERSONA = 3;

UPDATE TRABAJO SET ID_ESTADO_TRABAJO = 3 WHERE ID_ESTADO_TRABAJO IS NULL;