INSERT INTO TIPO_CALCULO_RELACION_COMIS (ID_TIPO_CALCULO_RELACION_COMIS, ID_TIPO_CALCULO, COD_TIPO_CALCULO_COMIS) VALUES (16, '003', 6);
INSERT INTO TIPO_CALCULO_RELACION_COMIS (ID_TIPO_CALCULO_RELACION_COMIS, ID_TIPO_CALCULO, COD_TIPO_CALCULO_COMIS) VALUES (17, '002', 7);
INSERT INTO TIPO_CALCULO_RELACION_COMIS (ID_TIPO_CALCULO_RELACION_COMIS, ID_TIPO_CALCULO, COD_TIPO_CALCULO_COMIS) VALUES (18, '001', 8);
