-- TIPO_DATO
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (5011, 'PRESENCIA_LOCALIZACION_SECCION_EMPLEADOS_POR_VENTA', 'Presencia [localizacion|seccion] [incluido venta empleados por venta]', 1, NULL, NULL);
