INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (4005, 'PRESENCIA_REAL_LOCALIZACION-SECCION-PERSONA-TIPO_HORA-REPARTIDOPROVINCIA', 'Presencias real [localizacion|seccion|persona|tipo hora|repartido provincia]', 0, 1, NULL);

--TODO[JAVIEREV] tipo grupo dato?
