INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3013, 'VENTA_ONLINE_IPOD_LOCALIZACION_TRASLADADA_DIA', 'Venta online ipod trasladada [localizacion] por dia festivo', 1, NULL, 2);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3014, 'VENTA_ONLINE_IPOD_LOCALIZACION_SECCION_TRASLADADA_DIA', 'Venta online ipod trasladada [localizacion|seccion] por dia festivo', 1, NULL, 2);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3015, 'VENTA_ONLINE_SINT_LOCALIZACION_TRASLADADA_DIA', 'Venta online sint trasladada [localizacion] por dia festivo', 1, NULL, 3);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3016, 'VENTA_ONLINE_SINT_LOCALIZACION_SECCION_TRASLADADA_DIA', 'Venta online sint trasladada [localizacion|seccion] por dia festivo', 1, NULL, 3);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3017, 'VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_TRASLADADA_DIA', 'Venta online entrega tienda trasladada [localizacion] por dia festivo', 1, NULL, 4);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3018, 'VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_SECCION_TRASLADADA_DIA', 'Venta online entrega tienda trasladada [localizacion|seccion] por dia festivo', 1, NULL, 4);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3019, 'VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_TRASLADADA_DIA', 'Venta online entrega domicilio trasladada [localizacion] por dia festivo', 1, NULL, 5);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3020, 'VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_SECCION_TRASLADADA_DIA', 'Venta online entrega domicilio trasladada [localizacion|seccion] por dia festivo', 1, NULL, 5);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3021, 'VENTA_ONLINE_IPOD_LOCALIZACION_TRASLADADA_SECCION', 'Venta online ipod trasladada [localizacion] por seccion cerrada', 1, NULL, 2);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3022, 'VENTA_ONLINE_IPOD_LOCALIZACION_SECCION_TRASLADADA_SECCION', 'Venta online ipod trasladada [localizacion|seccion] por seccion cerrada', 1, NULL, 2);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3023, 'VENTA_ONLINE_SINT_LOCALIZACION_TRASLADADA_SECCION', 'Venta online sint trasladada [localizacion] por seccion cerrada', 1, NULL, 3);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3024, 'VENTA_ONLINE_SINT_LOCALIZACION_SECCION_TRASLADADA_SECCION', 'Venta online sint trasladada [localizacion|seccion] por seccion cerrada', 1, NULL, 3);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3025, 'VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_TRASLADADA_SECCION', 'Venta online entrega tienda trasladada [localizacion] por seccion cerrada', 1, NULL, 4);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3026, 'VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_SECCION_TRASLADADA_SECCION', 'Venta online entrega tienda trasladada [localizacion|seccion] por seccion cerrada', 1, NULL, 4);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3027, 'VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_TRASLADADA_SECCION', 'Venta online entrega domicilio trasladada [localizacion] por seccion cerrada', 1, NULL, 5);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (3028, 'VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_SECCION_TRASLADADA_SECCION', 'Venta online entrega domicilio trasladada [localizacion|seccion] por seccion cerrada', 1, NULL, 5);

INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2007, 'VENTA_ONLINE_IPOD_LOCALIZACION_SECCION_TRASLADADA', 'Venta online ipod [localizacion|seccion] trasladada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2008, 'VENTA_ONLINE_SINT_LOCALIZACION_SECCION_TRASLADADA', 'Venta online sint [localizacion|seccion] trasladada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2009, 'VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_SECCION_TRASLADADA', 'Venta online entrega tienda[localizacion|seccion] trasladada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2010, 'VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_SECCION_TRASLADADA', 'Venta online entrega domicilio[localizacion|seccion] trasladada');

INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2011, 'VENTA_ONLINE_IPOD_LOCALIZACION_TRASLADADA', 'Venta online ipod [localizacion] trasladada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2012, 'VENTA_ONLINE_SINT_LOCALIZACION_TRASLADADA', 'Venta online sint [localizacion] trasladada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2013, 'VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_TRASLADADA', 'Venta online entrega tienda[localizacion] trasladada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2014, 'VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_TRASLADADA', 'Venta online entrega domicilio[localizacion] trasladada');

INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2015, 'VENTA_ONLINE_IPOD_LOCALIZACION_SECCION_TRASLADADA_TOTALIZADA', 'Venta online ipod [localizacion|seccion] trasladada y totalizada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2016, 'VENTA_ONLINE_SINT_LOCALIZACION_SECCION_TRASLADADA_TOTALIZADA', 'Venta online sint [localizacion|seccion] trasladada y totalizada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2017, 'VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_SECCION_TRASLADADA_TOTALIZADA', 'Venta online entrega tienda[localizacion|seccion] trasladada y totalizada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2018, 'VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_SECCION_TRASLADADA_TOTALIZADA', 'Venta online entrega domicilio[localizacion|seccion] trasladada y totalizada');

INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2019, 'VENTA_ONLINE_IPOD_LOCALIZACION_TRASLADADA_TOTALIZADA', 'Venta online ipod [localizacion] trasladada y totalizada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2020, 'VENTA_ONLINE_SINT_LOCALIZACION_TRASLADADA_TOTALIZADA', 'Venta online sint [localizacion] trasladaday totalizada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2021, 'VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_TRASLADADA_TOTALIZADA', 'Venta online entrega tienda[localizacion] trasladada y totalizada');
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2022, 'VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_TRASLADADA_TOTALIZADA', 'Venta online entrega domicilio[localizacion] trasladada y totalizada');

INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2007, 3014);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2007, 3022);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2008, 3016);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2008, 3024);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2009, 3018);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2009, 3026);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2010, 3020);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2010, 3028);

INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2011, 3013);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2011, 3021);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2012, 3015);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2012, 3023);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2013, 3017);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2013, 3025);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2014, 3019);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2014, 3027);

INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2015, 3014);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2015, 3022);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2015, 2004);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2016, 3016);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2016, 3024);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2016, 2006);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2017, 3018);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2017, 3026);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2017, 2008);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2018, 3020);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2018, 3028);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2018, 3002);

INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2019, 3013);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2019, 3021);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2019, 2003);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2020, 3015);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2020, 3023);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2020, 2005);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2021, 3017);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2021, 3025);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2021, 2007);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2022, 3019);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2022, 3027);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2022, 3001);
