  INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3011, 5016);
  INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3012, 5016);
  
  DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 3011 AND ID_TIPO_DATO = 5017;
  DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 3012 AND ID_TIPO_DATO = 5017;

