-- ACCION
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY)
VALUES (9, 'externosBrasilV1', 'External emploees in Spain', 100, 0, 0, 0, 0);
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY)
VALUES (10, 'externosSpainV1', 'External emploees in Spain', 100, 0, 0, 0, 0);
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY)
VALUES (11, 'externosBosniaV1', 'External emploees in Bosnia', 100, 0, 0, 0, 0);

-- ACCION_AMBITO
-- TODO [javierev] establecer los origenes y empresas de BR y BO
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT) VALUES (10, 11, 101);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT) VALUES (10, 11, 25);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT) VALUES (10, 11, 26);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT) VALUES (10, 11, 27);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT) VALUES (10, 11, 28);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT) VALUES (10, 11, 301);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT) VALUES (10, 11, 33);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT) VALUES (10, 11, 42);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT) VALUES (10, 11, 8);

-- FASE_ACCION
INSERT INTO FASE_ACCION (ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 9, 3, 200);
INSERT INTO FASE_ACCION (ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 10, 3, 200);
INSERT INTO FASE_ACCION (ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 11, 3, 200);
