-- ESTADO_TAREA
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (1, 'PENDIENTE');
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (2, 'EN CURSO');
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (3, 'FINALIZADO SIN ERRORES');
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (4, 'FINALIZADO CON ERRORES');
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (5, 'ERROR');
-- ESTADO_TAREA_PERSONA
INSERT INTO ESTADO_TAREA_PERSONA (ID_ESTADO_TAREA_PERSONA, NOMBRE) VALUES (1, 'PENDIENTE');
INSERT INTO ESTADO_TAREA_PERSONA (ID_ESTADO_TAREA_PERSONA, NOMBRE) VALUES (2, 'OK');
INSERT INTO ESTADO_TAREA_PERSONA (ID_ESTADO_TAREA_PERSONA, NOMBRE) VALUES (3, 'KO');
-- ESTADO_PERIODO_CALCULO_PERSONA
INSERT INTO ESTADO_PERIODO_CALCULO_PERSONA (ID_ESTADO_PERIODO_CALCULO_PERSONA, NOMBRE) VALUES (1, 'SIN CALCULAR');
INSERT INTO ESTADO_PERIODO_CALCULO_PERSONA (ID_ESTADO_PERIODO_CALCULO_PERSONA, NOMBRE) VALUES (2, 'CALCULADO');
INSERT INTO ESTADO_PERIODO_CALCULO_PERSONA (ID_ESTADO_PERIODO_CALCULO_PERSONA, NOMBRE) VALUES (3, 'CONFIRMADO');
INSERT INTO ESTADO_PERIODO_CALCULO_PERSONA (ID_ESTADO_PERIODO_CALCULO_PERSONA, NOMBRE) VALUES (4, 'CALCULADO_ERROR');
INSERT INTO ESTADO_PERIODO_CALCULO_PERSONA (ID_ESTADO_PERIODO_CALCULO_PERSONA, NOMBRE) VALUES (5, 'EXPORTADO');
INSERT INTO ESTADO_PERIODO_CALCULO_PERSONA (ID_ESTADO_PERIODO_CALCULO_PERSONA, NOMBRE) VALUES (6, 'PAGADO');
-- TIPO_AMBITO
INSERT INTO TIPO_AMBITO (ID_TIPO_AMBITO, NOMBRE) VALUES (1, 'SOCIEDAD');
INSERT INTO TIPO_AMBITO (ID_TIPO_AMBITO, NOMBRE) VALUES (2, 'ORIGEN');
INSERT INTO TIPO_AMBITO (ID_TIPO_AMBITO, NOMBRE) VALUES (3, 'EMPRESA');
INSERT INTO TIPO_AMBITO (ID_TIPO_AMBITO, NOMBRE) VALUES (4, 'LOCALIZACION');
INSERT INTO TIPO_AMBITO (ID_TIPO_AMBITO, NOMBRE) VALUES (5, 'PERSONA');
-- TIPO_CALCULO
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('000', 'NINGUNO');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('001', 'GLOBAL_TIENDA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('002', 'GLOBAL_SECCION');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('003', 'DIRECTO_SOBRE_VENTA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('004', 'DIRECTO_SOBRE_VENTA_CON_PRESENCIA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('005', 'DIRECTO_SOBRE_VENTA_CON_REDUCCION_DE_JORNADA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('006', 'DIRECTO_SOBRE_VENTA_CON_PRESENCIA_Y_REDUCCION_DE_JORNADA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('007', 'POR_VENTA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('008', 'POR_VENTA_SIMPLIFICADA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('009', 'POR_VENTA_INDIVIDUAL');
-- TIPO_COMISION
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES ('001', 'COMISION');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES ('002', 'RESALTA_FUNCION');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES ('003', 'RESALTA_PERSONAL');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES ('004', 'RESALTA_TIENDA'); 
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES ('005', 'INCENTIVO');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES ('006', 'COMISION_POR_TOPES');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES ('007', 'MANUAL');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES ('008', 'COMISION_DIARIA');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES ('009', 'PRIMA');
-- TIPO_DATO
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (1, 'IMPORTE_VENTA_FISICA_LOCALIZACION', 'Importe de la venta fisica (localizacion) agrupado por localizacion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (2, 'IMPORTE_VENTA_FISICA_LOCALIZACION_SECCION', 'Importe de la venta fisica (localizacion) agrupado por localizacion y seccion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (3, 'IMPORTE_VENTA_FISICA_LOCALIZACION_SECCION_PERSONA', 'Importe de la venta fisica (localizacion) agrupado por localizacion, seccion y persona', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (4, 'IMPORTE_VENTA_FISICA_INDIVIDUAL_LOCALIZACION', 'Importe de la venta fisica (persona) agrupado por localizacion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (5, 'IMPORTE_VENTA_FISICA_INDIVIDUAL_PERSONA_LOCALIZACION', 'Importe de la venta fisica (persona) agrupado por persona y localizacion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (6, 'IMPORTE_VENTA_FISICA_INDIVIDUAL_OPERACION_LOCALIZACION', 'Importe de la venta fisica (persona) agrupado por operacion y localizacion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (7, 'IMPORTE_VENTA_FISICA_INDIVIDUAL_OPERACION_PERSONA_LOCALIZACION', 'Importe de la venta fisica (persona) agrupado por operacion, persona y localizacion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (8, 'IMPORTE_VENTA_ONLINE_IPOD_LOCALIZACION', 'Importe de la venta online ipod (localizacion) agrupado por localizacion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (9, 'IMPORTE_VENTA_ONLINE_IPOD_LOCALIZACION_SECCION', 'Importe de la venta online ipod (localizacion) agrupado por localizacion y seccion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (10, 'IMPORTE_VENTA_ONLINE_IPOD_INDIVIDUAL_LOCALIZACION', 'Importe de la venta online ipod (persona) agrupado por localizacion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (11, 'IMPORTE_VENTA_ONLINE_IPOD_INDIVIDUAL_LOCALIZACION_PERSONA', 'Importe de la venta online ipod (persona) agrupado por localizacion y persona', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (12, 'IMPORTE_VENTA_ONLINE_IPOD_INDIVIDUAL_OPERACION_LOCALIZACION', 'Importe de la venta online ipod (persona) agrupado por operacion y localizacion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (13, 'IMPORTE_VENTA_ONLINE_PICKING_LOCALIZACION', 'Importe de la venta online sint (localizacion) agrupado por localizacion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (14, 'IMPORTE_VENTA_ONLINE_PICKING_LOCALIZACION_SECCION', 'Importe de la venta online sint (localizacion) agrupado por localizacion y seccion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (15, 'IMPORTE_VENTA_ONLINE_ENTREGA_TIENDA_LOCALIZACION', 'Importe de la venta online (tienda online) agrupado por localizacion',0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (16, 'IMPORTE_VENTA_ONLINE_ENTREGA_TIENDA_LOCALIZACION_SECCION', 'Importe de la venta online (tienda online) agrupado por localizacion y seccion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (17, 'IMPORTE_VENTA_ONLINE_ENTREGA_DOMICILIO_LOCALIZACION', 'Importe de la venta online (tienda online/entrega domicilio) agrupado por localizacion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (18, 'IMPORTE_VENTA_ONLINE_ENTREGA_DOMICILIO_LOCALIZACION_SECCION', 'Importe de la venta online (tienda online/entrega domicilio) agrupado por localizacion y seccion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (19, 'IMPORTE_DEVOLUCION_SECCION_LOCALIZACION', 'Importe devolucion agrupado por seccion y localizacion',0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (20, 'IMPORTE_DEVOLUCION_SECCION_LOCALIZACION_PERSONA', 'Importe devolucion agrupado por seccion, localizacion y persona', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (21, 'IMPORTE_DEVOLUCION_SECCION_LOCALIZACION_NO_VENDEDOR', 'Importe devolucion agrupado por seccion, localizacion y no vendedor', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (22, 'IMPORTE_VENTA_BRUTO', 'Importe bruto de ventas', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (23, 'IMPORTE_VENTA_IPOD_BRUTO', 'Importe bruto de ventas ipod', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (24, 'IMPORTE_VENTA_LOCALIZACION','Importe venta localizacion', 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (25, 'IMPORTE_VENTA_LOCALIZACION_SECCION', 'Importe venta localizacion y seccion', 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (26, 'IMPORTE_VENTA_FISICA_CADENA', 'Importe venta fisica agrupado por cadena', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (27, 'IMPORTE_VENTA_FISICA_CADENA_SECCION', 'Importe venta fisica agrupado por cadena y seccion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (28, 'IMPORTE_VENTA_ONLINE_ENTREGA_DOMICILIO_CADENA', 'Importe venta online (tienda online/entrega domicilio) agrupado por cadena', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (29, 'IMPORTE_VENTA_ONLINE_ENTREGA_DOMICILIO_CADENA_SECCION', 'Importe venta online (tienda online/entrega domicilio) agrupado por cadena y seccion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (30, 'IMPORTE_VENTA_FISICA_AGRUPACION_CADENA', 'Importe venta fisica agrupado por cadena', 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (31, 'IMPORTE_VENTA_FISICA_AGRUPACION_CADENA_SECCION', 'Importe venta fisica agrupado por cadena y seccion', 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (32, 'IMPORTE_VENTA_ONLINE_ENTREGA_DOMICILIO_AGRUPACION_CADENA', 'Importe venta online (tienda online/entrega domicilio) agrupado por cadena', 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (33, 'IMPORTE_VENTA_ONLINE_ENTREGA_DOMICILIO_AGRUPACION_CADENA_SECCION', 'Importe venta online (tienda online/entrega domicilio) agrupado por cadena y seccion', 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (34, 'IMPORTE_VENTA_ONLINE_TRASLADADA', 'Importe venta online trasladada en caso de festivo', 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (35, 'IMPORTE_VENTA_ONLINE_COMPENSADA', 'Importe venta online compensada en caso de festivo', 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (36, 'MINUTOS_TOTALES_SECCION', 'Minutos de presencia referentes a localizacion por seccion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (37, 'MINUTOS_INDIVIDUAL', 'Minutos de presencia referentes a persona', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (38, 'MINUTOS_INDIVIDUAL_MANUAL', 'Minutos de presencia referentes a persona de tipo manual', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (39, 'MINUTOS_TOTALES_SECCION_MANUAL', 'Minutos de presencia referentes a localizacion por seccion de tipo manual', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (40, 'MINUTOS_TOTALES', 'Minutos de presencia referentes a localizacion', 0);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, PROCESADO) VALUES (41, 'MINUTOS_TOTALES_MANUAL', 'Minutos de presencia referentes a localizacion de tipo manual', 0);

-- ALGORITMO
INSERT INTO ALGORITMO (ID_ALGORITMO, ACTIVO, NOMBRE) VALUES (1, 1, 'globalTiendaPorcentajeV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ACTIVO, NOMBRE) VALUES (2, 1, 'globalTiendaPorcentajeDiariaV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ACTIVO, NOMBRE) VALUES (3, 1, 'globalTiendaTopesV1');
INSERT INTO ALGORITMO (ID_ALGORITMO, ACTIVO, NOMBRE) VALUES (4, 1, 'globalTiendaManualV1');
-- ALGORITMO_TIPO_CALCULO
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (1, '001');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (2, '001');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (3, '001');
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (4, '001');
-- ALGORITMO_TIPO_COMISION
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (1, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (1, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (1, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (1, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (1, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (3, '006');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (4, '007');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (2, '008');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (1, '009');
-- ALGORITMO_TIPO_DATO
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1, 2);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1, 36);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1, 37);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1, 38);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1, 39);
-- [MOCK][INICIO] PROGRAMACION
-- Programacion: 1 | Programacion ambito: 1 || Sociedad: AT | Origen: 38 | Empresa: [95,135,251,315,329,340,425,468]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ACTIVA, FECHA_CREACION, FECHA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, HORA_PROGRAMACION_HUSO, ID_USUARIO, ID_TIPO_AMBITO) VALUES (1, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'AT_38_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_SOCIEDAD) VALUES (1, 1, 'AT');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, ID_ORIGEN) VALUES (1, '38');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (1, '95');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (1, '135');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (1, '251');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (1, '315');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (1, '329');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (1, '340');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (1, '425');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (1, '468');
-- Programacion: 2 | Programacion ambito: 2 || Sociedad: CA | Origen: 404 | Empresa: [97,362,395]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ACTIVA, FECHA_CREACION, FECHA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, HORA_PROGRAMACION_HUSO, ID_USUARIO, ID_TIPO_AMBITO) VALUES (2, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CA_404_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_SOCIEDAD) VALUES (2, 2, 'CA');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, ID_ORIGEN) VALUES (2, '404');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (2, '97');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (2, '362');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (2, '395');
-- Programacion: 3 | Programacion ambito: 3 || Sociedad: CH | Origen: 39 | Empresa: [36,100,137,143,325,348,456,481,508]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ACTIVA, FECHA_CREACION, FECHA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, HORA_PROGRAMACION_HUSO, ID_USUARIO, ID_TIPO_AMBITO) VALUES (3, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CH_39_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_SOCIEDAD) VALUES (3, 3, 'CH');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, ID_ORIGEN) VALUES (3, '39');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (3, '36');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (3, '100');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (3, '137');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (3, '143');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (3, '325');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (3, '348');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (3, '456');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (3, '481');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (3, '508');
-- Programacion: 4 | Programacion ambito: 4 || Sociedad: CZ | Origen: 61 | Empresa: [123,172,173,252,253,254,510,511]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ACTIVA, FECHA_CREACION, FECHA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, HORA_PROGRAMACION_HUSO, ID_USUARIO, ID_TIPO_AMBITO) VALUES (4, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CZ_61_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_SOCIEDAD) VALUES (4, 4, 'CZ');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, ID_ORIGEN) VALUES (4, '61');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (4, '123');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (4, '172');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (4, '173');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (4, '252');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (4, '253');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (4, '254');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (4, '510');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (4, '511');
-- Programacion: 5 | Programacion ambito: 5 || Sociedad: DE | Origen: 4 | Empresa: [52,107,132,316,323,333,338,342,347,370,386,393,403,408,424]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ACTIVA, FECHA_CREACION, FECHA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, HORA_PROGRAMACION_HUSO, ID_USUARIO, ID_TIPO_AMBITO) VALUES (5, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'DE_4_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_SOCIEDAD) VALUES (5, 5, 'DE');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, ID_ORIGEN) VALUES (5, '4');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '52');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '107');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '132');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '316');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '323');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '333');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '338');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '342');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '347');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '370');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '386');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '393');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '403');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '408');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (5, '424');
-- Programacion: 6 | Programacion ambito: 6 || Sociedad: HU | Origen: 64 | Empresa: [157,177,220,221,235,290,457]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ACTIVA, FECHA_CREACION, FECHA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, HORA_PROGRAMACION_HUSO, ID_USUARIO, ID_TIPO_AMBITO) VALUES (6, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'HU_64_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_SOCIEDAD) VALUES (6, 6, 'HU');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, ID_ORIGEN) VALUES (6, '64');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (6, '157');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (6, '177');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (6, '220');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (6, '221');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (6, '235');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (6, '290');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (6, '457');
-- Programacion: 7 | Programacion ambito: 7 || Sociedad: SK | Origen: 63 | Empresa: [209,222,223,224,470,476]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ACTIVA, FECHA_CREACION, FECHA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, HORA_PROGRAMACION_HUSO, ID_USUARIO, ID_TIPO_AMBITO) VALUES (7, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'SK_63_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_SOCIEDAD) VALUES (7, 7, 'SK');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, ID_ORIGEN) VALUES (7, '63');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (7, '209');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (7, '222');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (7, '223');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (7, '224');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (7, '470');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (7, '476');
-- Programacion: 8 | Programacion ambito: 8 || Sociedad: UY | Origen: 524 | Empresa: [87,429]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ACTIVA, FECHA_CREACION, FECHA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, HORA_PROGRAMACION_HUSO, ID_USUARIO, ID_TIPO_AMBITO) VALUES (8, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'UY_524_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_SOCIEDAD) VALUES (8, 8, 'UY');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, ID_ORIGEN) VALUES (8, '524');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (8, '87');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (8, '429');
-- Programacion: 9 | Programacion ambito: 9 || Sociedad: ZA | Origen: 388 | Empresa: [343,477]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ACTIVA, FECHA_CREACION, FECHA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, HORA_PROGRAMACION_HUSO, ID_USUARIO, ID_TIPO_AMBITO) VALUES (9, 0, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'ZA_388_ALL', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_SOCIEDAD) VALUES (9, 9, 'ZA');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, ID_ORIGEN) VALUES (9, '388');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (9, '343');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (9, '477');
-- Programacion: 10 | Programacion ambito: 10 || Sociedad: AT | Origen: 38 | Empresa: [95,135]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ACTIVA, FECHA_CREACION, FECHA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, HORA_PROGRAMACION_HUSO, ID_USUARIO, ID_TIPO_AMBITO) VALUES (10, 1, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'AT_38_DATA', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_SOCIEDAD) VALUES (10, 10, 'AT');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, ID_ORIGEN) VALUES (10, '38');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (10, '95');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (10, '135');
-- Programacion: 11 | Programacion ambito: 11 || Sociedad: CZ | Origen: 61 | Empresa: [123,173]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ACTIVA, FECHA_CREACION, FECHA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, HORA_PROGRAMACION_HUSO, ID_USUARIO, ID_TIPO_AMBITO) VALUES (11, 1, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CZ_61_DATA', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_SOCIEDAD) VALUES (11, 11, 'CZ');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, ID_ORIGEN) VALUES (11, '61');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (11, '123');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (11, '173');
-- Programacion: 12 | Programacion ambito: 12 || Sociedad: CH | Origen: 39 | Empresa: [100]
INSERT INTO PROGRAMACION (ID_PROGRAMACION, ACTIVA, FECHA_CREACION, FECHA_SIGUIENTE_EJECUCION, HORA_PROGRAMACION, HORA_PROGRAMACION_HUSO, ID_USUARIO, ID_TIPO_AMBITO) VALUES (12, 1, TIMESTAMP('1800-01-01 00:00:00'), TIMESTAMP('1800-01-01 00:00:00'), '00:00:00', 'UTC', 'CH_39_DATA', 3);
INSERT INTO PROGRAMACION_AMBITO (ID_PROGRAMACION_AMBITO, ID_PROGRAMACION, ID_SOCIEDAD) VALUES (12, 12, 'CH');
INSERT INTO PROGRAMACION_AMBITO_ORIGEN (ID_PROGRAMACION_AMBITO, ID_ORIGEN) VALUES (12, '39');
INSERT INTO PROGRAMACION_AMBITO_EMPRESA (ID_PROGRAMACION_AMBITO, ID_EMPRESA) VALUES (12, '100');
-- [MOCK][FIN] PROGRAMACION
-- [MOCK][INICIO] AGRUPACION_CADENA
--INSERT INTO TAREA_AGRUPACION_CADENA (ID_TAREA, ID_AGRUPACION, ID_CADENA, MULTIPLE) VALUES (1, 1, 1, 1);
--INSERT INTO TAREA_AGRUPACION_CADENA (ID_TAREA, ID_AGRUPACION, ID_CADENA, MULTIPLE) VALUES (1, 1, 2, 1);
--INSERT INTO TAREA_AGRUPACION_CADENA (ID_TAREA, ID_AGRUPACION, ID_CADENA, MULTIPLE) VALUES (1, 1, 3, 1);
--INSERT INTO TAREA_AGRUPACION_CADENA (ID_TAREA, ID_AGRUPACION, ID_CADENA, MULTIPLE) VALUES (1, 2, 4, 0);
--INSERT INTO TAREA_AGRUPACION_CADENA (ID_TAREA, ID_AGRUPACION, ID_CADENA, MULTIPLE) VALUES (1, 3, 5, 0);
--INSERT INTO TAREA_AGRUPACION_CADENA (ID_TAREA, ID_AGRUPACION, ID_CADENA, MULTIPLE) VALUES (1, 4, 6, 0);
--INSERT INTO TAREA_AGRUPACION_CADENA (ID_TAREA, ID_AGRUPACION, ID_CADENA, MULTIPLE) VALUES (1, 5, 7, 0);
--INSERT INTO TAREA_AGRUPACION_CADENA (ID_TAREA, ID_AGRUPACION, ID_CADENA, MULTIPLE) VALUES (1, 6, 8, 0);
--INSERT INTO TAREA_AGRUPACION_CADENA (ID_TAREA, ID_AGRUPACION, ID_CADENA, MULTIPLE) VALUES (1, 7, 11, 0);
--INSERT INTO TAREA_AGRUPACION_CADENA (ID_TAREA, ID_AGRUPACION, ID_CADENA, MULTIPLE) VALUES (1, 8, 14, 0);
--INSERT INTO TAREA_AGRUPACION_CADENA (ID_TAREA, ID_AGRUPACION, ID_CADENA, MULTIPLE) VALUES (1, 9, 17, 0);
--INSERT INTO TAREA_AGRUPACION_CADENA (ID_TAREA, ID_AGRUPACION, ID_CADENA, MULTIPLE) VALUES (1, 10, 18, 0);
-- [MOCK][FIN] AGRUPACION_CADENA

