-- Renombrado de tipos de dato
UPDATE tipo_dato SET NOMBRE='PRESENCIA_LOCALIZACION_EMPLEADOS_POR_VENTA', DESCRIPCION='Presencia [localizacion] [incluido venta empleados por venta]' WHERE ID_TIPO_DATO = 5011;
UPDATE tipo_dato SET NOMBRE='VENTA_SIN_DEVOLUCION_LOCALIZACION', DESCRIPCION='Venta fisica y iPod sin devolucion [localizacion]' WHERE ID_TIPO_DATO = 3034;
UPDATE tipo_dato SET NOMBRE='DEVOLUCION_LOCALIZACION', DESCRIPCION='Devolucion fisica y iPod [localizacion]' WHERE ID_TIPO_DATO = 3029;
UPDATE TIPO_DATO SET NOMBRE='DEVOLUCION_VENDEDOR_0_LOCALIZACION', DESCRIPCION='Devolucion fisica y iPod vendedor 0 [localizacion]' WHERE ID_TIPO_DATO = 3044;
UPDATE TIPO_DATO SET NOMBRE='DEVOLUCION_INDIVIDUAL_LOCALIZACION', DESCRIPCION='Devolucion fisica y iPod [localizacion|persona]' WHERE ID_TIPO_DATO = 3037;
UPDATE TIPO_DATO SET NOMBRE='VENTA_SIN_DEVOLUCION_INDIVIDUAL_LOCALIZACION', DESCRIPCION='Venta fisica y iPod sin devoluciones [localizacion|persona]' WHERE ID_TIPO_DATO = 3038;

-- Eliminación de la relación entre algoritmo PorVentaSimplificado en todas sus variantes y tipo cálculo
DELETE FROM ALGORITMO_TIPO_CALCULO WHERE ID_ALGORITMO IN (8001,8002,8003,8006,8007,8008,8011,8012,8013);

-- Eliminación de la relación entre algoritmo PorVentaSimplificado en tdoas sus variantes y tipo comisión
DELETE FROM ALGORITMO_TIPO_COMISION WHERE ID_ALGORITMO IN (8001,8002,8003,8006,8007,8008,8011,8012,8013);

-- Eliminación de la relación entre algoritmo PorVentaSimplificado en todas sus variantes y tipo dato
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO IN (8001,8002,8003,8006,8007,8008,8011,8012,8013);

-- Eliminación del propio algoritmo PorVentaSimplificado en todas sus variantes
DELETE FROM ALGORITMO WHERE ID_ALGORITMO IN (8001,8002,8003,8006,8007,8008,8011,8012,8013);

-- Tipos de dato relacionados con PorVentaSimplificado
DELETE FROM TIPO_DATO WHERE ID_TIPO_DATO IN (3032, 5013);

-- Eliminación de la relación entre algoritmo PorVentaGlobalTienda en todas sus variantes y tipo cálculo
DELETE FROM algoritmo_tipo_calculo WHERE ID_ALGORITMO IN (7020,7021,7022,7023,7024,7025);

-- Eliminación de la relación entre algoritmo PorVentaGlobalTienda en todas sus variantes y tipo comisión
DELETE FROM algoritmo_tipo_comision WHERE ID_ALGORITMO IN (7020,7021,7022,7023,7024,7025);

-- Eliminación de la relación entre algoritmo PorVentaGlobalTienda en todas sus variantes y tipo dato
DELETE FROM algoritmo_tipo_dato WHERE ID_ALGORITMO IN (7020,7021,7022,7023,7024,7025);

-- Desactivación propio algoritmo PorventaGlobalTienda en todas sus variantes
DELETE FROM algoritmo WHERE ID_ALGORITMO IN (7020,7021,7022,7023,7024,7025);

-- Nuevo tipo de grupo de dato para los calculos VentaOnline
-- TIPO_GRUPO_DATO
INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (2033, 'VENTA_ONLINE_EXCLUIDO_IPOD_LOCALIZACION', 'Venta online exclulido ipod [localizacion]');

-- TIPO_GRUPO_DATO_TIPO_DATO
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2033, 2006);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2033, 2008);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2033, 3002);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2033, 3008);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2033, 3010);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (2033, 3012);

--Nuevos tipos de cálculo y algoritmos para VentaOnline
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('015', 'GLOBAL_TIENDA_VENTA_ONLINE');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('016', 'GLOBAL_SECCION_VENTA_ONLINE');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES ('017', 'DIRECTO_VENTA_ONLINE');

-- Global Tienda Sólo Online
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (8001, 0, 'globalTiendaVentaOnlinePorcentajeV1', 0, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (8001, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8001, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8001, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8001, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8001, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8001, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8001, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8001, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8001, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8001, '017');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (8006, 0, 'globalTiendaVentaOnlinePorcentajeDesplazamientoV1', 1, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (8006, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8006, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8006, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8006, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8006, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8006, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8006, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8006, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8006, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8006, '017');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (8011, 0, 'globalTiendaVentaOnlinePorcentajeDesplazamientoBaseV1', 1, 1);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (8011, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8011, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8011, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8011, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8011, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8011, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8011, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8011, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8011, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (8011, '017');

--Global Sección sólo online
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (18001, 0, 'globalTiendaSeccionVentaOnlinePorcentajeV1', 0, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (18001, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18001, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18001, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18001, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18001, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18001, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18001, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18001, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18001, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18001, '017');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (18006, 0, 'globalTiendaSeccionVentaOnlinePorcentajeDesplazamientoV1', 1, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (18006, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18006, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18006, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18006, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18006, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18006, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18006, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18006, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18006, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18006, '017');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (18011, 0, 'globalTiendaSeccionVentaOnlinePorcentajeDesplazamientoBaseV1', 1, 1);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (18011, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18011, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18011, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18011, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18011, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18011, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18011, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18011, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18011, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (18011, '017');

--Directo Venta sólo online
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (19001, 0, 'directoVentaVentaOnlinePorcentajeV1', 0, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (19001, '017');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19001, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19001, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19001, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19001, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19001, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19001, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19001, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19001, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19001, '017');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (19006, 0, 'directoVentaVentaOnlinePorcentajeDesplazamientoV1', 1, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (19006, '017');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19006, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19006, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19006, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19006, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19006, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19006, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19006, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19006, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19006, '017');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (19011, 0, 'directoVentaVentaOnlinePorcentajeDesplazamientoBaseV1', 1, 1);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (19011, '017');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19011, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19011, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19011, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19011, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19011, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19011, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19011, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19011, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (19011, '017');

-- Global Tienda Personas Por Venta no vendedores (usando el tipo cálculo global tienda venta online)
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (20001, 0, 'globalTiendaPersonasPorVentaNoVendedoresPorcentajeV1', 0, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (20001, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20001, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20001, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20001, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20001, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20001, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20001, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20001, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20001, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20001, '017');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (20006, 0, 'globalTiendaPersonasPorVentaNoVendedoresPorcentajeDesplazamientoV1', 1, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (20006, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20006, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20006, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20006, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20006, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20006, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20006, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20006, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20006, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20006, '017');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (20011, 0, 'globalTiendaPersonasPorVentaNoVendedoresPorcentajeDesplazamientoBaseV1', 1, 1);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (20011, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20011, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20011, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20011, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20011, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20011, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20011, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20011, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20011, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (20011, '017');

-- Global Sección Personas Por Venta no vendedores (usando el tipo cálculo global tienda venta online)
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (21001, 0, 'globalTiendaSeccionPersonasPorVentaNoVendedoresPorcentajeV1', 0, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (21001, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21001, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21001, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21001, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21001, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21001, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21001, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21001, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21001, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21001, '017');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (21006, 0, 'globalTiendaSeccionPersonasPorVentaNoVendedoresPorcentajeDesplazamientoV1', 1, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (21006, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21006, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21006, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21006, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21006, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21006, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21006, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21006, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21006, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21006, '017');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (21011, 0, 'globalTiendaSeccionPersonasPorVentaNoVendedoresPorcentajeDesplazamientoBaseV1', 1, 1);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (21011, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21011, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21011, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21011, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21011, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21011, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21011, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21011, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21011, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (21011, '017');

--Directo Venta Personas Por Venta no vendedores (usando el tipo cálculo global tienda venta online)
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (22001, 0, 'directoVentaPersonasPorVentaNoVendedoresPorcentajeV1', 0, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (22001, '017');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22001, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22001, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22001, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22001, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22001, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22001, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22001, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22001, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22001, '017');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (22006, 0, 'directoVentaPersonasPorVentaNoVendedoresPorcentajeDesplazamientoV1', 1, 0);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (22006, '017');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22006, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22006, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22006, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22006, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22006, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22006, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22006, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22006, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22006, '017');
INSERT INTO ALGORITMO (ID_ALGORITMO, ES_ACTIVO, NOMBRE, ES_DESPLAZAMIENTO, ES_DESPLAZAMIENTO_BASE) VALUES (22011, 0, 'directoVentaPersonasPorVentaNoVendedoresPorcentajeDesplazamientoBaseV1', 1, 1);
INSERT INTO ALGORITMO_TIPO_CALCULO (ID_ALGORITMO, ID_TIPO_CALCULO) VALUES (22011, '017');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22011, '001');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22011, '002');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22011, '003');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22011, '004');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22011, '005');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22011, '009');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22011, '015');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22011, '016');
INSERT INTO ALGORITMO_TIPO_COMISION (ID_ALGORITMO, ID_TIPO_COMISION) VALUES (22011, '017');
