/**********************************************************************/
/** AQUI ESTÁN LOS ÍNDICES QUE AÑADIMOS DESPUES DEL CAMBIO DE MODELO **/
/**********************************************************************/
CREATE INDEX IX_TAREA_PERSONA_ESTRUCTURA_DESPLAZAMIENTO_TEMPORAL_01 ON TAREA_PERSONA_ESTRUCTURA_DESPLAZAMIENTO (FECHA_INICIO_PERIODO, ID_TAREA, ICM_ID_ESTR_COMISION_PADRE, ICM_ID_ESTR_COMISION_BASE, ICM_ID_ESTR_COMISION, ORDINAL_ESTRUCTURA, CCL_ID_PERSON, STD_OR_HR_PERIOD, FECHA_INICIO, FECHA_FIN);