-- > 6000 (Localizacion)
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (6002, 'LOCALIZACION', 'Localizacion', 0, NULL, NULL);
-- > 8000 (Persona)
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (8002, 'PERSONA', 'Tipo de dato para los fallos de validacion respecto a Personas', 0, NULL, NULL);
-- > 11000 (Motivos Desplazamiento)
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (11001, 'MOTIVOS_DESPLAZAMIENTO', 'Tipo de dato para los fallos de validacion respecto a Desplazamientos', 0, NULL, NULL);
>>>>>>> d8a5ef515e5a469b0fee2ca128f683906ebfbcb2
