-- TODO [javierev] WHERE 1 = 1 para evitar que Sonar se queje de que no tiene cláusula WHERE
DELETE FROM ALGORITMO_TIPO_DATO WHERE 1 = 1;
-- ALGORITMO_TIPO_DATO
-- > globalTiendaPorcentajeV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1001, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1001, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1001, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1001, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1001, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1001, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1001, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1001, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1001, 3012);
-- > globalTiendaPorcentajeV1 (Presencia [localizacion|seccion|persona|tipo hora])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1001, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1001, 4003);
-- > globalTiendaPorcentajeV1 (Presencia [localizacion] [incluido denominador])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1001, 5001);
-- > globalTiendaPorcentajeDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1006, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1006, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1006, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1006, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1006, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1006, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1006, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1006, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1006, 3012);
-- > globalTiendaPorcentajeDesplazamientoV1 (Presencia [localizacion|seccion|persona|tipo hora])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1006, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1006, 4003);
-- > globalTiendaPorcentajeDesplazamientoV1 (Presencia [localizacion] [incluido denominador])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1006, 5001);
-- > globalTiendaPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1011, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1011, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1011, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1011, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1011, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1011, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1011, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1011, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1011, 3012);
-- > globalTiendaPorcentajeDesplazamientoBaseV1 (Presencia [localizacion|seccion|persona|tipo hora])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1011, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1011, 4003);
-- > globalTiendaPorcentajeDesplazamientoBaseV1 (Presencia [localizacion] [incluido denominador])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (1011, 5001);
-- > globalTiendaSeccionPorcentajeV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2001, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2001, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2001, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2001, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2001, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2001, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2001, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2001, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2001, 3012);
-- > globalTiendaSeccionPorcentajeV1 (Presencia [localizacion|seccion|persona|tipo hora])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2001, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2001, 4003);
-- > globalTiendaSeccionPorcentajeV1 (Presencia [localizacion|seccion] [incluido denominador])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2001, 5002);
-- > globalTiendaSeccionPorcentajeDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2006, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2006, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2006, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2006, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2006, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2006, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2006, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2006, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2006, 3012);
-- > globalTiendaSeccionPorcentajeDesplazamientoV1 (Presencia [localizacion|seccion|persona|tipo hora])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2006, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2006, 4003);
-- > globalTiendaSeccionPorcentajeDesplazamientoV1 (Presencia [localizacion|seccion] [incluido denominador])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2006, 5002);
-- > globalTiendaSeccionPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2011, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2011, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2011, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2011, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2011, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2011, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2011, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2011, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2011, 3012);
-- > globalTiendaSeccionPorcentajeDesplazamientoBaseV1 (Presencia [localizacion|seccion|persona|tipo hora])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2011, 4002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2011, 4003);
-- > globalTiendaSeccionPorcentajeDesplazamientoBaseV1 (Presencia [localizacion|seccion] [incluido denominador])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (2011, 5002);
-- > directoVentaPorcentajeV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3001, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3001, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3001, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3001, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3001, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3001, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3001, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3001, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3001, 3012);
-- > directoVentaPorcentajeDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3006, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3006, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3006, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3006, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3006, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3006, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3006, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3006, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3006, 3012);
-- > directoVentaPorcentajeDesplazamientoV1 (Indicador Presencia [localizacion|persona|tipohora|desplazamiento])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3006, 5007);
-- > directoVentaPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3011, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3011, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3011, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3011, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3011, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3011, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3011, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3011, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3011, 3012);
-- > directoVentaPresenciaPorcentajeV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4001, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4001, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4001, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4001, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4001, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4001, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4001, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4001, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4001, 3012);
-- > directoVentaPresenciaPorcentajeV1 (Indicador Presencia [localizacion|persona|tipohora])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4001, 5006);
-- > directoVentaPresenciaPorcentajeDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4006, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4006, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4006, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4006, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4006, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4006, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4006, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4006, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4006, 3012);
-- > directoVentaPresenciaPorcentajeDesplazamientoV1 (Indicador Presencia [localizacion|persona|tipohora|desplazamiento])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4006, 5007);
-- > directoVentaPresenciaPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4011, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4011, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4011, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4011, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4011, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4011, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4011, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4011, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4011, 3012);
-- > directoVentaPresenciaPorcentajeDesplazamientoBaseV1 (Indicador Presencia [localizacion|persona|tipohora])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (4011, 5006);
-- > directoVentaReduccionJornadaPorcentajeV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5001, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5001, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5001, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5001, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5001, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5001, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5001, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5001, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5001, 3012);
-- > directoVentaReduccionJornadaPorcentajeDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5006, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5006, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5006, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5006, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5006, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5006, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5006, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5006, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5006, 3012);
-- > directoVentaReduccionJornadaPorcentajeDesplazamientoV1 (Indicador Presencia [localizacion|persona|tipohora|desplazamiento])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5006, 5007);
-- > directoVentaReduccionJornadaPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5011, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5011, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5011, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5011, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5011, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5011, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5011, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5011, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5011, 3012);
-- > directoVentaPresenciaReduccionJornadaPorcentajeV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6001, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6001, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6001, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6001, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6001, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6001, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6001, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6001, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6001, 3012);
-- > directoVentaPresenciaReduccionJornadaPorcentajeV1 (Indicador Presencia [localizacion|persona|tipohora])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6001, 5006);
-- > directoVentaPresenciaReduccionJornadaPorcentajeDesplazamientoV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6006, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6006, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6006, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6006, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6006, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6006, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6006, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6006, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6006, 3012);
-- > directoVentaPresenciaReduccionJornadaPorcentajeV1 (Indicador Presencia [localizacion|persona|tipohora|desplazamiento])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6006, 5007);
-- > directoVentaPresenciaReduccionJornadaPorcentajeDesplazamientoBaseV1 (Venta [localizacion|seccion])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6011, 2002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6011, 2004);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6011, 2006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6011, 2008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6011, 3002);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6011, 3006);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6011, 3008);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6011, 3010);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6011, 3012);
-- > directoVentaPresenciaReduccionJornadaPorcentajeV1 (Indicador Presencia [localizacion|persona|tipohora])
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (6011, 5006);
