INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (20, 'condicionesHistoricoSinChallengeV1', 'The employees conditions history differ between SIL and INCOME. ', 100, 1, 1, 2, 180000);
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (21, 'condicionesDesplazamientoSinChallengeV1', 'Displacement conditions differ between SIL and INCOME. ', 100, 1, 1, 2, 180000);
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (22, 'condicionesResaltaSinChallengeV1', 'Resalta conditions differ between SIL and INCOME. ', 100, 1, 1, 2, 180000);

INSERT INTO FASE_ACCION (ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 20, 3, 100);
INSERT INTO FASE_ACCION (ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 21, 3, 100);
INSERT INTO FASE_ACCION (ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 22, 3, 100);

--BY
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,73,486, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,73,486, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,73,486, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,73,487, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,73,487, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,73,487, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,73,488, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,73,488, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,73,488, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,73,489, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,73,489, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,73,489, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,73,490, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,73,490, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,73,490, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,73,491, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,73,491, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,73,491, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,73,492, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,73,492, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,73,492, 0, '', '0001-01-01 00:00:00', null, null, null, null);

--TW

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,736,360, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,736,360, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,736,360, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,736,390, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,736,390, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,736,390, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,736,406, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,736,406, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,736,406, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,736,413, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,736,413, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,736,413, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,736,414, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,736,414, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,736,414, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,736,473, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,736,473, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,736,473, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,736,513, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,736,513, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,736,513, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,736,514, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,736,514, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,736,514, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,736,515, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,736,515, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,736,515, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,736,516, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,736,516, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,736,516, 0, '', '0001-01-01 00:00:00', null, null, null, null);

--KZ
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,79,364, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,79,364, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,79,364, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,79,365, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,79,365, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,79,365, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,79,366, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,79,366, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,79,366, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,79,367, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,79,367, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,79,367, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,79,368, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,79,368, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,79,368, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,79,420, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,79,420, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,79,420, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,79,421, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,79,421, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,79,421, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,79,499, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,79,499, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,79,499, 0, '', '0001-01-01 00:00:00', null, null, null, null);


--JP

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,732,331, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,732,331, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,732,331, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,732,379, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,732,379, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,732,379, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,732,391, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,732,391, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,732,391, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,732,419, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,732,419, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,732,419, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,732,462, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,732,462, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,732,462, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,732,506, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,732,506, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,732,506, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,732,73, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,732,73, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,732,73, 0, '', '0001-01-01 00:00:00', null, null, null, null);

INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (20,732,77, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (21,732,77, 0, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (22,732,77, 0, '', '0001-01-01 00:00:00', null, null, null, null);


