-- Validacion comision manual
INSERT INTO ACCION (ID_ACCION, NOMBRE, DESCRIPCION, REACCION_PESO, ES_REACCION_ESPERAR, ES_REACCION_REINTENTO, REACCION_REINTENTO_MAX, REACCION_REINTENTO_DELAY) VALUES (23, 'comisionManualV1', 'The employees manual comission differ between SIL and INCOME. ', 100, 1, 1, 2, 180000);
INSERT INTO FASE_ACCION (ID_FASE, ID_ACCION, ID_PUNTO_EJECUCION, PESO) VALUES (1, 23, 3, 100);

-- Ambito
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (23,11,2, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (23,11,8, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (23,11,11, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (23,11,25, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (23,11,28, 1, '', '0001-01-01 00:00:00', null, null, null, null);
INSERT INTO ACCION_AMBITO (ID_ACCION, CCL_ID_ORIGEN, STD_ID_LEG_ENT, ES_ACTIVO, USUARIO_ALTA, FECHA_ALTA, USUARIO_MODIFICACION, FECHA_MODIFICACION, USUARIO_BAJA, FECHA_BAJA) VALUES (23,11,101, 1, '', '0001-01-01 00:00:00', null, null, null, null);
