/**********************************************************************/
/** AQUI ESTÁN LOS ÍNDICES QUE AÑADIMOS DESPUES DEL CAMBIO DE MODELO **/
/**********************************************************************/
-- TAREA_AGRUPACION_CADENA
CREATE INDEX IX_TAREA_AGRUPACION_CADENA_01 ON TAREA_AGRUPACION_CADENA (ID_TAREA, CCL_ID_CADENA);
-- TAREA_CALCULO_AJUSTE
CREATE INDEX IX_TAREA_CALCULO_AJUSTE_01 ON TAREA_CALCULO_AJUSTE (FECHA_INICIO_PERIODO, ID_TAREA, CCL_ID_PERSON, STD_OR_HR_PERIOD, FECHA);
-- TAREA_LOCALIZACION_ABIERTA
CREATE INDEX IX_TAREA_LOCALIZACION_ABIERTA_01 ON TAREA_LOCALIZACION_ABIERTA (ID_TAREA, CCL_ID_COD_ORIGEN, FECHA);
-- TAREA_LOCALIZACION_CALCULAR
CREATE INDEX IX_TAREA_LOCALIZACION_CALCULAR_01 ON TAREA_LOCALIZACION_CALCULAR (ID_TAREA, CCL_ID_COD_ORIGEN, FECHA_INICIO, FECHA_FIN);
CREATE INDEX IX_TAREA_LOCALIZACION_CALCULAR_02 ON TAREA_LOCALIZACION_CALCULAR (ID_TAREA, STD_ID_WORK_LOCAT, FECHA_INICIO, FECHA_FIN);
-- TAREA_LOCALIZACION_COMISION_HISTORICO
CREATE INDEX IX_TAREA_LOCALIZACION_COMISION_HISTORICO_01 ON TAREA_LOCALIZACION_COMISION_HISTORICO (ID_TAREA, CCL_ID_COD_ORIGEN, FECHA_INICIO, FECHA_FIN);
CREATE INDEX IX_TAREA_LOCALIZACION_COMISION_HISTORICO_02 ON TAREA_LOCALIZACION_COMISION_HISTORICO (ID_TAREA, STD_ID_WORK_LOCAT, FECHA_INICIO, FECHA_FIN);
-- TAREA_LOCALIZACION_FESTIVO
CREATE INDEX IX_TAREA_LOCALIZACION_FESTIVO_01 ON TAREA_LOCALIZACION_FESTIVO (ID_TAREA, STD_ID_WORK_LOCAT, FECHA);
-- TAREA_LOCALIZACION_ONLINE_HISTORICO
CREATE INDEX IX_TAREA_LOCALIZACION_ONLINE_HISTORICO_01 ON TAREA_LOCALIZACION_ONLINE_HISTORICO (ID_TAREA, CCL_ID_COD_ORIGEN, FECHA_INICIO, FECHA_FIN);
CREATE INDEX IX_TAREA_LOCALIZACION_ONLINE_HISTORICO_02 ON TAREA_LOCALIZACION_ONLINE_HISTORICO (ID_TAREA, STD_ID_WORK_LOCAT, FECHA_INICIO, FECHA_FIN);
-- TAREA_LOCALIZACION_HISTORICO
CREATE INDEX IX_TAREA_LOCALIZACION_HISTORICO_01 ON TAREA_LOCALIZACION_HISTORICO (ID_TAREA, CCL_ID_COD_ORIGEN, FECHA_INICIO, FECHA_FIN);
CREATE INDEX IX_TAREA_LOCALIZACION_HISTORICO_02 ON TAREA_LOCALIZACION_HISTORICO (ID_TAREA, STD_ID_WORK_LOCAT, FECHA_INICIO, FECHA_FIN);
-- TAREA_LOCALIZACION_PERSONA_PRESENCIA
CREATE INDEX IX_TAREA_LOCALIZACION_PERSONA_PRESENCIA_01 ON TAREA_LOCALIZACION_PERSONA_PRESENCIA (FECHA_INICIO_PERIODO, ID_TAREA, CCL_ID_PERSON, FECHA, CCL_ID_COD_ORIGEN);
CREATE INDEX IX_TAREA_LOCALIZACION_PERSONA_PRESENCIA_02 ON TAREA_LOCALIZACION_PERSONA_PRESENCIA (FECHA_INICIO_PERIODO, ID_TAREA, CCL_ID_COD_ORIGEN, FECHA, CCL_ID_PERSON);
-- TAREA_LOCALIZACION_PERSONA_VENTA
CREATE INDEX IX_TAREA_LOCALIZACION_PERSONA_VENTA_01 ON TAREA_LOCALIZACION_PERSONA_VENTA (FECHA_INICIO_PERIODO, ID_TAREA, CCL_ID_PERSON, FECHA, CCL_ID_COD_ORIGEN);
CREATE INDEX IX_TAREA_LOCALIZACION_PERSONA_VENTA_02 ON TAREA_LOCALIZACION_PERSONA_VENTA (FECHA_INICIO_PERIODO, ID_TAREA, CCL_ID_COD_ORIGEN, FECHA, CCL_ID_PERSON);
-- TAREA_LOCALIZACION_PRESENCIA
CREATE INDEX IX_TAREA_LOCALIZACION_PRESENCIA_01 ON TAREA_LOCALIZACION_PRESENCIA (FECHA_INICIO_PERIODO, ID_TAREA, CCL_ID_COD_ORIGEN, FECHA);
-- TAREA_LOCALIZACION_VENTA
CREATE INDEX IX_TAREA_LOCALIZACION_VENTA_01 ON TAREA_LOCALIZACION_VENTA (FECHA_INICIO_PERIODO, ID_TAREA, CCL_ID_COD_ORIGEN, FECHA);
-- TAREA_PERSONA_HISTORICO
CREATE INDEX IX_TAREA_PERSONA_HISTORICO_01 ON TAREA_PERSONA_HISTORICO (FECHA_INICIO_PERIODO, ID_TAREA, CCL_ID_PERSON, STD_OR_HR_PERIOD);
-- TAREA_PERSONA_ESTRUCTURA
CREATE INDEX IX_TAREA_PERSONA_ESTRUCTURA_01 ON TAREA_PERSONA_ESTRUCTURA (FECHA_INICIO_PERIODO, ID_TAREA, CCL_ID_PERSON, STD_OR_HR_PERIOD, ICM_ID_TP_CALCULO, ICM_ID_TP_COMISION);
-- TAREA_PERSONA_AUSENCIA_HISTORICO
CREATE INDEX IX_TAREA_PERSONA_AUSENCIA_HISTORICO_01 ON TAREA_PERSONA_AUSENCIA_HISTORICO (ID_TAREA, CCL_ID_PERSON, STD_OR_HR_PERIOD);
-- TAREA_PERSONA_COEFICIENTE
CREATE INDEX IX_TAREA_PERSONA_COEFICIENTE_01 ON TAREA_PERSONA_COEFICIENTE (ID_TAREA, CCL_ID_PERSON, STD_OR_HR_PERIOD);
-- TAREA_PERSONA_ESTRUCTURA_POLITICA
CREATE INDEX IX_TAREA_PERSONA_ESTRUCTURA_POLITICA_01 ON TAREA_PERSONA_ESTRUCTURA_POLITICA (FECHA_INICIO_PERIODO, ID_TAREA, CCL_ID_PERSON, STD_OR_HR_PERIOD, ID_TIPO_POLITICA);
-- TAREA_TIPO_HORA
CREATE INDEX IX_TAREA_TIPO_HORA_01 ON TAREA_TIPO_HORA (ID_TAREA, ID_TIPO_HORA);
-- TAREA_PERSONA_ESTRUCTURA_DESPLAZAMIENTO
CREATE INDEX IX_TAREA_PERSONA_ESTRUCTURA_DESPLAZAMIENTO_01 ON TAREA_PERSONA_ESTRUCTURA_DESPLAZAMIENTO (FECHA_INICIO_PERIODO, ID_TAREA, CCL_ID_PERSON, STD_OR_HR_PERIOD, ORDINAL_ESTRUCTURA);
-- TAREA_CALCULO
CREATE INDEX IX_TAREA_CALCULO_01 ON TAREA_CALCULO (FECHA_INICIO_PERIODO, ID_TAREA, CCL_ID_PERSON, STD_OR_HR_PERIOD, FECHA, STD_ID_WORK_LOCAT);
CREATE INDEX IX_TAREA_CALCULO_02 ON TAREA_CALCULO (FECHA_INICIO_PERIODO, ID_TAREA, CCL_ID_PERSON, STD_OR_HR_PERIOD, FECHA, STD_ID_WORK_LOCAT_PAGO);
