/*Tipos presupuesto*/
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (1, '01', 'Mensual', 'Mensual');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (2, '02', 'Bimensual', 'Bimensual');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (3, '03', 'Trimestral', 'Trimestral');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (4, '04', 'Cuatrimestral', 'Cuatrimestral');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (5, '05', 'Semestral', 'Semestral');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (6, '06', 'Anual', 'Anual');
INSERT INTO TIPO_PRESUPUESTO (ID_TIPO_PRESUPUESTO, ICM_ID_TP_PRESUPUESTO, NOMBRE, DESCRIPCION) VALUES (7, '07', 'Abierto', 'Abierto');

/*Tipos concepto venta challenge*/
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (1, 'VENTA_CAJA', 'Venta caja', '01', 1);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (2, 'DEVOLUCIONES_OTRAS_TIENDAS', 'Devoluciones otras tiendas', '02', 1);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (3, 'ONLINE_IPOD', 'Venta online iPod', '03', 2);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (4, 'ONLINE_SINT', 'Venta online SINT', '04', 3);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (5, 'ONLINE_ENTREGA_TIENDA', 'Venta online entrega en tienda', '05', 4);
INSERT INTO TIPO_VENTA_CONCEPTO_CHALLENGE (ID_TIPO_VENTA_CONCEPTO_CHALLENGE, NOMBRE, DESCRIPCION, ICM_ID_CONCEPTO_VENTA, ID_TIPO_VENTA) VALUES (6, 'ONLINE_ENTREGA_DOMICILIO', 'Venta online entrega en domicilio', '06', 5);

/*Nuevos tipos de dato*/
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2015, 'VENTA_RANGO_CONGELADA_FISICA_CAJA_LOCALIZACION', 'Venta rango congelada fisica [localizacion]', 0, NULL, 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2016, 'VENTA_RANGO_CONGELADA_FISICA_CAJA_LOCALIZACION_SECCION', 'Venta rango congelada fisica [localizacion|seccion]', 0, NULL, 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2017, 'VENTA_RANGO_CONGELADA_FISICA_DEVOLUCION_LOCALIZACION', 'Venta rango congelada fisica [localizacion]', 0, NULL, 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2018, 'VENTA_RANGO_CONGELADA_FISICA_DEVOLUCION_LOCALIZACION_SECCION', 'Venta rango congelada fisica [localizacion|seccion]', 0, NULL, 1);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2019, 'VENTA_RANGO_CONGELADA_ONLINE_ENTREGADOMICILIO_LOCALIZACION', 'Venta rango congelada online entrega domicilio [localizacion]', 0, NULL, 5);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2020, 'VENTA_RANGO_CONGELADA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_SECCION', 'Venta rango congelada online entrega domicilio [localizacion|seccion]', 0, NULL, 5);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2021, 'VENTA_RANGO_CONGELADA_ONLINE_IPOD_LOCALIZACION', 'Venta rango congelada online ipod [localizacion]', 0, NULL, 2);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2022, 'VENTA_RANGO_CONGELADA_ONLINE_IPOD_LOCALIZACION_SECCION', 'Venta rango congelada online ipod [localizacion|seccion]', 0, NULL, 2);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2023, 'VENTA_RANGO_CONGELADA_ONLINE_SINT_LOCALIZACION', 'Venta rango congelada online sint [localizacion]', 0, NULL, 3);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2024, 'VENTA_RANGO_CONGELADA_ONLINE_SINT_LOCALIZACION_SECCION', 'Venta rango congelada online sint [localizacion|seccion]', 0, NULL, 3);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2025, 'VENTA_RANGO_CONGELADA_ONLINE_ENTREGATIENDA_LOCALIZACION', 'Venta rango congelada online entrega tienda [localizacion]', 0, NULL, 4);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (2026, 'VENTA_RANGO_CONGELADA_ONLINE_ENTREGATIENDA_LOCALIZACION_SECCION', 'Venta rango congelada online entrega tienda [localizacion|seccion]', 0, NULL, 4);


