INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (5016, 'INDICADOR_LOCALIZACION-PERSONA-TIPOHORA-DESPLAZAMIENTO', 'Indicador [localizacion|persona|tipo hora|desplazamiento]', 0, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (5017, 'INDICADOR_LOCALIZACION-PERSONA-TIPOHORA-DESPLAZAMIENTO-BASE', 'Indicador [localizacion|persona|tipo hora|desplazamiento base]', 0, NULL, NULL);

DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 3006 AND ID_TIPO_DATO = 5007;
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 3007 AND ID_TIPO_DATO = 5007;
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 3008 AND ID_TIPO_DATO = 5007;
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 5006 AND ID_TIPO_DATO = 5007;
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 5007 AND ID_TIPO_DATO = 5007;
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 5008 AND ID_TIPO_DATO = 5007;

DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 3011 AND ID_TIPO_DATO = 5008;
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 3012 AND ID_TIPO_DATO = 5008;
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 3013 AND ID_TIPO_DATO = 5008;
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 5011 AND ID_TIPO_DATO = 5008;
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 5012 AND ID_TIPO_DATO = 5008;
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 5013 AND ID_TIPO_DATO = 5008;

INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3006, 5016);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3007, 5016);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3008, 5016);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5006, 5016);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5007, 5016);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5008, 5016);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (13006, 5016);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (16006, 5016);

INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3011, 5017);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3012, 5017);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (3013, 5017);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5011, 5017);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5012, 5017);
INSERT INTO ALGORITMO_TIPO_DATO (ID_ALGORITMO, ID_TIPO_DATO) VALUES (5013, 5017);
