UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 11011;
UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 11006;

UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 10011;
UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 10006;

UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 17011;
UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 17006;


