-- ESTADO_TAREA
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (1, 'PENDIENTE DATOS');
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (2, 'EN CURSO DATOS');
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (3, 'PENDIENTE CALCULO');
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (4, 'EN CURSO CALCULO');
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (5, 'PENDIENTE CONSOLIDACION');
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (6, 'EN CURSO CONSOLIDACION');
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (7, 'FINALIZADO SIN ERRORES');
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (8, 'FINALIZADO CON ERRORES');
INSERT INTO ESTADO_TAREA (ID_ESTADO_TAREA, NOMBRE) VALUES (9, 'ERROR');
-- ESTADO_PROCESO
INSERT INTO ESTADO_PROCESO (ID_ESTADO_PROCESO, NOMBRE) VALUES (1, 'PENDIENTE DATOS');
INSERT INTO ESTADO_PROCESO (ID_ESTADO_PROCESO, NOMBRE) VALUES (2, 'EN CURSO DATOS');
INSERT INTO ESTADO_PROCESO (ID_ESTADO_PROCESO, NOMBRE) VALUES (3, 'PENDIENTE CALCULO');
INSERT INTO ESTADO_PROCESO (ID_ESTADO_PROCESO, NOMBRE) VALUES (4, 'EN CURSO CALCULO');
INSERT INTO ESTADO_PROCESO (ID_ESTADO_PROCESO, NOMBRE) VALUES (5, 'PENDIENTE CONSOLIDACION');
INSERT INTO ESTADO_PROCESO (ID_ESTADO_PROCESO, NOMBRE) VALUES (6, 'EN CURSO CONSOLIDACION');
INSERT INTO ESTADO_PROCESO (ID_ESTADO_PROCESO, NOMBRE) VALUES (7, 'FINALIZADO SIN ERRORES');
INSERT INTO ESTADO_PROCESO (ID_ESTADO_PROCESO, NOMBRE) VALUES (8, 'FINALIZADO CON ERRORES');
INSERT INTO ESTADO_PROCESO (ID_ESTADO_PROCESO, NOMBRE) VALUES (9, 'ERROR');
-- ESTADO_PROCESO_EMPLEADO
INSERT INTO ESTADO_PROCESO_EMPLEADO (ID_ESTADO_PROCESO_EMPLEADO, NOMBRE) VALUES (1, 'PENDIENTE');
INSERT INTO ESTADO_PROCESO_EMPLEADO (ID_ESTADO_PROCESO_EMPLEADO, NOMBRE) VALUES (2, 'FINALIZADO');
INSERT INTO ESTADO_PROCESO_EMPLEADO (ID_ESTADO_PROCESO_EMPLEADO, NOMBRE) VALUES (3, 'ERROR');
-- TIPO_PROCESO_TIENDA
INSERT INTO TIPO_PROCESO_TIENDA (ID_TIPO_PROCESO_TIENDA, NOMBRE) VALUES (1, 'INICIAL');
INSERT INTO TIPO_PROCESO_TIENDA (ID_TIPO_PROCESO_TIENDA, NOMBRE) VALUES (2, 'PARAMETRO');
INSERT INTO TIPO_PROCESO_TIENDA (ID_TIPO_PROCESO_TIENDA, NOMBRE) VALUES (3, 'HISTORICO');
INSERT INTO TIPO_PROCESO_TIENDA (ID_TIPO_PROCESO_TIENDA, NOMBRE) VALUES (4, 'PRESENCIA');
-- TIPO_CALCULO
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES (0, 'NINGUNO');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES (1, 'GLOBAL_TIENDA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES (2, 'GLOBAL_SECCION');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES (3, 'DIRECTO_SOBRE_VENTA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES (4, 'DIRECTO_SOBRE_VENTA_CON_PRESENCIA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES (5, 'DIRECTO_SOBRE_VENTA_CON_REDUCCION_DE_JORNADA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES (6, 'DIRECTO_SOBRE_VENTA_CON_PRESENCIA_Y_REDUCCION_DE_JORNADA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES (7, 'POR_VENTA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES (8, 'POR_VENTA_SIMPLIFICADA');
INSERT INTO TIPO_CALCULO (ID_TIPO_CALCULO, NOMBRE) VALUES (9, 'POR_VENTA_INDIVIDUAL');
--TIPO_COMISION
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES (1, 'COMISION');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES (2, 'RESALTA_FUNCION');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES (3, 'RESALTA_PERSONAL');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES (4, 'RESALTA_TIENDA');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES (5, 'INCENTIVO');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES (6, 'COMISION_POR_TOPES');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES (7, 'MANUAL');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES (8, 'COMISION_DIARIA');
INSERT INTO TIPO_COMISION (ID_TIPO_COMISION, NOMBRE) VALUES (9, 'PRIMA');
--ALGORITMO
INSERT INTO ALGORITMO (ID_ALGORITMO, ACTIVO, NOMBRE, ID_TIPO_COMISION, ID_TIPO_CALCULO) VALUES (1, 1, 'globalTiendaVersion1Algoritmo', 1, 1);
