DELETE FROM ALGORITMO_TIPO_CALCULO WHERE ID_ALGORITMO = 11006;
DELETE FROM ALGORITMO_TIPO_COMISION WHERE ID_ALGORITMO = 11006;

DELETE FROM ALGORITMO_TIPO_CALCULO WHERE ID_ALGORITMO = 11011;
DELETE FROM ALGORITMO_TIPO_COMISION WHERE ID_ALGORITMO = 11011;
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 11011;

DELETE FROM ALGORITMO_TIPO_CALCULO WHERE ID_ALGORITMO = 17006;
DELETE FROM ALGORITMO_TIPO_COMISION WHERE ID_ALGORITMO = 17006;
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 17006;

DELETE FROM ALGORITMO_TIPO_CALCULO WHERE ID_ALGORITMO = 17011;
DELETE FROM ALGORITMO_TIPO_COMISION WHERE ID_ALGORITMO = 17011;
DELETE FROM ALGORITMO_TIPO_DATO WHERE ID_ALGORITMO = 17011;

DELETE FROM ALGORITMO WHERE ID_ALGORITMO = 16011;
DELETE FROM ALGORITMO WHERE ID_ALGORITMO = 11006;
DELETE FROM ALGORITMO WHERE ID_ALGORITMO = 11011;
DELETE FROM ALGORITMO WHERE ID_ALGORITMO = 13011;
DELETE FROM ALGORITMO WHERE ID_ALGORITMO = 17006;
DELETE FROM ALGORITMO WHERE ID_ALGORITMO = 17011;

UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 7003;
UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 7008;
UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 7013;
UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 8003;
UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 8008;
UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 8013;
UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 9003;
UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 9008;
UPDATE ALGORITMO SET ES_ACTIVO = 0 WHERE ID_ALGORITMO = 9013;
