INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (4004, 'PRESENCIA_REAL_LOCALIZACION-SECCION-PERSONA-TIPO_HORA-INCLUIDOECOMMERCE', 'Presencias real [localizacion|seccion|persona|tipo hora|incluido ecommerce]', 0, 1, NULL);

INSERT INTO TIPO_GRUPO_DATO (ID_TIPO_GRUPO_DATO, NOMBRE, DESCRIPCION) VALUES (3007, 'PRESENCIA_LOCALIZACION-SECCION-PERSONA-TIPO_HORA-INCLUIDOECOMMERCE', 'Presencias [localizacion|seccion|persona|tipo hora|incluido ecommerce]');

INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3007, 4004);
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3007, 4003);
