-- TIPO_UNIDAD_TIEMPO
INSERT INTO TIPO_UNIDAD_TIEMPO (ID_TIPO_UNIDAD_TIEMPO, NOMBRE, ICM_ID_UNIDAD_TIEMPO) VALUES (0, 'NINGUNO', '00');
INSERT INTO TIPO_UNIDAD_TIEMPO (ID_TIPO_UNIDAD_TIEMPO, NOMBRE, ICM_ID_UNIDAD_TIEMPO) VALUES (1, 'ANOS', '01');
INSERT INTO TIPO_UNIDAD_TIEMPO (ID_TIPO_UNIDAD_TIEMPO, NOMBRE, ICM_ID_UNIDAD_TIEMPO) VALUES (2, 'MESES', '02');
INSERT INTO TIPO_UNIDAD_TIEMPO (ID_TIPO_UNIDAD_TIEMPO, NOMBRE, ICM_ID_UNIDAD_TIEMPO) VALUES (3, 'SEMANAS', '03');
INSERT INTO TIPO_UNIDAD_TIEMPO (ID_TIPO_UNIDAD_TIEMPO, NOMBRE, ICM_ID_UNIDAD_TIEMPO) VALUES (4, 'DIAS', '04');
INSERT INTO TIPO_UNIDAD_TIEMPO (ID_TIPO_UNIDAD_TIEMPO, NOMBRE, ICM_ID_UNIDAD_TIEMPO) VALUES (5, 'HORAS', '05');
INSERT INTO TIPO_UNIDAD_TIEMPO (ID_TIPO_UNIDAD_TIEMPO, NOMBRE, ICM_ID_UNIDAD_TIEMPO) VALUES (6, 'MINUTOS', '06');
-- TIPO_AUSENCIA
INSERT INTO TIPO_AUSENCIA (ID_TIPO_AUSENCIA, ICM_TP_ABSENCE, NOMBRE) VALUES (1, '1', 'BAJA_IT');
INSERT INTO TIPO_AUSENCIA (ID_TIPO_AUSENCIA, ICM_TP_ABSENCE, NOMBRE) VALUES (2, '2', 'VACACIONES');
-- ALGORITMO_AJUSTE
INSERT INTO ALGORITMO_AJUSTE (ID_ALGORITMO_AJUSTE, ID_TIPO_POLITICA, NOMBRE, PESO, ES_ACTIVO) VALUES (1, 3, 'carenciaV1', 5, 1);
INSERT INTO ALGORITMO_AJUSTE (ID_ALGORITMO_AJUSTE, ID_TIPO_POLITICA, NOMBRE, PESO, ES_ACTIVO) VALUES (2, 4, 'antiguedadV1', 1, 1);
INSERT INTO ALGORITMO_AJUSTE (ID_ALGORITMO_AJUSTE, ID_TIPO_POLITICA, NOMBRE, PESO, ES_ACTIVO) VALUES (3, 5, 'bajaItV1', 2, 1);
INSERT INTO ALGORITMO_AJUSTE (ID_ALGORITMO_AJUSTE, ID_TIPO_POLITICA, NOMBRE, PESO, ES_ACTIVO) VALUES (4, 6, 'vacacionesV1', 3, 1);
INSERT INTO ALGORITMO_AJUSTE (ID_ALGORITMO_AJUSTE, ID_TIPO_POLITICA, NOMBRE, PESO, ES_ACTIVO) VALUES (5, 7, 'minimoGarantizadoV1', 4, 1);
INSERT INTO ALGORITMO_AJUSTE (ID_ALGORITMO_AJUSTE, ID_TIPO_POLITICA, NOMBRE, PESO, ES_ACTIVO) VALUES (6, 8, 'maximoGarantizadoV1', 4, 1);
-- > 5000 (Presencia Procesado)
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (5010, 'PRESENCIA_HORASFIJAS_LOCALIZACION-SECCION-PERSONA-TIPO_HORA', 'Presencias horas fijas [localizacion|seccion|persona|tipo hora]', 1, 2, NULL);
-- TIPO_GRUPO_DATO_TIPO_DATO
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (1000, 5010);
-- > 3001 (PRESENCIAS LOCALIZACION SECCION)
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3001, 5010);
-- > 3006 (PRESENCIAS)
INSERT INTO TIPO_GRUPO_DATO_TIPO_DATO (ID_TIPO_GRUPO_DATO, ID_TIPO_DATO) VALUES (3006, 5010);
-- > 10000 (Operacion)
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (10001, 'OPERACION_VENTA_FISICA_LOCALIZACION_SECCION', 'Operacion de venta', 0, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (10002, 'OPERACION_DEVOLUCION_FISICA_LOCALIZACION_SECCION', 'Operacion de devolucionn', 0, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (10003, 'OPERACION_VENTA_ONLINE_IPOD_LOCALIZACION_SECCION', 'Operacion de venta iPod', 0, NULL, NULL);
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (10004, 'OPERACION_DEVOLUCION_ONLINE_IPOD_LOCALIZACION_SECCION', 'Operacion de devolucion iPod', 0, NULL, NULL);

