-- TIPO_DATO
INSERT INTO TIPO_DATO (ID_TIPO_DATO, NOMBRE, DESCRIPCION, ES_PROCESADO, ID_TIPO_PRESENCIA, ID_TIPO_VENTA) VALUES (5011, 'PRESENCIA_LOCALIZACION_SECCION_EMPLEADOS_POR_VENTA', 'Presencia [localizacion|seccion] [incluido venta empleados por venta]', 1, NULL, NULL);
UPDATE TIPO_DATO SET NOMBRE = 'IMPORTE_COMISION_VENDEDORES_POR_VENTA', DESCRIPCION = 'Importe comision vendedores [localizacion|seccion]' WHERE ID_TIPO_DATO = 3031;
-- TIPO_GRUPO_DATO
DELETE FROM TIPO_GRUPO_DATO_TIPO_DATO WHERE ID_TIPO_GRUPO_DATO = 2025;
DELETE FROM TIPO_GRUPO_DATO WHERE ID_TIPO_GRUPO_DATO = 2025;
