package com.inditex.rrhh.icmclcwb.api.ptr.venta;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum PtrGroupSellerTypeEnum {

  FECHA_VENDEDOR_TIENDA("FECHA_VENDEDOR_TIENDA"), FECHA_VENDEDOR_TIENDA_SECCION(
      "FECHA_VENDEDOR_TIENDA_SECCION"),
  FECHA_VENDEDOR_TIENDA_SECCION_TEMPORADA_PRODUCTO(
      "FECHA_VENDEDOR_TIENDA_SECCION_TEMPORADA_PRODUCTO"),
  FECHA_VENDEDOR_TIENDA_SECCION_TEMPORADA_PRODUCTO_CAJERO(
      "FECHA_VENDEDOR_TIENDA_SECCION_TEMPORADA_PRODUCTO_CAJERO"),
  OPERACION_FECHA_VENDEDOR_TIENDA(
      "OPERACION_FECHA_VENDEDOR_TIENDA"),
  OPERACION_FECHA_VENDEDOR_TIENDA_SECCION(
      "OPERACION_FECHA_VENDEDOR_TIENDA_SECCION"),
  OPERACION_FECHA_VENDEDOR_TIENDA_SECCION_TEMPORADA_PRODUCTO(
      "OPERACION_FECHA_VENDEDOR_TIENDA_SECCION_TEMPORADA_PRODUCTO"),
  OPERACION_FECHA_VENTA_INICIAL_VENDEDOR_TIENDA(
      "OPERACION_FECHA_VENTA_INICIAL_VENDEDOR_TIENDA"),
  OPERACION_FECHA_VENTA_INICIAL_VENDEDOR_TIENDA_SECCION(
      "OPERACION_FECHA_VENTA_INICIAL_VENDEDOR_TIENDA_SECCION"),
  OPERACION_FECHA_VENTA_INICIAL_VENDEDOR_TIENDA_SECCION_TEMPORADA_PRODUCTO(
      "OPERACION_FECHA_VENTA_INICIAL_VENDEDOR_TIENDA_SECCION_TEMPORADA_PRODUCTO"),
  FECHA_TIENDA(
      "FECHA_TIENDA"),
  FECHA_TIENDA_SECCION(
      "FECHA_TIENDA_SECCION"),
  FECHA_TIENDA_TIPOHORA_SECCION(
      "FECHA_TIENDA_TIPOHORA_SECCION"),
  OPERACION_FECHA_TIENDA(
      "OPERACION_FECHA_TIENDA"),
  FECHA_ORIGEN_EMPRESA_CADENA(
      "FECHA_ORIGEN_EMPRESA_CADENA");

  private String value;

}
