package com.inditex.rrhh.icmclcwb.api.ptr.venta;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum PtrGroupTypeEnum {

  FECHA_TIENDA("FECHA_TIENDA"), FECHA_TIENDA_SECCION("FECHA_TIENDA_SECCION"), FECHA_TIENDA_SECCION_TEMPORADA_PRODUCTO(
      "FECHA_TIENDA_SECCION_TEMPORADA_PRODUCTO"),
  FECHA_ORIGEN_EMPRESA_CADENA(
      "FECHA_ORIGEN_EMPRESA_CADENA"),
  FECHA_ORIGEN_EMPRESA_CADENA_SECCION(
      "FECHA_ORIGEN_EMPRESA_CADENA_SECCION"),
  FECHA_CADENA("FECHA_CADENA"), FECHA_CADENA_SECCION(
      "FECHA_CADENA_SECCION"),
  PERSONA("PERSONA"), PERSONA_TIENDA(
      "PERSONA_TIENDA"),
  TIENDA("TIENDA"), FECHA_TIENDA_TIPOHORA(
      "FECHA_TIENDA_TIPOHORA"),
  FECHA_TIENDA_TIPOHORA_SECCION(
      "FECHA_TIENDA_TIPOHORA_SECCION"),
  TIENDA_SECCION(
      "TIENDA_SECCION"),
  OPERACION_TIENDA_SECCION(
      "OPERACION_TIENDA_SECCION"),
  OPERACION_TIENDA(
      "OPERACION_TIENDA");

  private String value;

}
