CREATE TABLE IF NOT EXISTS GESTION_COMISION.TIPO_CALCULO_PRECIO_HORA (
    ID_TIPO_CALCULO VARGRAPHIC(12) NOT NULL PRIMARY KEY,
    ES_CHALLENGE_JORNADA DECIMAL(1) NOT NULL,
    ES_ACTIVO DECIMAL(1) NOT NULL,
    FECHA_CREACION TIMESTAMP NOT NULL,
    CONSTRAINT FK_TIPO_CALC_PRECIO_HORA_TIPO_CALCULO
      FOREIGN KEY (ID_TIPO_CALCULO)
      REFERENCES GESTION_COMISION.TIPO_CALCULO (ID_TIPO_CALCULO)
)
IN GESTCOMIS_01
INDEX IN GESTCOMIS_IDX_01
LONG IN GESTCOMIS_LOBS_01
ORGANIZE BY ROW;

COMMENT ON COLUMN GESTION_COMISION.TIPO_CALCULO_PRECIO_HORA.ID_TIPO_CALCULO IS 'Identificador del tipo de cálculo';
COMMENT ON COLUMN GESTION_COMISION.TIPO_CALCULO_PRECIO_HORA.ES_CHALLENGE_JORNADA IS 'Indica si es Challenge Jornada';
COMMENT ON COLUMN GESTION_COMISION.TIPO_CALCULO_PRECIO_HORA.ES_ACTIVO IS 'Indica si está activo';
COMMENT ON COLUMN GESTION_COMISION.TIPO_CALCULO_PRECIO_HORA.FECHA_CREACION IS 'Fecha y hora de creación del registro.';
