CREATE TABLE GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA (
    ID_TAREA_CALCULO_PERSONA_PRECIO_HORA BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    ID_TAREA BIGINT NOT NULL,
    ICM_ID_PERIODO BIGINT NOT NULL,
    CCL_ID_ORIGEN VARGRAPHIC(24) NOT NULL,
    STD_ID_LEG_ENT VARGRAPHIC(24) NOT NULL,
    CCL_ID_PERSON VARGRAPHIC(24) NOT NULL,
    STD_OR_HR_PERIOD VARGRAPHIC(24) NOT NULL,
    FECHA DATE NOT NULL,
    PRECIO_HORA DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_TAREA_CALC_PRECIO_HORA_TAREA
      FOREIGN KEY (ID_TAREA)
      REFERENCES GESTION_COMISION.TAREA (ID_TAREA)
);

COMMENT ON COLUMN GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA.ID_TAREA_CALCULO_PERSONA_PRECIO_HORA IS 'Clave primaria autoincremental.';
COMMENT ON COLUMN GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA.ID_TAREA IS 'Identificador de la tarea.';
COMMENT ON COLUMN GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA.ICM_ID_PERIODO IS 'Id. Periodo, M4ICM_PERIODOS, Maestro de Periodos.';
COMMENT ON COLUMN GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA.CCL_ID_ORIGEN IS 'Id. Origen, M4CCL_ORIGEN_DATOS_SINCRO, Maestro de orÃ­genes de sincronización.';
COMMENT ON COLUMN GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA.STD_ID_LEG_ENT IS 'Id empresa, STD_LEG_ENT, Maestro de empresas.';
COMMENT ON COLUMN GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA.CCL_ID_PERSON IS 'Código de persona.';
COMMENT ON COLUMN GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA.STD_OR_HR_PERIOD IS 'Ordinal del periodo, vien de STD_HR_PERIOD, no hay tabla maestra de este campo.';
COMMENT ON COLUMN GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA.FECHA IS 'Fecha asociada al cálculo de precio hora';
COMMENT ON COLUMN GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA.PRECIO_HORA IS 'Precio por hora calculado (DECIMAL).';
