GRANT CONNECT ON DATABASE TO USER PINCOME;
GRANT CREATETAB ON DATABASE TO USER PINCOME;

-- Permisos GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA TO USER UINCOME;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA TO USER BDMINCOME;

-- Permisos GESTION_COMISION.TIPO_CALCULO_PRECIO_HORA
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE GESTION_COMISION.TIPO_CALCULO_PRECIO_HORA TO USER UINCOME;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE GESTION_COMISION.TIPO_CALCULO_PRECIO_HORA TO USER BDMINCOME;


