-- Permisos GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE GESTION_COMISION.TAREA_CALCULO_PERSONA_PRECIO_HORA TO USER UINCOMEM;

-- Permisos GESTION_COMISION.TIPO_CALCULO_PRECIO_HORA
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE GESTION_COMISION.TIPO_CALCULO_PRECIO_HORA TO USER UINCOMEM;
