package com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.empresas.dto;

import java.io.Serializable;

import lombok.Data;

@Data
public class EmpresaResultItemDto implements Serializable {

  private static final long serialVersionUID = -7497402778193815702L;

  private String m4AutoGeneratedRecordID;

  private boolean m4AutoGeneratedToDelete;

  private String idEmpresa;

  private String idOrigen;

  private String nombreEmpresa;

}
