package com.inditex.rrhh.icmclcwb.api.app.tarea;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum TipoGrupoDatoEnum {

    /* 2000 VENTA */
    VENTA_LOCALIZACION_SECCION(2001),
    VENTA_FISICA_LOCALIZACION(2002),
    VENTA_ONLINE_LOCALIZACION(2003),
    VENTA_ONLINE_IPOD_LOCALIZACION(2004),
    VENTA_ONLINE_SINT_LOCALIZACION(2005),
    VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION(2006),

    /* 3000 PRESENCIA */
    PRESENCIA_LOCALIZACION_SECCION_PERSONA_TIPOHORA(3001),
    PRESENCIA_LOCALIZACION_PERSONA_TIPOHORA(3002),
    PRESENCIA_LOCALIZACION_INCLUIDODENOMINADOR(3003),
    PRESENCIA_INCLUIDODENOMINADOR(3005);

    private final Integer id;

}
