package com.inditex.rrhh.icmclcwb.api.app.tarea;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum TipoDatoEnum {

    /* 2000 (Venta) */
    VENTA_FISICA_LOCALIZACION(2001), VENTA_FISICA_LOCALIZACION_SECCION(2002), VENTA_ONLINE_IPOD_LOCALIZACION(2003),
    VENTA_ONLINE_IPOD_LOCALIZACION_SECCION(2004), VENTA_ONLINE_SINT_LOCALIZACION(2005),
    VENTA_ONLINE_SINT_LOCALIZACION_SECCION(2006), VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION(2007),
    VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_SECCION(2008), VENTA_FISICA_AGRUPACIONONLINE(2009),
    VENTA_ONLINE_ENTREGADOMICILIO_AGRUPACIONONLINE(2010),
    /* 3000 (Venta Procesado) */
    VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION(3001), VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_SECCION(3002),
    VENTA_ONLINE_TRASLADADA(3003), VENTA_ONLINE_COMPENSADA(3004), VENTA_ONLINE_IPOD_LOCALIZACION_TRASLADADA(3005),
    VENTA_ONLINE_IPOD_LOCALIZACION_SECCION_TRASLADADA(3006), VENTA_ONLINE_SINT_LOCALIZACION_TRASLADADA(3007),
    VENTA_ONLINE_SINT_LOCALIZACION_SECCION_TRASLADADA(3008), VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_TRASLADADA(3009),
    VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_SECCION_TRASLADADA(3010), VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_TRASLADADA(3011),
    VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_SECCION_TRASLADADA(3012), VENTA_ONLINE_IPOD_LOCALIZACION_TRASLADADA_DIA(3013),
    VENTA_ONLINE_IPOD_LOCALIZACION_SECCION_TRASLADADA_DIA(3014), VENTA_ONLINE_SINT_LOCALIZACION_TRASLADADA_DIA(3015),
    VENTA_ONLINE_SINT_LOCALIZACION_SECCION_TRASLADADA_DIA(3016), VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_TRASLADADA_DIA(3017),
    VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_SECCION_TRASLADADA_DIA(3018), VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_TRASLADADA_DIA(3019),
    VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_SECCION_TRASLADADA_DIA(3020),VENTA_ONLINE_IPOD_LOCALIZACION_TRASLADADA_SECCION(3021),
    VENTA_ONLINE_IPOD_LOCALIZACION_SECCION_TRASLADADA_SECCION(3022), VENTA_ONLINE_SINT_LOCALIZACION_TRASLADADA_SECCION(3023),
    VENTA_ONLINE_SINT_LOCALIZACION_SECCION_TRASLADADA_SECCION(3024), VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_TRASLADADA_SECCION(3025),
    VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_SECCION_TRASLADADA_SECCION(3026), VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_TRASLADADA_SECCION(3027),
    VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_SECCION_TRASLADADA_SECCION(3028),
    /* 4000 (Presencia) */
    PRESENCIA_REAL_LOCALIZACION_SECCION_PERSONA_TIPOHORA(4002),
    PRESENCIA_MANUAL_LOCALIZACION_SECCION_PERSONA_TIPOHORA(4003),
    /* 5000 (Presencia Procesado) */
    PRESENCIA_LOCALIZACION_INCLUIDODENOMINADOR(5001), PRESENCIA_LOCALIZACION_SECCION_INCLUIDODENOMINADOR(5002),
    PRESENCIA_LOCALIZACION_PERSONA_TIPOHORA_INCLUIDODENOMINADOR(5003), PRESENCIA_LOCALIZACION_SECCION_INCLUIDOECOMMERCE(5004),
    PRESENCIA_AGRUPACIONONLINE_INCLUIDOECOMMERCE(5005), INDICADOR_PRESENCIA_LOCALIZACION_PERSONA_TIPOHORA(5006),
    INDICADOR_PRESENCIA_LOCALIZACION_PERSONA_TIPOHORA_DESPLAZAMIENTO(5007), INDICADOR_PRESENCIA_LOCALIZACION_PERSONA_TIPOHORA_DESPLAZAMIENTO_BASE(5008),
    INDICADOR_PRESENCIA_LOCALIZACION_PERSONA_TIPOHORA_DESPLAZAMIENTO_BASE_DESPLAZAMIENTO_MISMA_LOCALIZACION(5009),

	/* 6000 (Localizacion) */
    LOCALIZACION_FESTIVO(6001),
    /* 7000 (Localizacion Procesado) *//* 8000 (Persona) */
    PERSONA_COEFICIENTEREDUCCIONJORNADA(8001)/* 9000 (Persona Procesado) */;

    private final Integer id;

}
