package com.inditex.rrhh.icmclcwb.api.app.tarea;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum TipoImporteVentaEnum {

    IMPORTE_VENTA_FISICA_LOCALIZACION(1L),
    IMPORTE_VENTA_FISICA_LOCALIZACION_SECCION(2L), 
    IMPORTE_VENTA_FISICA_LOCALIZACION_SECCION_PERSONA(3L), 
    IMPORTE_VENTA_FISICA_INDIVIDUAL_LOCALIZACION(4L) , 
    IMPORTE_VENTA_FISICA_INDIVIDUAL_PERSONA_LOCALIZACION(5L), 
    IMPORTE_VENTA_FISICA_INDIVIDUAL_OPERACION_LOCALIZACION(6L),
    IMPORTE_VENTA_FISICA_INDIVIDUAL_OPERACION_PERSONA_LOCALIZACION(7L),
    IMPORTE_VENTA_ONLINE_IPOD_LOCALIZACION(8L), 
    IMPORTE_VENTA_ONLINE_IPOD_LOCALIZACION_SECCION(9L),
    IMPORTE_VENTA_ONLINE_IPOD_INDIVIDUAL_LOCALIZACION(10L),
    IMPORTE_VENTA_ONLINE_IPOD_INDIVIDUAL_LOCALIZACION_PERSONA(11L), 
    IMPORTE_VENTA_ONLINE_IPOD_INDIVIDUAL_OPERACION_LOCALIZACION(12L),
    IMPORTE_VENTA_ONLINE_PICKING_LOCALIZACION(13L),
    IMPORTE_VENTA_ONLINE_PICKING_LOCALIZACION_SECCION(14L),
    IMPORTE_VENTA_ONLINE_ENTREGA_TIENDA_LOCALIZACION(15L),
    IMPORTE_VENTA_ONLINE_ENTREGA_TIENDA_LOCALIZACION_SECCION(16L),
    IMPORTE_VENTA_ONLINE_ENTREGA_DOMICILIO_LOCALIZACION(17L), 
    IMPORTE_VENTA_ONLINE_ENTREGA_DOMICILIO_LOCALIZACION_SECCION(18L), 
    IMPORTE_DEVOLUCION_SECCION_LOCALIZACION(18L), 
    IMPORTE_DEVOLUCION_SECCION_LOCALIZACION_PERSONA(19L),
    IMPORTE_DEVOLUCION_SECCION_LOCALIZACION_NO_VENDEDOR(20L), 
    IMPORTE_VENTA_BRUTO(21L), 
    IMPORTE_VENTA_IPOD_BRUTO(22L), 
    IMPORTE_VENTA_LOCALIZACION(24L), 
    IMPORTE_VENTA_LOCALIZACION_SECCION(25L);
    

    private final Long id;

}
