package com.inditex.rrhh.icmclcwb.api.app.tarea;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum TipoGrupoDatoEnum {

    /* 2000 VENTA */
    VENTA_LOCALIZACION_SECCION(2001L),
    VENTA_FISICA_LOCALIZACION(2002L),
    VENTA_ONLINE_LOCALIZACION(2003L),
    VENTA_ONLINE_IPOD_LOCALIZACION(2004L),
    VENTA_ONLINE_SINT_LOCALIZACION(2005L),
    VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION(2006L),

    /* 3000 PRESENCIA */
    PRESENCIA_LOCALIZACION_SECCION_PERSONA_TIPOHORA(3001L),
    PRESENCIA_LOCALIZACION_PERSONA_TIPOHORA(3002L),
    PRESENCIA_LOCALIZACION_INCLUIDODENOMINADOR(3003L),
    PRESENCIA_LOCALIZACION_SECCION_INCLUIDOECOMMERCE(3004L);

    private final Long id;

}
