package com.inditex.rrhh.icmclcwb.api.app.tarea;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum TipoImporteVentaEnum {

    IMPORTE_VENTA_FISICA_LOCALIZACION_SECCION(1L), IMPORTE_VENTA_FISICA_LOCALIZACION_SECCION_PERSONA(2L), IMPORTE_VENTA_ONLINE_IPOD_LOCALIZACION_SECCION(3L),
    IMPORTE_VENTA_ONLINE_IPOD_LOCALIZACION_SECCION_PERSONA(4L), IMPORTE_VENTA_ONLINE_PICKING_LOCALIZACION_SECCION(5L), IMPORTE_VENTA_ONLINE_ENTREGA_TIENDA_LOCALIZACION_SECCION(6L),
    IMPORTE_VENTA_ONLINE_ENTREGA_DOMICILIO_LOCALIZACION_SECCION(7L), IMPORTE_DEVOLUCION_SECCION_LOCALIZACION(8L), IMPORTE_DEVOLUCION_SECCION_LOCALIZACION_PERSONA(9L),
    IMPORTE_DEVOLUCION_SECCION_LOCALIZACION_NO_VENDEDOR(10L), IMPORTE_VENTA_BRUTO(11L), IMPORTE_VENTA_IPOD_BRUTO(12L);

    private final Long id;

}
