package com.inditex.rrhh.icmclcwb.api.app.tarea;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum TipoDatoEnum {

    /* 2000 (Venta) */
    VENTA_FISICA_LOCALIZACION(2001L), VENTA_FISICA_LOCALIZACION_SECCION(2002L), VENTA_ONLINE_IPOD_LOCALIZACION(2003L),
    VENTA_ONLINE_IPOD_LOCALIZACION_SECCION(2004L), VENTA_ONLINE_SINT_LOCALIZACION(2005L),
    VENTA_ONLINE_SINT_LOCALIZACION_SECCION(2006L), VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION(2007L),
    VENTA_ONLINE_ENTREGATIENDA_LOCALIZACION_SECCION(2008L), VENTA_FISICA_AGRUPACIONONLINE(2009L),
    VENTA_ONLINE_ENTREGADOMICILIO_AGRUPACIONONLINE(2010L),
    /* 3000 (Venta Procesado) */
    VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION(3001L), VENTA_ONLINE_ENTREGADOMICILIO_LOCALIZACION_SECCION(3002L),
    VENTA_ONLINE_TRASLADADA(3003L), VENTA_ONLINE_COMPENSADA(3004L),
    /* 4000 (Presencia) */
    PRESENCIA_REAL_LOCALIZACION_SECCION_PERSONA_TIPOHORA(4002L),
    PRESENCIA_MANUAL_LOCALIZACION_SECCION_PERSONA_TIPOHORA(4003L),
    /* 5000 (Presencia Procesado) */
    PRESENCIA_LOCALIZACION_INCLUIDODENOMINADOR(5001L), PRESENCIA_LOCALIZACION_SECCION_INCLUIDODENOMINADOR(5002L),
    PRESENCIA_LOCALIZACION_PERSONA_TIPOHORA(5003L), PRESENCIA_LOCALIZACION_SECCION_INCLUIDOECOMMERCE(5004L),
    PRESENCIA_AGRUPACIONONLINE_INCLUIDOECOMMERCE(5005L),
    /* 6000 (Localizacion) */
    LOCALIZACION_FESTIVO(6001L),
    /* 7000 (Localizacion Procesado) *//* 8000 (Persona) */
    PERSONA_COEFICIENTEREDUCCIONJORNADA(8001L)/* 9000 (Persona Procesado) */;

    private final Long id;

}
