package com.inditex.rrhh.icmclcwb.model.meta4.icmwscalcincome.service;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.inditex.amigafwk.test.logcaptor.LogCaptor;
import com.inditex.amigafwk.test.logcaptor.LogCaptorExtension;
import com.inditex.rrhh.icmclcwb.api.meta4.dto.PageDto;
import com.inditex.rrhh.icmclcwb.api.meta4.dto.PageableListDto;

import ch.qos.logback.classic.Level;
import lombok.Data;
import lombok.RequiredArgsConstructor;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(LogCaptorExtension.class)
@RequiredArgsConstructor
class IncomeResponseComparatorTest {

  private static final String OPERATION = "testOperation";

  private final IncomeResponseComparator comparator = new IncomeResponseComparator();

  private final LogCaptor logCaptor;

  @Nested
  class EqualResponses {

    @Test
    void whenBothNullExpectNoWarn() {
      comparator.compareAndLogDiffs(OPERATION, null, null, null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

    @Test
    void whenIdenticalSingleObjectsExpectNoWarn() {
      var soap = item("d", "c", "1");
      var rest = item("d", "c", "1");

      comparator.compareAndLogDiffs(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

    @Test
    void whenIdenticalListsSameOrderExpectNoWarn() {
      var soap = Arrays.asList(item("d1", "c1", "1"), item("d2", "c2", "2"));
      var rest = Arrays.asList(item("d1", "c1", "1"), item("d2", "c2", "2"));

      comparator.compareAndLogDiffs(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

    @Test
    void whenIdenticalListsDifferentOrderExpectNoWarn() {
      var soap = Arrays.asList(item("d1", "c1", "1"), item("d2", "c2", "2"), item("d3", "c3", "3"));
      var rest = Arrays.asList(item("d3", "c3", "3"), item("d1", "c1", "1"), item("d2", "c2", "2"));

      comparator.compareAndLogDiffs(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

    @Test
    void whenAutoGeneratedFieldsDifferExpectNoWarn() {
      var soap = item("d", "c", "1");
      soap.setM4AutoGeneratedRecordID("soap-id");
      soap.setM4AutoGeneratedToDelete(true);
      var rest = item("d", "c", "1");
      rest.setM4AutoGeneratedRecordID(null);
      rest.setM4AutoGeneratedToDelete(false);

      comparator.compareAndLogDiffs(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

    @Test
    void whenAutoGeneratedFieldsDifferInsideListExpectNoWarn() {
      var soapItem = item("d", "c", "1");
      soapItem.setM4AutoGeneratedRecordID("soap-id");
      var restItem = item("d", "c", "1");
      restItem.setM4AutoGeneratedRecordID(null);

      comparator.compareAndLogDiffs(OPERATION, List.of(soapItem), List.of(restItem), null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

    @Test
    void whenIdenticalNestedObjectsExpectNoWarn() {
      var soap = item("d", "c", "1");
      soap.setInner(inner(7, "shared"));
      var rest = item("d", "c", "1");
      rest.setInner(inner(7, "shared"));

      comparator.compareAndLogDiffs(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

  }

  @Nested
  class DifferentResponses {

    @Test
    void whenSingleFieldDiffersExpectFieldDiffWarn() {
      var soap = item("d", "soapCadena", "1");
      var rest = item("d", "restCadena", "1");

      comparator.compareAndLogDiffs(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("Shadow REST and SOAP responses differ").withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("Field: idCadena. SOAP value: soapCadena. REST value: restCadena")
          .withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenMultipleFieldsDifferExpectMultipleFieldDiffWarns() {
      var soap = item("soapData", "soapCadena", "1");
      var rest = item("restData", "restCadena", "1");

      comparator.compareAndLogDiffs(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("Field: idCadena").withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("Field: idData").withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenNestedFieldDiffersExpectPathPrefixedWarn() {
      var soap = item("d", "c", "1");
      soap.setInner(inner(7, "soapVal"));
      var rest = item("d", "c", "1");
      rest.setInner(inner(7, "restVal"));

      comparator.compareAndLogDiffs(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("Field: inner.valueInner. SOAP value: soapVal. REST value: restVal")
          .withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenListHasExtraSoapElementExpectDiffWarn() {
      var soap = Arrays.asList(item("d1", "c1", "1"), item("d2", "c2", "2"));
      var rest = List.of(item("d1", "c1", "1"));

      comparator.compareAndLogDiffs(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("Shadow REST and SOAP responses differ").withLevel(Level.WARN).areNotZero();
    }

    @Test
    void whenInnerListElementFieldDiffersExpectIndexedPathWarn() {
      var soap = item("d", "c", "1");
      soap.setInnerList(Arrays.asList(inner(1, "matchA"), inner(2, "soapMismatch")));
      var rest = item("d", "c", "1");
      rest.setInnerList(Arrays.asList(inner(1, "matchA"), inner(2, "restMismatch")));

      comparator.compareAndLogDiffs(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("Shadow REST and SOAP responses differ").withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("Field: innerList").withLevel(Level.WARN).areNotZero();
    }

    @Test
    void whenSoapNullAndRestNotNullExpectDiffWarn() {
      var rest = item("d", "c", "1");

      comparator.compareAndLogDiffs(OPERATION, null, rest, null);

      logCaptor.verifyMessagesContaining("Shadow REST and SOAP responses differ").withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenEmptyAndNonEmptyListsExpectNoWarn() {
      comparator.compareAndLogDiffs(OPERATION, new ArrayList<ResultDto>(), List.of(item("d", "c", "1")), null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

  }

  @Nested
  class PageableListResponses {

    @Test
    void whenBothNullExpectNoWarn() {
      comparator.comparePageableListDto(OPERATION, null, null, null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

    @Test
    void whenSoapNullAndRestNotNullExpectDiffWarn() {
      var rest = pageable(List.of(item("d", "c", "1")), null);

      comparator.comparePageableListDto(OPERATION, null, rest, null);

      logCaptor.verifyMessagesContaining("Shadow REST and SOAP responses differ").withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenRestNullAndSoapNotNullExpectDiffWarn() {
      var soap = pageable(List.of(item("d", "c", "1")), page(1));

      comparator.comparePageableListDto(OPERATION, soap, null, null);

      logCaptor.verifyMessagesContaining("Shadow REST and SOAP responses differ").withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenSoapDataNullExpectNoWarn() {
      var soap = pageable(null, page(0));
      var rest = pageable(List.of(item("d", "c", "1")), null);

      comparator.comparePageableListDto(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

    @Test
    void whenSoapDataEmptyExpectNoWarn() {
      var soap = pageable(new ArrayList<>(), page(0));
      var rest = pageable(List.of(item("d", "c", "1")), null);

      comparator.comparePageableListDto(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

    @Test
    void whenRestDataNullAndSoapHasItemsExpectDiffWarn() {
      var soap = pageable(List.of(item("d1", "c1", "1"), item("d2", "c2", "2")), page(1));
      var rest = pageable(null, null);

      comparator.comparePageableListDto(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("REST data is empty but SOAP has 2 elements").withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenRestDataEmptyAndSoapHasItemsExpectDiffWarn() {
      var soap = pageable(List.of(item("d1", "c1", "1")), page(1));
      var rest = pageable(new ArrayList<>(), null);

      comparator.comparePageableListDto(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("REST data is empty but SOAP has 1 elements").withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenAllSoapItemsPresentInRestExpectNoWarn() {
      var soap = pageable(Arrays.asList(item("d1", "c1", "1"), item("d2", "c2", "2")), page(1));
      var rest = pageable(Arrays.asList(item("d2", "c2", "2"), item("d1", "c1", "1"), item("d3", "c3", "3")), null);

      comparator.comparePageableListDto(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

    @Test
    void whenSoapAndRestEqualExpectNoWarn() {
      var soap = pageable(List.of(item("d1", "c1", "1")), page(1));
      var rest = pageable(List.of(item("d1", "c1", "1")), null);

      comparator.comparePageableListDto(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

    @Test
    void whenPageDiffersButDataMatchesExpectNoWarn() {
      var soap = pageable(List.of(item("d1", "c1", "1")), page(5));
      var rest = pageable(List.of(item("d1", "c1", "1")), page(99));

      comparator.comparePageableListDto(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

    @Test
    void whenAutoGeneratedFieldsDifferExpectNoWarn() {
      var soapItem = item("d", "c", "1");
      soapItem.setM4AutoGeneratedRecordID("soap-id");
      soapItem.setM4AutoGeneratedToDelete(true);
      var restItem = item("d", "c", "1");

      var soap = pageable(List.of(soapItem), page(1));
      var rest = pageable(List.of(restItem), null);

      comparator.comparePageableListDto(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("").withLevel(Level.WARN).areZero();
    }

    @Test
    void whenOneSoapItemMissingInRestExpectClosestFieldDiffWarn() {
      var soap = pageable(Arrays.asList(item("d1", "c1", "1"), item("dMissing", "cMissing", "9")), page(1));
      var rest = pageable(List.of(item("d1", "c1", "1")), null);

      comparator.comparePageableListDto(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("SOAP item not found in REST response for testOperation (data[1])")
          .withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("Field: data[1].idData. SOAP value: dMissing. REST value: d1")
          .withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("Field: data[1].idCadena. SOAP value: cMissing. REST value: c1")
          .withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("Field: data[1].idLocalizacion. SOAP value: 9. REST value: 1")
          .withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("1 items REST/2 items SOAP. Found 1 discrepancies").withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenAllSoapItemsMissingInRestExpectAllClosestDiffWarns() {
      var soap = pageable(Arrays.asList(item("d1", "c1", "1"), item("d2", "c2", "2")), page(1));
      var rest = pageable(List.of(item("dOther", "cOther", "0")), null);

      comparator.comparePageableListDto(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("SOAP item not found in REST response for testOperation (data[0])")
          .withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("SOAP item not found in REST response for testOperation (data[1])")
          .withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("1 items REST/2 items SOAP. Found 2 discrepancies").withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenSoapItemDiffersByOneFieldExpectOnlyThatFieldWarn() {
      var soap = pageable(List.of(item("d1", "soapCadena", "1")), page(1));
      var rest = pageable(List.of(item("d1", "restCadena", "1")), null);

      comparator.comparePageableListDto(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("SOAP item not found in REST response for testOperation (data[0])")
          .withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("Field: data[0].idCadena. SOAP value: soapCadena. REST value: restCadena")
          .withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("Field:").withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenClosestRestItemIsPickedExpectMinimalDiffs() {
      var soap = pageable(List.of(item("d1", "c1", "1")), page(1));
      var rest = pageable(Arrays.asList(item("d1", "c1", "9"), item("xxx", "yyy", "zzz")), null);

      comparator.comparePageableListDto(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("Field: data[0].idLocalizacion. SOAP value: 1. REST value: 9")
          .withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("Field:").withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenSoapHasMatchAndExtraExpectOnlyExtraReportedAsMissing() {
      var soap = pageable(Arrays.asList(item("d1", "c1", "1"), item("dExtra", "cExtra", "9")), page(1));
      var rest = pageable(List.of(item("d1", "c1", "1")), null);

      comparator.comparePageableListDto(OPERATION, soap, rest, null);

      logCaptor.verifyMessagesContaining("SOAP item not found in REST response for testOperation (data[1])")
          .withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("Field: data[1].idData. SOAP value: dExtra. REST value: d1")
          .withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenNestedFieldDiffersInsidePageableExpectNestedPathWarn() {
      var soapItem = item("d", "c", "1");
      soapItem.setInner(inner(7, "soapVal"));
      var restItem = item("d", "c", "1");
      restItem.setInner(inner(7, "restVal"));

      comparator.comparePageableListDto(OPERATION, pageable(List.of(soapItem), page(1)), pageable(List.of(restItem), null), null);

      logCaptor.verifyMessagesContaining("Field: data[0].inner.valueInner. SOAP value: soapVal. REST value: restVal")
          .withLevel(Level.WARN).areExactly(1);
    }

    @Test
    void whenGenericEntryPointReceivesPageableExpectDispatchToPageableComparison() {
      var soap = pageable(List.of(item("d1", "soapCadena", "1")), page(1));
      var rest = pageable(List.of(item("d1", "restCadena", "1")), null);

      comparator.compareAndLogDiffs(OPERATION, (Object) soap, (Object) rest, null);

      logCaptor.verifyMessagesContaining("Field: data[0].idCadena. SOAP value: soapCadena. REST value: restCadena")
          .withLevel(Level.WARN).areExactly(1);
      logCaptor.verifyMessagesContaining("Field: page").withLevel(Level.WARN).areZero();
    }

  }

  private PageableListDto<ResultDto> pageable(List<ResultDto> data, PageDto page) {
    var dto = new PageableListDto<ResultDto>();
    dto.setData(data);
    dto.setPage(page);
    return dto;
  }

  private PageDto page(int pageNumber) {
    var p = new PageDto();
    p.setNumeroPagina(pageNumber);
    return p;
  }

  private ResultDto item(String idData, String idCadena, String idLocalizacion) {
    var dto = new ResultDto();
    dto.setIdData(idData);
    dto.setIdCadena(idCadena);
    dto.setIdLocalizacion(idLocalizacion);
    return dto;
  }

  private InnerDto inner(Integer idInner, String valueInner) {
    var dto = new InnerDto();
    dto.setIdInner(idInner);
    dto.setValueInner(valueInner);
    return dto;
  }

  @Data
  private static class ResultDto implements Serializable {
    private static final long serialVersionUID = 1L;

    private String idData;

    private String idCadena;

    private String idLocalizacion;

    private String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private InnerDto inner;

    private List<InnerDto> innerList;
  }

  @Data
  private static class InnerDto implements Serializable {
    private static final long serialVersionUID = 1L;

    private Integer idInner;

    private String valueInner;

    private String m4AutoGeneratedRecordID;
  }

}
