<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.inditex.rrhh.icmclcwb</groupId>
    <artifactId>APPWEB-INCOMEMotorCalculoJava-soap-clients</artifactId>
    <version>4.91.0</version>
  </parent>
  <artifactId>APPWEB-INCOMEMotorCalculoJava-client-soap-api-incomemotorcalculometa</artifactId>
  <packaging>jar</packaging>

  <name>${project.groupId}:${project.artifactId}</name>
  <description>SOAP client for consuming web-incomemotorcalculometa services</description>
  <properties>
    <amiga.service.cxf.generator.packageMapping>http://schemas.meta4.com/=com.inditex.rrhh.icmclcwb.model.meta4.icmwscalcincome.entity</amiga.service.cxf.generator.packageMapping>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.inditex.amigafwk.common</groupId>
      <artifactId>common-starter-soap-client-cxf</artifactId>
    </dependency>
  </dependencies>
</project>
