---
# For more information, see: https://github-cicd.docs.inditex.dev/githubcicd/stable/features/jira-transition.html#configuration-file
version: '1.0'
jira-transitions:
  name: 'Default transitions'
  default-transitions:
    draft: '131' # In progress
    ready-for-review: '141' # In review
    approved: '151' # Ready to Verify
    merged: '161' # Accepted
    reopened: '201' # To Reword
    release: '171' # To Deploy
issue-regexp-search: '^[\s]{0,}\[?(?<issueId>[A-Z]{2,}-\d+)\]?(.*)$'
