package com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.generic.dto;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class GenericFilterParametersDto implements Serializable {

    private static final long serialVersionUID = -1801905980562096849L;

    private String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private String idEmpleado;

    private String orEmpleado;

    private String idLugarTrabajo;
    
    private String activo;
    
    private String abierto;
    
    private String vigente;
    
    private String idTipoHora;

    private String idEmpleadoLocal;
    
    private String idLugarTrabajoMtu;

    private String idCadena;
    
    private String idOrigenReg;
    
    private String idSociedadReg;

}
