package com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.generic.dto;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.Data;

@Data
public class GenericEmpleadoResultItemDto implements Serializable {

  private static final long serialVersionUID = -631613481122106352L;

  private String m4AutoGeneratedRecordID;

  private boolean m4AutoGeneratedToDelete;

  private LocalDateTime fechaInicio;

  private LocalDateTime fecha;

  private LocalDateTime fechaFin;

  private LocalDateTime fechaFinSec;

  private LocalDateTime fechaInicioSec;

  private LocalDateTime fechaFinCom;

  private LocalDateTime fechaFinPar;

  private LocalDateTime fechaInicioLoc;

  private LocalDateTime fechaFinLoc;

  private LocalDateTime fechaInicioCom;

  private LocalDateTime fechaInicioPar;

  private LocalDateTime fechaAntiguedad;

  private String idCadena;

  private String idOrigen;

  private String idPais;

  private String idEmpresa;

  private String idEmpleado;

  private String orEmpleado;

  private String idSeccion;

  private Integer idTipoHora;

  private String idLugarTrabajoMtu;

  private String idLugarTrabajo;

  private String idEmpleadoLocal;

  private String coefJornada;

  private String importe;

  private String minutos;

  private String idPuesto;

}
