package com.inditex.rrhh.icmclcwb.api.app.calcular;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum TipoCalculoEnum {

  NINGUNO("000"), GLOBAL_TIENDA("001"), GLOBAL_SECCION("002"), DIRECTO_SOBRE_VENTA("003"),
  DIRECTO_SOBRE_VENTA_CON_PRESENCIA("004"), DIRECTO_SOBRE_VENTA_CON_REDUCCION_DE_JORNADA("005"),
  DIRECTO_SOBRE_VENTA_CON_PRESENCIA_Y_REDUCCION_DE_JORNADA("006"), POR_VENTA("007"),
  POR_VENTA_INDIVIDUAL("009"), CHALLENGE_PRECIO_HORA_TIENDA("010"),
  CHALLENGE_PRECIO_HORA_SECCION("011"), CHALLENGE_IMPORTE_TIENDA("012"),
  CHALLENGE_IMPORTE_SECCION("013"), PRECIO_HORA("014"),
  GLOBAL_TIENDA_SOLO_ONLINE("015"), GLOBAL_SECCION_SOLO_ONLINE("015"), DIRECTO_SOBRE_VENTA_SOLO_ONLINE("015"),
  CHALLENGE_PORCENTAJE("018"), CHALLENGE_JORNADA("019"), CHALLENGE_DIRECTO_VENTA("020");

  private final String id;

}
