<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.inditex.rrhh.icmclcwb</groupId>
    <artifactId>APPWEB-INCOMEMotorCalculoJava</artifactId>
    <version>4.66.0</version>
  </parent>
  <artifactId>APPWEB-INCOMEMotorCalculoJava-ws-api</artifactId>
  <name>${project.groupId}:${project.artifactId}</name>
  <description>Módulo para definición de los servicios REST</description>

  <dependencies>
    <dependency>
      <groupId>com.inditex.api</groupId>
      <artifactId>income-income-motor-calculo-java-api-v3-rest-stable</artifactId>
      <version>1.0.4</version>
    </dependency>

    <dependency>
      <groupId>com.inditex.amigafwk.common</groupId>
      <artifactId>common-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>com.inditex.amigafwk.service</groupId>
      <artifactId>service-starter-rest</artifactId>
    </dependency>
  </dependencies>

</project>
