package com.inditex.rrhh.icmclcwb.api.meta4.valorescondiciones.dto;

import java.io.Serializable;
import java.util.List;

import lombok.Data;

@Data
public class ValoresCondicionesResultItemDTO implements Serializable {
	
	private static final long serialVersionUID = 4719844473784557670L;
	
	private String m4AutoGeneratedRecordID;
	private boolean m4AutoGeneratedToDelete;
    private String inOut;
    private String nuevo;
    private String borrado;
    private String modificado;
    private String idPlantilla;
    private String idEstructura;
    private String idTipoPlantilla;
    private String nombrePlantilla;
    private String nombreEstructura;
    private String nombreTipoPlantilla;
    private List<CondicionesFijasResultItemDTO> condicionesFijas;
    private List<CondicionesComisionResultItemDTO> condicionesComision;
    private List<CondicionesPoliticasResultItemDTO> condicionesPoliticas;

}
