logging:
  level:
    root: WARN
    com.inditex.rrhh.icmclcwb: INFO
amiga:
  monitoring:
    metrics:
      enabled: true
      send: true
      functional:
        aspect:
          timer:
            enabled: true
          counter:
            enabled: true
  common:
    mail:
      host: mail.inditex.grp
      port: 25
      protocol: smtp
      default-encoding: UTF-8
    rest:
      client:
        http:
          connect-timeout: 300000
          read-timeout: 300000
        auth:
          method: BASIC
        slrhorcoms:
          auth-method: OAUTH2-CLIENT-CREDENTIALS
          client-name: client-income
          ping-query:
            enabled: true
            timeout: 2s
        ptr-venta:
          auth-method: BASIC
          ping-query:
            enabled: true
            timeout: 2s
        ptr-presencia:
          auth-method: BASIC
          ping-query:
            enabled: true
            timeout: 2s
        venta-integra:
          auth-method: OAUTH2-CLIENT-CREDENTIALS
          client-name: client-income
          ping-query:
            enabled: true
            timeout: 2s
  service:
    jms:
      listener:
        default:
          sessionTransacted: false
          globalTransacted: false
          pubSubDomain: false
          receiveTimeout: 1000
      trabajo-queue:
        destination-fqdn: ${metadata.tenant}.${metadata.domain}.${metadata.openshiftproject}.private.${metadata.service}-${metadata.jirakey}-trabajo-queue-${metadata.slot}
      tarea-queue:
        destination-fqdn: ${metadata.tenant}.${metadata.domain}.${metadata.openshiftproject}.private.${metadata.service}-${metadata.jirakey}-tarea-queue-${metadata.slot}
      limpieza-queue:
        destination-fqdn: ${metadata.tenant}.${metadata.domain}.${metadata.openshiftproject}.private.${metadata.service}-${metadata.jirakey}-limpieza-queue-${metadata.slot}
      programacion-queue:
        destination-fqdn: ${metadata.tenant}.${metadata.domain}.${metadata.openshiftproject}.private.${metadata.service}-${metadata.jirakey}-programacion-queue-${metadata.slot}
  data:
    binder:
      jms-activemq:
        default:
          consumer:
            enable-dlq: false
            send-original-payload-to-dlq: false
    jms:
      connection-factory:
        broker-escritura:
          minPoolSize: 10
          maxPoolSize: 20
          userName: usr-write
        broker-lectura:
          minPoolSize: 10
          maxPoolSize: 20
          userName: usr-read
      listener-container-factory:
        trabajo:
          concurrency: 1
          sessionTransacted: false
          globalTransacted: false
          pubSubDomain: false
          receiveTimeout: 1000
        tarea:
          concurrency: 3
          sessionTransacted: false
          globalTransacted: false
          pubSubDomain: false
          receiveTimeout: 1000
        limpieza:
          concurrency: 1
          sessionTransacted: false
          globalTransacted: false
          pubSubDomain: false
          receiveTimeout: 1000
        programacion:
          concurrency: 1
          sessionTransacted: false
          globalTransacted: false
          pubSubDomain: false
          receiveTimeout: 1000
      client:
        trabajo:
          destinationName: ${amiga.service.jms.trabajo-queue.destination-fqdn}
          pubSubDomain: false
          sessionTransacted: false
        tarea:
          destinationName: ${amiga.service.jms.tarea-queue.destination-fqdn}
          pubSubDomain: false
          sessionTransacted: false
        limpieza:
          destinationName: ${amiga.service.jms.limpieza-queue.destination-fqdn}
          pubSubDomain: false
          sessionTransacted: false
        programacion:
          destinationName: ${amiga.service.jms.programacion-queue.destination-fqdn}
          pubSubDomain: false
          sessionTransacted: false
    jdbc:
      query-timeout: 0s
      pool:
        hikari:
          maximum-pool-size: 10
          auto-commit: true
    jpa:
      properties:
        hibernate.dialect: com.inditex.rrhh.icmclcwb.model.primary.dialect.DB2NativeDialect
        hibernate.default_schema: GESTION_COMISION
app:
  envars:
    calculo:
      cast: true
      precision: 'DECIMAL(23,8)'
      round: true
      decimal: 2
    proceso:
      cast: true
      precision: 'DECIMAL(23,8)'
      round: false
      decimal: 8
    tarea:
      recolectar:
        days-number: 3
      validar:
        enabled: true
        logging: true
        exception: false
      calcular:
        algoritmo:
          thread-size: 2
          calculo:
            batch-size: 25
            thread-size: 4
      ajustar:
        algoritmo:
          thread-size: 2
          ajuste:
            batch-size: 200
            thread-size: 4
      regularizar:
        thread-size: 4
      prevalidacion:
        thread-size: 4
    repository:
      batch-size:
        default: 100
    limpieza:
      days-number: -7
      days-number-creation: -3
      max: 100
      batch-size:
        default: 100
    prevalidacion:
      baja:
        sincronizacion:
          activo: true
          max-empleados: 30
      carencia:
        sincronizacion:
          activo: true
          max-empleados: 30
      fechas:
        meses: 2
        sincronizacion:
          activo: true
          max-empleados: 30
      resalta:
        sincronizacion:
          activo: true
          max-empleados: 30
      desplazamiento:
        sincronizacion:
          activo: true
          max-empleados: 30
      historico:
        sincronizacion:
          activo: true
          max-empleados: 30
      primas:
        sincronizacion:
          activo: true
          max-empleados: 30
      manual:
        sincronizacion:
          activo: true
          max-empleados: 30
      personas:
        sincronizacion:
          activo: true
          max-empleados: 10
    ptr:
      config:
        max-attempts: 2
      venta:
        service:
          acumuladoVentaImporte:
            getVentaAcumDia:
              endpoint: /acumuladoVentaImporte/getVentaAcumDia
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
            getVentaAcumUTC:
              endpoint: /acumuladoVentaImporte/getVentaAcumUTC
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
            test:
              endpoint: /acumuladoVentaImporte/test
            getVersion:
              endpoint: /acumuladoVentaImporte/getVersion
          ventaEcommerce:
            getVentaOnlineEntregaTienda:
              endpoint: /ventaEcommerce/getVentaOnlineEntregaTienda
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
            getVentaOnlineEntregaDomicilio:
              endpoint: /ventaEcommerce/getVentaOnlineEntregaDomicilio
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
            getVentaOnlineiPod:
              endpoint: /ventaEcommerce/getVentaOnlineiPod
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
            getVentaOnlineIpodIndividualDetalle:
              endpoint: /ventaEcommerce/getVentaOnlineIpodIndividualDetalle
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
            getOrdersByCountrySectionProductHour:
              endpoint: /ventaEcommerce/getOrdersByCountrySectionProductHour
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
            getVentaOnlinePicking:
              endpoint: /ventaEcommerce/getVentaOnlinePicking
              filter:
                maxPageSize: 1000
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
            test:
              endpoint: /ventaEcommerce/test
            getVersion:
              endpoint: /ventaEcommerce/getVersion
          ventaEmpleado:
            getVentaIndividualDetalle:
              endpoint: /ventaEmpleado/getVentaIndividualDetalle
              filter:
                maxPageSize: 50
                maxPersistenceSize: 3
                periodSize: 0
                periodType: MONTHS
          ventaGeneral:
            getVentaTotalizado:
              endpoint: /ventaGeneral/getVentaTotalizado
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
      presencia:
        service:
          presenciasService:
            getPresenciasTotalizado:
              endpoint: /presenciasService/presenciasTotalizado
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
            getPresenciasDetalle:
              endpoint: /presenciasService/presenciasDetalle
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
            getPresenciasTiendasEmpleado:
              endpoint: /presenciasService/presenciasTiendasEmpleado
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
            getPresenciasEmpleadosTienda:
              endpoint: /presenciasService/presenciasEmpleadosTienda
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
            getTiposHoras:
              endpoint: /presenciasService/tiposHoras
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                periodSize: 1
                periodType: MONTHS
            getVersion:
              endpoint: /presenciasService/getVersion
    venta-integra:
      service:
        ventaIntegraService:
          endpoint: /v1/storedata
      config:
        max-attempts: 2
    meta4:
      config:
        max-attempts: 20
        credentials:
          user: INCOME_CALC
          language: 2
        pool:
          pre-login: false
          size: 10
          claimTimeout: 30000
          shutdownTimeout: 60000
        timeout:
          connectTimeout: 300000
          receiveTimeout: 300000
      icmwscalcincome:
        service:
          getEmpresa:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getOrigen:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getConfiguracionProductoVenta:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getFestivos:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getCoefJornada:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getFlagCalcula:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getPresenciaManual:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getEmpleadosPresencia:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getPeriodos:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          searchTiendas:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getTiendas:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          searchEmpleados:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
          getEstructurasCom:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 25
              maxPersistenceSize: 3
          getEstructurasPol:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 25
              maxPersistenceSize: 3
          getEmpleados:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getConfVentaOnline:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idagrupacion
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getAgrupOnline:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idagrupacion
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getTiendasOnline:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idagrupacion
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getEmpleadosDesplazamiento:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getAusencias:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
          getConfiguracion:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idOrigen
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
          getConfChallengeDiasMinimos:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idOrigen
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
          getPresupuestosWloc:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idOrigen
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
          getConfPrecioHora:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idOrigen
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
          getConfChallengeTpVenta:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idOrigen
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
          getPresupuestosRango:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idOrigen
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
          getVentaCongelada:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idOrigen
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
          getDesplazamientosMultiempresa:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idEmpresa
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
          getDesplazReal:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idOrigen
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
          getPresenciaManualWloc:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idOrigen
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
          getVentaManualWloc:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idOrigen
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
          sincronizacion:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idOrigen
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
          getTiposHoras:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 50
              tipoOrden: DESC
              campoOrden: idOrigen
            filter:
              maxPageSize: 50
              maxPersistenceSize: 3
