amiga:
  common:
    rest:
      client:
        slrhorcoms:
          base-url: https://sscc.central.inditex.grp
          #base-url: http://slrhorcoms.slrhorcoms.svc.cluster.local.:8080/slrhorcoms
        ptr-venta:
          base-url: https://openshift.axinocp1.central.inditex.grp/rhvtimpwsd
          #base-url: http://rhvtimpwsd.rhvtimpwsd.svc.cluster.local.:8080/rhvtimpwsd
        ptr-presencia:
          base-url: https://openshift.axinocp1.central.inditex.grp/rhpresnwsd
          #base-url: http://rhpresnwsd.rhpresnwsd.svc.cluster.local.:8080/rhpresnwsd
  data:
    jms:
      connection-factory:
        broker-escritura:
          #brokerURL: tcp://middleware-amq-tcp:61616
          brokerURL: tcp://middleware-amq-tcp.icmclcwb.svc.cluster.local.:61616
        broker-lectura:
          #brokerURL: tcp://middleware-amq-tcp:61616
          brokerURL: tcp://middleware-amq-tcp.icmclcwb.svc.cluster.local.:61616
app:
  envars:
    meta4:
      login:
        #server: https://icmclcws.axinocp1.central.inditex.grp/services/Login
        server: http://icmclcws.icmclcws.svc.cluster.local.:8080/icmclcws/services/Login
      icmwscalcincome:
        #server: https://icmclcws.axinocp1.central.inditex.grp/services/ICM_WS_CALC_INCOME
        server: http://icmclcws.icmclcws.svc.cluster.local.:8080/icmclcws/services/ICM_WS_CALC_INCOME
