logging:
  level:
    root: WARN
    org.hibernate.tool.hbm2ddl: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
    com.inditex.rrhh.icmclcwb: INFO
amiga:
  common:
    rest:
      client:
        defaultConnectTimeout: 300000
        defaultReadTimeout: 300000
        ptrVentaClient:
          base-url: http://axdesptrosb01-vip.central.inditex.grp:33313/VTIMPACESB
          #base-url: http://axpreptrosb01-vip.central.inditex.grp:10313/VTIMPACESB
        ptrPresenciaClient:
          base-url: http://axdesptrosb01-vip.central.inditex.grp:33313/RHPRSCAESB
          #base-url: http://axpreptrosb01-vip.central.inditex.grp:33313/RHPRSCAESB
        ptrPresenciaMockClient:
          base-url: https://develop-icmclcwb.axdesocp1.central.inditex.grp/presenciasMockService
          auth-method: BASIC
          username: username300
  service:
    jms:
      trabajo-queue:
        destination-fqdn: ${metadata.tenant}.${metadata.domain}.${metadata.openshiftproject}.private.trabajo-queue-${metadata.slot}
        concurrency: 10-20
  data:
    jdbc:
      configuration:
        prop:
          # 0: TRANSACTION_NONE
          # 1: TRANSACTION_READ_UNCOMMITTED
          # 2: TRANSACTION_READ_COMMITTED
          # 4: TRANSACTION_REPEATABLE_READ
          # 8: TRANSACTION_SERIALIZABLE
          default-isolation-level: 1
          max-pool-size: 20
      datasource:
        primary:
          driverClassName: com.ibm.db2.jcc.DB2Driver
          url: jdbc:db2://axdesdb22.central.inditex.grp:50000/INDITEX
          user: oincome
        secondary:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://axinsqldes.central.inditex.grp:1433;databaseName=PeopleNet
          user: People7
          #user: ncomis
    hibernate:
      primary:
        properties: '{''hibernate.dialect'':''com.inditex.rrhh.icmclcwb.model.primary.dialect.DB2NativeDialect'',''hibernate.enable_lazy_load_no_trans'':''true'',''hibernate.hbm2ddl.auto'':''validate'',''hibernate.connection.CharSet'':''utf8'',''hibernate.connection.characterEncoding'':''utf8'',''hibernate.connection.useUnicode'':''true'',''hibernate.show_sql'':''false'',''hibernate.format_sql'':''true''}'
      secondary:
        properties: '{''hibernate.dialect'':''com.inditex.rrhh.icmclcwb.model.secondary.dialect.SQLServerNativeDialect'',''hibernate.enable_lazy_load_no_trans'':''true'',''hibernate.hbm2ddl.auto'':''validate'',''hibernate.show_sql'':''false'',''hibernate.format_sql'':''true''}'
    jms:
      connectionFactory:
        brokerEscritura:
          brokerURL: tcp://middleware-amq-tcp:61616
          userName: usr-write
        brokerLectura:
          brokerURL: tcp://middleware-amq-tcp:61616
          userName: usr-read
      client:
        trabajoJmsClient:
          destinationName: ${amiga.service.jms.trabajo-queue.destination-fqdn}
          receiveTimeout: 100
          pubSubDomain: false
app:
  envars:
    ptr:
      venta:
        service: 
          getVentaTotalizado: 
            endpoint: /ventaGeneralService/getVentaTotalizado
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2
          getVentaIndividualDetalle: 
            endpoint: /ventaEmpleadoService/getVentaIndividualDetalle
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2
      presencia:
        service:
          getPresenciasTotalTiendaSeccion:
            endpoint: /presenciasService/presenciasTotalTiendaSeccion
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2
          getPresenciasDetalle:
            endpoint: /presenciasService/presenciasDetalle
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2
          getTiposHoras:
            endpoint: /presenciasService/tiposHoras
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2                   
    meta4:
      user: INCOME
      language: 2
      default-connect-timeout: 300000
      default-receive-timeout: 300000
      login:
        server: http://develop-icmclcws.axdesocp1.central.inditex.grp/services/Login
      icm-ws-income:
        server: http://develop-icmclcws.axdesocp1.central.inditex.grp/services/ICM_WS_INCOME
        service:
          getEmpleadosTienda:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2
          getEmpleadosEstructura:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2   
          getTiendaComisionable: 
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2                 
          getValoresCondiciones:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idplantilla
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2
      icm-ws-calc-income:
        server: http://develop-icmclcws.axdesocp1.central.inditex.grp/services/ICM_WS_CALC_INCOME
        service:
          getTiendasEmpleado:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2
          searchTiendas:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2
          getTiendas: 
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2
          searchEmpleados: 
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2
          getComisionEmpleado:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2
          getEmpleados:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxQuerySize: 3
              maxPersistenceSize: 3
              retryAttempts: 2                      