amiga:
  common:
    rest:
      client:
        slrhorcoms:
          base-url: https://sscc.central.inditex.grp
        ptr-venta:
          base-url: https://openshift.axinocp1.central.inditex.grp/rhvtimpwsd
        ptr-presencia:
          base-url: https://openshift.axinocp1.central.inditex.grp/rhpresnwsd
  data:
    jms:
      connection-factory:
        broker-escritura:
          brokerURL: tcp://middleware-amq-tcp:61616
        broker-lectura:
          brokerURL: tcp://middleware-amq-tcp:61616
app:
  envars:
    meta4:
      login:
        server: https://icmclcws.axinocp1.central.inditex.grp/services/Login
      icmwscalcincome:
        server: https://icmclcws.axinocp1.central.inditex.grp/services/ICM_WS_CALC_INCOME
