amiga:
  common:
    rest:
      client:
        slrhorcoms:
          base-url: https://sscc-pre.central.inditex.grp
          #server: http://slrhorcoms-pre.svc.cluster.local.:8080/slrhorcoms
        ptr-venta:
          base-url: https://pre-openshift.axpreocp1.central.inditex.grp/rhvtimpwsd
          #server: http://rhvtimpwsd-pre.svc.cluster.local.:8080/rhvtimpwsd
        ptr-presencia:
          base-url: https://pre-openshift.axpreocp1.central.inditex.grp/rhpresnwsd
          #server: http://rhpresnwsd-pre.svc.cluster.local.:8080/rhpresnwsd
  data:
    jms:
      connection-factory:
        broker-escritura:
          brokerURL: tcp://middleware-amq-tcp:61616
        broker-lectura:
          brokerURL: tcp://middleware-amq-tcp:61616
app:
  envars:
    meta4:
      login:
        server: https://pre-icmclcws.axpreocp1.central.inditex.grp/services/Login
        #server: http://icmclcws-pre.svc.cluster.local.:8080/services/Login
      icmwscalcincome:
        server: https://pre-icmclcws.axpreocp1.central.inditex.grp/services/ICM_WS_CALC_INCOME
        #server: http://icmclcws-pre.svc.cluster.local.:8080/services/ICM_WS_CALC_INCOME
