amiga:
  common:
    rest:
      client:
        defaultConnectTimeout: 300000
        defaultReadTimeout: 300000
  monitoring:
    metrics:
      send: true
  service:
    session:
      session-type: REMOTE