amiga:
  common:
    reactor:
      scheduler:
        default:
          enabled: true
        bounded:
          factories:
            default:
              thread-prefix: async-bounded-executor
              max-threads: 20
              queued-task-cap: 100000
              keep-alive-time: 60000  
    rest:
      client:
        ptr-venta:
          base-url: https://openshift.axinocp1.central.inditex.grp/rhvtimpwsd
          username: srvcicmclcwbAX
        ptr-presencia:
          base-url: https://openshift.axinocp1.central.inditex.grp/rhpresnwsd
          username: srvcicmclcwbAX
  data:
    jdbc:
      datasource:
        primary:
          xa-properties:
            serverName: axindb22v1.central.inditex.grp
            portNumber: 50000
            databaseName: INDITEX
            currentSchema: GESTION_COMISION
            user: uincome
        ptr:
          driverClassName: oracle.jdbc.OracleDriver
          url: 
          user: uincome
          defaultIsolationLevel: 8
#        ptr:
#          xa-data-source-class-name: oracle.jdbc.xa.client.OracleXADataSource
#          xa-properties:
#            serverName: 
#            serviceName: 
#            portNumber:
#            user: uincome
#            password: 
#            driverType: thin
        meta4:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://axinsqlm4v1:1433;databaseName=PeopleNet
          user: UINCOME
        comis1:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://FRSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis2:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://BESQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis3:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://NLSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis4:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://DESQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis5:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://ITSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis6:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://UKSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis7:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://UKSQL.SEDES.INDITEX.GRP:1433;databaseName=PersonalIrlanda
          user: ncomis
        comis8:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://DKSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis9:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://GRSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis10:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://PTSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis18:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://BESQL.SEDES.INDITEX.GRP:1433;databaseName=PersonalLuxemburgo
          user: ncomis
        comis28:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://DKSQL.SEDES.INDITEX.GRP:1433;databaseName=PersonalNoruega
          user: ncomis
        comis30:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://DKSQL.SEDES.INDITEX.GRP:1433;databaseName=PersonalSuecia
          user: ncomis
        comis32:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://DKSQL.SEDES.INDITEX.GRP:1433;databaseName=PersonalFinlandia
          user: ncomis
        comis38:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://ATSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis39:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://CHSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis52:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://TRSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis60:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://PLSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis61:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://CZSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis63:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://CZSQL.SEDES.INDITEX.GRP:1433;databaseName=PersonalEslovaquia
          user: ncomis
        comis64:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://HUSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis66:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://ROSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis68:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://BGSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis72:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://UASQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis75:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://RUSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis79:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://KZSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis92:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://HRSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis93:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://BASQL.SEDES.INDITEX.GRP:1433;databaseName=PersonalBosnia
          user: ncomis
        comis96:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://MKSQL.SEDES.INDITEX.GRP:1433;databaseName=PersonalMacedonia
          user: ncomis
        comis97:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://RSSQL.SEDES.INDITEX.GRP:1433;databaseName=PersonalMontenegro
          user: ncomis
        comis98:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://RSSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis139:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://CHSQL.SEDES.INDITEX.GRP:1433;databaseName=PersonalMerken
          user: ncomis
        comis388:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://ZAFSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis400:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://USSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis404:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://CASQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis412:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://MXSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis508:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://BRSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis512:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://CLSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis524:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://UYSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis528:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://ARSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis664:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://INSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis720:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://CNSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis728:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://KRSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis732:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://JPSQL.JAPON.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis736:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://TWSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis740:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://HKSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis
        comis743:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://HKSQL.SEDES.INDITEX.GRP:1433;databaseName=PersonalMacao
          user: ncomis
        comis800:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://AUSQL.SEDES.INDITEX.GRP:1433;databaseName=Personal
          user: ncomis            
app:
  envars:
    ptr:
      venta:
        service:
          version: 1.0.34-rc.2
      presencia:
        service:
          version: 1.0.16-rc.5
    meta4:
      config:
        credentials:
          user: SRVCICMCLCWSAX
      login:
        #server: https://openshift.axinocp1.central.inditex.grp/icmclcws/services/Login
        server: https://icmclcws.axinocp1.central.inditex.grp/services/Login
      icmwscalcincome:
        #server: https://openshift.axinocp1.central.inditex.grp/icmclcws/services/ICM_WS_CALC_INCOME
        server: https://icmclcws.axinocp1.central.inditex.grp/services/ICM_WS_CALC_INCOME