logging:
  level:
    root: WARN
    com.inditex.rrhh.icmclcwb: DEBUG
amiga:
  common:
    rest:
      virtual:
        base-url: http://virtualhost:8081
      client:
        defaultConnectTimeout: 600000
        defaultReadTimeout: 600000
        ptrClientVenta:
          base-url: http://axpreptrosb01-vip.central.inditex.grp:10313/VTIMPACESB
          send-itx-headers: false
          ref-project-key: test_project_key
          auth-method: BASIC
          username: rcastro
          virtualized: false
          response-validated: false
        ptrClientPresencia:
          base-url: http://axdesptrosb01-vip.central.inditex.grp:33313/RHPRSCAESB
          send-itx-headers: false
          ref-project-key: test_project_key
          auth-method: BASIC
          username: rcastro
          virtualized: false
          response-validated: false
  service:
    jms:
      job-queue:
        destination-fqdn: ${metadata.tenant}.${metadata.domain}.${metadata.openshiftproject}.private.job-queue-${metadata.slot}
  data:
    jdbc:
      datasource:
        primary:
          driverClassName: org.h2.Driver
          url: jdbc:h2:mem:INDITEX;MODE=DB2;INIT=CREATE SCHEMA IF NOT EXISTS INCOME
          user: sa
        secondary:
          driverClassName: org.h2.Driver
          url: jdbc:h2:mem:PeopleNet;MODE=MSSQLServer
          user: sa
    hibernate:
      primary:
        properties: '{''hibernate.dialect'':''org.hibernate.dialect.H2Dialect'',''hibernate.hbm2ddl.auto'':''create'',''hibernate.show_sql'':''true'',''hibernate.format_sql'':''true''}'
      secondary:
        properties: '{''hibernate.dialect'':''org.hibernate.dialect.H2Dialect'',''hibernate.hbm2ddl.auto'':''create'',''hibernate.show_sql'':''true'',''hibernate.format_sql'':''true''}'
    jms:
      connectionFactory:
        brokerEscritura:
          brokerURL: tcp://middleware-amq-tcp:61616
          userName: usr-write
        brokerLectura:
          brokerURL: tcp://middleware-amq-tcp:61616
          userName: usr-read
      client:
        jobJmsClient:
          destinationName: ${amiga.service.jms.job-queue.destination-fqdn}
          receiveTimeout: 100
          pubSubDomain: false
app:
  envars:
    meta4:
      userName: INCOME
      language: 2
      login:
        server: https://axdeswas19.central.inditex.grp/RRHHAPPWSC-Income/services/Login
      icm-ws-income:
        server: https://axdeswas19.central.inditex.grp/RRHHAPPWSC-Income/services/ICM_WS_INCOME