logging:
  level:
    root: WARN
    com.inditex.rrhh.icmclcwb: INFO
amiga:
  monitoring:
    metrics:
      enabled: true
      send: true
  common:
    rest:
      client:
        defaultConnectTimeout: 1000
        defaultReadTimeout: 1000
        ptr-venta:
          base-url: http://axpreptrapp01-vip.central.inditex.grp:10813/OFDAVTIMPADWSD/service
        ptr-presencia:
          base-url: http://axpreptrapp01-vip.central.inditex.grp:10813/OFDARHPRSCAWSD/service
  service:
    jms:
      trabajo-queue:
        destination-fqdn: ${metadata.tenant}.${metadata.domain}.${metadata.openshiftproject}.private.trabajo-queue-${metadata.slot}
        concurrency: 10-20
  data:
    jdbc:
      configuration:
        prop:
          default-isolation-level: 1
          max-pool-size: 20
      datasource:
        primary:
          driverClassName: com.ibm.db2.jcc.DB2Driver
          url: jdbc:db2://axpredb22.central.inditex.grp:50000/INDITEX:currentSchema=INCOME;
          user: uincome
    hibernate:
      primary:
        properties: '{''hibernate.dialect'':''com.inditex.rrhh.icmclcwb.model.primary.dialect.DB2NativeDialect'',''hibernate.connection.CharSet'':''utf8'',''hibernate.connection.characterEncoding'':''utf8'',''hibernate.connection.useUnicode'':''true'',''hibernate.show_sql'':''false'',''hibernate.format_sql'':''false'',''hibernate.jdbc.batch_size'':''1000'',''hibernate.order_inserts'':''true'',''hibernate.order_updates'':''true'',''hibernate.jdbc.batch_versioned_data'':''true'',''hibernate.generate_statistics'':''true''}'
    jms:
      connection-factory:
        broker-escritura:
          brokerURL: tcp://middleware-amq-tcp:61616
          userName: usr-write
        broker-lectura:
          brokerURL: tcp://middleware-amq-tcp:61616
          userName: usr-read
      client:
        trabajo:
          destinationName: ${amiga.service.jms.trabajo-queue.destination-fqdn}
          receiveTimeout: 100
          pubSubDomain: false
app:
  envars:
    calculo:
      service:
        getGTAlgoritmoProperties:
          numBlock: 1000
    ptr:
      config:
        maxAttempts: 2
      venta:
        service:
          version: 1.0.21
          ventaEmpleado: 
            getVentaIndividualDetalle:
              endpoint: /ventaEmpleado/getVentaIndividualDetalle
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                maxBatchSize: 100
            getVentaIndividualDetalleByMCC:
              endpoint: /ventaEmpleado/getVentaIndividualDetalleByMCC
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                maxBatchSize: 100
            getVentaIndividual:
              endpoint: /ventaEmpleado/getVentaIndividual
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                maxBatchSize: 100           
            getVentaIndividualByMCC:
              endpoint: /ventaEmpleado/getVentaIndividualByMCC
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                maxBatchSize: 100 
            test:
              endpoint: /ventaEmpleado/test
            getVersion:
              endpoint: /ventaEmpleado/getVersion                   
          ventaGeneral:
            getVentaTotalizado:
              endpoint: /ventaGeneral/getVentaTotalizado
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                maxBatchSize: 100
            getVentaMensual:
              endpoint: /ventaGeneral/getVentaMensual
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                maxBatchSize: 100
            getVentaDiaria: 
              endpoint: /ventaGeneral/getVentaDiaria
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                maxBatchSize: 100        
            getVentaTotalizadoXML: 
              endpoint: /ventaGeneral/getVentaTotalizadoXML
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                maxBatchSize: 100 
            getVentaTotalizadoByMCC: 
              endpoint: /ventaGeneral/getVentaTotalizadoByMCC
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                maxBatchSize: 100   
            getVentaPresupuestadaMensual:
              endpoint: /ventaGeneral/getVentaPresupuestadaMensual
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                maxBatchSize: 100   
            test:
              endpoint: /ventaGeneral/test
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                maxBatchSize: 100 
            getVersion:
              endpoint: /ventaGeneral/getVersion
              filter:
                maxPageSize: 200
                maxPersistenceSize: 3
                maxBatchSize: 100                                               
      presencia:
        service:
          version: 1.0.3
          getPresenciasTotalTiendaSeccion:
            endpoint: /presenciasService/presenciasTotalTiendaSeccion
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
              maxBatchSize: 100
          getPresenciasDetalle:
            endpoint: /presenciasService/presenciasDetalle
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
              maxBatchSize: 100
          getPresenciasDetalleComisionable:
            endpoint: /presenciasService/presenciasDetalleComisionable
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
              maxBatchSize: 100                
          getTiposHoras:
            endpoint: /presenciasService/tiposHoras
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
              maxBatchSize: 100
    meta4:
      config:
        maxAttempts: 20
        credentials:
          user: INCOME_CALC
          password: 123
          language: 2
        pool:
          size: 20
          claimTimeout: 30000
          shutdownTimeout: 60000
        timeout:
          connectTimeout: 300000
          receiveTimeout: 300000
      login:
        server: https://develop-icmclcws.axdesocp1.central.inditex.grp/services/Login
      icmwscalcincome:
        server: https://develop-icmclcws.axdesocp1.central.inditex.grp/services/ICM_WS_CALC_INCOME
        service:
          getTiendasEmpleado:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
              maxBatchSize: 100
          searchTiendas:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
              maxBatchSize: 100
          getTiendas:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
              maxBatchSize: 100
          searchEmpleados:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
              maxBatchSize: 100
          getComisionEmpleado:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
              maxBatchSize: 100
          getEmpleados:
            page:
              numeroPagina: 1
              numeroRegistrosPagina: 200
              tipoOrden: DESC
              campoOrden: idempleado
            filter:
              maxPageSize: 200
              maxPersistenceSize: 3
              maxBatchSize: 100