
package com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.icm_ws_income;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Clase Java para Icm_CondicionescomisionRecord complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="Icm_CondicionescomisionRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="inout" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nuevo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="borrado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idcomision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modificado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orcomision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="porcentaje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idtipoventa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idporcentaje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idtipocalculo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombrecomision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idtipocondicion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombretipoventa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idseccioncalculo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombretipocalculo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idsubtipocondicion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombretipocondicion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombreseccioncalculo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombresubtipocondicion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Icm_Condicionestopes" type="{http://schemas.meta4.com/}Icm_CondicionestopesBlock"/>
 *         &lt;element name="Icm_Condicionesresalta" type="{http://schemas.meta4.com/}Icm_CondicionesresaltaBlock"/>
 *         &lt;element name="Icm_Condicionesdesplazamiento" type="{http://schemas.meta4.com/}Icm_CondicionesdesplazamientoBlock"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_CondicionescomisionRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "inout",
    "nuevo",
    "borrado",
    "idcomision",
    "modificado",
    "orcomision",
    "porcentaje",
    "idtipoventa",
    "idporcentaje",
    "idtipocalculo",
    "nombrecomision",
    "idtipocondicion",
    "nombretipoventa",
    "idseccioncalculo",
    "nombretipocalculo",
    "idsubtipocondicion",
    "nombretipocondicion",
    "nombreseccioncalculo",
    "nombresubtipocondicion",
    "icmCondicionestopes",
    "icmCondicionesresalta",
    "icmCondicionesdesplazamiento"
})
public class IcmCondicionescomisionRecord implements Cloneable, CopyTo2, Equals2, HashCode2, ToString2
{

    @XmlElement(required = true, nillable = true)
    protected String m4AutoGeneratedRecordID;
    protected boolean m4AutoGeneratedToDelete;
    @XmlElement(required = true, nillable = true)
    protected String inout;
    @XmlElement(required = true, nillable = true)
    protected String nuevo;
    @XmlElement(required = true, nillable = true)
    protected String borrado;
    @XmlElement(required = true, nillable = true)
    protected String idcomision;
    @XmlElement(required = true, nillable = true)
    protected String modificado;
    @XmlElement(required = true, nillable = true)
    protected String orcomision;
    @XmlElement(required = true, nillable = true)
    protected String porcentaje;
    @XmlElement(required = true, nillable = true)
    protected String idtipoventa;
    @XmlElement(required = true, nillable = true)
    protected String idporcentaje;
    @XmlElement(required = true, nillable = true)
    protected String idtipocalculo;
    @XmlElement(required = true, nillable = true)
    protected String nombrecomision;
    @XmlElement(required = true, nillable = true)
    protected String idtipocondicion;
    @XmlElement(required = true, nillable = true)
    protected String nombretipoventa;
    @XmlElement(required = true, nillable = true)
    protected String idseccioncalculo;
    @XmlElement(required = true, nillable = true)
    protected String nombretipocalculo;
    @XmlElement(required = true, nillable = true)
    protected String idsubtipocondicion;
    @XmlElement(required = true, nillable = true)
    protected String nombretipocondicion;
    @XmlElement(required = true, nillable = true)
    protected String nombreseccioncalculo;
    @XmlElement(required = true, nillable = true)
    protected String nombresubtipocondicion;
    @XmlElement(name = "Icm_Condicionestopes", required = true, nillable = true)
    protected IcmCondicionestopesBlock icmCondicionestopes;
    @XmlElement(name = "Icm_Condicionesresalta", required = true, nillable = true)
    protected IcmCondicionesresaltaBlock icmCondicionesresalta;
    @XmlElement(name = "Icm_Condicionesdesplazamiento", required = true, nillable = true)
    protected IcmCondicionesdesplazamientoBlock icmCondicionesdesplazamiento;

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM4AutoGeneratedRecordID(String value) {
        this.m4AutoGeneratedRecordID = value;
    }

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public void setM4AutoGeneratedToDelete(boolean value) {
        this.m4AutoGeneratedToDelete = value;
    }

    /**
     * Obtiene el valor de la propiedad inout.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInout() {
        return inout;
    }

    /**
     * Define el valor de la propiedad inout.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInout(String value) {
        this.inout = value;
    }

    /**
     * Obtiene el valor de la propiedad nuevo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuevo() {
        return nuevo;
    }

    /**
     * Define el valor de la propiedad nuevo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuevo(String value) {
        this.nuevo = value;
    }

    /**
     * Obtiene el valor de la propiedad borrado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrado() {
        return borrado;
    }

    /**
     * Define el valor de la propiedad borrado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrado(String value) {
        this.borrado = value;
    }

    /**
     * Obtiene el valor de la propiedad idcomision.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdcomision() {
        return idcomision;
    }

    /**
     * Define el valor de la propiedad idcomision.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdcomision(String value) {
        this.idcomision = value;
    }

    /**
     * Obtiene el valor de la propiedad modificado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificado() {
        return modificado;
    }

    /**
     * Define el valor de la propiedad modificado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificado(String value) {
        this.modificado = value;
    }

    /**
     * Obtiene el valor de la propiedad orcomision.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrcomision() {
        return orcomision;
    }

    /**
     * Define el valor de la propiedad orcomision.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrcomision(String value) {
        this.orcomision = value;
    }

    /**
     * Obtiene el valor de la propiedad porcentaje.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPorcentaje() {
        return porcentaje;
    }

    /**
     * Define el valor de la propiedad porcentaje.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPorcentaje(String value) {
        this.porcentaje = value;
    }

    /**
     * Obtiene el valor de la propiedad idtipoventa.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdtipoventa() {
        return idtipoventa;
    }

    /**
     * Define el valor de la propiedad idtipoventa.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdtipoventa(String value) {
        this.idtipoventa = value;
    }

    /**
     * Obtiene el valor de la propiedad idporcentaje.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdporcentaje() {
        return idporcentaje;
    }

    /**
     * Define el valor de la propiedad idporcentaje.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdporcentaje(String value) {
        this.idporcentaje = value;
    }

    /**
     * Obtiene el valor de la propiedad idtipocalculo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdtipocalculo() {
        return idtipocalculo;
    }

    /**
     * Define el valor de la propiedad idtipocalculo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdtipocalculo(String value) {
        this.idtipocalculo = value;
    }

    /**
     * Obtiene el valor de la propiedad nombrecomision.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombrecomision() {
        return nombrecomision;
    }

    /**
     * Define el valor de la propiedad nombrecomision.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombrecomision(String value) {
        this.nombrecomision = value;
    }

    /**
     * Obtiene el valor de la propiedad idtipocondicion.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdtipocondicion() {
        return idtipocondicion;
    }

    /**
     * Define el valor de la propiedad idtipocondicion.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdtipocondicion(String value) {
        this.idtipocondicion = value;
    }

    /**
     * Obtiene el valor de la propiedad nombretipoventa.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombretipoventa() {
        return nombretipoventa;
    }

    /**
     * Define el valor de la propiedad nombretipoventa.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombretipoventa(String value) {
        this.nombretipoventa = value;
    }

    /**
     * Obtiene el valor de la propiedad idseccioncalculo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdseccioncalculo() {
        return idseccioncalculo;
    }

    /**
     * Define el valor de la propiedad idseccioncalculo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdseccioncalculo(String value) {
        this.idseccioncalculo = value;
    }

    /**
     * Obtiene el valor de la propiedad nombretipocalculo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombretipocalculo() {
        return nombretipocalculo;
    }

    /**
     * Define el valor de la propiedad nombretipocalculo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombretipocalculo(String value) {
        this.nombretipocalculo = value;
    }

    /**
     * Obtiene el valor de la propiedad idsubtipocondicion.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdsubtipocondicion() {
        return idsubtipocondicion;
    }

    /**
     * Define el valor de la propiedad idsubtipocondicion.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdsubtipocondicion(String value) {
        this.idsubtipocondicion = value;
    }

    /**
     * Obtiene el valor de la propiedad nombretipocondicion.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombretipocondicion() {
        return nombretipocondicion;
    }

    /**
     * Define el valor de la propiedad nombretipocondicion.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombretipocondicion(String value) {
        this.nombretipocondicion = value;
    }

    /**
     * Obtiene el valor de la propiedad nombreseccioncalculo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreseccioncalculo() {
        return nombreseccioncalculo;
    }

    /**
     * Define el valor de la propiedad nombreseccioncalculo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreseccioncalculo(String value) {
        this.nombreseccioncalculo = value;
    }

    /**
     * Obtiene el valor de la propiedad nombresubtipocondicion.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombresubtipocondicion() {
        return nombresubtipocondicion;
    }

    /**
     * Define el valor de la propiedad nombresubtipocondicion.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombresubtipocondicion(String value) {
        this.nombresubtipocondicion = value;
    }

    /**
     * Obtiene el valor de la propiedad icmCondicionestopes.
     * 
     * @return
     *     possible object is
     *     {@link IcmCondicionestopesBlock }
     *     
     */
    public IcmCondicionestopesBlock getIcmCondicionestopes() {
        return icmCondicionestopes;
    }

    /**
     * Define el valor de la propiedad icmCondicionestopes.
     * 
     * @param value
     *     allowed object is
     *     {@link IcmCondicionestopesBlock }
     *     
     */
    public void setIcmCondicionestopes(IcmCondicionestopesBlock value) {
        this.icmCondicionestopes = value;
    }

    /**
     * Obtiene el valor de la propiedad icmCondicionesresalta.
     * 
     * @return
     *     possible object is
     *     {@link IcmCondicionesresaltaBlock }
     *     
     */
    public IcmCondicionesresaltaBlock getIcmCondicionesresalta() {
        return icmCondicionesresalta;
    }

    /**
     * Define el valor de la propiedad icmCondicionesresalta.
     * 
     * @param value
     *     allowed object is
     *     {@link IcmCondicionesresaltaBlock }
     *     
     */
    public void setIcmCondicionesresalta(IcmCondicionesresaltaBlock value) {
        this.icmCondicionesresalta = value;
    }

    /**
     * Obtiene el valor de la propiedad icmCondicionesdesplazamiento.
     * 
     * @return
     *     possible object is
     *     {@link IcmCondicionesdesplazamientoBlock }
     *     
     */
    public IcmCondicionesdesplazamientoBlock getIcmCondicionesdesplazamiento() {
        return icmCondicionesdesplazamiento;
    }

    /**
     * Define el valor de la propiedad icmCondicionesdesplazamiento.
     * 
     * @param value
     *     allowed object is
     *     {@link IcmCondicionesdesplazamientoBlock }
     *     
     */
    public void setIcmCondicionesdesplazamiento(IcmCondicionesdesplazamientoBlock value) {
        this.icmCondicionesdesplazamiento = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final IcmCondicionescomisionRecord that = ((IcmCondicionescomisionRecord) object);
        {
            String lhsM4AutoGeneratedRecordID;
            lhsM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            String rhsM4AutoGeneratedRecordID;
            rhsM4AutoGeneratedRecordID = that.getM4AutoGeneratedRecordID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedRecordID", lhsM4AutoGeneratedRecordID), LocatorUtils.property(thatLocator, "m4AutoGeneratedRecordID", rhsM4AutoGeneratedRecordID), lhsM4AutoGeneratedRecordID, rhsM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null), (that.m4AutoGeneratedRecordID!= null))) {
                return false;
            }
        }
        {
            boolean lhsM4AutoGeneratedToDelete;
            lhsM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            boolean rhsM4AutoGeneratedToDelete;
            rhsM4AutoGeneratedToDelete = that.isM4AutoGeneratedToDelete();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedToDelete", lhsM4AutoGeneratedToDelete), LocatorUtils.property(thatLocator, "m4AutoGeneratedToDelete", rhsM4AutoGeneratedToDelete), lhsM4AutoGeneratedToDelete, rhsM4AutoGeneratedToDelete, true, true)) {
                return false;
            }
        }
        {
            String lhsInout;
            lhsInout = this.getInout();
            String rhsInout;
            rhsInout = that.getInout();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "inout", lhsInout), LocatorUtils.property(thatLocator, "inout", rhsInout), lhsInout, rhsInout, (this.inout!= null), (that.inout!= null))) {
                return false;
            }
        }
        {
            String lhsNuevo;
            lhsNuevo = this.getNuevo();
            String rhsNuevo;
            rhsNuevo = that.getNuevo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nuevo", lhsNuevo), LocatorUtils.property(thatLocator, "nuevo", rhsNuevo), lhsNuevo, rhsNuevo, (this.nuevo!= null), (that.nuevo!= null))) {
                return false;
            }
        }
        {
            String lhsBorrado;
            lhsBorrado = this.getBorrado();
            String rhsBorrado;
            rhsBorrado = that.getBorrado();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "borrado", lhsBorrado), LocatorUtils.property(thatLocator, "borrado", rhsBorrado), lhsBorrado, rhsBorrado, (this.borrado!= null), (that.borrado!= null))) {
                return false;
            }
        }
        {
            String lhsIdcomision;
            lhsIdcomision = this.getIdcomision();
            String rhsIdcomision;
            rhsIdcomision = that.getIdcomision();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idcomision", lhsIdcomision), LocatorUtils.property(thatLocator, "idcomision", rhsIdcomision), lhsIdcomision, rhsIdcomision, (this.idcomision!= null), (that.idcomision!= null))) {
                return false;
            }
        }
        {
            String lhsModificado;
            lhsModificado = this.getModificado();
            String rhsModificado;
            rhsModificado = that.getModificado();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "modificado", lhsModificado), LocatorUtils.property(thatLocator, "modificado", rhsModificado), lhsModificado, rhsModificado, (this.modificado!= null), (that.modificado!= null))) {
                return false;
            }
        }
        {
            String lhsOrcomision;
            lhsOrcomision = this.getOrcomision();
            String rhsOrcomision;
            rhsOrcomision = that.getOrcomision();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orcomision", lhsOrcomision), LocatorUtils.property(thatLocator, "orcomision", rhsOrcomision), lhsOrcomision, rhsOrcomision, (this.orcomision!= null), (that.orcomision!= null))) {
                return false;
            }
        }
        {
            String lhsPorcentaje;
            lhsPorcentaje = this.getPorcentaje();
            String rhsPorcentaje;
            rhsPorcentaje = that.getPorcentaje();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "porcentaje", lhsPorcentaje), LocatorUtils.property(thatLocator, "porcentaje", rhsPorcentaje), lhsPorcentaje, rhsPorcentaje, (this.porcentaje!= null), (that.porcentaje!= null))) {
                return false;
            }
        }
        {
            String lhsIdtipoventa;
            lhsIdtipoventa = this.getIdtipoventa();
            String rhsIdtipoventa;
            rhsIdtipoventa = that.getIdtipoventa();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idtipoventa", lhsIdtipoventa), LocatorUtils.property(thatLocator, "idtipoventa", rhsIdtipoventa), lhsIdtipoventa, rhsIdtipoventa, (this.idtipoventa!= null), (that.idtipoventa!= null))) {
                return false;
            }
        }
        {
            String lhsIdporcentaje;
            lhsIdporcentaje = this.getIdporcentaje();
            String rhsIdporcentaje;
            rhsIdporcentaje = that.getIdporcentaje();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idporcentaje", lhsIdporcentaje), LocatorUtils.property(thatLocator, "idporcentaje", rhsIdporcentaje), lhsIdporcentaje, rhsIdporcentaje, (this.idporcentaje!= null), (that.idporcentaje!= null))) {
                return false;
            }
        }
        {
            String lhsIdtipocalculo;
            lhsIdtipocalculo = this.getIdtipocalculo();
            String rhsIdtipocalculo;
            rhsIdtipocalculo = that.getIdtipocalculo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idtipocalculo", lhsIdtipocalculo), LocatorUtils.property(thatLocator, "idtipocalculo", rhsIdtipocalculo), lhsIdtipocalculo, rhsIdtipocalculo, (this.idtipocalculo!= null), (that.idtipocalculo!= null))) {
                return false;
            }
        }
        {
            String lhsNombrecomision;
            lhsNombrecomision = this.getNombrecomision();
            String rhsNombrecomision;
            rhsNombrecomision = that.getNombrecomision();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nombrecomision", lhsNombrecomision), LocatorUtils.property(thatLocator, "nombrecomision", rhsNombrecomision), lhsNombrecomision, rhsNombrecomision, (this.nombrecomision!= null), (that.nombrecomision!= null))) {
                return false;
            }
        }
        {
            String lhsIdtipocondicion;
            lhsIdtipocondicion = this.getIdtipocondicion();
            String rhsIdtipocondicion;
            rhsIdtipocondicion = that.getIdtipocondicion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idtipocondicion", lhsIdtipocondicion), LocatorUtils.property(thatLocator, "idtipocondicion", rhsIdtipocondicion), lhsIdtipocondicion, rhsIdtipocondicion, (this.idtipocondicion!= null), (that.idtipocondicion!= null))) {
                return false;
            }
        }
        {
            String lhsNombretipoventa;
            lhsNombretipoventa = this.getNombretipoventa();
            String rhsNombretipoventa;
            rhsNombretipoventa = that.getNombretipoventa();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nombretipoventa", lhsNombretipoventa), LocatorUtils.property(thatLocator, "nombretipoventa", rhsNombretipoventa), lhsNombretipoventa, rhsNombretipoventa, (this.nombretipoventa!= null), (that.nombretipoventa!= null))) {
                return false;
            }
        }
        {
            String lhsIdseccioncalculo;
            lhsIdseccioncalculo = this.getIdseccioncalculo();
            String rhsIdseccioncalculo;
            rhsIdseccioncalculo = that.getIdseccioncalculo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idseccioncalculo", lhsIdseccioncalculo), LocatorUtils.property(thatLocator, "idseccioncalculo", rhsIdseccioncalculo), lhsIdseccioncalculo, rhsIdseccioncalculo, (this.idseccioncalculo!= null), (that.idseccioncalculo!= null))) {
                return false;
            }
        }
        {
            String lhsNombretipocalculo;
            lhsNombretipocalculo = this.getNombretipocalculo();
            String rhsNombretipocalculo;
            rhsNombretipocalculo = that.getNombretipocalculo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nombretipocalculo", lhsNombretipocalculo), LocatorUtils.property(thatLocator, "nombretipocalculo", rhsNombretipocalculo), lhsNombretipocalculo, rhsNombretipocalculo, (this.nombretipocalculo!= null), (that.nombretipocalculo!= null))) {
                return false;
            }
        }
        {
            String lhsIdsubtipocondicion;
            lhsIdsubtipocondicion = this.getIdsubtipocondicion();
            String rhsIdsubtipocondicion;
            rhsIdsubtipocondicion = that.getIdsubtipocondicion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idsubtipocondicion", lhsIdsubtipocondicion), LocatorUtils.property(thatLocator, "idsubtipocondicion", rhsIdsubtipocondicion), lhsIdsubtipocondicion, rhsIdsubtipocondicion, (this.idsubtipocondicion!= null), (that.idsubtipocondicion!= null))) {
                return false;
            }
        }
        {
            String lhsNombretipocondicion;
            lhsNombretipocondicion = this.getNombretipocondicion();
            String rhsNombretipocondicion;
            rhsNombretipocondicion = that.getNombretipocondicion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nombretipocondicion", lhsNombretipocondicion), LocatorUtils.property(thatLocator, "nombretipocondicion", rhsNombretipocondicion), lhsNombretipocondicion, rhsNombretipocondicion, (this.nombretipocondicion!= null), (that.nombretipocondicion!= null))) {
                return false;
            }
        }
        {
            String lhsNombreseccioncalculo;
            lhsNombreseccioncalculo = this.getNombreseccioncalculo();
            String rhsNombreseccioncalculo;
            rhsNombreseccioncalculo = that.getNombreseccioncalculo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nombreseccioncalculo", lhsNombreseccioncalculo), LocatorUtils.property(thatLocator, "nombreseccioncalculo", rhsNombreseccioncalculo), lhsNombreseccioncalculo, rhsNombreseccioncalculo, (this.nombreseccioncalculo!= null), (that.nombreseccioncalculo!= null))) {
                return false;
            }
        }
        {
            String lhsNombresubtipocondicion;
            lhsNombresubtipocondicion = this.getNombresubtipocondicion();
            String rhsNombresubtipocondicion;
            rhsNombresubtipocondicion = that.getNombresubtipocondicion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nombresubtipocondicion", lhsNombresubtipocondicion), LocatorUtils.property(thatLocator, "nombresubtipocondicion", rhsNombresubtipocondicion), lhsNombresubtipocondicion, rhsNombresubtipocondicion, (this.nombresubtipocondicion!= null), (that.nombresubtipocondicion!= null))) {
                return false;
            }
        }
        {
            IcmCondicionestopesBlock lhsIcmCondicionestopes;
            lhsIcmCondicionestopes = this.getIcmCondicionestopes();
            IcmCondicionestopesBlock rhsIcmCondicionestopes;
            rhsIcmCondicionestopes = that.getIcmCondicionestopes();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "icmCondicionestopes", lhsIcmCondicionestopes), LocatorUtils.property(thatLocator, "icmCondicionestopes", rhsIcmCondicionestopes), lhsIcmCondicionestopes, rhsIcmCondicionestopes, (this.icmCondicionestopes!= null), (that.icmCondicionestopes!= null))) {
                return false;
            }
        }
        {
            IcmCondicionesresaltaBlock lhsIcmCondicionesresalta;
            lhsIcmCondicionesresalta = this.getIcmCondicionesresalta();
            IcmCondicionesresaltaBlock rhsIcmCondicionesresalta;
            rhsIcmCondicionesresalta = that.getIcmCondicionesresalta();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "icmCondicionesresalta", lhsIcmCondicionesresalta), LocatorUtils.property(thatLocator, "icmCondicionesresalta", rhsIcmCondicionesresalta), lhsIcmCondicionesresalta, rhsIcmCondicionesresalta, (this.icmCondicionesresalta!= null), (that.icmCondicionesresalta!= null))) {
                return false;
            }
        }
        {
            IcmCondicionesdesplazamientoBlock lhsIcmCondicionesdesplazamiento;
            lhsIcmCondicionesdesplazamiento = this.getIcmCondicionesdesplazamiento();
            IcmCondicionesdesplazamientoBlock rhsIcmCondicionesdesplazamiento;
            rhsIcmCondicionesdesplazamiento = that.getIcmCondicionesdesplazamiento();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "icmCondicionesdesplazamiento", lhsIcmCondicionesdesplazamiento), LocatorUtils.property(thatLocator, "icmCondicionesdesplazamiento", rhsIcmCondicionesdesplazamiento), lhsIcmCondicionesdesplazamiento, rhsIcmCondicionesdesplazamiento, (this.icmCondicionesdesplazamiento!= null), (that.icmCondicionesdesplazamiento!= null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            String theM4AutoGeneratedRecordID;
            theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            strategy.appendField(locator, this, "m4AutoGeneratedRecordID", buffer, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null));
        }
        {
            boolean theM4AutoGeneratedToDelete;
            theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            strategy.appendField(locator, this, "m4AutoGeneratedToDelete", buffer, theM4AutoGeneratedToDelete, true);
        }
        {
            String theInout;
            theInout = this.getInout();
            strategy.appendField(locator, this, "inout", buffer, theInout, (this.inout!= null));
        }
        {
            String theNuevo;
            theNuevo = this.getNuevo();
            strategy.appendField(locator, this, "nuevo", buffer, theNuevo, (this.nuevo!= null));
        }
        {
            String theBorrado;
            theBorrado = this.getBorrado();
            strategy.appendField(locator, this, "borrado", buffer, theBorrado, (this.borrado!= null));
        }
        {
            String theIdcomision;
            theIdcomision = this.getIdcomision();
            strategy.appendField(locator, this, "idcomision", buffer, theIdcomision, (this.idcomision!= null));
        }
        {
            String theModificado;
            theModificado = this.getModificado();
            strategy.appendField(locator, this, "modificado", buffer, theModificado, (this.modificado!= null));
        }
        {
            String theOrcomision;
            theOrcomision = this.getOrcomision();
            strategy.appendField(locator, this, "orcomision", buffer, theOrcomision, (this.orcomision!= null));
        }
        {
            String thePorcentaje;
            thePorcentaje = this.getPorcentaje();
            strategy.appendField(locator, this, "porcentaje", buffer, thePorcentaje, (this.porcentaje!= null));
        }
        {
            String theIdtipoventa;
            theIdtipoventa = this.getIdtipoventa();
            strategy.appendField(locator, this, "idtipoventa", buffer, theIdtipoventa, (this.idtipoventa!= null));
        }
        {
            String theIdporcentaje;
            theIdporcentaje = this.getIdporcentaje();
            strategy.appendField(locator, this, "idporcentaje", buffer, theIdporcentaje, (this.idporcentaje!= null));
        }
        {
            String theIdtipocalculo;
            theIdtipocalculo = this.getIdtipocalculo();
            strategy.appendField(locator, this, "idtipocalculo", buffer, theIdtipocalculo, (this.idtipocalculo!= null));
        }
        {
            String theNombrecomision;
            theNombrecomision = this.getNombrecomision();
            strategy.appendField(locator, this, "nombrecomision", buffer, theNombrecomision, (this.nombrecomision!= null));
        }
        {
            String theIdtipocondicion;
            theIdtipocondicion = this.getIdtipocondicion();
            strategy.appendField(locator, this, "idtipocondicion", buffer, theIdtipocondicion, (this.idtipocondicion!= null));
        }
        {
            String theNombretipoventa;
            theNombretipoventa = this.getNombretipoventa();
            strategy.appendField(locator, this, "nombretipoventa", buffer, theNombretipoventa, (this.nombretipoventa!= null));
        }
        {
            String theIdseccioncalculo;
            theIdseccioncalculo = this.getIdseccioncalculo();
            strategy.appendField(locator, this, "idseccioncalculo", buffer, theIdseccioncalculo, (this.idseccioncalculo!= null));
        }
        {
            String theNombretipocalculo;
            theNombretipocalculo = this.getNombretipocalculo();
            strategy.appendField(locator, this, "nombretipocalculo", buffer, theNombretipocalculo, (this.nombretipocalculo!= null));
        }
        {
            String theIdsubtipocondicion;
            theIdsubtipocondicion = this.getIdsubtipocondicion();
            strategy.appendField(locator, this, "idsubtipocondicion", buffer, theIdsubtipocondicion, (this.idsubtipocondicion!= null));
        }
        {
            String theNombretipocondicion;
            theNombretipocondicion = this.getNombretipocondicion();
            strategy.appendField(locator, this, "nombretipocondicion", buffer, theNombretipocondicion, (this.nombretipocondicion!= null));
        }
        {
            String theNombreseccioncalculo;
            theNombreseccioncalculo = this.getNombreseccioncalculo();
            strategy.appendField(locator, this, "nombreseccioncalculo", buffer, theNombreseccioncalculo, (this.nombreseccioncalculo!= null));
        }
        {
            String theNombresubtipocondicion;
            theNombresubtipocondicion = this.getNombresubtipocondicion();
            strategy.appendField(locator, this, "nombresubtipocondicion", buffer, theNombresubtipocondicion, (this.nombresubtipocondicion!= null));
        }
        {
            IcmCondicionestopesBlock theIcmCondicionestopes;
            theIcmCondicionestopes = this.getIcmCondicionestopes();
            strategy.appendField(locator, this, "icmCondicionestopes", buffer, theIcmCondicionestopes, (this.icmCondicionestopes!= null));
        }
        {
            IcmCondicionesresaltaBlock theIcmCondicionesresalta;
            theIcmCondicionesresalta = this.getIcmCondicionesresalta();
            strategy.appendField(locator, this, "icmCondicionesresalta", buffer, theIcmCondicionesresalta, (this.icmCondicionesresalta!= null));
        }
        {
            IcmCondicionesdesplazamientoBlock theIcmCondicionesdesplazamiento;
            theIcmCondicionesdesplazamiento = this.getIcmCondicionesdesplazamiento();
            strategy.appendField(locator, this, "icmCondicionesdesplazamiento", buffer, theIcmCondicionesdesplazamiento, (this.icmCondicionesdesplazamiento!= null));
        }
        return buffer;
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            String theM4AutoGeneratedRecordID;
            theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", theM4AutoGeneratedRecordID), currentHashCode, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null));
        }
        {
            boolean theM4AutoGeneratedToDelete;
            theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", theM4AutoGeneratedToDelete), currentHashCode, theM4AutoGeneratedToDelete, true);
        }
        {
            String theInout;
            theInout = this.getInout();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "inout", theInout), currentHashCode, theInout, (this.inout!= null));
        }
        {
            String theNuevo;
            theNuevo = this.getNuevo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nuevo", theNuevo), currentHashCode, theNuevo, (this.nuevo!= null));
        }
        {
            String theBorrado;
            theBorrado = this.getBorrado();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "borrado", theBorrado), currentHashCode, theBorrado, (this.borrado!= null));
        }
        {
            String theIdcomision;
            theIdcomision = this.getIdcomision();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idcomision", theIdcomision), currentHashCode, theIdcomision, (this.idcomision!= null));
        }
        {
            String theModificado;
            theModificado = this.getModificado();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "modificado", theModificado), currentHashCode, theModificado, (this.modificado!= null));
        }
        {
            String theOrcomision;
            theOrcomision = this.getOrcomision();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orcomision", theOrcomision), currentHashCode, theOrcomision, (this.orcomision!= null));
        }
        {
            String thePorcentaje;
            thePorcentaje = this.getPorcentaje();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "porcentaje", thePorcentaje), currentHashCode, thePorcentaje, (this.porcentaje!= null));
        }
        {
            String theIdtipoventa;
            theIdtipoventa = this.getIdtipoventa();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idtipoventa", theIdtipoventa), currentHashCode, theIdtipoventa, (this.idtipoventa!= null));
        }
        {
            String theIdporcentaje;
            theIdporcentaje = this.getIdporcentaje();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idporcentaje", theIdporcentaje), currentHashCode, theIdporcentaje, (this.idporcentaje!= null));
        }
        {
            String theIdtipocalculo;
            theIdtipocalculo = this.getIdtipocalculo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idtipocalculo", theIdtipocalculo), currentHashCode, theIdtipocalculo, (this.idtipocalculo!= null));
        }
        {
            String theNombrecomision;
            theNombrecomision = this.getNombrecomision();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nombrecomision", theNombrecomision), currentHashCode, theNombrecomision, (this.nombrecomision!= null));
        }
        {
            String theIdtipocondicion;
            theIdtipocondicion = this.getIdtipocondicion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idtipocondicion", theIdtipocondicion), currentHashCode, theIdtipocondicion, (this.idtipocondicion!= null));
        }
        {
            String theNombretipoventa;
            theNombretipoventa = this.getNombretipoventa();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nombretipoventa", theNombretipoventa), currentHashCode, theNombretipoventa, (this.nombretipoventa!= null));
        }
        {
            String theIdseccioncalculo;
            theIdseccioncalculo = this.getIdseccioncalculo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idseccioncalculo", theIdseccioncalculo), currentHashCode, theIdseccioncalculo, (this.idseccioncalculo!= null));
        }
        {
            String theNombretipocalculo;
            theNombretipocalculo = this.getNombretipocalculo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nombretipocalculo", theNombretipocalculo), currentHashCode, theNombretipocalculo, (this.nombretipocalculo!= null));
        }
        {
            String theIdsubtipocondicion;
            theIdsubtipocondicion = this.getIdsubtipocondicion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idsubtipocondicion", theIdsubtipocondicion), currentHashCode, theIdsubtipocondicion, (this.idsubtipocondicion!= null));
        }
        {
            String theNombretipocondicion;
            theNombretipocondicion = this.getNombretipocondicion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nombretipocondicion", theNombretipocondicion), currentHashCode, theNombretipocondicion, (this.nombretipocondicion!= null));
        }
        {
            String theNombreseccioncalculo;
            theNombreseccioncalculo = this.getNombreseccioncalculo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nombreseccioncalculo", theNombreseccioncalculo), currentHashCode, theNombreseccioncalculo, (this.nombreseccioncalculo!= null));
        }
        {
            String theNombresubtipocondicion;
            theNombresubtipocondicion = this.getNombresubtipocondicion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nombresubtipocondicion", theNombresubtipocondicion), currentHashCode, theNombresubtipocondicion, (this.nombresubtipocondicion!= null));
        }
        {
            IcmCondicionestopesBlock theIcmCondicionestopes;
            theIcmCondicionestopes = this.getIcmCondicionestopes();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "icmCondicionestopes", theIcmCondicionestopes), currentHashCode, theIcmCondicionestopes, (this.icmCondicionestopes!= null));
        }
        {
            IcmCondicionesresaltaBlock theIcmCondicionesresalta;
            theIcmCondicionesresalta = this.getIcmCondicionesresalta();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "icmCondicionesresalta", theIcmCondicionesresalta), currentHashCode, theIcmCondicionesresalta, (this.icmCondicionesresalta!= null));
        }
        {
            IcmCondicionesdesplazamientoBlock theIcmCondicionesdesplazamiento;
            theIcmCondicionesdesplazamiento = this.getIcmCondicionesdesplazamiento();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "icmCondicionesdesplazamiento", theIcmCondicionesdesplazamiento), currentHashCode, theIcmCondicionesdesplazamiento, (this.icmCondicionesdesplazamiento!= null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof IcmCondicionescomisionRecord) {
            final IcmCondicionescomisionRecord copy = ((IcmCondicionescomisionRecord) draftCopy);
            {
                Boolean m4AutoGeneratedRecordIDShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.m4AutoGeneratedRecordID!= null));
                if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceM4AutoGeneratedRecordID;
                    sourceM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
                    String copyM4AutoGeneratedRecordID = ((String) strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", sourceM4AutoGeneratedRecordID), sourceM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null)));
                    copy.setM4AutoGeneratedRecordID(copyM4AutoGeneratedRecordID);
                } else {
                    if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.m4AutoGeneratedRecordID = null;
                    }
                }
            }
            {
                Boolean m4AutoGeneratedToDeleteShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, true);
                if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.TRUE) {
                    boolean sourceM4AutoGeneratedToDelete;
                    sourceM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
                    boolean copyM4AutoGeneratedToDelete = strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", sourceM4AutoGeneratedToDelete), sourceM4AutoGeneratedToDelete, true);
                    copy.setM4AutoGeneratedToDelete(copyM4AutoGeneratedToDelete);
                } else {
                    if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.FALSE) {
                    }
                }
            }
            {
                Boolean inoutShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.inout!= null));
                if (inoutShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceInout;
                    sourceInout = this.getInout();
                    String copyInout = ((String) strategy.copy(LocatorUtils.property(locator, "inout", sourceInout), sourceInout, (this.inout!= null)));
                    copy.setInout(copyInout);
                } else {
                    if (inoutShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.inout = null;
                    }
                }
            }
            {
                Boolean nuevoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.nuevo!= null));
                if (nuevoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceNuevo;
                    sourceNuevo = this.getNuevo();
                    String copyNuevo = ((String) strategy.copy(LocatorUtils.property(locator, "nuevo", sourceNuevo), sourceNuevo, (this.nuevo!= null)));
                    copy.setNuevo(copyNuevo);
                } else {
                    if (nuevoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.nuevo = null;
                    }
                }
            }
            {
                Boolean borradoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.borrado!= null));
                if (borradoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceBorrado;
                    sourceBorrado = this.getBorrado();
                    String copyBorrado = ((String) strategy.copy(LocatorUtils.property(locator, "borrado", sourceBorrado), sourceBorrado, (this.borrado!= null)));
                    copy.setBorrado(copyBorrado);
                } else {
                    if (borradoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.borrado = null;
                    }
                }
            }
            {
                Boolean idcomisionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idcomision!= null));
                if (idcomisionShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdcomision;
                    sourceIdcomision = this.getIdcomision();
                    String copyIdcomision = ((String) strategy.copy(LocatorUtils.property(locator, "idcomision", sourceIdcomision), sourceIdcomision, (this.idcomision!= null)));
                    copy.setIdcomision(copyIdcomision);
                } else {
                    if (idcomisionShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idcomision = null;
                    }
                }
            }
            {
                Boolean modificadoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.modificado!= null));
                if (modificadoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceModificado;
                    sourceModificado = this.getModificado();
                    String copyModificado = ((String) strategy.copy(LocatorUtils.property(locator, "modificado", sourceModificado), sourceModificado, (this.modificado!= null)));
                    copy.setModificado(copyModificado);
                } else {
                    if (modificadoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.modificado = null;
                    }
                }
            }
            {
                Boolean orcomisionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.orcomision!= null));
                if (orcomisionShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceOrcomision;
                    sourceOrcomision = this.getOrcomision();
                    String copyOrcomision = ((String) strategy.copy(LocatorUtils.property(locator, "orcomision", sourceOrcomision), sourceOrcomision, (this.orcomision!= null)));
                    copy.setOrcomision(copyOrcomision);
                } else {
                    if (orcomisionShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.orcomision = null;
                    }
                }
            }
            {
                Boolean porcentajeShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.porcentaje!= null));
                if (porcentajeShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourcePorcentaje;
                    sourcePorcentaje = this.getPorcentaje();
                    String copyPorcentaje = ((String) strategy.copy(LocatorUtils.property(locator, "porcentaje", sourcePorcentaje), sourcePorcentaje, (this.porcentaje!= null)));
                    copy.setPorcentaje(copyPorcentaje);
                } else {
                    if (porcentajeShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.porcentaje = null;
                    }
                }
            }
            {
                Boolean idtipoventaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idtipoventa!= null));
                if (idtipoventaShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdtipoventa;
                    sourceIdtipoventa = this.getIdtipoventa();
                    String copyIdtipoventa = ((String) strategy.copy(LocatorUtils.property(locator, "idtipoventa", sourceIdtipoventa), sourceIdtipoventa, (this.idtipoventa!= null)));
                    copy.setIdtipoventa(copyIdtipoventa);
                } else {
                    if (idtipoventaShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idtipoventa = null;
                    }
                }
            }
            {
                Boolean idporcentajeShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idporcentaje!= null));
                if (idporcentajeShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdporcentaje;
                    sourceIdporcentaje = this.getIdporcentaje();
                    String copyIdporcentaje = ((String) strategy.copy(LocatorUtils.property(locator, "idporcentaje", sourceIdporcentaje), sourceIdporcentaje, (this.idporcentaje!= null)));
                    copy.setIdporcentaje(copyIdporcentaje);
                } else {
                    if (idporcentajeShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idporcentaje = null;
                    }
                }
            }
            {
                Boolean idtipocalculoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idtipocalculo!= null));
                if (idtipocalculoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdtipocalculo;
                    sourceIdtipocalculo = this.getIdtipocalculo();
                    String copyIdtipocalculo = ((String) strategy.copy(LocatorUtils.property(locator, "idtipocalculo", sourceIdtipocalculo), sourceIdtipocalculo, (this.idtipocalculo!= null)));
                    copy.setIdtipocalculo(copyIdtipocalculo);
                } else {
                    if (idtipocalculoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idtipocalculo = null;
                    }
                }
            }
            {
                Boolean nombrecomisionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.nombrecomision!= null));
                if (nombrecomisionShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceNombrecomision;
                    sourceNombrecomision = this.getNombrecomision();
                    String copyNombrecomision = ((String) strategy.copy(LocatorUtils.property(locator, "nombrecomision", sourceNombrecomision), sourceNombrecomision, (this.nombrecomision!= null)));
                    copy.setNombrecomision(copyNombrecomision);
                } else {
                    if (nombrecomisionShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.nombrecomision = null;
                    }
                }
            }
            {
                Boolean idtipocondicionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idtipocondicion!= null));
                if (idtipocondicionShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdtipocondicion;
                    sourceIdtipocondicion = this.getIdtipocondicion();
                    String copyIdtipocondicion = ((String) strategy.copy(LocatorUtils.property(locator, "idtipocondicion", sourceIdtipocondicion), sourceIdtipocondicion, (this.idtipocondicion!= null)));
                    copy.setIdtipocondicion(copyIdtipocondicion);
                } else {
                    if (idtipocondicionShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idtipocondicion = null;
                    }
                }
            }
            {
                Boolean nombretipoventaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.nombretipoventa!= null));
                if (nombretipoventaShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceNombretipoventa;
                    sourceNombretipoventa = this.getNombretipoventa();
                    String copyNombretipoventa = ((String) strategy.copy(LocatorUtils.property(locator, "nombretipoventa", sourceNombretipoventa), sourceNombretipoventa, (this.nombretipoventa!= null)));
                    copy.setNombretipoventa(copyNombretipoventa);
                } else {
                    if (nombretipoventaShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.nombretipoventa = null;
                    }
                }
            }
            {
                Boolean idseccioncalculoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idseccioncalculo!= null));
                if (idseccioncalculoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdseccioncalculo;
                    sourceIdseccioncalculo = this.getIdseccioncalculo();
                    String copyIdseccioncalculo = ((String) strategy.copy(LocatorUtils.property(locator, "idseccioncalculo", sourceIdseccioncalculo), sourceIdseccioncalculo, (this.idseccioncalculo!= null)));
                    copy.setIdseccioncalculo(copyIdseccioncalculo);
                } else {
                    if (idseccioncalculoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idseccioncalculo = null;
                    }
                }
            }
            {
                Boolean nombretipocalculoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.nombretipocalculo!= null));
                if (nombretipocalculoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceNombretipocalculo;
                    sourceNombretipocalculo = this.getNombretipocalculo();
                    String copyNombretipocalculo = ((String) strategy.copy(LocatorUtils.property(locator, "nombretipocalculo", sourceNombretipocalculo), sourceNombretipocalculo, (this.nombretipocalculo!= null)));
                    copy.setNombretipocalculo(copyNombretipocalculo);
                } else {
                    if (nombretipocalculoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.nombretipocalculo = null;
                    }
                }
            }
            {
                Boolean idsubtipocondicionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idsubtipocondicion!= null));
                if (idsubtipocondicionShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdsubtipocondicion;
                    sourceIdsubtipocondicion = this.getIdsubtipocondicion();
                    String copyIdsubtipocondicion = ((String) strategy.copy(LocatorUtils.property(locator, "idsubtipocondicion", sourceIdsubtipocondicion), sourceIdsubtipocondicion, (this.idsubtipocondicion!= null)));
                    copy.setIdsubtipocondicion(copyIdsubtipocondicion);
                } else {
                    if (idsubtipocondicionShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idsubtipocondicion = null;
                    }
                }
            }
            {
                Boolean nombretipocondicionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.nombretipocondicion!= null));
                if (nombretipocondicionShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceNombretipocondicion;
                    sourceNombretipocondicion = this.getNombretipocondicion();
                    String copyNombretipocondicion = ((String) strategy.copy(LocatorUtils.property(locator, "nombretipocondicion", sourceNombretipocondicion), sourceNombretipocondicion, (this.nombretipocondicion!= null)));
                    copy.setNombretipocondicion(copyNombretipocondicion);
                } else {
                    if (nombretipocondicionShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.nombretipocondicion = null;
                    }
                }
            }
            {
                Boolean nombreseccioncalculoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.nombreseccioncalculo!= null));
                if (nombreseccioncalculoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceNombreseccioncalculo;
                    sourceNombreseccioncalculo = this.getNombreseccioncalculo();
                    String copyNombreseccioncalculo = ((String) strategy.copy(LocatorUtils.property(locator, "nombreseccioncalculo", sourceNombreseccioncalculo), sourceNombreseccioncalculo, (this.nombreseccioncalculo!= null)));
                    copy.setNombreseccioncalculo(copyNombreseccioncalculo);
                } else {
                    if (nombreseccioncalculoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.nombreseccioncalculo = null;
                    }
                }
            }
            {
                Boolean nombresubtipocondicionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.nombresubtipocondicion!= null));
                if (nombresubtipocondicionShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceNombresubtipocondicion;
                    sourceNombresubtipocondicion = this.getNombresubtipocondicion();
                    String copyNombresubtipocondicion = ((String) strategy.copy(LocatorUtils.property(locator, "nombresubtipocondicion", sourceNombresubtipocondicion), sourceNombresubtipocondicion, (this.nombresubtipocondicion!= null)));
                    copy.setNombresubtipocondicion(copyNombresubtipocondicion);
                } else {
                    if (nombresubtipocondicionShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.nombresubtipocondicion = null;
                    }
                }
            }
            {
                Boolean icmCondicionestopesShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.icmCondicionestopes!= null));
                if (icmCondicionestopesShouldBeCopiedAndSet == Boolean.TRUE) {
                    IcmCondicionestopesBlock sourceIcmCondicionestopes;
                    sourceIcmCondicionestopes = this.getIcmCondicionestopes();
                    IcmCondicionestopesBlock copyIcmCondicionestopes = ((IcmCondicionestopesBlock) strategy.copy(LocatorUtils.property(locator, "icmCondicionestopes", sourceIcmCondicionestopes), sourceIcmCondicionestopes, (this.icmCondicionestopes!= null)));
                    copy.setIcmCondicionestopes(copyIcmCondicionestopes);
                } else {
                    if (icmCondicionestopesShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.icmCondicionestopes = null;
                    }
                }
            }
            {
                Boolean icmCondicionesresaltaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.icmCondicionesresalta!= null));
                if (icmCondicionesresaltaShouldBeCopiedAndSet == Boolean.TRUE) {
                    IcmCondicionesresaltaBlock sourceIcmCondicionesresalta;
                    sourceIcmCondicionesresalta = this.getIcmCondicionesresalta();
                    IcmCondicionesresaltaBlock copyIcmCondicionesresalta = ((IcmCondicionesresaltaBlock) strategy.copy(LocatorUtils.property(locator, "icmCondicionesresalta", sourceIcmCondicionesresalta), sourceIcmCondicionesresalta, (this.icmCondicionesresalta!= null)));
                    copy.setIcmCondicionesresalta(copyIcmCondicionesresalta);
                } else {
                    if (icmCondicionesresaltaShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.icmCondicionesresalta = null;
                    }
                }
            }
            {
                Boolean icmCondicionesdesplazamientoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.icmCondicionesdesplazamiento!= null));
                if (icmCondicionesdesplazamientoShouldBeCopiedAndSet == Boolean.TRUE) {
                    IcmCondicionesdesplazamientoBlock sourceIcmCondicionesdesplazamiento;
                    sourceIcmCondicionesdesplazamiento = this.getIcmCondicionesdesplazamiento();
                    IcmCondicionesdesplazamientoBlock copyIcmCondicionesdesplazamiento = ((IcmCondicionesdesplazamientoBlock) strategy.copy(LocatorUtils.property(locator, "icmCondicionesdesplazamiento", sourceIcmCondicionesdesplazamiento), sourceIcmCondicionesdesplazamiento, (this.icmCondicionesdesplazamiento!= null)));
                    copy.setIcmCondicionesdesplazamiento(copyIcmCondicionesdesplazamiento);
                } else {
                    if (icmCondicionesdesplazamientoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.icmCondicionesdesplazamiento = null;
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new IcmCondicionescomisionRecord();
    }

}
