
package com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.icm_ws_income;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Icm_CondicionesdesplazamientoRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Icm_CondicionesdesplazamientoRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="inout" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nuevo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="borrado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modificado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idpuestodestino" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idtiendadestino" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idtipocondicion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="iddesplazamiento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idsecciondestino" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ordesplazamiento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idsubtipocondicion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idtipoopcioncalculo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombrepuestodestino" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombretiendadestino" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombretipocondicion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombredesplazamiento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombresecciondestino" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombresubtipocondicion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombretipoopcioncalculo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contabilizartiendaorigen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contabilizartiendadestino" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_CondicionesdesplazamientoRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "inout",
    "nuevo",
    "borrado",
    "modificado",
    "idpuestodestino",
    "idtiendadestino",
    "idtipocondicion",
    "iddesplazamiento",
    "idsecciondestino",
    "ordesplazamiento",
    "idsubtipocondicion",
    "idtipoopcioncalculo",
    "nombrepuestodestino",
    "nombretiendadestino",
    "nombretipocondicion",
    "nombredesplazamiento",
    "nombresecciondestino",
    "nombresubtipocondicion",
    "nombretipoopcioncalculo",
    "contabilizartiendaorigen",
    "contabilizartiendadestino"
})
public class IcmCondicionesdesplazamientoRecord {

    @XmlElement(required = true, nillable = true)
    protected String m4AutoGeneratedRecordID;
    protected boolean m4AutoGeneratedToDelete;
    @XmlElement(required = true, nillable = true)
    protected String inout;
    @XmlElement(required = true, nillable = true)
    protected String nuevo;
    @XmlElement(required = true, nillable = true)
    protected String borrado;
    @XmlElement(required = true, nillable = true)
    protected String modificado;
    @XmlElement(required = true, nillable = true)
    protected String idpuestodestino;
    @XmlElement(required = true, nillable = true)
    protected String idtiendadestino;
    @XmlElement(required = true, nillable = true)
    protected String idtipocondicion;
    @XmlElement(required = true, nillable = true)
    protected String iddesplazamiento;
    @XmlElement(required = true, nillable = true)
    protected String idsecciondestino;
    @XmlElement(required = true, nillable = true)
    protected String ordesplazamiento;
    @XmlElement(required = true, nillable = true)
    protected String idsubtipocondicion;
    @XmlElement(required = true, nillable = true)
    protected String idtipoopcioncalculo;
    @XmlElement(required = true, nillable = true)
    protected String nombrepuestodestino;
    @XmlElement(required = true, nillable = true)
    protected String nombretiendadestino;
    @XmlElement(required = true, nillable = true)
    protected String nombretipocondicion;
    @XmlElement(required = true, nillable = true)
    protected String nombredesplazamiento;
    @XmlElement(required = true, nillable = true)
    protected String nombresecciondestino;
    @XmlElement(required = true, nillable = true)
    protected String nombresubtipocondicion;
    @XmlElement(required = true, nillable = true)
    protected String nombretipoopcioncalculo;
    @XmlElement(required = true, nillable = true)
    protected String contabilizartiendaorigen;
    @XmlElement(required = true, nillable = true)
    protected String contabilizartiendadestino;

    /**
     * Gets the value of the m4AutoGeneratedRecordID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }

    /**
     * Sets the value of the m4AutoGeneratedRecordID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM4AutoGeneratedRecordID(String value) {
        this.m4AutoGeneratedRecordID = value;
    }

    /**
     * Gets the value of the m4AutoGeneratedToDelete property.
     * 
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }

    /**
     * Sets the value of the m4AutoGeneratedToDelete property.
     * 
     */
    public void setM4AutoGeneratedToDelete(boolean value) {
        this.m4AutoGeneratedToDelete = value;
    }

    /**
     * Gets the value of the inout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInout() {
        return inout;
    }

    /**
     * Sets the value of the inout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInout(String value) {
        this.inout = value;
    }

    /**
     * Gets the value of the nuevo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuevo() {
        return nuevo;
    }

    /**
     * Sets the value of the nuevo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuevo(String value) {
        this.nuevo = value;
    }

    /**
     * Gets the value of the borrado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrado() {
        return borrado;
    }

    /**
     * Sets the value of the borrado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrado(String value) {
        this.borrado = value;
    }

    /**
     * Gets the value of the modificado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificado() {
        return modificado;
    }

    /**
     * Sets the value of the modificado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificado(String value) {
        this.modificado = value;
    }

    /**
     * Gets the value of the idpuestodestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdpuestodestino() {
        return idpuestodestino;
    }

    /**
     * Sets the value of the idpuestodestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdpuestodestino(String value) {
        this.idpuestodestino = value;
    }

    /**
     * Gets the value of the idtiendadestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdtiendadestino() {
        return idtiendadestino;
    }

    /**
     * Sets the value of the idtiendadestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdtiendadestino(String value) {
        this.idtiendadestino = value;
    }

    /**
     * Gets the value of the idtipocondicion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdtipocondicion() {
        return idtipocondicion;
    }

    /**
     * Sets the value of the idtipocondicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdtipocondicion(String value) {
        this.idtipocondicion = value;
    }

    /**
     * Gets the value of the iddesplazamiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIddesplazamiento() {
        return iddesplazamiento;
    }

    /**
     * Sets the value of the iddesplazamiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIddesplazamiento(String value) {
        this.iddesplazamiento = value;
    }

    /**
     * Gets the value of the idsecciondestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdsecciondestino() {
        return idsecciondestino;
    }

    /**
     * Sets the value of the idsecciondestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdsecciondestino(String value) {
        this.idsecciondestino = value;
    }

    /**
     * Gets the value of the ordesplazamiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdesplazamiento() {
        return ordesplazamiento;
    }

    /**
     * Sets the value of the ordesplazamiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdesplazamiento(String value) {
        this.ordesplazamiento = value;
    }

    /**
     * Gets the value of the idsubtipocondicion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdsubtipocondicion() {
        return idsubtipocondicion;
    }

    /**
     * Sets the value of the idsubtipocondicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdsubtipocondicion(String value) {
        this.idsubtipocondicion = value;
    }

    /**
     * Gets the value of the idtipoopcioncalculo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdtipoopcioncalculo() {
        return idtipoopcioncalculo;
    }

    /**
     * Sets the value of the idtipoopcioncalculo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdtipoopcioncalculo(String value) {
        this.idtipoopcioncalculo = value;
    }

    /**
     * Gets the value of the nombrepuestodestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombrepuestodestino() {
        return nombrepuestodestino;
    }

    /**
     * Sets the value of the nombrepuestodestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombrepuestodestino(String value) {
        this.nombrepuestodestino = value;
    }

    /**
     * Gets the value of the nombretiendadestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombretiendadestino() {
        return nombretiendadestino;
    }

    /**
     * Sets the value of the nombretiendadestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombretiendadestino(String value) {
        this.nombretiendadestino = value;
    }

    /**
     * Gets the value of the nombretipocondicion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombretipocondicion() {
        return nombretipocondicion;
    }

    /**
     * Sets the value of the nombretipocondicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombretipocondicion(String value) {
        this.nombretipocondicion = value;
    }

    /**
     * Gets the value of the nombredesplazamiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombredesplazamiento() {
        return nombredesplazamiento;
    }

    /**
     * Sets the value of the nombredesplazamiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombredesplazamiento(String value) {
        this.nombredesplazamiento = value;
    }

    /**
     * Gets the value of the nombresecciondestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombresecciondestino() {
        return nombresecciondestino;
    }

    /**
     * Sets the value of the nombresecciondestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombresecciondestino(String value) {
        this.nombresecciondestino = value;
    }

    /**
     * Gets the value of the nombresubtipocondicion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombresubtipocondicion() {
        return nombresubtipocondicion;
    }

    /**
     * Sets the value of the nombresubtipocondicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombresubtipocondicion(String value) {
        this.nombresubtipocondicion = value;
    }

    /**
     * Gets the value of the nombretipoopcioncalculo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombretipoopcioncalculo() {
        return nombretipoopcioncalculo;
    }

    /**
     * Sets the value of the nombretipoopcioncalculo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombretipoopcioncalculo(String value) {
        this.nombretipoopcioncalculo = value;
    }

    /**
     * Gets the value of the contabilizartiendaorigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContabilizartiendaorigen() {
        return contabilizartiendaorigen;
    }

    /**
     * Sets the value of the contabilizartiendaorigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContabilizartiendaorigen(String value) {
        this.contabilizartiendaorigen = value;
    }

    /**
     * Gets the value of the contabilizartiendadestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContabilizartiendadestino() {
        return contabilizartiendadestino;
    }

    /**
     * Sets the value of the contabilizartiendadestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContabilizartiendadestino(String value) {
        this.contabilizartiendadestino = value;
    }

}
