
package com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.icm_ws_income;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Icm_EstadostiendaseccionRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Icm_EstadostiendaseccionRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="inout" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nuevo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="borrado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fechafin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idestado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idseccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modificado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fechainicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombreestado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombreseccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idlugartrabajo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_EstadostiendaseccionRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "inout",
    "nuevo",
    "borrado",
    "fechafin",
    "idestado",
    "idseccion",
    "modificado",
    "fechainicio",
    "nombreestado",
    "nombreseccion",
    "idlugartrabajo"
})
public class IcmEstadostiendaseccionRecord {

    @XmlElement(required = true, nillable = true)
    protected String m4AutoGeneratedRecordID;
    protected boolean m4AutoGeneratedToDelete;
    @XmlElement(required = true, nillable = true)
    protected String inout;
    @XmlElement(required = true, nillable = true)
    protected String nuevo;
    @XmlElement(required = true, nillable = true)
    protected String borrado;
    @XmlElement(required = true, nillable = true)
    protected String fechafin;
    @XmlElement(required = true, nillable = true)
    protected String idestado;
    @XmlElement(required = true, nillable = true)
    protected String idseccion;
    @XmlElement(required = true, nillable = true)
    protected String modificado;
    @XmlElement(required = true, nillable = true)
    protected String fechainicio;
    @XmlElement(required = true, nillable = true)
    protected String nombreestado;
    @XmlElement(required = true, nillable = true)
    protected String nombreseccion;
    @XmlElement(required = true, nillable = true)
    protected String idlugartrabajo;

    /**
     * Gets the value of the m4AutoGeneratedRecordID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }

    /**
     * Sets the value of the m4AutoGeneratedRecordID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM4AutoGeneratedRecordID(String value) {
        this.m4AutoGeneratedRecordID = value;
    }

    /**
     * Gets the value of the m4AutoGeneratedToDelete property.
     * 
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }

    /**
     * Sets the value of the m4AutoGeneratedToDelete property.
     * 
     */
    public void setM4AutoGeneratedToDelete(boolean value) {
        this.m4AutoGeneratedToDelete = value;
    }

    /**
     * Gets the value of the inout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInout() {
        return inout;
    }

    /**
     * Sets the value of the inout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInout(String value) {
        this.inout = value;
    }

    /**
     * Gets the value of the nuevo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuevo() {
        return nuevo;
    }

    /**
     * Sets the value of the nuevo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuevo(String value) {
        this.nuevo = value;
    }

    /**
     * Gets the value of the borrado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrado() {
        return borrado;
    }

    /**
     * Sets the value of the borrado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrado(String value) {
        this.borrado = value;
    }

    /**
     * Gets the value of the fechafin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechafin() {
        return fechafin;
    }

    /**
     * Sets the value of the fechafin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechafin(String value) {
        this.fechafin = value;
    }

    /**
     * Gets the value of the idestado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdestado() {
        return idestado;
    }

    /**
     * Sets the value of the idestado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdestado(String value) {
        this.idestado = value;
    }

    /**
     * Gets the value of the idseccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdseccion() {
        return idseccion;
    }

    /**
     * Sets the value of the idseccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdseccion(String value) {
        this.idseccion = value;
    }

    /**
     * Gets the value of the modificado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificado() {
        return modificado;
    }

    /**
     * Sets the value of the modificado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificado(String value) {
        this.modificado = value;
    }

    /**
     * Gets the value of the fechainicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechainicio() {
        return fechainicio;
    }

    /**
     * Sets the value of the fechainicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechainicio(String value) {
        this.fechainicio = value;
    }

    /**
     * Gets the value of the nombreestado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreestado() {
        return nombreestado;
    }

    /**
     * Sets the value of the nombreestado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreestado(String value) {
        this.nombreestado = value;
    }

    /**
     * Gets the value of the nombreseccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreseccion() {
        return nombreseccion;
    }

    /**
     * Sets the value of the nombreseccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreseccion(String value) {
        this.nombreseccion = value;
    }

    /**
     * Gets the value of the idlugartrabajo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdlugartrabajo() {
        return idlugartrabajo;
    }

    /**
     * Sets the value of the idlugartrabajo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdlugartrabajo(String value) {
        this.idlugartrabajo = value;
    }

}
