
package com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.icm_ws_income;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Icm_PlantillacondicionesRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Icm_PlantillacondicionesRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="inout" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nuevo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="borrado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modificado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idplantilla" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idestructura" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idtipoplantilla" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombreplantilla" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombreestructura" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombretipoplantilla" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Icm_Condicionesfijas" type="{http://schemas.meta4.com/}Icm_CondicionesfijasBlock"/>
 *         &lt;element name="Icm_Condicionescomision" type="{http://schemas.meta4.com/}Icm_CondicionescomisionBlock"/>
 *         &lt;element name="Icm_Condicionespoliticas" type="{http://schemas.meta4.com/}Icm_CondicionespoliticasBlock"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_PlantillacondicionesRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "inout",
    "nuevo",
    "borrado",
    "modificado",
    "idplantilla",
    "idestructura",
    "idtipoplantilla",
    "nombreplantilla",
    "nombreestructura",
    "nombretipoplantilla",
    "icmCondicionesfijas",
    "icmCondicionescomision",
    "icmCondicionespoliticas"
})
public class IcmPlantillacondicionesRecord {

    @XmlElement(required = true, nillable = true)
    protected String m4AutoGeneratedRecordID;
    protected boolean m4AutoGeneratedToDelete;
    @XmlElement(required = true, nillable = true)
    protected String inout;
    @XmlElement(required = true, nillable = true)
    protected String nuevo;
    @XmlElement(required = true, nillable = true)
    protected String borrado;
    @XmlElement(required = true, nillable = true)
    protected String modificado;
    @XmlElement(required = true, nillable = true)
    protected String idplantilla;
    @XmlElement(required = true, nillable = true)
    protected String idestructura;
    @XmlElement(required = true, nillable = true)
    protected String idtipoplantilla;
    @XmlElement(required = true, nillable = true)
    protected String nombreplantilla;
    @XmlElement(required = true, nillable = true)
    protected String nombreestructura;
    @XmlElement(required = true, nillable = true)
    protected String nombretipoplantilla;
    @XmlElement(name = "Icm_Condicionesfijas", required = true, nillable = true)
    protected IcmCondicionesfijasBlock icmCondicionesfijas;
    @XmlElement(name = "Icm_Condicionescomision", required = true, nillable = true)
    protected IcmCondicionescomisionBlock icmCondicionescomision;
    @XmlElement(name = "Icm_Condicionespoliticas", required = true, nillable = true)
    protected IcmCondicionespoliticasBlock icmCondicionespoliticas;

    /**
     * Gets the value of the m4AutoGeneratedRecordID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }

    /**
     * Sets the value of the m4AutoGeneratedRecordID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM4AutoGeneratedRecordID(String value) {
        this.m4AutoGeneratedRecordID = value;
    }

    /**
     * Gets the value of the m4AutoGeneratedToDelete property.
     * 
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }

    /**
     * Sets the value of the m4AutoGeneratedToDelete property.
     * 
     */
    public void setM4AutoGeneratedToDelete(boolean value) {
        this.m4AutoGeneratedToDelete = value;
    }

    /**
     * Gets the value of the inout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInout() {
        return inout;
    }

    /**
     * Sets the value of the inout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInout(String value) {
        this.inout = value;
    }

    /**
     * Gets the value of the nuevo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuevo() {
        return nuevo;
    }

    /**
     * Sets the value of the nuevo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuevo(String value) {
        this.nuevo = value;
    }

    /**
     * Gets the value of the borrado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrado() {
        return borrado;
    }

    /**
     * Sets the value of the borrado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrado(String value) {
        this.borrado = value;
    }

    /**
     * Gets the value of the modificado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificado() {
        return modificado;
    }

    /**
     * Sets the value of the modificado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificado(String value) {
        this.modificado = value;
    }

    /**
     * Gets the value of the idplantilla property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdplantilla() {
        return idplantilla;
    }

    /**
     * Sets the value of the idplantilla property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdplantilla(String value) {
        this.idplantilla = value;
    }

    /**
     * Gets the value of the idestructura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdestructura() {
        return idestructura;
    }

    /**
     * Sets the value of the idestructura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdestructura(String value) {
        this.idestructura = value;
    }

    /**
     * Gets the value of the idtipoplantilla property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdtipoplantilla() {
        return idtipoplantilla;
    }

    /**
     * Sets the value of the idtipoplantilla property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdtipoplantilla(String value) {
        this.idtipoplantilla = value;
    }

    /**
     * Gets the value of the nombreplantilla property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreplantilla() {
        return nombreplantilla;
    }

    /**
     * Sets the value of the nombreplantilla property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreplantilla(String value) {
        this.nombreplantilla = value;
    }

    /**
     * Gets the value of the nombreestructura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreestructura() {
        return nombreestructura;
    }

    /**
     * Sets the value of the nombreestructura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreestructura(String value) {
        this.nombreestructura = value;
    }

    /**
     * Gets the value of the nombretipoplantilla property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombretipoplantilla() {
        return nombretipoplantilla;
    }

    /**
     * Sets the value of the nombretipoplantilla property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombretipoplantilla(String value) {
        this.nombretipoplantilla = value;
    }

    /**
     * Gets the value of the icmCondicionesfijas property.
     * 
     * @return
     *     possible object is
     *     {@link IcmCondicionesfijasBlock }
     *     
     */
    public IcmCondicionesfijasBlock getIcmCondicionesfijas() {
        return icmCondicionesfijas;
    }

    /**
     * Sets the value of the icmCondicionesfijas property.
     * 
     * @param value
     *     allowed object is
     *     {@link IcmCondicionesfijasBlock }
     *     
     */
    public void setIcmCondicionesfijas(IcmCondicionesfijasBlock value) {
        this.icmCondicionesfijas = value;
    }

    /**
     * Gets the value of the icmCondicionescomision property.
     * 
     * @return
     *     possible object is
     *     {@link IcmCondicionescomisionBlock }
     *     
     */
    public IcmCondicionescomisionBlock getIcmCondicionescomision() {
        return icmCondicionescomision;
    }

    /**
     * Sets the value of the icmCondicionescomision property.
     * 
     * @param value
     *     allowed object is
     *     {@link IcmCondicionescomisionBlock }
     *     
     */
    public void setIcmCondicionescomision(IcmCondicionescomisionBlock value) {
        this.icmCondicionescomision = value;
    }

    /**
     * Gets the value of the icmCondicionespoliticas property.
     * 
     * @return
     *     possible object is
     *     {@link IcmCondicionespoliticasBlock }
     *     
     */
    public IcmCondicionespoliticasBlock getIcmCondicionespoliticas() {
        return icmCondicionespoliticas;
    }

    /**
     * Sets the value of the icmCondicionespoliticas property.
     * 
     * @param value
     *     allowed object is
     *     {@link IcmCondicionespoliticasBlock }
     *     
     */
    public void setIcmCondicionespoliticas(IcmCondicionespoliticasBlock value) {
        this.icmCondicionespoliticas = value;
    }

}
