
package com.inditex.rrhh.icmclcwb.model.meta4.icmwscalcincome.entity;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Clase Java para Icm_ListaconfprevalidRecord complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="Icm_ListaconfprevalidRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="delay" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idaccion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idestado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="delaytiempo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idprioridad" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idvalidacion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="reintentomax" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_ListaconfprevalidRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "delay",
    "idaccion",
    "idestado",
    "delaytiempo",
    "idprioridad",
    "idvalidacion",
    "reintentomax"
})
public class IcmListaconfprevalidRecord implements Serializable, Cloneable, CopyTo2, Equals2, HashCode2, ToString2
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true, nillable = true)
    protected String m4AutoGeneratedRecordID;
    protected boolean m4AutoGeneratedToDelete;
    @XmlElement(required = true, nillable = true)
    protected String delay;
    @XmlElement(required = true, nillable = true)
    protected String idaccion;
    @XmlElement(required = true, nillable = true)
    protected String idestado;
    @XmlElement(required = true, nillable = true)
    protected String delaytiempo;
    @XmlElement(required = true, nillable = true)
    protected String idprioridad;
    @XmlElement(required = true, nillable = true)
    protected String idvalidacion;
    @XmlElement(required = true, nillable = true)
    protected String reintentomax;

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM4AutoGeneratedRecordID(String value) {
        this.m4AutoGeneratedRecordID = value;
    }

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public void setM4AutoGeneratedToDelete(boolean value) {
        this.m4AutoGeneratedToDelete = value;
    }

    /**
     * Obtiene el valor de la propiedad delay.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelay() {
        return delay;
    }

    /**
     * Define el valor de la propiedad delay.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelay(String value) {
        this.delay = value;
    }

    /**
     * Obtiene el valor de la propiedad idaccion.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdaccion() {
        return idaccion;
    }

    /**
     * Define el valor de la propiedad idaccion.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdaccion(String value) {
        this.idaccion = value;
    }

    /**
     * Obtiene el valor de la propiedad idestado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdestado() {
        return idestado;
    }

    /**
     * Define el valor de la propiedad idestado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdestado(String value) {
        this.idestado = value;
    }

    /**
     * Obtiene el valor de la propiedad delaytiempo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelaytiempo() {
        return delaytiempo;
    }

    /**
     * Define el valor de la propiedad delaytiempo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelaytiempo(String value) {
        this.delaytiempo = value;
    }

    /**
     * Obtiene el valor de la propiedad idprioridad.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdprioridad() {
        return idprioridad;
    }

    /**
     * Define el valor de la propiedad idprioridad.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdprioridad(String value) {
        this.idprioridad = value;
    }

    /**
     * Obtiene el valor de la propiedad idvalidacion.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdvalidacion() {
        return idvalidacion;
    }

    /**
     * Define el valor de la propiedad idvalidacion.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdvalidacion(String value) {
        this.idvalidacion = value;
    }

    /**
     * Obtiene el valor de la propiedad reintentomax.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReintentomax() {
        return reintentomax;
    }

    /**
     * Define el valor de la propiedad reintentomax.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReintentomax(String value) {
        this.reintentomax = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final IcmListaconfprevalidRecord that = ((IcmListaconfprevalidRecord) object);
        {
            String lhsM4AutoGeneratedRecordID;
            lhsM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            String rhsM4AutoGeneratedRecordID;
            rhsM4AutoGeneratedRecordID = that.getM4AutoGeneratedRecordID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedRecordID", lhsM4AutoGeneratedRecordID), LocatorUtils.property(thatLocator, "m4AutoGeneratedRecordID", rhsM4AutoGeneratedRecordID), lhsM4AutoGeneratedRecordID, rhsM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null), (that.m4AutoGeneratedRecordID!= null))) {
                return false;
            }
        }
        {
            boolean lhsM4AutoGeneratedToDelete;
            lhsM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            boolean rhsM4AutoGeneratedToDelete;
            rhsM4AutoGeneratedToDelete = that.isM4AutoGeneratedToDelete();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedToDelete", lhsM4AutoGeneratedToDelete), LocatorUtils.property(thatLocator, "m4AutoGeneratedToDelete", rhsM4AutoGeneratedToDelete), lhsM4AutoGeneratedToDelete, rhsM4AutoGeneratedToDelete, true, true)) {
                return false;
            }
        }
        {
            String lhsDelay;
            lhsDelay = this.getDelay();
            String rhsDelay;
            rhsDelay = that.getDelay();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "delay", lhsDelay), LocatorUtils.property(thatLocator, "delay", rhsDelay), lhsDelay, rhsDelay, (this.delay!= null), (that.delay!= null))) {
                return false;
            }
        }
        {
            String lhsIdaccion;
            lhsIdaccion = this.getIdaccion();
            String rhsIdaccion;
            rhsIdaccion = that.getIdaccion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idaccion", lhsIdaccion), LocatorUtils.property(thatLocator, "idaccion", rhsIdaccion), lhsIdaccion, rhsIdaccion, (this.idaccion!= null), (that.idaccion!= null))) {
                return false;
            }
        }
        {
            String lhsIdestado;
            lhsIdestado = this.getIdestado();
            String rhsIdestado;
            rhsIdestado = that.getIdestado();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idestado", lhsIdestado), LocatorUtils.property(thatLocator, "idestado", rhsIdestado), lhsIdestado, rhsIdestado, (this.idestado!= null), (that.idestado!= null))) {
                return false;
            }
        }
        {
            String lhsDelaytiempo;
            lhsDelaytiempo = this.getDelaytiempo();
            String rhsDelaytiempo;
            rhsDelaytiempo = that.getDelaytiempo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "delaytiempo", lhsDelaytiempo), LocatorUtils.property(thatLocator, "delaytiempo", rhsDelaytiempo), lhsDelaytiempo, rhsDelaytiempo, (this.delaytiempo!= null), (that.delaytiempo!= null))) {
                return false;
            }
        }
        {
            String lhsIdprioridad;
            lhsIdprioridad = this.getIdprioridad();
            String rhsIdprioridad;
            rhsIdprioridad = that.getIdprioridad();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idprioridad", lhsIdprioridad), LocatorUtils.property(thatLocator, "idprioridad", rhsIdprioridad), lhsIdprioridad, rhsIdprioridad, (this.idprioridad!= null), (that.idprioridad!= null))) {
                return false;
            }
        }
        {
            String lhsIdvalidacion;
            lhsIdvalidacion = this.getIdvalidacion();
            String rhsIdvalidacion;
            rhsIdvalidacion = that.getIdvalidacion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idvalidacion", lhsIdvalidacion), LocatorUtils.property(thatLocator, "idvalidacion", rhsIdvalidacion), lhsIdvalidacion, rhsIdvalidacion, (this.idvalidacion!= null), (that.idvalidacion!= null))) {
                return false;
            }
        }
        {
            String lhsReintentomax;
            lhsReintentomax = this.getReintentomax();
            String rhsReintentomax;
            rhsReintentomax = that.getReintentomax();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "reintentomax", lhsReintentomax), LocatorUtils.property(thatLocator, "reintentomax", rhsReintentomax), lhsReintentomax, rhsReintentomax, (this.reintentomax!= null), (that.reintentomax!= null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE2;
        return equals(null, null, object, strategy);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE2;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            String theM4AutoGeneratedRecordID;
            theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            strategy.appendField(locator, this, "m4AutoGeneratedRecordID", buffer, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null));
        }
        {
            boolean theM4AutoGeneratedToDelete;
            theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            strategy.appendField(locator, this, "m4AutoGeneratedToDelete", buffer, theM4AutoGeneratedToDelete, true);
        }
        {
            String theDelay;
            theDelay = this.getDelay();
            strategy.appendField(locator, this, "delay", buffer, theDelay, (this.delay!= null));
        }
        {
            String theIdaccion;
            theIdaccion = this.getIdaccion();
            strategy.appendField(locator, this, "idaccion", buffer, theIdaccion, (this.idaccion!= null));
        }
        {
            String theIdestado;
            theIdestado = this.getIdestado();
            strategy.appendField(locator, this, "idestado", buffer, theIdestado, (this.idestado!= null));
        }
        {
            String theDelaytiempo;
            theDelaytiempo = this.getDelaytiempo();
            strategy.appendField(locator, this, "delaytiempo", buffer, theDelaytiempo, (this.delaytiempo!= null));
        }
        {
            String theIdprioridad;
            theIdprioridad = this.getIdprioridad();
            strategy.appendField(locator, this, "idprioridad", buffer, theIdprioridad, (this.idprioridad!= null));
        }
        {
            String theIdvalidacion;
            theIdvalidacion = this.getIdvalidacion();
            strategy.appendField(locator, this, "idvalidacion", buffer, theIdvalidacion, (this.idvalidacion!= null));
        }
        {
            String theReintentomax;
            theReintentomax = this.getReintentomax();
            strategy.appendField(locator, this, "reintentomax", buffer, theReintentomax, (this.reintentomax!= null));
        }
        return buffer;
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            String theM4AutoGeneratedRecordID;
            theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", theM4AutoGeneratedRecordID), currentHashCode, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null));
        }
        {
            boolean theM4AutoGeneratedToDelete;
            theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", theM4AutoGeneratedToDelete), currentHashCode, theM4AutoGeneratedToDelete, true);
        }
        {
            String theDelay;
            theDelay = this.getDelay();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "delay", theDelay), currentHashCode, theDelay, (this.delay!= null));
        }
        {
            String theIdaccion;
            theIdaccion = this.getIdaccion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idaccion", theIdaccion), currentHashCode, theIdaccion, (this.idaccion!= null));
        }
        {
            String theIdestado;
            theIdestado = this.getIdestado();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idestado", theIdestado), currentHashCode, theIdestado, (this.idestado!= null));
        }
        {
            String theDelaytiempo;
            theDelaytiempo = this.getDelaytiempo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "delaytiempo", theDelaytiempo), currentHashCode, theDelaytiempo, (this.delaytiempo!= null));
        }
        {
            String theIdprioridad;
            theIdprioridad = this.getIdprioridad();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idprioridad", theIdprioridad), currentHashCode, theIdprioridad, (this.idprioridad!= null));
        }
        {
            String theIdvalidacion;
            theIdvalidacion = this.getIdvalidacion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idvalidacion", theIdvalidacion), currentHashCode, theIdvalidacion, (this.idvalidacion!= null));
        }
        {
            String theReintentomax;
            theReintentomax = this.getReintentomax();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "reintentomax", theReintentomax), currentHashCode, theReintentomax, (this.reintentomax!= null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE2;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE2;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof IcmListaconfprevalidRecord) {
            final IcmListaconfprevalidRecord copy = ((IcmListaconfprevalidRecord) draftCopy);
            {
                Boolean m4AutoGeneratedRecordIDShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.m4AutoGeneratedRecordID!= null));
                if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceM4AutoGeneratedRecordID;
                    sourceM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
                    String copyM4AutoGeneratedRecordID = ((String) strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", sourceM4AutoGeneratedRecordID), sourceM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null)));
                    copy.setM4AutoGeneratedRecordID(copyM4AutoGeneratedRecordID);
                } else {
                    if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.m4AutoGeneratedRecordID = null;
                    }
                }
            }
            {
                Boolean m4AutoGeneratedToDeleteShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, true);
                if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.TRUE) {
                    boolean sourceM4AutoGeneratedToDelete;
                    sourceM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
                    boolean copyM4AutoGeneratedToDelete = strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", sourceM4AutoGeneratedToDelete), sourceM4AutoGeneratedToDelete, true);
                    copy.setM4AutoGeneratedToDelete(copyM4AutoGeneratedToDelete);
                } else {
                    if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.FALSE) {
                    }
                }
            }
            {
                Boolean delayShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.delay!= null));
                if (delayShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceDelay;
                    sourceDelay = this.getDelay();
                    String copyDelay = ((String) strategy.copy(LocatorUtils.property(locator, "delay", sourceDelay), sourceDelay, (this.delay!= null)));
                    copy.setDelay(copyDelay);
                } else {
                    if (delayShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.delay = null;
                    }
                }
            }
            {
                Boolean idaccionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idaccion!= null));
                if (idaccionShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdaccion;
                    sourceIdaccion = this.getIdaccion();
                    String copyIdaccion = ((String) strategy.copy(LocatorUtils.property(locator, "idaccion", sourceIdaccion), sourceIdaccion, (this.idaccion!= null)));
                    copy.setIdaccion(copyIdaccion);
                } else {
                    if (idaccionShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idaccion = null;
                    }
                }
            }
            {
                Boolean idestadoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idestado!= null));
                if (idestadoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdestado;
                    sourceIdestado = this.getIdestado();
                    String copyIdestado = ((String) strategy.copy(LocatorUtils.property(locator, "idestado", sourceIdestado), sourceIdestado, (this.idestado!= null)));
                    copy.setIdestado(copyIdestado);
                } else {
                    if (idestadoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idestado = null;
                    }
                }
            }
            {
                Boolean delaytiempoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.delaytiempo!= null));
                if (delaytiempoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceDelaytiempo;
                    sourceDelaytiempo = this.getDelaytiempo();
                    String copyDelaytiempo = ((String) strategy.copy(LocatorUtils.property(locator, "delaytiempo", sourceDelaytiempo), sourceDelaytiempo, (this.delaytiempo!= null)));
                    copy.setDelaytiempo(copyDelaytiempo);
                } else {
                    if (delaytiempoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.delaytiempo = null;
                    }
                }
            }
            {
                Boolean idprioridadShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idprioridad!= null));
                if (idprioridadShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdprioridad;
                    sourceIdprioridad = this.getIdprioridad();
                    String copyIdprioridad = ((String) strategy.copy(LocatorUtils.property(locator, "idprioridad", sourceIdprioridad), sourceIdprioridad, (this.idprioridad!= null)));
                    copy.setIdprioridad(copyIdprioridad);
                } else {
                    if (idprioridadShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idprioridad = null;
                    }
                }
            }
            {
                Boolean idvalidacionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idvalidacion!= null));
                if (idvalidacionShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdvalidacion;
                    sourceIdvalidacion = this.getIdvalidacion();
                    String copyIdvalidacion = ((String) strategy.copy(LocatorUtils.property(locator, "idvalidacion", sourceIdvalidacion), sourceIdvalidacion, (this.idvalidacion!= null)));
                    copy.setIdvalidacion(copyIdvalidacion);
                } else {
                    if (idvalidacionShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idvalidacion = null;
                    }
                }
            }
            {
                Boolean reintentomaxShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.reintentomax!= null));
                if (reintentomaxShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceReintentomax;
                    sourceReintentomax = this.getReintentomax();
                    String copyReintentomax = ((String) strategy.copy(LocatorUtils.property(locator, "reintentomax", sourceReintentomax), sourceReintentomax, (this.reintentomax!= null)));
                    copy.setReintentomax(copyReintentomax);
                } else {
                    if (reintentomaxShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.reintentomax = null;
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new IcmListaconfprevalidRecord();
    }

}
