
package com.inditex.rrhh.icmclcwb.model.meta4.icmwscalcincome.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Clase Java para Icm_ListaporcentajesdespRecord complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="Icm_ListaporcentajesdespRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="tramo" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="idseccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="porcentaje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_ListaporcentajesdespRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "tramo",
    "idseccion",
    "porcentaje"
})
public class IcmListaporcentajesdespRecord implements Cloneable, CopyTo2, Equals2, HashCode2, ToString2
{

    @XmlElement(required = true, nillable = true)
    protected String m4AutoGeneratedRecordID;
    protected boolean m4AutoGeneratedToDelete;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double tramo;
    @XmlElement(required = true, nillable = true)
    protected String idseccion;
    @XmlElement(required = true, nillable = true)
    protected String porcentaje;

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM4AutoGeneratedRecordID(String value) {
        this.m4AutoGeneratedRecordID = value;
    }

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public void setM4AutoGeneratedToDelete(boolean value) {
        this.m4AutoGeneratedToDelete = value;
    }

    /**
     * Obtiene el valor de la propiedad tramo.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTramo() {
        return tramo;
    }

    /**
     * Define el valor de la propiedad tramo.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTramo(Double value) {
        this.tramo = value;
    }

    /**
     * Obtiene el valor de la propiedad idseccion.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdseccion() {
        return idseccion;
    }

    /**
     * Define el valor de la propiedad idseccion.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdseccion(String value) {
        this.idseccion = value;
    }

    /**
     * Obtiene el valor de la propiedad porcentaje.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPorcentaje() {
        return porcentaje;
    }

    /**
     * Define el valor de la propiedad porcentaje.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPorcentaje(String value) {
        this.porcentaje = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final IcmListaporcentajesdespRecord that = ((IcmListaporcentajesdespRecord) object);
        {
            String lhsM4AutoGeneratedRecordID;
            lhsM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            String rhsM4AutoGeneratedRecordID;
            rhsM4AutoGeneratedRecordID = that.getM4AutoGeneratedRecordID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedRecordID", lhsM4AutoGeneratedRecordID), LocatorUtils.property(thatLocator, "m4AutoGeneratedRecordID", rhsM4AutoGeneratedRecordID), lhsM4AutoGeneratedRecordID, rhsM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null), (that.m4AutoGeneratedRecordID!= null))) {
                return false;
            }
        }
        {
            boolean lhsM4AutoGeneratedToDelete;
            lhsM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            boolean rhsM4AutoGeneratedToDelete;
            rhsM4AutoGeneratedToDelete = that.isM4AutoGeneratedToDelete();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedToDelete", lhsM4AutoGeneratedToDelete), LocatorUtils.property(thatLocator, "m4AutoGeneratedToDelete", rhsM4AutoGeneratedToDelete), lhsM4AutoGeneratedToDelete, rhsM4AutoGeneratedToDelete, true, true)) {
                return false;
            }
        }
        {
            Double lhsTramo;
            lhsTramo = this.getTramo();
            Double rhsTramo;
            rhsTramo = that.getTramo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "tramo", lhsTramo), LocatorUtils.property(thatLocator, "tramo", rhsTramo), lhsTramo, rhsTramo, (this.tramo!= null), (that.tramo!= null))) {
                return false;
            }
        }
        {
            String lhsIdseccion;
            lhsIdseccion = this.getIdseccion();
            String rhsIdseccion;
            rhsIdseccion = that.getIdseccion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idseccion", lhsIdseccion), LocatorUtils.property(thatLocator, "idseccion", rhsIdseccion), lhsIdseccion, rhsIdseccion, (this.idseccion!= null), (that.idseccion!= null))) {
                return false;
            }
        }
        {
            String lhsPorcentaje;
            lhsPorcentaje = this.getPorcentaje();
            String rhsPorcentaje;
            rhsPorcentaje = that.getPorcentaje();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "porcentaje", lhsPorcentaje), LocatorUtils.property(thatLocator, "porcentaje", rhsPorcentaje), lhsPorcentaje, rhsPorcentaje, (this.porcentaje!= null), (that.porcentaje!= null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE2;
        return equals(null, null, object, strategy);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE2;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            String theM4AutoGeneratedRecordID;
            theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            strategy.appendField(locator, this, "m4AutoGeneratedRecordID", buffer, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null));
        }
        {
            boolean theM4AutoGeneratedToDelete;
            theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            strategy.appendField(locator, this, "m4AutoGeneratedToDelete", buffer, theM4AutoGeneratedToDelete, true);
        }
        {
            Double theTramo;
            theTramo = this.getTramo();
            strategy.appendField(locator, this, "tramo", buffer, theTramo, (this.tramo!= null));
        }
        {
            String theIdseccion;
            theIdseccion = this.getIdseccion();
            strategy.appendField(locator, this, "idseccion", buffer, theIdseccion, (this.idseccion!= null));
        }
        {
            String thePorcentaje;
            thePorcentaje = this.getPorcentaje();
            strategy.appendField(locator, this, "porcentaje", buffer, thePorcentaje, (this.porcentaje!= null));
        }
        return buffer;
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            String theM4AutoGeneratedRecordID;
            theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", theM4AutoGeneratedRecordID), currentHashCode, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null));
        }
        {
            boolean theM4AutoGeneratedToDelete;
            theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", theM4AutoGeneratedToDelete), currentHashCode, theM4AutoGeneratedToDelete, true);
        }
        {
            Double theTramo;
            theTramo = this.getTramo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "tramo", theTramo), currentHashCode, theTramo, (this.tramo!= null));
        }
        {
            String theIdseccion;
            theIdseccion = this.getIdseccion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idseccion", theIdseccion), currentHashCode, theIdseccion, (this.idseccion!= null));
        }
        {
            String thePorcentaje;
            thePorcentaje = this.getPorcentaje();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "porcentaje", thePorcentaje), currentHashCode, thePorcentaje, (this.porcentaje!= null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE2;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE2;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof IcmListaporcentajesdespRecord) {
            final IcmListaporcentajesdespRecord copy = ((IcmListaporcentajesdespRecord) draftCopy);
            {
                Boolean m4AutoGeneratedRecordIDShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.m4AutoGeneratedRecordID!= null));
                if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceM4AutoGeneratedRecordID;
                    sourceM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
                    String copyM4AutoGeneratedRecordID = ((String) strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", sourceM4AutoGeneratedRecordID), sourceM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null)));
                    copy.setM4AutoGeneratedRecordID(copyM4AutoGeneratedRecordID);
                } else {
                    if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.m4AutoGeneratedRecordID = null;
                    }
                }
            }
            {
                Boolean m4AutoGeneratedToDeleteShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, true);
                if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.TRUE) {
                    boolean sourceM4AutoGeneratedToDelete;
                    sourceM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
                    boolean copyM4AutoGeneratedToDelete = strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", sourceM4AutoGeneratedToDelete), sourceM4AutoGeneratedToDelete, true);
                    copy.setM4AutoGeneratedToDelete(copyM4AutoGeneratedToDelete);
                } else {
                    if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.FALSE) {
                    }
                }
            }
            {
                Boolean tramoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.tramo!= null));
                if (tramoShouldBeCopiedAndSet == Boolean.TRUE) {
                    Double sourceTramo;
                    sourceTramo = this.getTramo();
                    Double copyTramo = ((Double) strategy.copy(LocatorUtils.property(locator, "tramo", sourceTramo), sourceTramo, (this.tramo!= null)));
                    copy.setTramo(copyTramo);
                } else {
                    if (tramoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.tramo = null;
                    }
                }
            }
            {
                Boolean idseccionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idseccion!= null));
                if (idseccionShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdseccion;
                    sourceIdseccion = this.getIdseccion();
                    String copyIdseccion = ((String) strategy.copy(LocatorUtils.property(locator, "idseccion", sourceIdseccion), sourceIdseccion, (this.idseccion!= null)));
                    copy.setIdseccion(copyIdseccion);
                } else {
                    if (idseccionShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idseccion = null;
                    }
                }
            }
            {
                Boolean porcentajeShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.porcentaje!= null));
                if (porcentajeShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourcePorcentaje;
                    sourcePorcentaje = this.getPorcentaje();
                    String copyPorcentaje = ((String) strategy.copy(LocatorUtils.property(locator, "porcentaje", sourcePorcentaje), sourcePorcentaje, (this.porcentaje!= null)));
                    copy.setPorcentaje(copyPorcentaje);
                } else {
                    if (porcentajeShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.porcentaje = null;
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new IcmListaporcentajesdespRecord();
    }

}
