
package com.inditex.rrhh.icmclcwb.model.meta4.icmwscalcincome.entity;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

/**
 * <p>Java class for Icm_ListaempleadoRecord complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Icm_ListaempleadoRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="fechafin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idcadena" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idorigen" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idempresa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idseccion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idempleado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="orempleado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechafinloc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechafinsec" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechainicio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechainicioloc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechainiciosec" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idlugartrabajo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechaantiguedad" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idempleadolocal" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idlugartrabajomtu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_ListaempleadoRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "fechafin",
    "idcadena",
    "idorigen",
    "idempresa",
    "idseccion",
    "idempleado",
    "orempleado",
    "fechafinloc",
    "fechafinsec",
    "fechainicio",
    "fechainicioloc",
    "fechainiciosec",
    "idlugartrabajo",
    "fechaantiguedad",
    "idempleadolocal",
    "idlugartrabajomtu"
})
public class IcmListaempleadoRecord implements Serializable, Cloneable, CopyTo2, Equals2, HashCode2, ToString2 {

  private final static long serialVersionUID = 1L;

  @XmlElement(required = true, nillable = true)
  protected String m4AutoGeneratedRecordID;

  protected boolean m4AutoGeneratedToDelete;

  @XmlElement(required = true, nillable = true)
  protected String fechafin;

  @XmlElement(required = true, nillable = true)
  protected String idcadena;

  @XmlElement(required = true, nillable = true)
  protected String idorigen;

  @XmlElement(required = true, nillable = true)
  protected String idempresa;

  @XmlElement(required = true, nillable = true)
  protected String idseccion;

  @XmlElement(required = true, nillable = true)
  protected String idempleado;

  @XmlElement(required = true, nillable = true)
  protected String orempleado;

  @XmlElement(required = true, nillable = true)
  protected String fechafinloc;

  @XmlElement(required = true, nillable = true)
  protected String fechafinsec;

  @XmlElement(required = true, nillable = true)
  protected String fechainicio;

  @XmlElement(required = true, nillable = true)
  protected String fechainicioloc;

  @XmlElement(required = true, nillable = true)
  protected String fechainiciosec;

  @XmlElement(required = true, nillable = true)
  protected String idlugartrabajo;

  @XmlElement(required = true, nillable = true)
  protected String fechaantiguedad;

  @XmlElement(required = true, nillable = true)
  protected String idempleadolocal;

  @XmlElement(required = true, nillable = true)
  protected String idlugartrabajomtu;

  /**
   * Gets the value of the m4AutoGeneratedRecordID property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getM4AutoGeneratedRecordID() {
    return m4AutoGeneratedRecordID;
  }

  /**
   * Sets the value of the m4AutoGeneratedRecordID property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setM4AutoGeneratedRecordID(String value) {
    this.m4AutoGeneratedRecordID = value;
  }

  /**
   * Gets the value of the m4AutoGeneratedToDelete property.
   *
   */
  public boolean isM4AutoGeneratedToDelete() {
    return m4AutoGeneratedToDelete;
  }

  /**
   * Sets the value of the m4AutoGeneratedToDelete property.
   *
   */
  public void setM4AutoGeneratedToDelete(boolean value) {
    this.m4AutoGeneratedToDelete = value;
  }

  /**
   * Gets the value of the fechafin property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getFechafin() {
    return fechafin;
  }

  /**
   * Sets the value of the fechafin property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setFechafin(String value) {
    this.fechafin = value;
  }

  /**
   * Gets the value of the idcadena property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getIdcadena() {
    return idcadena;
  }

  /**
   * Sets the value of the idcadena property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setIdcadena(String value) {
    this.idcadena = value;
  }

  /**
   * Gets the value of the idorigen property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getIdorigen() {
    return idorigen;
  }

  /**
   * Sets the value of the idorigen property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setIdorigen(String value) {
    this.idorigen = value;
  }

  /**
   * Gets the value of the idempresa property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getIdempresa() {
    return idempresa;
  }

  /**
   * Sets the value of the idempresa property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setIdempresa(String value) {
    this.idempresa = value;
  }

  /**
   * Gets the value of the idseccion property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getIdseccion() {
    return idseccion;
  }

  /**
   * Sets the value of the idseccion property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setIdseccion(String value) {
    this.idseccion = value;
  }

  /**
   * Gets the value of the idempleado property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getIdempleado() {
    return idempleado;
  }

  /**
   * Sets the value of the idempleado property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setIdempleado(String value) {
    this.idempleado = value;
  }

  /**
   * Gets the value of the orempleado property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getOrempleado() {
    return orempleado;
  }

  /**
   * Sets the value of the orempleado property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setOrempleado(String value) {
    this.orempleado = value;
  }

  /**
   * Gets the value of the fechafinloc property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getFechafinloc() {
    return fechafinloc;
  }

  /**
   * Sets the value of the fechafinloc property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setFechafinloc(String value) {
    this.fechafinloc = value;
  }

  /**
   * Gets the value of the fechafinsec property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getFechafinsec() {
    return fechafinsec;
  }

  /**
   * Sets the value of the fechafinsec property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setFechafinsec(String value) {
    this.fechafinsec = value;
  }

  /**
   * Gets the value of the fechainicio property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getFechainicio() {
    return fechainicio;
  }

  /**
   * Sets the value of the fechainicio property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setFechainicio(String value) {
    this.fechainicio = value;
  }

  /**
   * Gets the value of the fechainicioloc property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getFechainicioloc() {
    return fechainicioloc;
  }

  /**
   * Sets the value of the fechainicioloc property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setFechainicioloc(String value) {
    this.fechainicioloc = value;
  }

  /**
   * Gets the value of the fechainiciosec property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getFechainiciosec() {
    return fechainiciosec;
  }

  /**
   * Sets the value of the fechainiciosec property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setFechainiciosec(String value) {
    this.fechainiciosec = value;
  }

  /**
   * Gets the value of the idlugartrabajo property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getIdlugartrabajo() {
    return idlugartrabajo;
  }

  /**
   * Sets the value of the idlugartrabajo property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setIdlugartrabajo(String value) {
    this.idlugartrabajo = value;
  }

  /**
   * Gets the value of the fechaantiguedad property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getFechaantiguedad() {
    return fechaantiguedad;
  }

  /**
   * Sets the value of the fechaantiguedad property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setFechaantiguedad(String value) {
    this.fechaantiguedad = value;
  }

  /**
   * Gets the value of the idempleadolocal property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getIdempleadolocal() {
    return idempleadolocal;
  }

  /**
   * Sets the value of the idempleadolocal property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setIdempleadolocal(String value) {
    this.idempleadolocal = value;
  }

  /**
   * Gets the value of the idlugartrabajomtu property.
   *
   * @return possible object is {@link String }
   *
   */
  public String getIdlugartrabajomtu() {
    return idlugartrabajomtu;
  }

  /**
   * Sets the value of the idlugartrabajomtu property.
   *
   * @param value allowed object is {@link String }
   *
   */
  public void setIdlugartrabajomtu(String value) {
    this.idlugartrabajomtu = value;
  }

  public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
    if ((object == null) || (this.getClass() != object.getClass())) {
      return false;
    }
    if (this == object) {
      return true;
    }
    final IcmListaempleadoRecord that = ((IcmListaempleadoRecord) object);
    {
      String lhsM4AutoGeneratedRecordID;
      lhsM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
      String rhsM4AutoGeneratedRecordID;
      rhsM4AutoGeneratedRecordID = that.getM4AutoGeneratedRecordID();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedRecordID", lhsM4AutoGeneratedRecordID),
          LocatorUtils.property(thatLocator, "m4AutoGeneratedRecordID", rhsM4AutoGeneratedRecordID), lhsM4AutoGeneratedRecordID,
          rhsM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID != null), (that.m4AutoGeneratedRecordID != null))) {
        return false;
      }
    }
    {
      boolean lhsM4AutoGeneratedToDelete;
      lhsM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
      boolean rhsM4AutoGeneratedToDelete;
      rhsM4AutoGeneratedToDelete = that.isM4AutoGeneratedToDelete();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedToDelete", lhsM4AutoGeneratedToDelete),
          LocatorUtils.property(thatLocator, "m4AutoGeneratedToDelete", rhsM4AutoGeneratedToDelete), lhsM4AutoGeneratedToDelete,
          rhsM4AutoGeneratedToDelete, true, true)) {
        return false;
      }
    }
    {
      String lhsFechafin;
      lhsFechafin = this.getFechafin();
      String rhsFechafin;
      rhsFechafin = that.getFechafin();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "fechafin", lhsFechafin),
          LocatorUtils.property(thatLocator, "fechafin", rhsFechafin), lhsFechafin, rhsFechafin, (this.fechafin != null),
          (that.fechafin != null))) {
        return false;
      }
    }
    {
      String lhsIdcadena;
      lhsIdcadena = this.getIdcadena();
      String rhsIdcadena;
      rhsIdcadena = that.getIdcadena();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "idcadena", lhsIdcadena),
          LocatorUtils.property(thatLocator, "idcadena", rhsIdcadena), lhsIdcadena, rhsIdcadena, (this.idcadena != null),
          (that.idcadena != null))) {
        return false;
      }
    }
    {
      String lhsIdorigen;
      lhsIdorigen = this.getIdorigen();
      String rhsIdorigen;
      rhsIdorigen = that.getIdorigen();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "idorigen", lhsIdorigen),
          LocatorUtils.property(thatLocator, "idorigen", rhsIdorigen), lhsIdorigen, rhsIdorigen, (this.idorigen != null),
          (that.idorigen != null))) {
        return false;
      }
    }
    {
      String lhsIdempresa;
      lhsIdempresa = this.getIdempresa();
      String rhsIdempresa;
      rhsIdempresa = that.getIdempresa();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "idempresa", lhsIdempresa),
          LocatorUtils.property(thatLocator, "idempresa", rhsIdempresa), lhsIdempresa, rhsIdempresa, (this.idempresa != null),
          (that.idempresa != null))) {
        return false;
      }
    }
    {
      String lhsIdseccion;
      lhsIdseccion = this.getIdseccion();
      String rhsIdseccion;
      rhsIdseccion = that.getIdseccion();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "idseccion", lhsIdseccion),
          LocatorUtils.property(thatLocator, "idseccion", rhsIdseccion), lhsIdseccion, rhsIdseccion, (this.idseccion != null),
          (that.idseccion != null))) {
        return false;
      }
    }
    {
      String lhsIdempleado;
      lhsIdempleado = this.getIdempleado();
      String rhsIdempleado;
      rhsIdempleado = that.getIdempleado();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "idempleado", lhsIdempleado),
          LocatorUtils.property(thatLocator, "idempleado", rhsIdempleado), lhsIdempleado, rhsIdempleado, (this.idempleado != null),
          (that.idempleado != null))) {
        return false;
      }
    }
    {
      String lhsOrempleado;
      lhsOrempleado = this.getOrempleado();
      String rhsOrempleado;
      rhsOrempleado = that.getOrempleado();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "orempleado", lhsOrempleado),
          LocatorUtils.property(thatLocator, "orempleado", rhsOrempleado), lhsOrempleado, rhsOrempleado, (this.orempleado != null),
          (that.orempleado != null))) {
        return false;
      }
    }
    {
      String lhsFechafinloc;
      lhsFechafinloc = this.getFechafinloc();
      String rhsFechafinloc;
      rhsFechafinloc = that.getFechafinloc();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "fechafinloc", lhsFechafinloc),
          LocatorUtils.property(thatLocator, "fechafinloc", rhsFechafinloc), lhsFechafinloc, rhsFechafinloc, (this.fechafinloc != null),
          (that.fechafinloc != null))) {
        return false;
      }
    }
    {
      String lhsFechafinsec;
      lhsFechafinsec = this.getFechafinsec();
      String rhsFechafinsec;
      rhsFechafinsec = that.getFechafinsec();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "fechafinsec", lhsFechafinsec),
          LocatorUtils.property(thatLocator, "fechafinsec", rhsFechafinsec), lhsFechafinsec, rhsFechafinsec, (this.fechafinsec != null),
          (that.fechafinsec != null))) {
        return false;
      }
    }
    {
      String lhsFechainicio;
      lhsFechainicio = this.getFechainicio();
      String rhsFechainicio;
      rhsFechainicio = that.getFechainicio();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "fechainicio", lhsFechainicio),
          LocatorUtils.property(thatLocator, "fechainicio", rhsFechainicio), lhsFechainicio, rhsFechainicio, (this.fechainicio != null),
          (that.fechainicio != null))) {
        return false;
      }
    }
    {
      String lhsFechainicioloc;
      lhsFechainicioloc = this.getFechainicioloc();
      String rhsFechainicioloc;
      rhsFechainicioloc = that.getFechainicioloc();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "fechainicioloc", lhsFechainicioloc),
          LocatorUtils.property(thatLocator, "fechainicioloc", rhsFechainicioloc), lhsFechainicioloc, rhsFechainicioloc,
          (this.fechainicioloc != null), (that.fechainicioloc != null))) {
        return false;
      }
    }
    {
      String lhsFechainiciosec;
      lhsFechainiciosec = this.getFechainiciosec();
      String rhsFechainiciosec;
      rhsFechainiciosec = that.getFechainiciosec();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "fechainiciosec", lhsFechainiciosec),
          LocatorUtils.property(thatLocator, "fechainiciosec", rhsFechainiciosec), lhsFechainiciosec, rhsFechainiciosec,
          (this.fechainiciosec != null), (that.fechainiciosec != null))) {
        return false;
      }
    }
    {
      String lhsIdlugartrabajo;
      lhsIdlugartrabajo = this.getIdlugartrabajo();
      String rhsIdlugartrabajo;
      rhsIdlugartrabajo = that.getIdlugartrabajo();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "idlugartrabajo", lhsIdlugartrabajo),
          LocatorUtils.property(thatLocator, "idlugartrabajo", rhsIdlugartrabajo), lhsIdlugartrabajo, rhsIdlugartrabajo,
          (this.idlugartrabajo != null), (that.idlugartrabajo != null))) {
        return false;
      }
    }
    {
      String lhsFechaantiguedad;
      lhsFechaantiguedad = this.getFechaantiguedad();
      String rhsFechaantiguedad;
      rhsFechaantiguedad = that.getFechaantiguedad();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "fechaantiguedad", lhsFechaantiguedad),
          LocatorUtils.property(thatLocator, "fechaantiguedad", rhsFechaantiguedad), lhsFechaantiguedad, rhsFechaantiguedad,
          (this.fechaantiguedad != null), (that.fechaantiguedad != null))) {
        return false;
      }
    }
    {
      String lhsIdempleadolocal;
      lhsIdempleadolocal = this.getIdempleadolocal();
      String rhsIdempleadolocal;
      rhsIdempleadolocal = that.getIdempleadolocal();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "idempleadolocal", lhsIdempleadolocal),
          LocatorUtils.property(thatLocator, "idempleadolocal", rhsIdempleadolocal), lhsIdempleadolocal, rhsIdempleadolocal,
          (this.idempleadolocal != null), (that.idempleadolocal != null))) {
        return false;
      }
    }
    {
      String lhsIdlugartrabajomtu;
      lhsIdlugartrabajomtu = this.getIdlugartrabajomtu();
      String rhsIdlugartrabajomtu;
      rhsIdlugartrabajomtu = that.getIdlugartrabajomtu();
      if (!strategy.equals(LocatorUtils.property(thisLocator, "idlugartrabajomtu", lhsIdlugartrabajomtu),
          LocatorUtils.property(thatLocator, "idlugartrabajomtu", rhsIdlugartrabajomtu), lhsIdlugartrabajomtu, rhsIdlugartrabajomtu,
          (this.idlugartrabajomtu != null), (that.idlugartrabajomtu != null))) {
        return false;
      }
    }
    return true;
  }

  public boolean equals(Object object) {
    final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE2;
    return equals(null, null, object, strategy);
  }

  public String toString() {
    final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE2;
    final StringBuilder buffer = new StringBuilder();
    append(null, buffer, strategy);
    return buffer.toString();
  }

  public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
    strategy.appendStart(locator, this, buffer);
    appendFields(locator, buffer, strategy);
    strategy.appendEnd(locator, this, buffer);
    return buffer;
  }

  public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
    {
      String theM4AutoGeneratedRecordID;
      theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
      strategy.appendField(locator, this, "m4AutoGeneratedRecordID", buffer, theM4AutoGeneratedRecordID,
          (this.m4AutoGeneratedRecordID != null));
    }
    {
      boolean theM4AutoGeneratedToDelete;
      theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
      strategy.appendField(locator, this, "m4AutoGeneratedToDelete", buffer, theM4AutoGeneratedToDelete, true);
    }
    {
      String theFechafin;
      theFechafin = this.getFechafin();
      strategy.appendField(locator, this, "fechafin", buffer, theFechafin, (this.fechafin != null));
    }
    {
      String theIdcadena;
      theIdcadena = this.getIdcadena();
      strategy.appendField(locator, this, "idcadena", buffer, theIdcadena, (this.idcadena != null));
    }
    {
      String theIdorigen;
      theIdorigen = this.getIdorigen();
      strategy.appendField(locator, this, "idorigen", buffer, theIdorigen, (this.idorigen != null));
    }
    {
      String theIdempresa;
      theIdempresa = this.getIdempresa();
      strategy.appendField(locator, this, "idempresa", buffer, theIdempresa, (this.idempresa != null));
    }
    {
      String theIdseccion;
      theIdseccion = this.getIdseccion();
      strategy.appendField(locator, this, "idseccion", buffer, theIdseccion, (this.idseccion != null));
    }
    {
      String theIdempleado;
      theIdempleado = this.getIdempleado();
      strategy.appendField(locator, this, "idempleado", buffer, theIdempleado, (this.idempleado != null));
    }
    {
      String theOrempleado;
      theOrempleado = this.getOrempleado();
      strategy.appendField(locator, this, "orempleado", buffer, theOrempleado, (this.orempleado != null));
    }
    {
      String theFechafinloc;
      theFechafinloc = this.getFechafinloc();
      strategy.appendField(locator, this, "fechafinloc", buffer, theFechafinloc, (this.fechafinloc != null));
    }
    {
      String theFechafinsec;
      theFechafinsec = this.getFechafinsec();
      strategy.appendField(locator, this, "fechafinsec", buffer, theFechafinsec, (this.fechafinsec != null));
    }
    {
      String theFechainicio;
      theFechainicio = this.getFechainicio();
      strategy.appendField(locator, this, "fechainicio", buffer, theFechainicio, (this.fechainicio != null));
    }
    {
      String theFechainicioloc;
      theFechainicioloc = this.getFechainicioloc();
      strategy.appendField(locator, this, "fechainicioloc", buffer, theFechainicioloc, (this.fechainicioloc != null));
    }
    {
      String theFechainiciosec;
      theFechainiciosec = this.getFechainiciosec();
      strategy.appendField(locator, this, "fechainiciosec", buffer, theFechainiciosec, (this.fechainiciosec != null));
    }
    {
      String theIdlugartrabajo;
      theIdlugartrabajo = this.getIdlugartrabajo();
      strategy.appendField(locator, this, "idlugartrabajo", buffer, theIdlugartrabajo, (this.idlugartrabajo != null));
    }
    {
      String theFechaantiguedad;
      theFechaantiguedad = this.getFechaantiguedad();
      strategy.appendField(locator, this, "fechaantiguedad", buffer, theFechaantiguedad, (this.fechaantiguedad != null));
    }
    {
      String theIdempleadolocal;
      theIdempleadolocal = this.getIdempleadolocal();
      strategy.appendField(locator, this, "idempleadolocal", buffer, theIdempleadolocal, (this.idempleadolocal != null));
    }
    {
      String theIdlugartrabajomtu;
      theIdlugartrabajomtu = this.getIdlugartrabajomtu();
      strategy.appendField(locator, this, "idlugartrabajomtu", buffer, theIdlugartrabajomtu, (this.idlugartrabajomtu != null));
    }
    return buffer;
  }

  public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
    int currentHashCode = 1;
    {
      String theM4AutoGeneratedRecordID;
      theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", theM4AutoGeneratedRecordID),
          currentHashCode, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID != null));
    }
    {
      boolean theM4AutoGeneratedToDelete;
      theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", theM4AutoGeneratedToDelete),
          currentHashCode, theM4AutoGeneratedToDelete, true);
    }
    {
      String theFechafin;
      theFechafin = this.getFechafin();
      currentHashCode =
          strategy.hashCode(LocatorUtils.property(locator, "fechafin", theFechafin), currentHashCode, theFechafin, (this.fechafin != null));
    }
    {
      String theIdcadena;
      theIdcadena = this.getIdcadena();
      currentHashCode =
          strategy.hashCode(LocatorUtils.property(locator, "idcadena", theIdcadena), currentHashCode, theIdcadena, (this.idcadena != null));
    }
    {
      String theIdorigen;
      theIdorigen = this.getIdorigen();
      currentHashCode =
          strategy.hashCode(LocatorUtils.property(locator, "idorigen", theIdorigen), currentHashCode, theIdorigen, (this.idorigen != null));
    }
    {
      String theIdempresa;
      theIdempresa = this.getIdempresa();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idempresa", theIdempresa), currentHashCode, theIdempresa,
          (this.idempresa != null));
    }
    {
      String theIdseccion;
      theIdseccion = this.getIdseccion();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idseccion", theIdseccion), currentHashCode, theIdseccion,
          (this.idseccion != null));
    }
    {
      String theIdempleado;
      theIdempleado = this.getIdempleado();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idempleado", theIdempleado), currentHashCode, theIdempleado,
          (this.idempleado != null));
    }
    {
      String theOrempleado;
      theOrempleado = this.getOrempleado();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orempleado", theOrempleado), currentHashCode, theOrempleado,
          (this.orempleado != null));
    }
    {
      String theFechafinloc;
      theFechafinloc = this.getFechafinloc();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fechafinloc", theFechafinloc), currentHashCode, theFechafinloc,
          (this.fechafinloc != null));
    }
    {
      String theFechafinsec;
      theFechafinsec = this.getFechafinsec();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fechafinsec", theFechafinsec), currentHashCode, theFechafinsec,
          (this.fechafinsec != null));
    }
    {
      String theFechainicio;
      theFechainicio = this.getFechainicio();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fechainicio", theFechainicio), currentHashCode, theFechainicio,
          (this.fechainicio != null));
    }
    {
      String theFechainicioloc;
      theFechainicioloc = this.getFechainicioloc();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fechainicioloc", theFechainicioloc), currentHashCode,
          theFechainicioloc, (this.fechainicioloc != null));
    }
    {
      String theFechainiciosec;
      theFechainiciosec = this.getFechainiciosec();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fechainiciosec", theFechainiciosec), currentHashCode,
          theFechainiciosec, (this.fechainiciosec != null));
    }
    {
      String theIdlugartrabajo;
      theIdlugartrabajo = this.getIdlugartrabajo();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idlugartrabajo", theIdlugartrabajo), currentHashCode,
          theIdlugartrabajo, (this.idlugartrabajo != null));
    }
    {
      String theFechaantiguedad;
      theFechaantiguedad = this.getFechaantiguedad();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fechaantiguedad", theFechaantiguedad), currentHashCode,
          theFechaantiguedad, (this.fechaantiguedad != null));
    }
    {
      String theIdempleadolocal;
      theIdempleadolocal = this.getIdempleadolocal();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idempleadolocal", theIdempleadolocal), currentHashCode,
          theIdempleadolocal, (this.idempleadolocal != null));
    }
    {
      String theIdlugartrabajomtu;
      theIdlugartrabajomtu = this.getIdlugartrabajomtu();
      currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idlugartrabajomtu", theIdlugartrabajomtu), currentHashCode,
          theIdlugartrabajomtu, (this.idlugartrabajomtu != null));
    }
    return currentHashCode;
  }

  public int hashCode() {
    final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE2;
    return this.hashCode(null, strategy);
  }

  public Object clone() {
    return copyTo(createNewInstance());
  }

  public Object copyTo(Object target) {
    final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE2;
    return copyTo(null, target, strategy);
  }

  public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
    final Object draftCopy = ((target == null) ? createNewInstance() : target);
    if (draftCopy instanceof IcmListaempleadoRecord) {
      final IcmListaempleadoRecord copy = ((IcmListaempleadoRecord) draftCopy);
      {
        Boolean m4AutoGeneratedRecordIDShouldBeCopiedAndSet =
            strategy.shouldBeCopiedAndSet(locator, (this.m4AutoGeneratedRecordID != null));
        if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceM4AutoGeneratedRecordID;
          sourceM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
          String copyM4AutoGeneratedRecordID =
              ((String) strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", sourceM4AutoGeneratedRecordID),
                  sourceM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID != null)));
          copy.setM4AutoGeneratedRecordID(copyM4AutoGeneratedRecordID);
        } else {
          if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.m4AutoGeneratedRecordID = null;
          }
        }
      }
      {
        Boolean m4AutoGeneratedToDeleteShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, true);
        if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.TRUE) {
          boolean sourceM4AutoGeneratedToDelete;
          sourceM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
          boolean copyM4AutoGeneratedToDelete =
              strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", sourceM4AutoGeneratedToDelete),
                  sourceM4AutoGeneratedToDelete, true);
          copy.setM4AutoGeneratedToDelete(copyM4AutoGeneratedToDelete);
        } else {
          if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.FALSE) {
          }
        }
      }
      {
        Boolean fechafinShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.fechafin != null));
        if (fechafinShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceFechafin;
          sourceFechafin = this.getFechafin();
          String copyFechafin =
              ((String) strategy.copy(LocatorUtils.property(locator, "fechafin", sourceFechafin), sourceFechafin, (this.fechafin != null)));
          copy.setFechafin(copyFechafin);
        } else {
          if (fechafinShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.fechafin = null;
          }
        }
      }
      {
        Boolean idcadenaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idcadena != null));
        if (idcadenaShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceIdcadena;
          sourceIdcadena = this.getIdcadena();
          String copyIdcadena =
              ((String) strategy.copy(LocatorUtils.property(locator, "idcadena", sourceIdcadena), sourceIdcadena, (this.idcadena != null)));
          copy.setIdcadena(copyIdcadena);
        } else {
          if (idcadenaShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.idcadena = null;
          }
        }
      }
      {
        Boolean idorigenShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idorigen != null));
        if (idorigenShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceIdorigen;
          sourceIdorigen = this.getIdorigen();
          String copyIdorigen =
              ((String) strategy.copy(LocatorUtils.property(locator, "idorigen", sourceIdorigen), sourceIdorigen, (this.idorigen != null)));
          copy.setIdorigen(copyIdorigen);
        } else {
          if (idorigenShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.idorigen = null;
          }
        }
      }
      {
        Boolean idempresaShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idempresa != null));
        if (idempresaShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceIdempresa;
          sourceIdempresa = this.getIdempresa();
          String copyIdempresa = ((String) strategy.copy(LocatorUtils.property(locator, "idempresa", sourceIdempresa), sourceIdempresa,
              (this.idempresa != null)));
          copy.setIdempresa(copyIdempresa);
        } else {
          if (idempresaShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.idempresa = null;
          }
        }
      }
      {
        Boolean idseccionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idseccion != null));
        if (idseccionShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceIdseccion;
          sourceIdseccion = this.getIdseccion();
          String copyIdseccion = ((String) strategy.copy(LocatorUtils.property(locator, "idseccion", sourceIdseccion), sourceIdseccion,
              (this.idseccion != null)));
          copy.setIdseccion(copyIdseccion);
        } else {
          if (idseccionShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.idseccion = null;
          }
        }
      }
      {
        Boolean idempleadoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idempleado != null));
        if (idempleadoShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceIdempleado;
          sourceIdempleado = this.getIdempleado();
          String copyIdempleado = ((String) strategy.copy(LocatorUtils.property(locator, "idempleado", sourceIdempleado), sourceIdempleado,
              (this.idempleado != null)));
          copy.setIdempleado(copyIdempleado);
        } else {
          if (idempleadoShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.idempleado = null;
          }
        }
      }
      {
        Boolean orempleadoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.orempleado != null));
        if (orempleadoShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceOrempleado;
          sourceOrempleado = this.getOrempleado();
          String copyOrempleado = ((String) strategy.copy(LocatorUtils.property(locator, "orempleado", sourceOrempleado), sourceOrempleado,
              (this.orempleado != null)));
          copy.setOrempleado(copyOrempleado);
        } else {
          if (orempleadoShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.orempleado = null;
          }
        }
      }
      {
        Boolean fechafinlocShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.fechafinloc != null));
        if (fechafinlocShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceFechafinloc;
          sourceFechafinloc = this.getFechafinloc();
          String copyFechafinloc = ((String) strategy.copy(LocatorUtils.property(locator, "fechafinloc", sourceFechafinloc),
              sourceFechafinloc, (this.fechafinloc != null)));
          copy.setFechafinloc(copyFechafinloc);
        } else {
          if (fechafinlocShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.fechafinloc = null;
          }
        }
      }
      {
        Boolean fechafinsecShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.fechafinsec != null));
        if (fechafinsecShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceFechafinsec;
          sourceFechafinsec = this.getFechafinsec();
          String copyFechafinsec = ((String) strategy.copy(LocatorUtils.property(locator, "fechafinsec", sourceFechafinsec),
              sourceFechafinsec, (this.fechafinsec != null)));
          copy.setFechafinsec(copyFechafinsec);
        } else {
          if (fechafinsecShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.fechafinsec = null;
          }
        }
      }
      {
        Boolean fechainicioShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.fechainicio != null));
        if (fechainicioShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceFechainicio;
          sourceFechainicio = this.getFechainicio();
          String copyFechainicio = ((String) strategy.copy(LocatorUtils.property(locator, "fechainicio", sourceFechainicio),
              sourceFechainicio, (this.fechainicio != null)));
          copy.setFechainicio(copyFechainicio);
        } else {
          if (fechainicioShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.fechainicio = null;
          }
        }
      }
      {
        Boolean fechainiciolocShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.fechainicioloc != null));
        if (fechainiciolocShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceFechainicioloc;
          sourceFechainicioloc = this.getFechainicioloc();
          String copyFechainicioloc = ((String) strategy.copy(LocatorUtils.property(locator, "fechainicioloc", sourceFechainicioloc),
              sourceFechainicioloc, (this.fechainicioloc != null)));
          copy.setFechainicioloc(copyFechainicioloc);
        } else {
          if (fechainiciolocShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.fechainicioloc = null;
          }
        }
      }
      {
        Boolean fechainiciosecShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.fechainiciosec != null));
        if (fechainiciosecShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceFechainiciosec;
          sourceFechainiciosec = this.getFechainiciosec();
          String copyFechainiciosec = ((String) strategy.copy(LocatorUtils.property(locator, "fechainiciosec", sourceFechainiciosec),
              sourceFechainiciosec, (this.fechainiciosec != null)));
          copy.setFechainiciosec(copyFechainiciosec);
        } else {
          if (fechainiciosecShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.fechainiciosec = null;
          }
        }
      }
      {
        Boolean idlugartrabajoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idlugartrabajo != null));
        if (idlugartrabajoShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceIdlugartrabajo;
          sourceIdlugartrabajo = this.getIdlugartrabajo();
          String copyIdlugartrabajo = ((String) strategy.copy(LocatorUtils.property(locator, "idlugartrabajo", sourceIdlugartrabajo),
              sourceIdlugartrabajo, (this.idlugartrabajo != null)));
          copy.setIdlugartrabajo(copyIdlugartrabajo);
        } else {
          if (idlugartrabajoShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.idlugartrabajo = null;
          }
        }
      }
      {
        Boolean fechaantiguedadShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.fechaantiguedad != null));
        if (fechaantiguedadShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceFechaantiguedad;
          sourceFechaantiguedad = this.getFechaantiguedad();
          String copyFechaantiguedad = ((String) strategy.copy(LocatorUtils.property(locator, "fechaantiguedad", sourceFechaantiguedad),
              sourceFechaantiguedad, (this.fechaantiguedad != null)));
          copy.setFechaantiguedad(copyFechaantiguedad);
        } else {
          if (fechaantiguedadShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.fechaantiguedad = null;
          }
        }
      }
      {
        Boolean idempleadolocalShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idempleadolocal != null));
        if (idempleadolocalShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceIdempleadolocal;
          sourceIdempleadolocal = this.getIdempleadolocal();
          String copyIdempleadolocal = ((String) strategy.copy(LocatorUtils.property(locator, "idempleadolocal", sourceIdempleadolocal),
              sourceIdempleadolocal, (this.idempleadolocal != null)));
          copy.setIdempleadolocal(copyIdempleadolocal);
        } else {
          if (idempleadolocalShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.idempleadolocal = null;
          }
        }
      }
      {
        Boolean idlugartrabajomtuShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idlugartrabajomtu != null));
        if (idlugartrabajomtuShouldBeCopiedAndSet == Boolean.TRUE) {
          String sourceIdlugartrabajomtu;
          sourceIdlugartrabajomtu = this.getIdlugartrabajomtu();
          String copyIdlugartrabajomtu =
              ((String) strategy.copy(LocatorUtils.property(locator, "idlugartrabajomtu", sourceIdlugartrabajomtu), sourceIdlugartrabajomtu,
                  (this.idlugartrabajomtu != null)));
          copy.setIdlugartrabajomtu(copyIdlugartrabajomtu);
        } else {
          if (idlugartrabajomtuShouldBeCopiedAndSet == Boolean.FALSE) {
            copy.idlugartrabajomtu = null;
          }
        }
      }
    }
    return draftCopy;
  }

  public Object createNewInstance() {
    return new IcmListaempleadoRecord();
  }

}
