
package com.inditex.rrhh.icmclcwb.model.meta4.icmwscalcincome.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Clase Java para Icm_ParametrosentradaRecord complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="Icm_ParametrosentradaRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="m4AutoGeneratedRecordID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="m4AutoGeneratedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="activo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="abierto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vigente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idperiodo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idempleado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idtipohora" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orempleado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idcadenareg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idorigenreg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idlugartrabajo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idempleadolocal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idlugartrabajomtu" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Icm_ParametrosentradaRecord", propOrder = {
    "m4AutoGeneratedRecordID",
    "m4AutoGeneratedToDelete",
    "activo",
    "abierto",
    "vigente",
    "idperiodo",
    "idempleado",
    "idtipohora",
    "orempleado",
    "idcadenareg",
    "idorigenreg",
    "idlugartrabajo",
    "idempleadolocal",
    "idlugartrabajomtu"
})
public class IcmParametrosentradaRecord implements Cloneable, CopyTo2, Equals2, HashCode2, ToString2
{

    @XmlElement(required = true, nillable = true)
    protected String m4AutoGeneratedRecordID;
    protected boolean m4AutoGeneratedToDelete;
    @XmlElement(required = true, nillable = true)
    protected String activo;
    @XmlElement(required = true, nillable = true)
    protected String abierto;
    @XmlElement(required = true, nillable = true)
    protected String vigente;
    @XmlElement(required = true, nillable = true)
    protected String idperiodo;
    @XmlElement(required = true, nillable = true)
    protected String idempleado;
    @XmlElement(required = true, nillable = true)
    protected String idtipohora;
    @XmlElement(required = true, nillable = true)
    protected String orempleado;
    @XmlElement(required = true, nillable = true)
    protected String idcadenareg;
    @XmlElement(required = true, nillable = true)
    protected String idorigenreg;
    @XmlElement(required = true, nillable = true)
    protected String idlugartrabajo;
    @XmlElement(required = true, nillable = true)
    protected String idempleadolocal;
    @XmlElement(required = true, nillable = true)
    protected String idlugartrabajomtu;

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedRecordID.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM4AutoGeneratedRecordID(String value) {
        this.m4AutoGeneratedRecordID = value;
    }

    /**
     * Obtiene el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }

    /**
     * Define el valor de la propiedad m4AutoGeneratedToDelete.
     * 
     */
    public void setM4AutoGeneratedToDelete(boolean value) {
        this.m4AutoGeneratedToDelete = value;
    }

    /**
     * Obtiene el valor de la propiedad activo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivo() {
        return activo;
    }

    /**
     * Define el valor de la propiedad activo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivo(String value) {
        this.activo = value;
    }

    /**
     * Obtiene el valor de la propiedad abierto.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbierto() {
        return abierto;
    }

    /**
     * Define el valor de la propiedad abierto.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbierto(String value) {
        this.abierto = value;
    }

    /**
     * Obtiene el valor de la propiedad vigente.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVigente() {
        return vigente;
    }

    /**
     * Define el valor de la propiedad vigente.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVigente(String value) {
        this.vigente = value;
    }

    /**
     * Obtiene el valor de la propiedad idperiodo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdperiodo() {
        return idperiodo;
    }

    /**
     * Define el valor de la propiedad idperiodo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdperiodo(String value) {
        this.idperiodo = value;
    }

    /**
     * Obtiene el valor de la propiedad idempleado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdempleado() {
        return idempleado;
    }

    /**
     * Define el valor de la propiedad idempleado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdempleado(String value) {
        this.idempleado = value;
    }

    /**
     * Obtiene el valor de la propiedad idtipohora.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdtipohora() {
        return idtipohora;
    }

    /**
     * Define el valor de la propiedad idtipohora.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdtipohora(String value) {
        this.idtipohora = value;
    }

    /**
     * Obtiene el valor de la propiedad orempleado.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrempleado() {
        return orempleado;
    }

    /**
     * Define el valor de la propiedad orempleado.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrempleado(String value) {
        this.orempleado = value;
    }

    /**
     * Obtiene el valor de la propiedad idcadenareg.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdcadenareg() {
        return idcadenareg;
    }

    /**
     * Define el valor de la propiedad idcadenareg.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdcadenareg(String value) {
        this.idcadenareg = value;
    }

    /**
     * Obtiene el valor de la propiedad idorigenreg.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdorigenreg() {
        return idorigenreg;
    }

    /**
     * Define el valor de la propiedad idorigenreg.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdorigenreg(String value) {
        this.idorigenreg = value;
    }

    /**
     * Obtiene el valor de la propiedad idlugartrabajo.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdlugartrabajo() {
        return idlugartrabajo;
    }

    /**
     * Define el valor de la propiedad idlugartrabajo.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdlugartrabajo(String value) {
        this.idlugartrabajo = value;
    }

    /**
     * Obtiene el valor de la propiedad idempleadolocal.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdempleadolocal() {
        return idempleadolocal;
    }

    /**
     * Define el valor de la propiedad idempleadolocal.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdempleadolocal(String value) {
        this.idempleadolocal = value;
    }

    /**
     * Obtiene el valor de la propiedad idlugartrabajomtu.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdlugartrabajomtu() {
        return idlugartrabajomtu;
    }

    /**
     * Define el valor de la propiedad idlugartrabajomtu.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdlugartrabajomtu(String value) {
        this.idlugartrabajomtu = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final IcmParametrosentradaRecord that = ((IcmParametrosentradaRecord) object);
        {
            String lhsM4AutoGeneratedRecordID;
            lhsM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            String rhsM4AutoGeneratedRecordID;
            rhsM4AutoGeneratedRecordID = that.getM4AutoGeneratedRecordID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedRecordID", lhsM4AutoGeneratedRecordID), LocatorUtils.property(thatLocator, "m4AutoGeneratedRecordID", rhsM4AutoGeneratedRecordID), lhsM4AutoGeneratedRecordID, rhsM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null), (that.m4AutoGeneratedRecordID!= null))) {
                return false;
            }
        }
        {
            boolean lhsM4AutoGeneratedToDelete;
            lhsM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            boolean rhsM4AutoGeneratedToDelete;
            rhsM4AutoGeneratedToDelete = that.isM4AutoGeneratedToDelete();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "m4AutoGeneratedToDelete", lhsM4AutoGeneratedToDelete), LocatorUtils.property(thatLocator, "m4AutoGeneratedToDelete", rhsM4AutoGeneratedToDelete), lhsM4AutoGeneratedToDelete, rhsM4AutoGeneratedToDelete, true, true)) {
                return false;
            }
        }
        {
            String lhsActivo;
            lhsActivo = this.getActivo();
            String rhsActivo;
            rhsActivo = that.getActivo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "activo", lhsActivo), LocatorUtils.property(thatLocator, "activo", rhsActivo), lhsActivo, rhsActivo, (this.activo!= null), (that.activo!= null))) {
                return false;
            }
        }
        {
            String lhsAbierto;
            lhsAbierto = this.getAbierto();
            String rhsAbierto;
            rhsAbierto = that.getAbierto();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "abierto", lhsAbierto), LocatorUtils.property(thatLocator, "abierto", rhsAbierto), lhsAbierto, rhsAbierto, (this.abierto!= null), (that.abierto!= null))) {
                return false;
            }
        }
        {
            String lhsVigente;
            lhsVigente = this.getVigente();
            String rhsVigente;
            rhsVigente = that.getVigente();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "vigente", lhsVigente), LocatorUtils.property(thatLocator, "vigente", rhsVigente), lhsVigente, rhsVigente, (this.vigente!= null), (that.vigente!= null))) {
                return false;
            }
        }
        {
            String lhsIdperiodo;
            lhsIdperiodo = this.getIdperiodo();
            String rhsIdperiodo;
            rhsIdperiodo = that.getIdperiodo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idperiodo", lhsIdperiodo), LocatorUtils.property(thatLocator, "idperiodo", rhsIdperiodo), lhsIdperiodo, rhsIdperiodo, (this.idperiodo!= null), (that.idperiodo!= null))) {
                return false;
            }
        }
        {
            String lhsIdempleado;
            lhsIdempleado = this.getIdempleado();
            String rhsIdempleado;
            rhsIdempleado = that.getIdempleado();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idempleado", lhsIdempleado), LocatorUtils.property(thatLocator, "idempleado", rhsIdempleado), lhsIdempleado, rhsIdempleado, (this.idempleado!= null), (that.idempleado!= null))) {
                return false;
            }
        }
        {
            String lhsIdtipohora;
            lhsIdtipohora = this.getIdtipohora();
            String rhsIdtipohora;
            rhsIdtipohora = that.getIdtipohora();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idtipohora", lhsIdtipohora), LocatorUtils.property(thatLocator, "idtipohora", rhsIdtipohora), lhsIdtipohora, rhsIdtipohora, (this.idtipohora!= null), (that.idtipohora!= null))) {
                return false;
            }
        }
        {
            String lhsOrempleado;
            lhsOrempleado = this.getOrempleado();
            String rhsOrempleado;
            rhsOrempleado = that.getOrempleado();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "orempleado", lhsOrempleado), LocatorUtils.property(thatLocator, "orempleado", rhsOrempleado), lhsOrempleado, rhsOrempleado, (this.orempleado!= null), (that.orempleado!= null))) {
                return false;
            }
        }
        {
            String lhsIdcadenareg;
            lhsIdcadenareg = this.getIdcadenareg();
            String rhsIdcadenareg;
            rhsIdcadenareg = that.getIdcadenareg();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idcadenareg", lhsIdcadenareg), LocatorUtils.property(thatLocator, "idcadenareg", rhsIdcadenareg), lhsIdcadenareg, rhsIdcadenareg, (this.idcadenareg!= null), (that.idcadenareg!= null))) {
                return false;
            }
        }
        {
            String lhsIdorigenreg;
            lhsIdorigenreg = this.getIdorigenreg();
            String rhsIdorigenreg;
            rhsIdorigenreg = that.getIdorigenreg();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idorigenreg", lhsIdorigenreg), LocatorUtils.property(thatLocator, "idorigenreg", rhsIdorigenreg), lhsIdorigenreg, rhsIdorigenreg, (this.idorigenreg!= null), (that.idorigenreg!= null))) {
                return false;
            }
        }
        {
            String lhsIdlugartrabajo;
            lhsIdlugartrabajo = this.getIdlugartrabajo();
            String rhsIdlugartrabajo;
            rhsIdlugartrabajo = that.getIdlugartrabajo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idlugartrabajo", lhsIdlugartrabajo), LocatorUtils.property(thatLocator, "idlugartrabajo", rhsIdlugartrabajo), lhsIdlugartrabajo, rhsIdlugartrabajo, (this.idlugartrabajo!= null), (that.idlugartrabajo!= null))) {
                return false;
            }
        }
        {
            String lhsIdempleadolocal;
            lhsIdempleadolocal = this.getIdempleadolocal();
            String rhsIdempleadolocal;
            rhsIdempleadolocal = that.getIdempleadolocal();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idempleadolocal", lhsIdempleadolocal), LocatorUtils.property(thatLocator, "idempleadolocal", rhsIdempleadolocal), lhsIdempleadolocal, rhsIdempleadolocal, (this.idempleadolocal!= null), (that.idempleadolocal!= null))) {
                return false;
            }
        }
        {
            String lhsIdlugartrabajomtu;
            lhsIdlugartrabajomtu = this.getIdlugartrabajomtu();
            String rhsIdlugartrabajomtu;
            rhsIdlugartrabajomtu = that.getIdlugartrabajomtu();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "idlugartrabajomtu", lhsIdlugartrabajomtu), LocatorUtils.property(thatLocator, "idlugartrabajomtu", rhsIdlugartrabajomtu), lhsIdlugartrabajomtu, rhsIdlugartrabajomtu, (this.idlugartrabajomtu!= null), (that.idlugartrabajomtu!= null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            String theM4AutoGeneratedRecordID;
            theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            strategy.appendField(locator, this, "m4AutoGeneratedRecordID", buffer, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null));
        }
        {
            boolean theM4AutoGeneratedToDelete;
            theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            strategy.appendField(locator, this, "m4AutoGeneratedToDelete", buffer, theM4AutoGeneratedToDelete, true);
        }
        {
            String theActivo;
            theActivo = this.getActivo();
            strategy.appendField(locator, this, "activo", buffer, theActivo, (this.activo!= null));
        }
        {
            String theAbierto;
            theAbierto = this.getAbierto();
            strategy.appendField(locator, this, "abierto", buffer, theAbierto, (this.abierto!= null));
        }
        {
            String theVigente;
            theVigente = this.getVigente();
            strategy.appendField(locator, this, "vigente", buffer, theVigente, (this.vigente!= null));
        }
        {
            String theIdperiodo;
            theIdperiodo = this.getIdperiodo();
            strategy.appendField(locator, this, "idperiodo", buffer, theIdperiodo, (this.idperiodo!= null));
        }
        {
            String theIdempleado;
            theIdempleado = this.getIdempleado();
            strategy.appendField(locator, this, "idempleado", buffer, theIdempleado, (this.idempleado!= null));
        }
        {
            String theIdtipohora;
            theIdtipohora = this.getIdtipohora();
            strategy.appendField(locator, this, "idtipohora", buffer, theIdtipohora, (this.idtipohora!= null));
        }
        {
            String theOrempleado;
            theOrempleado = this.getOrempleado();
            strategy.appendField(locator, this, "orempleado", buffer, theOrempleado, (this.orempleado!= null));
        }
        {
            String theIdcadenareg;
            theIdcadenareg = this.getIdcadenareg();
            strategy.appendField(locator, this, "idcadenareg", buffer, theIdcadenareg, (this.idcadenareg!= null));
        }
        {
            String theIdorigenreg;
            theIdorigenreg = this.getIdorigenreg();
            strategy.appendField(locator, this, "idorigenreg", buffer, theIdorigenreg, (this.idorigenreg!= null));
        }
        {
            String theIdlugartrabajo;
            theIdlugartrabajo = this.getIdlugartrabajo();
            strategy.appendField(locator, this, "idlugartrabajo", buffer, theIdlugartrabajo, (this.idlugartrabajo!= null));
        }
        {
            String theIdempleadolocal;
            theIdempleadolocal = this.getIdempleadolocal();
            strategy.appendField(locator, this, "idempleadolocal", buffer, theIdempleadolocal, (this.idempleadolocal!= null));
        }
        {
            String theIdlugartrabajomtu;
            theIdlugartrabajomtu = this.getIdlugartrabajomtu();
            strategy.appendField(locator, this, "idlugartrabajomtu", buffer, theIdlugartrabajomtu, (this.idlugartrabajomtu!= null));
        }
        return buffer;
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            String theM4AutoGeneratedRecordID;
            theM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", theM4AutoGeneratedRecordID), currentHashCode, theM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null));
        }
        {
            boolean theM4AutoGeneratedToDelete;
            theM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", theM4AutoGeneratedToDelete), currentHashCode, theM4AutoGeneratedToDelete, true);
        }
        {
            String theActivo;
            theActivo = this.getActivo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "activo", theActivo), currentHashCode, theActivo, (this.activo!= null));
        }
        {
            String theAbierto;
            theAbierto = this.getAbierto();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "abierto", theAbierto), currentHashCode, theAbierto, (this.abierto!= null));
        }
        {
            String theVigente;
            theVigente = this.getVigente();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "vigente", theVigente), currentHashCode, theVigente, (this.vigente!= null));
        }
        {
            String theIdperiodo;
            theIdperiodo = this.getIdperiodo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idperiodo", theIdperiodo), currentHashCode, theIdperiodo, (this.idperiodo!= null));
        }
        {
            String theIdempleado;
            theIdempleado = this.getIdempleado();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idempleado", theIdempleado), currentHashCode, theIdempleado, (this.idempleado!= null));
        }
        {
            String theIdtipohora;
            theIdtipohora = this.getIdtipohora();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idtipohora", theIdtipohora), currentHashCode, theIdtipohora, (this.idtipohora!= null));
        }
        {
            String theOrempleado;
            theOrempleado = this.getOrempleado();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "orempleado", theOrempleado), currentHashCode, theOrempleado, (this.orempleado!= null));
        }
        {
            String theIdcadenareg;
            theIdcadenareg = this.getIdcadenareg();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idcadenareg", theIdcadenareg), currentHashCode, theIdcadenareg, (this.idcadenareg!= null));
        }
        {
            String theIdorigenreg;
            theIdorigenreg = this.getIdorigenreg();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idorigenreg", theIdorigenreg), currentHashCode, theIdorigenreg, (this.idorigenreg!= null));
        }
        {
            String theIdlugartrabajo;
            theIdlugartrabajo = this.getIdlugartrabajo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idlugartrabajo", theIdlugartrabajo), currentHashCode, theIdlugartrabajo, (this.idlugartrabajo!= null));
        }
        {
            String theIdempleadolocal;
            theIdempleadolocal = this.getIdempleadolocal();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idempleadolocal", theIdempleadolocal), currentHashCode, theIdempleadolocal, (this.idempleadolocal!= null));
        }
        {
            String theIdlugartrabajomtu;
            theIdlugartrabajomtu = this.getIdlugartrabajomtu();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "idlugartrabajomtu", theIdlugartrabajomtu), currentHashCode, theIdlugartrabajomtu, (this.idlugartrabajomtu!= null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof IcmParametrosentradaRecord) {
            final IcmParametrosentradaRecord copy = ((IcmParametrosentradaRecord) draftCopy);
            {
                Boolean m4AutoGeneratedRecordIDShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.m4AutoGeneratedRecordID!= null));
                if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceM4AutoGeneratedRecordID;
                    sourceM4AutoGeneratedRecordID = this.getM4AutoGeneratedRecordID();
                    String copyM4AutoGeneratedRecordID = ((String) strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedRecordID", sourceM4AutoGeneratedRecordID), sourceM4AutoGeneratedRecordID, (this.m4AutoGeneratedRecordID!= null)));
                    copy.setM4AutoGeneratedRecordID(copyM4AutoGeneratedRecordID);
                } else {
                    if (m4AutoGeneratedRecordIDShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.m4AutoGeneratedRecordID = null;
                    }
                }
            }
            {
                Boolean m4AutoGeneratedToDeleteShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, true);
                if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.TRUE) {
                    boolean sourceM4AutoGeneratedToDelete;
                    sourceM4AutoGeneratedToDelete = this.isM4AutoGeneratedToDelete();
                    boolean copyM4AutoGeneratedToDelete = strategy.copy(LocatorUtils.property(locator, "m4AutoGeneratedToDelete", sourceM4AutoGeneratedToDelete), sourceM4AutoGeneratedToDelete, true);
                    copy.setM4AutoGeneratedToDelete(copyM4AutoGeneratedToDelete);
                } else {
                    if (m4AutoGeneratedToDeleteShouldBeCopiedAndSet == Boolean.FALSE) {
                    }
                }
            }
            {
                Boolean activoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.activo!= null));
                if (activoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceActivo;
                    sourceActivo = this.getActivo();
                    String copyActivo = ((String) strategy.copy(LocatorUtils.property(locator, "activo", sourceActivo), sourceActivo, (this.activo!= null)));
                    copy.setActivo(copyActivo);
                } else {
                    if (activoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.activo = null;
                    }
                }
            }
            {
                Boolean abiertoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.abierto!= null));
                if (abiertoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceAbierto;
                    sourceAbierto = this.getAbierto();
                    String copyAbierto = ((String) strategy.copy(LocatorUtils.property(locator, "abierto", sourceAbierto), sourceAbierto, (this.abierto!= null)));
                    copy.setAbierto(copyAbierto);
                } else {
                    if (abiertoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.abierto = null;
                    }
                }
            }
            {
                Boolean vigenteShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.vigente!= null));
                if (vigenteShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceVigente;
                    sourceVigente = this.getVigente();
                    String copyVigente = ((String) strategy.copy(LocatorUtils.property(locator, "vigente", sourceVigente), sourceVigente, (this.vigente!= null)));
                    copy.setVigente(copyVigente);
                } else {
                    if (vigenteShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.vigente = null;
                    }
                }
            }
            {
                Boolean idperiodoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idperiodo!= null));
                if (idperiodoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdperiodo;
                    sourceIdperiodo = this.getIdperiodo();
                    String copyIdperiodo = ((String) strategy.copy(LocatorUtils.property(locator, "idperiodo", sourceIdperiodo), sourceIdperiodo, (this.idperiodo!= null)));
                    copy.setIdperiodo(copyIdperiodo);
                } else {
                    if (idperiodoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idperiodo = null;
                    }
                }
            }
            {
                Boolean idempleadoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idempleado!= null));
                if (idempleadoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdempleado;
                    sourceIdempleado = this.getIdempleado();
                    String copyIdempleado = ((String) strategy.copy(LocatorUtils.property(locator, "idempleado", sourceIdempleado), sourceIdempleado, (this.idempleado!= null)));
                    copy.setIdempleado(copyIdempleado);
                } else {
                    if (idempleadoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idempleado = null;
                    }
                }
            }
            {
                Boolean idtipohoraShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idtipohora!= null));
                if (idtipohoraShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdtipohora;
                    sourceIdtipohora = this.getIdtipohora();
                    String copyIdtipohora = ((String) strategy.copy(LocatorUtils.property(locator, "idtipohora", sourceIdtipohora), sourceIdtipohora, (this.idtipohora!= null)));
                    copy.setIdtipohora(copyIdtipohora);
                } else {
                    if (idtipohoraShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idtipohora = null;
                    }
                }
            }
            {
                Boolean orempleadoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.orempleado!= null));
                if (orempleadoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceOrempleado;
                    sourceOrempleado = this.getOrempleado();
                    String copyOrempleado = ((String) strategy.copy(LocatorUtils.property(locator, "orempleado", sourceOrempleado), sourceOrempleado, (this.orempleado!= null)));
                    copy.setOrempleado(copyOrempleado);
                } else {
                    if (orempleadoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.orempleado = null;
                    }
                }
            }
            {
                Boolean idcadenaregShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idcadenareg!= null));
                if (idcadenaregShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdcadenareg;
                    sourceIdcadenareg = this.getIdcadenareg();
                    String copyIdcadenareg = ((String) strategy.copy(LocatorUtils.property(locator, "idcadenareg", sourceIdcadenareg), sourceIdcadenareg, (this.idcadenareg!= null)));
                    copy.setIdcadenareg(copyIdcadenareg);
                } else {
                    if (idcadenaregShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idcadenareg = null;
                    }
                }
            }
            {
                Boolean idorigenregShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idorigenreg!= null));
                if (idorigenregShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdorigenreg;
                    sourceIdorigenreg = this.getIdorigenreg();
                    String copyIdorigenreg = ((String) strategy.copy(LocatorUtils.property(locator, "idorigenreg", sourceIdorigenreg), sourceIdorigenreg, (this.idorigenreg!= null)));
                    copy.setIdorigenreg(copyIdorigenreg);
                } else {
                    if (idorigenregShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idorigenreg = null;
                    }
                }
            }
            {
                Boolean idlugartrabajoShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idlugartrabajo!= null));
                if (idlugartrabajoShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdlugartrabajo;
                    sourceIdlugartrabajo = this.getIdlugartrabajo();
                    String copyIdlugartrabajo = ((String) strategy.copy(LocatorUtils.property(locator, "idlugartrabajo", sourceIdlugartrabajo), sourceIdlugartrabajo, (this.idlugartrabajo!= null)));
                    copy.setIdlugartrabajo(copyIdlugartrabajo);
                } else {
                    if (idlugartrabajoShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idlugartrabajo = null;
                    }
                }
            }
            {
                Boolean idempleadolocalShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idempleadolocal!= null));
                if (idempleadolocalShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdempleadolocal;
                    sourceIdempleadolocal = this.getIdempleadolocal();
                    String copyIdempleadolocal = ((String) strategy.copy(LocatorUtils.property(locator, "idempleadolocal", sourceIdempleadolocal), sourceIdempleadolocal, (this.idempleadolocal!= null)));
                    copy.setIdempleadolocal(copyIdempleadolocal);
                } else {
                    if (idempleadolocalShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idempleadolocal = null;
                    }
                }
            }
            {
                Boolean idlugartrabajomtuShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, (this.idlugartrabajomtu!= null));
                if (idlugartrabajomtuShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceIdlugartrabajomtu;
                    sourceIdlugartrabajomtu = this.getIdlugartrabajomtu();
                    String copyIdlugartrabajomtu = ((String) strategy.copy(LocatorUtils.property(locator, "idlugartrabajomtu", sourceIdlugartrabajomtu), sourceIdlugartrabajomtu, (this.idlugartrabajomtu!= null)));
                    copy.setIdlugartrabajomtu(copyIdlugartrabajomtu);
                } else {
                    if (idlugartrabajomtuShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.idlugartrabajomtu = null;
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new IcmParametrosentradaRecord();
    }

}
