package com.inditex.rrhh.icmclcwb.model.app.trabajo.mapper;

import java.util.List;

import com.inditex.rrhh.icmclcwb.api.app.trabajo.dto.TrabajoAmbitoOrigenDto;
import com.inditex.rrhh.icmclcwb.api.app.util.ErrorConstants;
import com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.save.proceso.dto.SaveProcesoParametersDto;
import com.inditex.rrhh.icmclcwb.dto.TrabajoAmbitoOrigenDTO;
import com.inditex.rrhh.icmclcwb.dto.TrabajoDTO;
import com.inditex.rrhh.icmclcwb.model.app.trabajo.mapper.decorator.TrabajoAmbitoOrigenMapperDecorator;
import com.inditex.rrhh.icmclcwb.model.primary.trabajo.entity.TrabajoAmbitoOrigen;

import org.mapstruct.DecoratedWith;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper
@DecoratedWith(value = TrabajoAmbitoOrigenMapperDecorator.class)
public abstract class TrabajoAmbitoOrigenMapper {

  @Mapping(target = "idTrabajo", source = "trabajo.id")
  public abstract TrabajoAmbitoOrigenDTO trabajoAmbitoOrigenToTrabajoAmbitoOrigenDto(TrabajoAmbitoOrigen src);

  public abstract List<TrabajoAmbitoOrigenDTO> trabajoAmbitoOrigenToTrabajoAmbitoOrigenDto(
      List<TrabajoAmbitoOrigen> src);

  @InheritInverseConfiguration
  public abstract TrabajoAmbitoOrigen trabajoAmbitoOrigenDtoToTrabajoAmbitoOrigen(TrabajoAmbitoOrigenDTO src);

  public abstract List<TrabajoAmbitoOrigen> trabajoAmbitoOrigenDtoToTrabajoAmbitoOrigen(
      List<TrabajoAmbitoOrigenDTO> src);

  @Mapping(target = "id", ignore = true)
  @Mapping(target = "trabajo.id", source = "srcTrabajo.id")
  public abstract TrabajoAmbitoOrigen mergeTrabajoAmbitoOrigenDtoAndTrabajoDtoToTrabajoAmbitoOrigen(
      TrabajoAmbitoOrigenDTO srcTrabajoAmbitoOrigen, TrabajoDTO srcTrabajo);

  public List<TrabajoAmbitoOrigen> mergeTrabajoAmbitoOrigenDtoAndTrabajoDtoToTrabajoAmbitoOrigen(
      final List<TrabajoAmbitoOrigenDTO> srcTrabajoAmbitoOrigen, final TrabajoDTO srcTrabajo) {
    throw new UnsupportedOperationException(ErrorConstants.NOT_IMPLEMENTED);
  }

  @Mapping(target = "m4AutoGeneratedRecordID", ignore = true)
  @Mapping(target = "m4AutoGeneratedToDelete", ignore = true)
  @Mapping(target = "idEmpleado", ignore = true)
  @Mapping(target = "orEmpleado", ignore = true)
  @Mapping(target = "idLugarTrabajo", ignore = true)
  @Mapping(target = "activo", ignore = true)
  @Mapping(target = "ambito", ignore = true)
  @Mapping(target = "idPais", ignore = true)
  @Mapping(target = "abierto", ignore = true)
  @Mapping(target = "vigente", ignore = true)
  @Mapping(target = "idTipoHora", ignore = true)
  @Mapping(target = "idEmpleadoLocal", ignore = true)
  @Mapping(target = "idLugarTrabajoMtu", ignore = true)
  @Mapping(target = "idCadena", ignore = true)
  @Mapping(target = "idSociedadReg", ignore = true)
  @Mapping(target = "idEstado", ignore = true)
  @Mapping(target = "idRegion", ignore = true)
  @Mapping(target = "idPeriodo", ignore = true)
  @Mapping(target = "idUsuario", ignore = true)
  @Mapping(target = "resultado", ignore = true)
  @Mapping(target = "fechaDesde", ignore = true)
  @Mapping(target = "fechaHasta", ignore = true)
  @Mapping(target = "idCadenaReg", ignore = true)
  @Mapping(target = "idPoblacion", ignore = true)
  @Mapping(target = "idTipoProceso", ignore = true)
  @Mapping(target = "nombreEmpleado", ignore = true)
  @Mapping(target = "fechaFinCalculo", ignore = true)
  @Mapping(target = "apellidoEmpleado", ignore = true)
  @Mapping(target = "fechaInicioCalculo", ignore = true)
  @Mapping(target = "idManualProgramado", ignore = true)
  @Mapping(target = "fechaFinExportacion", ignore = true)
  @Mapping(target = "fechaInicioExportacion", ignore = true)
  @Mapping(target = "idEmpresa", ignore = true)
  @Mapping(target = "idOrigenReg", source = "cclIdOrigen")
  public abstract SaveProcesoParametersDto trabajoAmbitoOrigenDtoToSaveProcesoParametersDto(
      TrabajoAmbitoOrigenDto src);

  public abstract List<SaveProcesoParametersDto> trabajoAmbitoOrigenDtoToSaveProcesoParametersDto(
      List<TrabajoAmbitoOrigenDto> src);

}
