package com.inditex.rrhh.icmclcwb.model.app.trabajo.mapper;

import java.util.List;

import com.inditex.rrhh.icmclcwb.api.app.util.ErrorConstants;
import com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.save.proceso.dto.SaveProcesoParametersDto;
import com.inditex.rrhh.icmclcwb.dto.TrabajoAmbitoPersonaDTO;
import com.inditex.rrhh.icmclcwb.dto.TrabajoDTO;
import com.inditex.rrhh.icmclcwb.model.app.trabajo.mapper.decorator.TrabajoAmbitoPersonaMapperDecorator;
import com.inditex.rrhh.icmclcwb.model.primary.trabajo.entity.TrabajoAmbitoPersona;

import org.mapstruct.DecoratedWith;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper
@DecoratedWith(value = TrabajoAmbitoPersonaMapperDecorator.class)
public abstract class TrabajoAmbitoPersonaMapper {

  @Mapping(target = "idTrabajo", source = "trabajo.id")
  public abstract TrabajoAmbitoPersonaDTO trabajoAmbitoPersonaToTrabajoAmbitoPersonaDto(TrabajoAmbitoPersona src);

  public abstract List<TrabajoAmbitoPersonaDTO> trabajoAmbitoPersonaToTrabajoAmbitoPersonaDto(
      List<TrabajoAmbitoPersona> src);

  @InheritInverseConfiguration
  public abstract TrabajoAmbitoPersona trabajoAmbitoPersonaDtoToTrabajoAmbitoPersona(TrabajoAmbitoPersonaDTO src);

  public abstract List<TrabajoAmbitoPersona> trabajoAmbitoPersonaDtoToTrabajoAmbitoPersona(
      List<TrabajoAmbitoPersonaDTO> src);

  @Mapping(target = "id", ignore = true)
  @Mapping(target = "trabajo.id", source = "srcTrabajo.id")
  public abstract TrabajoAmbitoPersona mergeTrabajoAmbitoPersonaDtoAndTrabajoDtoToTrabajoAmbitoPersona(
      TrabajoAmbitoPersonaDTO srcTrabajoAmbitoPersona, TrabajoDTO srcTrabajo);

  public List<TrabajoAmbitoPersona> mergeTrabajoAmbitoPersonaDtoAndTrabajoDtoToTrabajoAmbitoPersona(
      final List<TrabajoAmbitoPersonaDTO> srcTrabajoAmbitoPersona, final TrabajoDTO srcTrabajo) {
    throw new UnsupportedOperationException(ErrorConstants.NOT_IMPLEMENTED);
  }

  @Mapping(target = "m4AutoGeneratedRecordID", ignore = true)
  @Mapping(target = "m4AutoGeneratedToDelete", ignore = true)
  @Mapping(target = "idLugarTrabajo", ignore = true)
  @Mapping(target = "activo", ignore = true)
  @Mapping(target = "ambito", ignore = true)
  @Mapping(target = "idPais", ignore = true)
  @Mapping(target = "abierto", ignore = true)
  @Mapping(target = "vigente", ignore = true)
  @Mapping(target = "idTipoHora", ignore = true)
  @Mapping(target = "idLugarTrabajoMtu", ignore = true)
  @Mapping(target = "idCadena", ignore = true)
  @Mapping(target = "idSociedadReg", ignore = true)
  @Mapping(target = "idEstado", ignore = true)
  @Mapping(target = "idRegion", ignore = true)
  @Mapping(target = "idPeriodo", ignore = true)
  @Mapping(target = "idUsuario", ignore = true)
  @Mapping(target = "resultado", ignore = true)
  @Mapping(target = "fechaDesde", ignore = true)
  @Mapping(target = "fechaHasta", ignore = true)
  @Mapping(target = "idCadenaReg", ignore = true)
  @Mapping(target = "idPoblacion", ignore = true)
  @Mapping(target = "idTipoProceso", ignore = true)
  @Mapping(target = "nombreEmpleado", ignore = true)
  @Mapping(target = "fechaFinCalculo", ignore = true)
  @Mapping(target = "apellidoEmpleado", ignore = true)
  @Mapping(target = "fechaInicioCalculo", ignore = true)
  @Mapping(target = "idManualProgramado", ignore = true)
  @Mapping(target = "fechaFinExportacion", ignore = true)
  @Mapping(target = "fechaInicioExportacion", ignore = true)
  @Mapping(target = "idOrigenReg", source = "cclIdOrigen")
  @Mapping(target = "idEmpresa", source = "stdIdLegEnt")
  @Mapping(target = "idEmpleado", source = "cclIdPerson")
  @Mapping(target = "orEmpleado", source = "stdOrHrPeriod")
  @Mapping(target = "idEmpleadoLocal", source = "cclIdPerson")
  public abstract SaveProcesoParametersDto trabajoAmbitoPersonaDtoToSaveProcesoParametersDto(
      TrabajoAmbitoPersonaDTO src);

  public abstract List<SaveProcesoParametersDto> trabajoAmbitoPersonaDtoToSaveProcesoParametersDto(
      List<TrabajoAmbitoPersonaDTO> src);

}
