amiga:
  common:
    oauth2-client:
      clients:
        client-income:
          client-id: oauthincomedes
    cache:
      redis:
        cluster:
          nodes: redis-cluster-icmclcwb-v5.icmclcwb.svc.cluster.local.:6379
    rest:
      client:
        iopcomercialcalendar:
          base-url: https://people-pre.inditex.com/michorario
          ping-query:
            path: https://people-pre.inditex.com/michorario/amiga/health
        ptr-venta:
          base-url: http://rhvtimpwsd.rhvtimpwsd.svc.cluster.local.:8080/rhvtimpwsd
          username: srvcicmclcwbdes
          ping-query:
            path: http://rhvtimpwsd.rhvtimpwsd.svc.cluster.local.:8081/rhvtimpwsd/amiga/health
        ptr-presencia:
          base-url: http://rhpresnwsd.rhpresnwsd.svc.cluster.local.:8080/rhpresnwsd
          username: srvcicmclcwbdes
          ping-query:
            path: http://rhpresnwsd.rhpresnwsd.svc.cluster.local.:8081/rhpresnwsd/amiga/health
        venta-integra:
          base-url: http://dqservice.dqservice.svc.cluster.local.:8080/dqservice
          ping-query:
            path: http://dqservice.dqservice.svc.cluster.local.:8081/dqservice/amiga/health
        incomemeta:
          base-url: http://incomemeta.incomemeta.svc.cluster.local.:8080/incomemeta
          ping-query:
            path: http://incomemeta.incomemeta.svc.cluster.local.:8081/incomemeta/amiga/health
    metrics:
      type: influx
  data:
    jms:
      connection-factory:
        broker-escritura:
          brokerURL: tcp://middleware-amq-icmclcwb-tcp.icmclcwb.svc.cluster.local.:61616
        broker-lectura:
          brokerURL: tcp://middleware-amq-icmclcwb-tcp.icmclcwb.svc.cluster.local.:61616
    jdbc:
      datasource:
        primary:
          username: uincome
          jdbc-url: jdbc:db2://axdesdb26fin1.central.inditex.grp:50000/INDITEX:currentSchema=GESTION_COMISION;
        ptr:
          jdbc-url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=ocmdesptrdb-scan.ocimaditx.net)(PORT=7521)))(CONNECT_DATA=(SERVICE_NAME=s_pdbds01rt_gener.central.inditex.grp)))
          username: uincome
        comis1:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis2:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis3:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis4:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis5:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis6:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis7:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis8:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis9:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis10:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis11-8:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis11-20:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis11-233:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis11-28:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis11-33:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis11-101:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis11-11:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis11-2:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis11-30:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis11-25:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis18:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis28:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis30:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis32:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis38:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis39:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis52:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis60:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis61:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis63:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis64:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis66:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis68:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis70:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis72:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis73:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis75:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis79:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis91:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis92:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis93:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis95:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis96:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis97:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis98:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis139:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis388:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis400:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis404:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis412:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis508:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis512:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis524:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis528:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis664:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis720:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis728:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis732:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis736:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis740:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis743:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        comis800:
          jdbc-url: jdbc:sqlserver://AXDESSQL1:11433;databaseName=Personal;encrypt=false;trustServerCertificate=true
          username: uincome
        stream:
      bindings:
        commision-calculation-out-0:
          destination: sscc.global.des.rhcompensa.commision-calculation.public.v1
        commision-calculation-v2-out-0:
          destination: sscc.global.des.rhcompensa.commision-calculation.public.v2
  service:
    web:
      api:
        problem-details:
          enabled: false
    aaa:
      user-details:
        heimdal:
          remote:
            oauth-service-user:
              client-id: oauthincomedes
app:
  envars:
    mail:
      sender: 'noreply@inditex.com'
      receiver: 'incomealerts@inditex.com'
    ptr:
      venta:
        service:
          version: 1.0.34-rc.2
      presencia:
        service:
          version: 1.0.16-rc.5
    meta4:
      config:
        credentials:
          user: SRVCICMCLCWSDESAX
      ping-query-custom:
        path: https://des-openshift.axdesocp1.central.inditex.grp/icmclcws/validationCheck
      login:
        server: https://des-openshift.axdesocp1.central.inditex.grp/icmclcws/services/Login
      icmwscalcincome:
        server: https://des-openshift.axdesocp1.central.inditex.grp/icmclcws/services/ICM_WS_CALC_INCOME
    pipe:
      commission-calculation:
        message-max-size: 2000
