package com.inditex.rrhh.icmclcwb.api.meta4.icm_ws_income.valorescondiciones.dto;

import java.io.Serializable;

import lombok.Data;

@Data
public class CondicionesPoliticasResultItemDto implements Serializable {

	private static final long serialVersionUID = -7729698551562400680L;

	private String m4AutoGeneratedRecordID;
	private boolean m4AutoGeneratedToDelete;
    private String inOut;
    private String nuevo;
    private String borrado;
    private String idPolitica;
    private String modificado;
    private String orPolitica;
    private String porcentaje;
    private String idMotivoBaja;
    private String idPorcentaje;
    private String numDiasAplica;
    private String cantidadLimite;
    private String nombrePolitica;
    private String idTipoCondicion;
    private String nombreMotivoBaja;
    private String idSubtipoCondicion;
    private String nombreTipoCondicion;
    private String nombreSubtipoCondicion;
    private String considerarMediaComision;
}
