package com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.configuracionventaonline.dto;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.Data;

@Data
public class ConfiguracionVentaOnlineResultItemDto implements Serializable {

  private static final long serialVersionUID = 5306363287589542882L;

  private String m4AutoGeneratedRecordID;

  private boolean m4AutoGeneratedToDelete;

  private LocalDateTime fechaInicio;

  private LocalDateTime fechaFin;

  private String idOrigen;

  private String idConcepto;

  private String porcentaje;

  private String idAgrupacion;

}
