package com.inditex.rrhh.icmclcwb.model.meta4.icmwscalcincome.mapper;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.LocalDateTime;
import java.util.List;

import com.inditex.rrhh.icmclccore.calculoincome.rest.client.model.SearchTiendasOnlineRequestDto;
import com.inditex.rrhh.icmclccore.calculoincome.rest.client.model.SearchTiendasOnlineResponseDto;
import com.inditex.rrhh.icmclccore.calculoincome.rest.client.model.TiendaOnlineDto;
import com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.generic.dto.GenericFilterDto;
import com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.tiendasonline.dto.TiendaOnlineRequestDto;
import com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.tiendasonline.dto.TiendaOnlineResponseDto;
import com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.tiendasonline.dto.TiendaOnlineResultItemDto;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.mapstruct.factory.Mappers;

class PeopleAclMapperTest {

  static final LocalDateTime FECHA_INICIO = LocalDateTime.parse("2026-01-01T00:00:00");

  static final LocalDateTime FECHA_FIN = LocalDateTime.parse("2026-12-31T23:59:59");

  PeopleAclMapper mapper;

  @BeforeEach
  void beforeEach() {
    mapper = Mappers.getMapper(PeopleAclMapper.class);
  }

  @Nested
  class ToSearchTiendasOnlineRequestDtoFromFilter {

    @Test
    void whenFilterPopulatedExpectFieldsMappedAndIdCadenasIgnored() {
      GenericFilterDto src = new GenericFilterDto();
      src.setIdOrigen("ORIG-1");
      src.setFechaInicio(FECHA_INICIO);
      src.setFechaFin(FECHA_FIN);
      src.setIdCadena("CAD-1");

      SearchTiendasOnlineRequestDto result = mapper.toSearchTiendasOnlineRequestDto(src);

      assertThat(result).isNotNull();
      assertThat(result.getIdOrigen()).isEqualTo("ORIG-1");
      assertThat(result.getFechaInicio()).isEqualTo(FECHA_INICIO);
      assertThat(result.getFechaFin()).isEqualTo(FECHA_FIN);
      assertThat(result.getIdCadenas()).isEmpty();
    }

    @Test
    void whenFilterNullExpectNull() {
      SearchTiendasOnlineRequestDto result = mapper.toSearchTiendasOnlineRequestDto((GenericFilterDto) null);

      assertThat(result).isNull();
    }
  }

  @Nested
  class ToSearchTiendasOnlineRequestDtoFromRequest {

    @Test
    void whenRequestPopulatedExpectDataUnwrappedAndMapped() {
      GenericFilterDto filter = new GenericFilterDto();
      filter.setIdOrigen("ORIG-2");
      filter.setFechaInicio(FECHA_INICIO);
      filter.setFechaFin(FECHA_FIN);
      TiendaOnlineRequestDto src = new TiendaOnlineRequestDto();
      src.setData(filter);

      SearchTiendasOnlineRequestDto result = mapper.toSearchTiendasOnlineRequestDto(src);

      assertThat(result).isNotNull();
      assertThat(result.getIdOrigen()).isEqualTo("ORIG-2");
      assertThat(result.getFechaInicio()).isEqualTo(FECHA_INICIO);
      assertThat(result.getFechaFin()).isEqualTo(FECHA_FIN);
      assertThat(result.getIdCadenas()).isEmpty();
    }
  }

  @Nested
  class ToTiendaOnlineResultItemDto {

    @Test
    void whenSourcePopulatedExpectFieldsMappedAndRenamed() {
      TiendaOnlineDto src = new TiendaOnlineDto();
      src.setIdOrigen("ORIG-3");
      src.setIdEmpresa("EMP-1");
      src.setIdCadena("CAD-2");
      src.setIdLugarTrabajo("123");
      src.setIdLugarTrabajoMtu("MTU-1");
      src.setFechaInicio(FECHA_INICIO);
      src.setFechaFin(FECHA_FIN);

      TiendaOnlineResultItemDto result = mapper.toTiendaOnlineResultItemDto(src);

      assertThat(result).isNotNull();
      assertThat(result.getIdOrigen()).isEqualTo("ORIG-3");
      assertThat(result.getIdEmpresa()).isEqualTo("EMP-1");
      assertThat(result.getIdCadena()).isEqualTo("CAD-2");
      assertThat(result.getIdLocalizacion()).isEqualTo(123L);
      assertThat(result.getIdLocalizacionMeta4()).isEqualTo("MTU-1");
      assertThat(result.getFechaInicio()).isEqualTo(FECHA_INICIO);
      assertThat(result.getFechaFin()).isEqualTo(FECHA_FIN);
      assertThat(result.getM4AutoGeneratedRecordID()).isNull();
      assertThat(result.isM4AutoGeneratedToDelete()).isFalse();
    }

    @Test
    void whenSourceNullExpectNull() {
      TiendaOnlineResultItemDto result = mapper.toTiendaOnlineResultItemDto(null);

      assertThat(result).isNull();
    }
  }

  @Nested
  class ToTiendaOnlineResultItemDtoList {

    @Test
    void whenListPopulatedExpectAllItemsMapped() {
      TiendaOnlineDto first = new TiendaOnlineDto();
      first.setIdOrigen("ORIG-A");
      first.setIdLugarTrabajo("1");
      first.setIdLugarTrabajoMtu("MTU-A");
      TiendaOnlineDto second = new TiendaOnlineDto();
      second.setIdOrigen("ORIG-B");
      second.setIdLugarTrabajo("2");
      second.setIdLugarTrabajoMtu("MTU-B");

      List<TiendaOnlineResultItemDto> result = mapper.toTiendaOnlineResultItemDtoList(List.of(first, second));

      assertThat(result).hasSize(2);
      assertThat(result.get(0).getIdOrigen()).isEqualTo("ORIG-A");
      assertThat(result.get(0).getIdLocalizacion()).isEqualTo(1L);
      assertThat(result.get(0).getIdLocalizacionMeta4()).isEqualTo("MTU-A");
      assertThat(result.get(1).getIdOrigen()).isEqualTo("ORIG-B");
      assertThat(result.get(1).getIdLocalizacion()).isEqualTo(2L);
      assertThat(result.get(1).getIdLocalizacionMeta4()).isEqualTo("MTU-B");
    }

    @Test
    void whenNullListExpectNull() {
      List<TiendaOnlineResultItemDto> result = mapper.toTiendaOnlineResultItemDtoList(null);

      assertThat(result).isNull();
    }

    @Test
    void whenEmptyListExpectEmptyList() {
      List<TiendaOnlineResultItemDto> result = mapper.toTiendaOnlineResultItemDtoList(List.of());

      assertThat(result).isEmpty();
    }
  }

  @Nested
  class ToTiendaOnlineResponseDto {

    @Test
    void whenResponsePopulatedExpectDataMappedAndPageIgnored() {
      TiendaOnlineDto item = new TiendaOnlineDto();
      item.setIdOrigen("ORIG-X");
      item.setIdLugarTrabajo("99");
      item.setIdLugarTrabajoMtu("MTU-X");
      SearchTiendasOnlineResponseDto src = new SearchTiendasOnlineResponseDto();
      src.setData(List.of(item));

      TiendaOnlineResponseDto result = mapper.toTiendaOnlineResponseDto(src);

      assertThat(result).isNotNull();
      assertThat(result.getData()).hasSize(1);
      assertThat(result.getData().get(0).getIdOrigen()).isEqualTo("ORIG-X");
      assertThat(result.getData().get(0).getIdLocalizacion()).isEqualTo(99L);
      assertThat(result.getData().get(0).getIdLocalizacionMeta4()).isEqualTo("MTU-X");
      assertThat(result.getPage()).isNull();
    }

    @Test
    void whenSourceNullExpectNull() {
      TiendaOnlineResponseDto result = mapper.toTiendaOnlineResponseDto(null);

      assertThat(result).isNull();
    }

    @Test
    void whenEmptyDataExpectEmptyList() {
      SearchTiendasOnlineResponseDto src = new SearchTiendasOnlineResponseDto();
      src.setData(List.of());

      TiendaOnlineResponseDto result = mapper.toTiendaOnlineResponseDto(src);

      assertThat(result).isNotNull();
      assertThat(result.getData()).isEmpty();
      assertThat(result.getPage()).isNull();
    }
  }
}
