
package com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginService", targetNamespace = "http://schemas.meta4.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginService {


    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login.M4LoginOutput
     * @throws M4SoapException_Exception
     */
    @WebMethod
    @WebResult(name = "loginReturn", targetNamespace = "http://schemas.meta4.com/")
    @RequestWrapper(localName = "login", targetNamespace = "http://schemas.meta4.com/", className = "com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://schemas.meta4.com/", className = "com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login.LoginResponse")
    public M4LoginOutput login(
        @WebParam(name = "in0", targetNamespace = "http://schemas.meta4.com/")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://schemas.meta4.com/")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://schemas.meta4.com/")
        String in2)
        throws M4SoapException_Exception
    ;

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login.M4LoginOutput
     * @throws M4SoapException_Exception
     */
    @WebMethod
    @WebResult(name = "loginWithRoleReturn", targetNamespace = "http://schemas.meta4.com/")
    @RequestWrapper(localName = "loginWithRole", targetNamespace = "http://schemas.meta4.com/", className = "com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login.LoginWithRole")
    @ResponseWrapper(localName = "loginWithRoleResponse", targetNamespace = "http://schemas.meta4.com/", className = "com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login.LoginWithRoleResponse")
    public M4LoginOutput loginWithRole(
        @WebParam(name = "in0", targetNamespace = "http://schemas.meta4.com/")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://schemas.meta4.com/")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://schemas.meta4.com/")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://schemas.meta4.com/")
        String in3)
        throws M4SoapException_Exception
    ;

    /**
     * 
     * @return
     *     returns int
     * @throws M4SoapException_Exception
     */
    @WebMethod
    @WebResult(name = "logoutReturn", targetNamespace = "http://schemas.meta4.com/")
    @RequestWrapper(localName = "logout", targetNamespace = "http://schemas.meta4.com/", className = "com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://schemas.meta4.com/", className = "com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login.LogoutResponse")
    public int logout()
        throws M4SoapException_Exception
    ;

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login.M4LoginOutput
     * @throws M4SoapException_Exception
     */
    @WebMethod
    @WebResult(name = "loginWithCertificateReturn", targetNamespace = "http://schemas.meta4.com/")
    @RequestWrapper(localName = "loginWithCertificate", targetNamespace = "http://schemas.meta4.com/", className = "com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login.LoginWithCertificate")
    @ResponseWrapper(localName = "loginWithCertificateResponse", targetNamespace = "http://schemas.meta4.com/", className = "com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login.LoginWithCertificateResponse")
    public M4LoginOutput loginWithCertificate(
        @WebParam(name = "in0", targetNamespace = "http://schemas.meta4.com/")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://schemas.meta4.com/")
        String in1)
        throws M4SoapException_Exception
    ;

    /**
     * 
     * @param in0
     * @return
     *     returns int
     * @throws M4SoapException_Exception
     */
    @WebMethod
    @WebResult(name = "retrieveM4SessionReturn", targetNamespace = "http://schemas.meta4.com/")
    @RequestWrapper(localName = "retrieveM4Session", targetNamespace = "http://schemas.meta4.com/", className = "com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login.RetrieveM4Session")
    @ResponseWrapper(localName = "retrieveM4SessionResponse", targetNamespace = "http://schemas.meta4.com/", className = "com.inditex.rrhh.icmclcwb.api.ws.meta4.model.rrhhappwscincome.login.RetrieveM4SessionResponse")
    public int retrieveM4Session(
        @WebParam(name = "in0", targetNamespace = "http://schemas.meta4.com/")
        String in0)
        throws M4SoapException_Exception
    ;

}
