package com.inditex.rrhh.icmclcwb.model.primary.tarea.repository;

public interface TareaCalculoAlgoritmoGlobalTiendaPersonasPorVentaNoVendedoresPorcentajeDesplazamientoBaseV1RepositoryCustom
    extends TareaCalculoAlgoritmoBaseRepositoryCustom {

}
