package com.inditex.rrhh.icmclcwb.model.primary.tarea.repository;

public interface TareaCalculoAlgoritmoGlobalTiendaSeccionPersonasPorVentaNoVendedoresPorcentajeDesplazamientoBaseV1RepositoryCustom
    extends TareaCalculoAlgoritmoBaseRepositoryCustom {

}
