package com.inditex.rrhh.icmclcwb.model.primary.tarea.repository;

public interface TareaCalculoAlgoritmoDirectoVentaPersonasPorVentaNoVendedoresPorcentajeDesplazamientoBaseV1RepositoryCustom
    extends TareaCalculoAlgoritmoBaseRepositoryCustom {

}
