package com.inditex.rrhh.icmclcwb.api.meta4.icmwscalcincome.configuracionorganizacion;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class ConfiguracionItemDto implements Serializable {

  private static final long serialVersionUID = -5659137927641835338L;

  private String m4AutoGeneratedRecordID;

  private boolean m4AutoGeneratedToDelete;

  private LocalDateTime fechaInicio;

  private LocalDateTime fechaFin;

  private String idConfiguracion;

  private String idOrigen;

  private Integer idTipoHora;

  private Boolean icmCkVentaImpuestos;

  private Boolean icmCkIncIvaEvalPtpo;

  private Boolean icmCkRedJornada;

}
