package com.inditex.rrhh.icmclcwb.api.app.util;

public class SqlPipeConstants {
  // PARAMETROS DE FILTROS
  public static final String SQL_PARAM_ID_TAREA = "idTarea";

  public static final String SQL_PARAM_ICM_ID_TAREA_ACTUAL = "idTareaActual";

  public static final String SQL_PARAM_FECHA_INICIO_PERIODO = "fechaInicioPeriodo";

  public static final String SQL_PARAM_STD_ID_LEG_ENT = "stdIdLegEnt";

  public static final String SQL_PARAM_ICM_ID_PERIODO = "icmIdPeriodo";

  public static final String SQL_PARAM_CCL_ID_ORIGEN = "cclIdOrigen";

  public static final String SQL_PARAM_ID_ESTADO = "idEstado";

  public static final String SQL_PARAM_LIMIT = "limit";

  public static final String SQL_PARAM_OFFSET = "offset";

  // RESULTADOS DE CONSULTAS
  public static final String SQL_RESULT_ICM_ID_PERIODO = "ICM_ID_PERIODO";

  public static final String SQL_RESULT_CCL_ID_ORIGEN = "CCL_ID_ORIGEN";

  public static final String SQL_RESULT_STD_ID_LEG_ENT = "STD_ID_LEG_ENT";

  public static final String SQL_RESULT_CCL_ID_PERSON = "CCL_ID_PERSON";

  public static final String SQL_RESULT_STD_OR_HR_PERIOD = "STD_OR_HR_PERIOD";

  public static final String SQL_RESULT_ID_ESTADO = "ID_ESTADO";

  public static final String SQL_RESULT_FECHA_INICIO_PERIODO = "FECHA_INICIO_PERIODO";

  public static final String SQL_RESULT_FECHA_FIN_PERIODO = "FECHA_FIN_PERIODO";

  public static final String SQL_RESULT_FECHA = "FECHA";

  public static final String SQL_RESULT_TIENDA_CALCULO = "TIENDA_CALCULO";

  public static final String SQL_RESULT_FECHA_INICIO_ESTRUCTURA = "FECHA_INICIO_ESTRUCTURA";

  public static final String SQL_RESULT_FECHA_FIN_ESTRUCTURA = "FECHA_FIN_ESTRUCTURA";

  public static final String SQL_RESULT_CCL_ID_SECCION = "CCL_ID_SECCION";

  public static final String SQL_RESULT_BANDA = "BANDA";

  public static final String SQL_RESULT_VALOR = "VALOR";

  public static final String SQL_RESULT_ICM_ID_TP_COMISION = "ICM_ID_TP_COMISION";

  public static final String SQL_RESULT_ICM_ID_TP_CALCULO = "ICM_ID_TP_CALCULO";

  public static final String SQL_RESULT_ICM_GRUPO_MANUAL = "ICM_GRUPO_MANUAL";

  public static final String SQL_RESULT_ID_TIPO_OPCION_CALCULO = "ID_TIPO_OPCION_CALCULO";

  public static final String SQL_RESULT_CCL_ID_COD_ORIGEN_DESTINO = "CCL_ID_COD_ORIGEN_DESTINO";

  public static final String SQL_RESULT_COD_TIPO_HORA = "COD_TIPO_HORA";

  public static final String SQL_RESULT_MINUTOS = "MINUTOS";

  public static final String SQL_RESULT_COD_TIENDA_PRESENCIA_EMPLEADO = "COD_TIENDA_PRESENCIA_EMPLEADO";

  public static final String SQL_RESULT_COD_SECCION_PRESENCIA_EMPLEADO = "COD_SECCION_PRESENCIA_EMPLEADO";

  public static final String SQL_RESULT_MINUTOS_TIENDA = "MINUTOS_TIENDA";

  public static final String SQL_RESULT_COD_TIENDA_PRESENCIA = "COD_TIENDA_PRESENCIA";

  public static final String SQL_RESULT_COD_SECCION_PRESENCIA = "COD_SECCION_PRESENCIA";

  public static final String SQL_RESULT_IMPORTE_TOTAL = "IMPORTE_TOTAL";

  public static final String SQL_RESULT_IMPORTE_TOTAL_SIN_AJUSTE = "IMPORTE_TOTAL_SIN_AJUSTE";

  public static final String SQL_RESULT_IMPORTE_AJUSTE_TOTAL = "IMPORTE_AJUSTE_TOTAL";

  public static final String SQL_RESULT_IMPORTE_FISICA = "IMPORTE_FISICA";

  public static final String SQL_RESULT_IMPORTE_FISICA_SIN_AJUSTE = "IMPORTE_FISICA_SIN_AJUSTE";

  public static final String SQL_RESULT_IMPORTE_AJUSTE_FISICA = "IMPORTE_AJUSTE_FISICA";

  public static final String SQL_RESULT_IMPORTE_ONLINE_IPOD = "IMPORTE_ONLINE_IPOD";

  public static final String SQL_RESULT_IMPORTE_ONLINE_IPOD_SIN_AJUSTE = "IMPORTE_ONLINE_IPOD_SIN_AJUSTE";

  public static final String SQL_RESULT_IMPORTE_AJUSTE_ONLINE_IPOD = "IMPORTE_AJUSTE_ONLINE_IPOD";

  public static final String SQL_RESULT_IMPORTE_ONLINE_SINT = "IMPORTE_ONLINE_SINT";

  public static final String SQL_RESULT_IMPORTE_ONLINE_SINT_SIN_AJUSTE = "IMPORTE_ONLINE_SINT_SIN_AJUSTE";

  public static final String SQL_RESULT_IMPORTE_AJUSTE_ONLINE_SINT = "IMPORTE_AJUSTE_ONLINE_SINT";

  public static final String SQL_RESULT_IMPORTE_ONLINE_ENTREGA_TIENDA = "IMPORTE_ONLINE_ENTREGA_TIENDA";

  public static final String SQL_RESULT_IMPORTE_ONLINE_ENTREGA_TIENDA_SIN_AJUSTE = "IMPORTE_ONLINE_ENTREGA_TIENDA_SIN_AJUSTE";

  public static final String SQL_RESULT_IMPORTE_AJUSTE_ONLINE_ENTREGA_TIENDA = "IMPORTE_AJUSTE_ONLINE_ENTREGA_TIENDA";

  public static final String SQL_RESULT_IMPORTE_ONLINE_ENTREGA_DOMICILIO = "IMPORTE_ONLINE_ENTREGA_DOMICILIO";

  public static final String SQL_RESULT_IMPORTE_ONLINE_ENTREGA_DOMICILIO_SIN_AJUSTE = "IMPORTE_ONLINE_ENTREGA_DOMICILIO_SIN_AJUSTE";

  public static final String SQL_RESULT_IMPORTE_AJUSTE_ONLINE_ENTREGA_DOMICILIO = "IMPORTE_AJUSTE_ONLINE_ENTREGA_DOMICILIO";

  public static final String SQL_RESULT_VENTA_TOTAL = "VENTA_TOTAL";

  public static final String SQL_RESULT_VENTA_FISICA = "VENTA_FISICA";

  public static final String SQL_RESULT_VENTA_ONLINE_IPOD = "VENTA_ONLINE_IPOD";

  public static final String SQL_RESULT_VENTA_ONLINE_SINT = "VENTA_ONLINE_SINT";

  public static final String SQL_RESULT_VENTA_ONLINE_ENTREGA_TIENDA = "VENTA_ONLINE_ENTREGA_TIENDA";

  public static final String SQL_RESULT_VENTA_ONLINE_ENTREGA_DOMICILIO = "VENTA_ONLINE_ENTREGA_DOMICILIO";

  public static final String SQL_RESULT_OBJETIVO = "OBJETIVO";

  public static final String SQL_RESULT_EXCEPCIONADA = "EXCEPCIONADA";

  public static final String SQL_RESULT_CONGELADA = "CONGELADA";

  public static final String SQL_RESULT_CHALLENGE_VENTA_TOTAL = "CHALLENGE_VENTA_TOTAL";

  public static final String SQL_RESULT_CHALLENGE_VENTA_CAJA = "CHALLENGE_VENTA_CAJA";

  public static final String SQL_RESULT_CHALLENGE_DEVOLUCIONES = "CHALLENGE_DEVOLUCIONES";

  public static final String SQL_RESULT_CHALLENGE_VENTA_ONLINE_IPOD = "CHALLENGE_VENTA_ONLINE_IPOD";

  public static final String SQL_RESULT_CHALLENGE_VENTA_ONLINE_PICKING = "CHALLENGE_VENTA_ONLINE_PICKING";

  public static final String SQL_RESULT_CHALLENGE_VENTA_ONLINE_ENTREGA_TIENDA = "CHALLENGE_VENTA_ONLINE_ENTREGA_TIENDA";

  public static final String SQL_RESULT_IMPORTE_VENTA_FISICA_INDIVIDUAL = "IMPORTE_VENTA_FISICA_INDIVIDUAL";

  public static final String SQL_RESULT_IMPORTE_DEVOLUCION_FISICA_INDIVIDUAL = "IMPORTE_DEVOLUCION_FISICA_INDIVIDUAL";

  public static final String SQL_RESULT_IMPORTE_VENTA_ONLINE_IPOD = "IMPORTE_VENTA_ONLINE_IPOD";

  public static final String SQL_RESULT_IMPORTE_DEVOLUCION_INDIVIDUAL_IPOD = "IMPORTE_DEVOLUCION_INDIVIDUAL_IPOD";

  public static final String SQL_RESULT_COEFICIENTE_REDUCCION_JORNADA = "COEFICIENTE_REDUCCION_JORNADA";

  public static final String SQL_RESULT_ICM_CK_INC_IVA_EVAL_PTPO = "ICM_CK_INC_IVA_EVAL_PTPO";

  public static final String SQL_RESULT_COD_SECCION_BANDA = "COD_SECCION_BANDA";

  public static final String SQL_RESULT_TIPO_PORCENTAJE_POLITICA = "TIPO_PORCENTAJE_POLITICA";

  public static final String SQL_RESULT_COD_TIENDA_BANDA = "COD_TIENDA_BANDA";

  private SqlPipeConstants() {
  }
}
