name: adaptation-PR-verifier

concurrency:
  group: adaptation-PR-verifier-${{ github.event.pull_request.number || github.event.workflow_run.head_branch }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows:
      - apigateway-definitions
      - audit-PR-verify
      - code-maven-PR-verify
      - code-npm-PR-verify
      - database-PR-verify
      - escalation-PR-verify
      - monit-PR-verify
      - pipe-PR-verify
      - slm-PR-verify
    types: [completed]
    branches: [refactoring/*]
  pull_request:
    types: [opened]

env:
  SCM_USERNAME: butler-ci-bot
  SCM_EMAIL: srvcibot@inditex.com
  SCM_TOKEN: ${{ secrets.GH_TOKEN_PUSH }}
  SCM_COMMITTER_PGP_KEY: ${{ secrets.BUTLER_PGP_KEY }}
  FEATURES_WITHOUT_VERIFY: '["icarus", "authz", "job"]'

jobs:
  preconditions:
    runs-on: ubuntu-20.04
    outputs:
      preconditions: ${{ steps.preconditions.outputs.preconditions }}
    steps:
      - name: Check preconditions
        id: preconditions
        run: |
          preconditions=false
          if [ '${{ github.event_name }}' == 'workflow_run' ]; then
            preconditions=true
          elif [[ "${{ github.head_ref }}" =~ "from-bitbucket" ]]; then
            features=$(echo "$FEATURES_WITHOUT_VERIFY" | jq -r '.[]')
            for feature in $features; do
              if echo "${{ github.head_ref }}" | grep -q "$feature"; then
                preconditions=true
                break
              fi
            done
          fi

          echo "preconditions=$preconditions" >> "$GITHUB_OUTPUT"

  get-metadata:
    needs: [preconditions]
    runs-on: ubuntu-20.04
    if: needs.preconditions.outputs.preconditions == 'true'
    outputs:
      CONCLUSSION: ${{ steps.get-metadata.outputs.conclussion }}
      WORKFLOW_URL: ${{ steps.get-metadata.outputs.workflow_url }}
      BRANCH: ${{ steps.get-metadata.outputs.branch }}
      PR: ${{ steps.get-metadata.outputs.pr }}
      TASK_NAME: ${{ steps.get-metadata.outputs.task_name }}
      FILE_NAME: ${{ steps.get-metadata.outputs.file_name }}
      NEED_TO_REPORT: ${{ steps.get-metadata.outputs.need_to_report }}
    steps:
      - name: Checkout working branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get metadata to report
        id: get-metadata
        env:
          GITHUB_TOKEN: ${{ secrets.DARWINBOT_PR_PAT }}
        run: |
          conclussion="missing"
          workflow_url="none"
          branch="${{ github.head_ref }}"
          pr="${{ github.event.pull_request.html_url }}"
          task_name="${{ github.event.pull_request.title }}"
          file_name="code"

          if [ -n "${{ github.event.workflow_run }}" ]; then
            conclussion="${{ github.event.workflow_run.conclusion }}"
            workflow_url="${{ github.event.workflow_run.html_url }}"
            branch="${{ github.event.workflow_run.head_branch }}"
            pr_number="${{ github.event.workflow_run.pull_requests[0].number }}"
            pr="https://github.com/${{ github.repository }}/pull/$pr_number"
            task_name=$(gh pr view $pr_number --json title --jq ".title")
            workflow_run_id=$(basename $workflow_url)
          fi

          if [[ "$conclussion" == "success" ]] || [[ "$conclussion" == "missing" ]]; then
            gh pr ready $pr
          fi

          if [[ ! "$task_name" =~ ^Adapt ]]; then
            file_name=$(echo "$task_name" | sed -E "s/Migrate '(.*)' feature from Bitbucket/\1/")
          fi

          if [[ "$file_name" == "code" ]]; then
            if gh run view $workflow_run_id | grep "X sonar-scanner / Run scanner"; then
              conclussion="warning"
            fi
          fi

          echo "conclussion=$conclussion" >> "$GITHUB_OUTPUT"
          echo "workflow_url=$workflow_url" >> "$GITHUB_OUTPUT"
          echo "branch=$branch" >> "$GITHUB_OUTPUT"
          echo "pr=$pr" >> "$GITHUB_OUTPUT"
          echo "task_name=$task_name" >> "$GITHUB_OUTPUT"
          echo "file_name=$file_name" >> "$GITHUB_OUTPUT"

          branch_name=internal/adaptation-status
          if [ -n "$(git ls-remote --heads origin $branch_name)" ]
          then
            git checkout "$branch_name"
            if [[ ! -f "reports/$file_name.yml" ]]; then
              echo "need_to_report=true" >> "$GITHUB_OUTPUT"
            fi
          fi

  report-status:
    runs-on: ubuntu-20.04
    needs: [get-metadata]
    if: needs.get-metadata.outputs.NEED_TO_REPORT == 'true'
    steps:
      - name: Checkout working branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.DARWINBOT_PR_PAT }}

      - name: Prepare committer information
        run: |
          echo "$SCM_COMMITTER_PGP_KEY" | gpg --import
          git config user.name "$SCM_USERNAME"
          git config user.email "$SCM_EMAIL"
          git config commit.gpgsign true

      - name: Create orphan branch
        run: |
          branch_name=internal/adaptation-status
          if ! [ -n "$(git ls-remote --heads origin $branch_name)" ]
          then
            git switch --orphan "$branch_name"
            git commit --allow-empty -m "chore: Create orphan branch"
            git push --set-upstream origin "$branch_name"
          else
            git checkout "$branch_name"
            git pull origin "$branch_name"
          fi
          mkdir -p reports/

      - name: Workflow run / Create progression file for adaptation step
        working-directory: reports
        run: |
          file=${{ needs.get-metadata.outputs.FILE_NAME }}.yml

          touch $file
          echo "conclusion: ${{ needs.get-metadata.outputs.CONCLUSSION }}
          workflow: ${{ needs.get-metadata.outputs.WORKFLOW_URL }}
          branch: ${{ needs.get-metadata.outputs.BRANCH }}
          pr: ${{ needs.get-metadata.outputs.PR }}
          task-name: \"${{ needs.get-metadata.outputs.TASK_NAME }}\"" > $file

          git add $file
          git commit -m "chore: Create $file"
          git pull --rebase origin internal/adaptation-status
          git push
