---
name: amginspector-analyzer

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, labeled, edited, synchronize]
  workflow_dispatch:

env:
  WORKFLOW_VERSION: 1.44.0
  TOOL_VERSIONS: |
    ivm-node 18.12.1

jobs:
  run-inspector:
    name: AmgInspector / Analyze
    timeout-minutes: 20
    if: |-
      ${{ github.event_name == 'workflow_dispatch' ||
        github.event_name == 'push' ||
        (github.event_name == 'pull_request' && contains( github.event.pull_request.labels.*.name, 'amiga-inspector'))
      }}
    runs-on: [self-hosted, inspector]
    env:
      ASDF_DATA_DIR: /tmp/asdf/data
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Custom Rules
        uses: actions/checkout@v4
        with:
          repository: inditex/cac-amigainspectorrules
          path: cac-amigainspectorrules
          token: ${{ secrets.GH_TOKEN_READER }}

      - name: IVM / Create .tool-versions
        run: |
          echo "$TOOL_VERSIONS" > ${{ github.workspace }}/.tool-versions
      - name: IVM / Create ASDF_DATA_DIR
        run: |
          mkdir -p "$ASDF_DATA_DIR"
      - name: IVM / Setup plugins
        uses: inditex/gha-ivmactions/setup-plugins@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_READER }}
        with:
          tool-versions-directory: "."

      - name: IVM / Setup environment
        uses: inditex/gha-ivmactions/setup-environment@v0
        with:
          tool-versions-directory: "."


      - name: Get metadata
        id: metadata
        shell: python
        run: |
          import yaml
          import os

          with open('application.yml') as f:
            application = yaml.safe_load(f)

          github_output = os.getenv('GITHUB_OUTPUT')
          with open(github_output, "a") as gh_out:
            gh_out.write(f'project-key={ application["metadata"]["project_key"] }\n')
            gh_out.write(f'project-name={ application["metadata"]["project_name"] }\n')

      - name: Get global config
        id: config
        shell: python
        run: |
          import yaml
          import os

          with open('cac-amigainspectorrules/amginspector/config.yml') as f:
            config = yaml.safe_load(f)

          github_output = os.getenv('GITHUB_OUTPUT')
          with open(github_output, "a") as gh_out:
            gh_out.write(f'exclusions={ config["exclusions"] }\n')
            gh_out.write(f'process-timeout={ config["process-timeout"] }\n')
            gh_out.write(f'file-timeout={ config["file-timeout"] }\n')
            gh_out.write(f'ignore-default-rules={ config["ignore-default-rules"] }\n')
            gh_out.write(f'match-limit={ config["match-limit"] }\n')
            gh_out.write(f'react-scanner-enabled={ config["features"]["react-scanner"]["enabled"] }\n')

      - name: Get branch name (merge)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> "$GITHUB_ENV"

      - name: Run AMIGA Inspector
        uses: inditex/gha-amigainspectoractions/run@main
        with:
          project-key: ${{ steps.metadata.outputs.project-key }}
          project-name: ${{ steps.metadata.outputs.project-name }}
          branch: ${{ env.BRANCH_NAME }}
          custom-rules-path: cac-amigainspectorrules/amginspector/rules
          timeout: ${{ steps.config.outputs.process-timeout }}
          file-timeout: ${{ steps.config.outputs.file-timeout }}
          exclusions: ${{ steps.config.outputs.exclusions }}
          ignore-default-rules: ${{ steps.config.outputs.ignore-default-rules }}
          match-limit: ${{ steps.config.outputs.match-limit }}
          react-scanner-enabled: ${{ steps.config.outputs.react-scanner-enabled }}

        env:
          AMGINSPECT_USERNAME: ${{ secrets.AMGINSPECT_USER }}
          AMGINSPECT_PASSWORD: ${{ secrets.AMGINSPECT_PASS }}
