---
name: code-maven-build-snapshot

concurrency:
  group: code-build-snapshot
  cancel-in-progress: true

on:
  push:
    branches: ['develop', 'develop-*', 'main', 'main-*']
    paths: ['code/**', '.github/workflows/code**']

env:
  WORKFLOW_VERSION: 2.12.0
  GITHUB_REGISTRY: ghcr.io
  ASDF_IMAGE_NAME: inditex/ci-agents/asdf
  DT_ENDPOINT: ${{ secrets.DT_ENDPOINT }}
  DT_SECRET: ${{ secrets.DT_SECRET }}
  NPM_EMAIL: ${{ secrets.DIST_PLAT_DEPLOYER_USERNAME }}
  NPM_AUTH: ${{ secrets.DIST_PLAT_DEPLOYER_NPM_AUTH }}

jobs:
  build-snapshot:
    name: Build Snapshot
    runs-on: ubuntu-20.04
    if: ${{ (vars.DEVELOPMENT_FLOW == 'trunk-based-development' && (github.ref_name == 'main' || startsWith(github.ref_name, 'main-'))) || (vars.DEVELOPMENT_FLOW != 'trunk-based-development' && (github.ref_name == 'develop' || startsWith(github.ref_name, 'develop-'))) }}
    steps:
      - name: Checkout Branch Head
        uses: actions/checkout@v4

      - name: Setup Maven Cache
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup asdf Cache
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: ~/.asdf/data
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-

      - name: Log in to GitHub Registry
        run: echo "${{ secrets.GH_TOKEN_READER }}" | docker login "${GITHUB_REGISTRY}" -u none --password-stdin

      - name: Infer ci-agents asdf image
        uses: inditex/gha-ivmactions/infer-ci-agent-asdf@v1
        env:
          ASDF_UBUNTU_IMAGE_TAG: 0.14.0-ubuntu20.04-r3
          ASDF_RHUBI_IMAGE_TAG: 0.14.0-rhubi-r4
          ASDF_CENTOS_IMAGE_TAG: 0.14.0-centos-r3
        with:
          tool-versions-directory: code
          github-token: ${{ secrets.GH_TOKEN_READER }}

      - name: Maven / Set Maven Build Cache options
        id: maven-opts
        if: ${{ vars.MAVEN_BUILD_CACHE_REMOTE == 'true' && !contains(join(github.event.pull_request.labels.*.name, ', '), 'skip-build-cache') }}
        uses: inditex/gha-citool/set-maven-build-cache@v0
        with:
          save-remote-enabled: true

      - name: Build & Deploy Snapshots
        env:
          MVN_BUILD_CACHE_OPTS: ${{ steps.maven-opts.outputs.maven-build-cache-opts }}
        run: |
          mkdir -p "$HOME"/.m2/repository
          mkdir -p "$HOME"/.asdf/data
          # shellcheck disable=SC2086
          docker run --workdir /app/code \
            -u runner \
            -e DP_USERNAME=${{ secrets.DIST_PLAT_DEPLOYER_USERNAME }} \
            -e DP_TOKEN=${{ secrets.DIST_PLAT_DEPLOYER_TOKEN }} \
            -e DT_ENDPOINT -e DT_SECRET \
            -e NPM_EMAIL -e NPM_AUTH \
            -e GITHUB_TOKEN=${{ secrets.GH_TOKEN_READER }} \
            -e TOOLVER_DISTRO_BRANCH=${{ vars.TOOLVER_DISTRO_BRANCH }} \
            --mount type=bind,src="$HOME"/.m2/repository,dst=/home/runner/.m2/repository \
            --mount type=bind,src="$(pwd)",dst=/app \
            --mount type=bind,src="$HOME"/.asdf/data,dst=/opt/asdf/data \
            "${GITHUB_REGISTRY}/${ASDF_IMAGE_NAME}:${ASDF_IMAGE_TAG}" \
            mvn -B clean deploy -DskipTests -DskipUTs -DskipITs -Dbuild.type=snapshot $MVN_BUILD_CACHE_OPTS
