---
name: code-sonarqube-fallback

on:
  pull_request:

env:
  WORKFLOW_VERSION: 2.27.0

jobs:
  sonar-check:
    if: 'false'
    name: SonarQube Code Analysis
    runs-on: ${{ fromJSON( vars.RUNSON_SONARQUBE_GENERIC || '["ubuntu-24.04"]' ) }}
    steps:
      - run: 'echo "No SonarScanner required"'
