---
name: code-maven-sca-analysis
run-name: "SCA Analysis on branch '${{ github.head_ref || github.ref_name }}'"

permissions:
  contents: write
  issues: write
  actions: write
  pull-requests: write
  id-token: write

concurrency:
  group: code-sca-analysis-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, closed]
    branches: ["main", "main-*", "develop", "develop-*"]
    paths: [".github/workflows/code-*-sca_analysis.yml", "code/**/pom.xml"]

env:
  WORKFLOW_VERSION: 1.3.1
  WORKING_DIR: code

jobs:
  sca-analysis-execution:
    runs-on: ${{ fromJSON( vars.RUNSON_SCA_MAVEN_JAVA_ONPREM || '["auditassistant-icr__sca-ubuntu24.04"]' ) }}
    name: SCA / Analysis execution
    if: ${{ (github.event.pull_request.draft == true && (vars.PR_VERIFY_RUNS_ON_DRAFT != 'false' || contains(github.event.pull_request.labels.*.name, 'pr-verify/force-on-draft'))) || github.event.pull_request.draft == false }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merged == true && github.event.repository.default_branch || github.event.pull_request.head.sha }}

      - name: Setup IVM environment
        uses: inditex/gha-ivmactions/setup-environment@v1
        with:
          tool-versions-directory: ${{ env.WORKING_DIR }}
          distro-branch: ${{ vars.TOOLVER_DISTRO_BRANCH }}
          github-token: ${{ secrets.GH_TOKEN_READER }}
          jfrog-token: ${{ secrets.DIST_PLAT_READER_TOKEN }}

      - name: Run Maven Install
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          mvn -B install -DskipTests -DskipUTs -DskipITs -DskipEnforceSnapshots

      - name: Run SCA Analysis
        id: sca-analysis
        uses: inditex/gha-xygeniactions/sca-scan@main
        with:
          xygeni-token: ${{ secrets.XYGENI_TOKEN }}
          project-name: ${{ github.repository }}
          working-directory: ${{ env.WORKING_DIR }}
          development-flow: ${{ vars.DEVELOPMENT_FLOW }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SCA Report to DefectDojo
        if: ${{ (github.event_name == 'workflow_dispatch') || (github.event.pull_request.merged == true && ( (vars.DEVELOPMENT_FLOW == 'trunk-based-development' && (github.ref_name == 'main' || startsWith(github.ref_name, 'main-'))) || (vars.DEVELOPMENT_FLOW != 'trunk-based-development' && (github.ref_name == 'develop' || startsWith(github.ref_name, 'develop-'))) ) ) }}
        uses: inditex/gha-defectdojoactions/upload-report@main
        with:
          origin: "DEVHUB"
          tool: "Xygeni SCA"
          report-path: "sca-report-filtered.json"
          working-directory: ${{ env.WORKING_DIR }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: SCA Analysis Status Check
        if: ${{ always() && !cancelled() }}
        run: |
          if [ "${{ steps.sca-analysis.outputs.sca_vulnerabilities_found }}" = "true" ]; then
            echo "❌ Vulnerabilities found during SCA analysis. Failing the workflow."
            exit 1
          else
            echo "✅ No SCA vulnerabilities found."
          fi
