---
name: code-sonarcloud-fallback

on:
  pull_request:

env:
  WORKFLOW_VERSION: 2.8.0

jobs:
  sonar-check:
    if: 'false'
    name: SonarCloud Code Analysis
    runs-on: ubuntu-20.04
    steps:
      - run: 'echo "No SonarScanner required"'
