---
name: monit-deploy
run-name: Monit deploy to AlertHub
on:
  pull_request:
    types: [closed]
    branches: [main]
    paths: ['monit/**', '.github/workflows/monit-deploy.yml']
  workflow_dispatch:

env:
  WORKFLOW_VERSION: 1.51.0
  SRVC_ALERTHUBINTDESAX_USERNAME: ${{ secrets.SRVC_ALERTHUBINTDESAX_USERNAME }}
  SRVC_ALERTHUBINTDESAX_PASSWORD: ${{ secrets.SRVC_ALERTHUBINTDESAX_PASSWORD }}
  SRVC_ALERTHUBINTPREAX_USERNAME: ${{ secrets.SRVC_ALERTHUBINTPREAX_USERNAME }}
  SRVC_ALERTHUBINTPREAX_PASSWORD: ${{ secrets.SRVC_ALERTHUBINTPREAX_PASSWORD }}
  SRVC_ALERTHUBINTAX_USERNAME: ${{ secrets.SRVC_ALERTHUBINTAX_USERNAME }}
  SRVC_ALERTHUBINTAX_PASSWORD: ${{ secrets.SRVC_ALERTHUBINTAX_PASSWORD }}

jobs:
  linter:
    name: Linter
    if: github.event_name == 'workflow_dispatch'
    timeout-minutes: 30
    runs-on: ${{ fromJSON(vars.RUNSON_ALERTHUB_DOCKER || '["citool-github__ubuntu24.04-medium"]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.sha}}

      - name: Linter
        uses: github/super-linter@v4.8.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: monit/.*
          VALIDATE_JSON: true

  monit:
    name: Monit
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ${{ fromJSON(vars.RUNSON_ALERTHUB_ONPREM || '["citool-icr__code-ubuntu24.04-large"]') }}
    steps:
      - name: Set environment
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "env=\"pro\"" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v6

      - name: Get metadata
        id: metadata
        shell: python
        run: |
          import yaml
          import os

          with open('application.yml') as f:
            application = yaml.safe_load(f)

          github_output = os.getenv('GITHUB_OUTPUT')
          with open(github_output, "a") as gh_out:
            gh_out.write(f'project-key={ application["metadata"]["project_key"] }\n')

      - name: Setup Java tool
        uses: inditex/gha-ivmactions/setup-tool@v1
        with:
          tool-name: ivm-java
          tool-version: openjdk-17
          install: true
          github-token: ${{ secrets.GH_TOKEN_READER }}
          jfrog-token: ${{ secrets.DIST_PLAT_READER_TOKEN }}

      - name: Monit step
        uses: inditex/gha-alerthub/code@main
        with:
          project-key: ${{ steps.metadata.outputs.project-key }}
          env: ${{ env.env }}
