---
name: paas-deploy-instances
run-name: "Args: action=${{ inputs.ACTION }}"

on:
  workflow_dispatch:
    inputs:
      ISSUE_NUMBER:
        description: "Related issue number"
        required: true
      ISSUE_COMMENT_ID:
        description: "Issue comment ID that triggered the action"
        required: true
      ACTION:
        description: "Action to run"
        required: true
        type: choice
        options:
          - approve
          - cancel
          - continue
          - merge
          - restore
          - retry
          - rollback
      SKIP:
        description: 'Steps to be skipped during rollout flow'
        required: false
        default: ''
      SUPRAENVS:
        description: 'Supra environments used during action execution'
        required: false
        default: ''
      ENVS:
        description: 'Environments used during action execution'
        required: false
        default: ''
      PLATFORMS:
        description: 'Platforms used during action execution'
        required: false
        default: ''
      TENANTS:
        description: 'Tenants used during action execution'
        required: false
        default: ''
      SLOTS:
        description: 'Slots used during action execution'
        required: false
        default: 'default'

env:
  WORKFLOW_VERSION: 2.5.0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DIR_PATH_STATUS: "/tmp/restore-results"

jobs:

  verify:
    name: PaaS / Verify User Permissions in Repository
    runs-on: ubuntu-20.04
    if: ${{ contains(fromJSON('["merge", "approve"]'), github.event.inputs.ACTION) }}
    needs: [validate-permutations, get-affected-prs]
    outputs:
      summary: ${{ steps.verify-permissions.outputs.summary }}
      has-errors: ${{ steps.verify-permissions.outputs.has-errors }}

    steps:
      - name: ignore verify if action is approve
        if: ${{ github.event.inputs.ACTION == 'approve' }}
        id: skip-verify
        run: |
          echo "has-errors=False" >> "$GITHUB_OUTPUT"
          echo "skip-verify=True" >> "$GITHUB_OUTPUT"

      - name: Get user
        if: ${{ steps.skip-verify.outputs.skip-verify != 'True' }}
        id: get-user
        run: |
          login=$(gh api /repos/${{ github.repository }}/issues/comments/${{ github.event.inputs.ISSUE_COMMENT_ID }} -q '.user.login')
          echo "login=${login}" >> "$GITHUB_OUTPUT"

      - name: PaaS / Get Affected PRs information
        id: get-prs-to-verify-info
        if: ${{ steps.skip-verify.outputs.skip-verify != 'True' }}
        uses: inditex/gha-paasdeployment/get-permutations-info@v0
        with:
          filter-for-action: "MERGE"
          affected-prs: '${{ needs.get-affected-prs.outputs.affected-prs }}'
          permutations: '${{ needs.validate-permutations.outputs.filtered-permutations }}'

      - name: Verify enough permissions
        if: ${{ steps.skip-verify.outputs.skip-verify != 'True' }}
        uses: inditex/gha-paasdeployment/verify-pr-permissions@v0
        id: verify-permissions
        with:
          prs-to-process: ${{ steps.get-prs-to-verify-info.outputs.permutations-info }}
          user: ${{ steps.get-user.outputs.login }}
          token: ${{ secrets.CHATBOT_PR_PAT }}

  validate-permutations:
    name: PaaS / Validate permutations
    runs-on: ubuntu-20.04
    if: ${{ contains(fromJSON('["restore", "approve", "merge"]'), github.event.inputs.ACTION) }}
    outputs:
      filtered-permutations: ${{ steps.filter-permutations-by-coordinates.outputs.filtered-permutations }}
      error-message: ${{ steps.validate-slots.outputs.error-message }}

    steps:
      - name: Validate slots
        id: validate-slots
        uses: inditex/actions/deployment/validate-slots@main
        with:
          slots: ${{ github.event.inputs.SLOTS }}
          strategy: default

      - name: Stop if slots are not valid
        if: ${{ steps.validate-slots.outputs.is-valid != 'true' }}
        run: |
          echo "::error ::Error validating the slots. ${{ steps.validate-slots.outputs.error-message }}" | tr -s '\n' ' '
          exit 1

      - name: PaaS / Filter permutations by coordinates
        id: filter-permutations-by-coordinates
        uses: inditex/gha-paasdeployment/filter-permutations-by-coordinates@v0
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          supraenvs: ${{ github.event.inputs.SUPRAENVS }}
          envs: ${{ github.event.inputs.ENVS }}
          platforms: ${{ github.event.inputs.PLATFORMS }}
          tenants: ${{ github.event.inputs.TENANTS }}
          slots: ${{ github.event.inputs.SLOTS }}

  get-affected-prs:
    name: PaaS / Get affected PRs
    runs-on: ubuntu-20.04
    if: ${{ contains(fromJSON('["restore", "approve", "merge"]'), github.event.inputs.ACTION) }}
    outputs:
      affected-prs: ${{ steps.affected-prs-by-issue.outputs.affected-prs }}

    steps:
      - name: PaaS / Get affected PRs by issue
        id: affected-prs-by-issue
        uses: inditex/gha-paasdeployment/affected-prs-by-issue@v0
        with:
          issue-number: ${{ github.event.inputs.ISSUE_NUMBER }}
          token: ${{ secrets.GITHUB_TOKEN }}

  cancel:
    name: PaaS / Cancel related PRs
    runs-on: ubuntu-20.04
    if: ${{ github.event.inputs.ACTION == 'cancel' }}
    outputs:
      summary: ${{ steps.cancel.outputs.summary }}
    steps:
      - name: Get user
        id: user
        run: |
          login=$(gh api /repos/${{ github.repository }}/issues/comments/${{ github.event.inputs.ISSUE_COMMENT_ID }} -q '.user.login')
          echo "login=${login}" >> "$GITHUB_OUTPUT"

      - name: PaaS / Cancel deploy PRs
        uses: inditex/gha-paasdeployment/cancel-related-prs@v0
        id: cancel
        with:
          issue-number: ${{ github.event.inputs.ISSUE_NUMBER }}
          user: ${{ steps.user.outputs.login }}
          token: ${{ secrets.GITHUB_TOKEN }}

  rollout:
    name: PaaS / Run rollout command in PRs
    runs-on: ubuntu-20.04
    if: ${{ !contains(fromJSON('["merge", "cancel", "restore", "approve"]'), github.event.inputs.ACTION) }}
    outputs:
      summary: ${{ steps.post-command.outputs.summary }}
    env:
      LABEL_PREFIX: from-issue
      BASE_COMMAND: /deploy-rollout-strategy
    steps:
      - name: Post command in PRs
        env:
          GITHUB_TOKEN: ${{ secrets.CHATBOT_PR_PAT }}
        id: post-command
        run: |
          label="${{ env.LABEL_PREFIX }}/${{ github.event.inputs.ISSUE_NUMBER }}"
          prs=$(gh pr list -R ${{ github.repository }} \
                  --state merged --limit 100 --base "deployment" --label "${label}" \
                  --json number -q '[.[].number] | join(" ")')
          echo ">> PRs related to the issue: ${prs}"

          command="${BASE_COMMAND} --action ${{ github.event.inputs.ACTION }}"

          skip="${{ github.event.inputs.SKIP }}"
          if [[ -n "$skip" ]]; then
            command="${command} --skip ${skip}"
          fi

          summary="<b>Command to execute:</b> <code>${command}</code>"

          set +e
          for pr in $prs; do
              sleep 2  # Avoid abuse limit
              echo ">> Post command in PR #${pr}"
              summary+="\n* #${pr}"

              if gh pr comment "${pr}" -R ${{ github.repository }} --body "${command}";
              then
                summary+=" - :heavy_check_mark: Command executed"
              else
                summary+=" - :x: Error executing command"
              fi
          done
          set -e

          echo -e ">> Summary:\n${summary}"
          echo "summary=${summary//$'\n'/%0A}" >> "$GITHUB_OUTPUT"  # Replace newlines with GitHub escape code

  restore-init:
    name: PaaS / Restore init
    runs-on: ubuntu-20.04
    needs: [validate-permutations, get-affected-prs]
    if: ${{ github.event.inputs.ACTION == 'restore' }}
    outputs:
      permutations-info: ${{ steps.get-permutations-info.outputs.permutations-info }}
      restore-issue-number: ${{ steps.check-and-create-issue.outputs.issue-number }}

    steps:
      - name: Add comment with started status
        if: ${{ github.event.inputs.ISSUE_NUMBER != '' }}
        uses: inditex/gha-citool/add-comment@v0
        id: starting-comment
        with:
          issue-number: '${{ github.event.inputs.ISSUE_NUMBER }}'
          body: |
            #### :gear: The `paas-restore` workflow is currently running

            Deployment permutations are being validated and then will be restored to their second last commit respectively.
            The pull request(s) related to this task will be opened shortly ...

            See the [workflow log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PaaS / Get permutations information
        id: get-permutations-info
        uses: inditex/gha-paasdeployment/get-permutations-info@v0
        with:
          filter-for-action: "RESTORE"
          affected-prs: '${{ needs.get-affected-prs.outputs.affected-prs }}'
          permutations: '${{ needs.validate-permutations.outputs.filtered-permutations }}'

      - name: PaaS / Check and create issue
        id: check-and-create-issue
        uses: inditex/gha-paasdeployment/check-and-create-issue@v0
        with:
          label: "restored-from/${{ github.event.inputs.ISSUE_NUMBER }}"
          issue-title: "[Automated] :white_check_mark: Restored pull requests from workflow ${{ github.workflow }}-${{ github.run_id }}"
          issue-body: |
            Workflow in progress, you will see here the results of the restore process.
            See the [workflow log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add comment when get restore data fails
        if: ${{ failure() && !cancelled() && (github.event.inputs.ISSUE_NUMBER != '') }}
        uses: inditex/gha-citool/add-comment@v0
        with:
          issue-number: '${{ github.event.inputs.ISSUE_NUMBER }}'
          body: |
            #### :x: An error has occurred preparing data to restore permutations.

            ${{ needs.validate-permutations.outputs.error-message }}

            The `${{ github.workflow }}` workflow has failed at the `${{ github.job }}` job.
            See the [workflow log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  restore:
    name: Restore affected PRs
    runs-on: ubuntu-20.04
    needs: [restore-init]
    if: ${{ fromJson(needs.restore-init.outputs.permutations-info) }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        permutations: ${{ fromJson(needs.restore-init.outputs.permutations-info) }}

    steps:
      - name: PaaS / Restore deployment PR
        id: restore-deployment-pr
        uses: inditex/gha-paasdeployment/restore-deployment-pr@v0
        with:
          issue-or-pr-number: ${{ github.event.inputs.ISSUE_NUMBER }}
          permutation-folder: ${{ matrix.permutations.permutation }}
          restore-issue-number: ${{ needs.restore-init.outputs.restore-issue-number }}
          token: ${{ secrets.CHATBOT_PR_PAT }}
          artifact-path: ${{ env.DIR_PATH_STATUS }}

        env:
          SCM_COMMITTER_PGP_KEY: ${{ secrets.BUTLER_PGP_KEY }}

      - name: Upload restore results
        uses: actions/upload-artifact@v3
        with:
          name: "pr-${{ steps.restore-deployment-pr.outputs.pr-number }}-run-${{ github.run_id }}-result"
          path: "${{ env.DIR_PATH_STATUS }}/pr-${{ steps.restore-deployment-pr.outputs.pr-number }}-run-${{ github.run_id }}-result.txt"
          retention-days: 7

      - name: Upload restore error results
        if: ${{ steps.restore-deployment-pr.outputs.have-errors == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: "run-${{ github.run_id }}-error"
          path: "${{ env.DIR_PATH_STATUS }}/run-${{ github.run_id }}-error.txt"
          retention-days: 7

      - name: Add comment when restoration fails
        if: ${{ failure() && !cancelled() && (github.event.inputs.ISSUE_NUMBER != '') }}
        uses: inditex/gha-citool/add-comment@v0
        with:
          issue-number: '${{ github.event.inputs.ISSUE_NUMBER }}'
          body: |
            #### :x: An error has occurred restoring permutations.

            The `${{ github.workflow }}` workflow has failed at the `${{ github.job }}` job.
            See the [workflow log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  restore-summary:
    if: ${{ success() && !cancelled() && (github.event.inputs.ISSUE_NUMBER != '') }}
    name: Restore summary
    runs-on: ubuntu-20.04
    needs: [restore, restore-init]
    outputs:
      summary: ${{ steps.restore-summary-message.outputs.summary }}
    steps:
      - name: PaaS / Download restore summary
        uses: actions/download-artifact@v3
        with:
          path: ${{ env.DIR_PATH_STATUS }}

      - name: PaaS / Get result artifact content
        id: get-success-results
        continue-on-error: true
        run: |
          pr_result_list=""
          for file in ${{ env.DIR_PATH_STATUS }}/*/*result.txt; do
            if [ -e "$file" ]; then
              content=$(cat "$file")
              pr_result_list="${pr_result_list}${content}"
            fi
          done
          echo "pr-result-list=$pr_result_list" >> "$GITHUB_OUTPUT"

      - name: PaaS / Get error artifact content
        id: get-error-results
        continue-on-error: true
        run: |
          pr_errors=""
          for error_file in ${{ env.DIR_PATH_STATUS }}/*/*error.txt; do
            if [ -e "$error_file" ]; then
              error_content=$(cat "$error_file")
              pr_errors="${pr_errors}${error_content}"
            fi
          done
          echo "pr-errors=$pr_errors" >> "$GITHUB_OUTPUT"

      - name: Add comment with finished status
        if: ${{ github.event.inputs.ISSUE_NUMBER != '' && needs.restore-init.outputs.restore-issue-number != '' }}
        id: restore-summary-message
        run: |
          message="
          #### :white_check_mark: The *paas-restore* workflow has finished
          A issue to manage restore pull request has been created: #${{ needs.restore-init.outputs.restore-issue-number }}
          "
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          {
            echo "summary<<$EOF"
            echo "$message"
            echo "$EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Add comment with finished status in restore issue
        if: ${{ github.event.inputs.ISSUE_NUMBER != '' && needs.restore-init.outputs.restore-issue-number != '' }}
        run: |
          text="
          #### :white_check_mark: The *paas-restore* workflow launched from issue #${{ github.event.inputs.ISSUE_NUMBER }} has finished
          The next pull request(s) related to this task have been processed:
          ${{ format(steps.get-success-results.outputs.pr-result-list, '%0A -') }}

          ${{ steps.get-error-results.outputs.pr-errors }}
          "
          body=$(echo -e "${text//\%0A/\\n}")
          gh issue edit ${{ needs.restore-init.outputs.restore-issue-number }} --repo ${{ github.repository }} --body "$body"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  approve:
    name: PaaS / Approve affected PRs
    runs-on: ubuntu-20.04
    needs: [validate-permutations, get-affected-prs, verify]
    if: contains(fromJSON('["approve", "merge"]'), github.event.inputs.ACTION) && needs.verify.outputs.has-errors != 'True'

    outputs:
      summary: ${{ steps.approve-summary-message.outputs.summary }}
      has-errors: ${{ steps.approve-deployment-pr.outputs.has-errors }}

    permissions:
      id-token: write  # This is required for requesting the JWT
      issues: write  # This is required for getting user from comment
      contents: read

    steps:
      - name: Add comment with started status
        if: ${{ github.event.inputs.ISSUE_NUMBER != '' }}
        uses: inditex/gha-citool/add-comment@v0
        id: starting-comment
        with:
          issue-number: '${{ github.event.inputs.ISSUE_NUMBER }}'
          body: |
            #### :gear: The `paas-deploy-instances --action approve` workflow is currently running

            Affected PRs for this issue are being validated using MIMIC to act on behalf of you.
            The pull request(s) related to this task will be approved shortly...
            You can grant access to mimic doing click [here](https://github.com/login/oauth/authorize?client_id=Iv1.6c66202dc9c51e4d).

            See the [workflow log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PaaS / Get Affected PRs information
        id: get-prs-to-approve-info
        uses: inditex/gha-paasdeployment/get-permutations-info@v0
        with:
          filter-for-action: "APPROVE"
          affected-prs: '${{ needs.get-affected-prs.outputs.affected-prs }}'
          permutations: '${{ needs.validate-permutations.outputs.filtered-permutations }}'

      - name: Get user
        id: approve-user
        run: |
          login=$(gh api /repos/${{ github.repository }}/issues/comments/${{ github.event.inputs.ISSUE_COMMENT_ID }} -q '.user.login')
          echo "login=${login}" >> "$GITHUB_OUTPUT"

      - name: Paas / Get MIMIC token
        id: get-mimic-token
        uses: inditex/gha-paasdeployment/get-mimic-token@v0
        with:
          audience: "mimic"

      - name: PaaS / Approve affected PRs
        id: approve-deployment-pr
        uses: inditex/gha-paasdeployment/request-mimic-api@v0
        with:
          repository: ${{ github.repository }}
          user: ${{ steps.approve-user.outputs.login }}
          prs-to-process: ${{ steps.get-prs-to-approve-info.outputs.permutations-info }}
          action: "approve"
          mimic-app-id: ${{ vars.MIMIC_APP_ID }}
        env:
          MIMIC_TOKEN: ${{ steps.get-mimic-token.outputs.mimic-token }}

      - name: Add comment with finished status
        if: ${{ github.event.inputs.ISSUE_NUMBER != '' && steps.approve-deployment-pr.outputs.results != '' }}
        id: approve-summary-message
        run: |
          message="
          #### :white_check_mark: The *paas-approve* workflow launched from issue #${{ github.event.inputs.ISSUE_NUMBER }} has finished
          The next pull request(s) related to this task have been processed:

          ${{ steps.approve-deployment-pr.outputs.results }}
          "

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          {
            echo "summary<<$EOF"
            echo "$message"
            echo "$EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Add comment when get approve data fails
        if: ${{ failure() && !cancelled() && (github.event.inputs.ISSUE_NUMBER != '') }}
        uses: inditex/gha-citool/add-comment@v0
        with:
          issue-number: '${{ github.event.inputs.ISSUE_NUMBER }}'
          body: |
            #### :x: An error has occurred preparing data to approve PRs.

            ${{ needs.validate-permutations.outputs.error-message }}

            The `${{ github.workflow }}` workflow has failed at the `${{ github.job }}` job.
            See the [workflow log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge:
    name: PaaS / Merge affected PRs with MIMIC
    runs-on: ubuntu-20.04
    needs: [validate-permutations, get-affected-prs, approve, verify]
    if: github.event.inputs.ACTION == 'merge' && needs.verify.outputs.has-errors != 'True' && needs.approve.outputs.has-errors != 'True'
    outputs:
      summary: ${{ steps.merge-summary-message.outputs.summary }}

    permissions:
      id-token: write  # This is required for requesting the JWT
      issues: write  # This is required for getting user from comment
      contents: read

    steps:
      - name: Add comment with started status
        if: ${{ github.event.inputs.ISSUE_NUMBER != '' }}
        uses: inditex/gha-citool/add-comment@v0
        id: merge-starting-comment
        with:
          issue-number: '${{ github.event.inputs.ISSUE_NUMBER }}'
          body: |
            #### :gear: The `paas-deploy-instances --action merge` workflow is currently running

            Affected PRs for this issue are goona be merged using MIMIC to act on behalf of you.
            The pull request(s) related to this task will be merge shortly...

            See the [workflow log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PaaS / Get Affected PRs information
        id: get-prs-to-merge-info
        uses: inditex/gha-paasdeployment/get-permutations-info@v0
        with:
          filter-for-action: "MERGE"
          affected-prs: '${{ needs.get-affected-prs.outputs.affected-prs }}'
          permutations: '${{ needs.validate-permutations.outputs.filtered-permutations }}'

      - name: Get user
        id: merge-user
        run: |
          login=$(gh api /repos/${{ github.repository }}/issues/comments/${{ github.event.inputs.ISSUE_COMMENT_ID }} -q '.user.login')
          echo "login=${login}" >> "$GITHUB_OUTPUT"

      - name: Paas / Get MIMIC token
        id: merge-get-mimic-token
        uses: inditex/gha-paasdeployment/get-mimic-token@v0
        with:
          audience: "mimic"

      - name: PaaS / Merge affected PRs
        id: merge-deployment-pr
        uses: inditex/gha-paasdeployment/request-mimic-api@v0
        with:
          repository: ${{ github.repository }}
          user: ${{ steps.merge-user.outputs.login }}
          prs-to-process: ${{ steps.get-prs-to-merge-info.outputs.permutations-info }}
          action: "merge"
          mimic-app-id: ${{ vars.MIMIC_APP_ID }}
        env:
          MIMIC_TOKEN: ${{ steps.merge-get-mimic-token.outputs.mimic-token }}

      - name: Add comment with finished status
        if: ${{ github.event.inputs.ISSUE_NUMBER != '' && steps.merge-deployment-pr.outputs.results != '' }}
        id: merge-summary-message
        run: |
          message="
          #### :white_check_mark: The *paas-merge* workflow launched from issue #${{ github.event.inputs.ISSUE_NUMBER }} has finished
          The next pull request(s) related to this task have been merged:

          ${{ steps.merge-deployment-pr.outputs.results }}
          "

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          {
            echo "summary<<$EOF"
            echo "$message"
            echo "$EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Add comment when Merge data fails
        if: ${{ failure() && !cancelled() && (github.event.inputs.ISSUE_NUMBER != '') }}
        uses: inditex/gha-citool/add-comment@v0
        with:
          issue-number: '${{ github.event.inputs.ISSUE_NUMBER }}'
          body: |
            #### :x: An error has occurred preparing data to approve PRs.

            ${{ needs.validate-permutations.outputs.error-message }}

            The `${{ github.workflow }}` workflow has failed at the `${{ github.job }}` job.
            See the [workflow log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  summary:
    name: PaaS / Summary
    runs-on: ubuntu-20.04
    if: ${{ always() && !cancelled() }}
    needs: [merge, rollout, cancel, restore-summary, approve, verify]
    steps:
      - name: Generate comment
        id: comment
        run: |
          comment=$(gh api /repos/${{ github.repository }}/issues/comments/${{ github.event.inputs.ISSUE_COMMENT_ID }})
          first_line=$(echo "$comment" | jq -r .body | head -n1 | tr -d '\r\n')
          link=$(echo "$comment" | jq -r .html_url)

          message="${{ needs.merge.outputs.summary || needs.rollout.outputs.summary || needs.cancel.outputs.summary || needs.restore-summary.outputs.summary || needs.approve.outputs.summary || needs.verify.outputs.summary }}"
          if [ -z "${message}" ]; then
            message=":x: Unexpected error. More information in the [workflow log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          fi

          # Ensure message does not have any newlines and use GitHub escape
          # characters as replacement. Awful.
          echo -E "Message: ${message}"
          message=${message//'\r'/}
          message=${message//'\n'/%0A}
          message=${message//$'\n'/%0A}

          comment="<b>This is a response to <a href=\"${link}\">this message</a>:</b><br><i>${first_line}</i><hr><h3>ChatBot says:</b></h3>${message}"
          echo -E "Comment: ${comment}"
          echo "body=${comment}" >> "$GITHUB_OUTPUT"

      - name: Add comment with the summary
        uses: inditex/gha-citool/add-comment@v0
        with:
          issue-number: "${{ github.event.inputs.ISSUE_NUMBER }}"
          body: ${{ steps.comment.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.CHATBOT_PR_PAT }}
