---
name: pipe-service-account

on:
  workflow_dispatch:

env:
  WORKFLOW_VERSION: 2.0.0

jobs:
  service-account:
    name: PIPE / Create Service Account
    timeout-minutes: 30
    runs-on: [self-hosted, pipe]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get metadata
        id: metadata
        shell: python
        run: |
          import yaml
          import os
          with open('application.yml') as f:
            application = yaml.safe_load(f)

          github_output = os.getenv('GITHUB_OUTPUT')
          with open(github_output, "a") as gh_out:
            gh_out.write(f'project-key={ application["metadata"]["project_key"] }\n')

      - name: PIPE / Create Service Account
        uses: inditex/gha-pipeactions/service-account@main
        with:
          project-dir: ${GITHUB_WORKSPACE}
        env:
          JIRAKEY: ${{ steps.metadata.outputs.project-key }}
