---
name: security-detect_secrets-fallback

on:
  pull_request:

env:
  WORKFLOW_VERSION: 2.5.0

jobs:
  detect-secrets-pr:
    if: 'false'
    name: DSecrets / PR
    runs-on: ${{ fromJSON(vars.RUNSON_DSECRETS_ONPREM || '["ubuntu-24.04"]') }}
    steps:
      - run: 'echo "DSecrets / PR required"'
